export interface PublicWord {
  german: string;
  hungarian: string;
  example?: string;
  case?: string;
  note?: string;
  category?: string;
}

export const publicVocabulary: PublicWord[] = [
  // --- QUIZ 1: A1 Basics ---
  { german: "der Mann, die Männer", hungarian: "a férfi" },
  { german: "die Frau, die Frauen", hungarian: "a nő" },
  { german: "das Kind, die Kinder", hungarian: "a gyerek" },
  { german: "das Haus, die Häuser", hungarian: "a ház" },
  { german: "das Auto, die Autos", hungarian: "az autó" },
  { german: "der Hund, die Hunde", hungarian: "a kutya" },
  { german: "die Katze, die Katzen", hungarian: "a macska" },
  { german: "der Tag, die Tage", hungarian: "a nap" },
  { german: "die Nacht, die Nächte", hungarian: "az éjszaka" },
  { german: "das Buch, die Bücher", hungarian: "a könyv" },
  { german: "der Tisch, die Tische", hungarian: "az asztal" },
  { german: "der Stuhl, die Stühle", hungarian: "a szék" },
  { german: "das Wasser, -", hungarian: "a víz" },
  { german: "das Brot, die Brote", hungarian: "a kenyér" },
  { german: "groß", hungarian: "nagy" },
  { german: "klein", hungarian: "kicsi" },
  { german: "gut", hungarian: "jó" },
  { german: "schlecht", hungarian: "rossz" },
  { german: "sein (ist)", hungarian: "lenni" },
  { german: "haben (hat)", hungarian: "birtokolni" },

  // --- QUIZ 2: A1 Everyday Life ---
  { german: "der Apfel, die Äpfel", hungarian: "az alma", example: "Ich esse jeden Morgen einen frischen und leckeren Apfel." },
  { german: "die Straße, die Straßen", hungarian: "az utca", example: "Unsere Familie wohnt in einer sehr ruhigen Straße am Stadtrand." },
  { german: "die Stadt, die Städte", hungarian: "a város", example: "Berlin ist eine sehr große, laute und faszinierende Stadt." },
  { german: "das Geld, die Gelder", hungarian: "a pénz", example: "Hast du genug Geld für das teure Zugticket nach München?" },
  { german: "die Arbeit, die Arbeiten", hungarian: "a munka", example: "Meine neue Arbeit im Büro macht mir wirklich viel Spaß." },
  { german: "der Freund, die Freunde", hungarian: "a barát", example: "Mein bester Freund besucht mich heute Nachmittag zu Hause." },
  { german: "die Schule, die Schulen", hungarian: "az iskola", example: "Die Kinder gehen jeden Morgen sehr früh in die Schule." },
  { german: "der Lehrer, die Lehrer", hungarian: "a tanár", example: "Der nette Lehrer erklärt die deutsche Grammatik sehr gut." },
  { german: "das Zimmer, die Zimmer", hungarian: "a szoba", example: "Mein neues Zimmer ist sehr hell, groß und wirklich gemütlich." },
  { german: "das Bett, die Betten", hungarian: "az ágy", example: "Ich bin extrem müde und gehe jetzt sofort ins warme Bett." },
  { german: "machen", hungarian: "csinálni", example: "Was machst du heute am späten Abend mit deinen Freunden?" },
  { german: "gehen", hungarian: "menni", example: "Wir gehen am sonnigen Nachmittag gemeinsam in den großen Park." },
  { german: "kommen", hungarian: "jönni", example: "Kommst du am Wochenende zu meiner Geburtstagsparty?" },
  { german: "sehen", hungarian: "látni", example: "Ich sehe ein wunderschönes rotes Auto drüben auf der Straße." },
  {  german: "hören", hungarian: "hallani", example: "Ich höre beim Kochen in der Küche sehr gerne klassische Musik." },
  { german: "schnell", hungarian: "gyors", example: "Sein neues Elektroauto fährt wirklich unglaublich schnell." },
  { german: "langsam", hungarian: "lassú", example: "Könnten Sie bitte ein bisschen langsamer und deutlicher sprechen?" },
  { german: "heute", hungarian: "ma", example: "Heute ist das Wetter draußen besonders warm und wunderschön." },
  { german: "morgen", hungarian: "holnap", example: "Wir fahren morgen früh mit dem Auto in den gemeinsamen Urlaub." },
  { german: "gestern", hungarian: "tegnap", example: "Gestern war ich leider den ganzen Tag krank im Bett." },

  // --- QUIZ 3: A1 Food & Travel ---
  { german: "der Bahnhof, die Bahnhöfe", hungarian: "a pályaudvar", example: "Der schnelle Zug fährt gleich vom Hauptbahnhof in Berlin ab." },
  { german: "der Zug, die Züge", hungarian: "a vonat", example: "Wir nehmen heute den direkten Zug nach Süddeutschland." },
  { german: "das Ticket, die Tickets", hungarian: "a jegy", example: "Hast du das teure Ticket für das Konzert schon gekauft?" },
  { german: "das Restaurant, die Restaurants", hungarian: "az étterem", example: "Wir essen heute Abend in einem sehr guten italienischen Restaurant." },
  { german: "das Fleisch, -", hungarian: "a hús", example: "Ich esse schon lange kein Fleisch mehr, weil ich Vegetarier bin." },
  { german: "der Käse, -", hungarian: "a sajt", example: "Dieser berühmte französische Käse schmeckt wirklich fantastisch." },
  { german: "die Milch, -", hungarian: "a tej", example: "Trinkst du deinen starken Kaffee lieber mit oder ohne Milch?" },
  { german: "der Kaffee, die Kaffees", hungarian: "a kávé", example: "Ein heißer Kaffee am frühen Morgen ist für mich sehr wichtig." },
  { german: "der Tee, die Tees", hungarian: "a tea", example: "Möchtest du am Nachmittag eine Tasse heißen schwarzen Tee trinken?" },
  { german: "der Morgen, die Morgen", hungarian: "a reggel", example: "Jeden Morgen lese ich entspannt die Zeitung am Küchentisch." },
  { german: "der Abend, die Abende", hungarian: "az este", example: "Am späten Abend schaue ich gerne gute Filme auf dem Sofa." },
  { german: "essen", hungarian: "enni", example: "Was möchtest du heute am liebsten zum Frühstück essen?" },
  { german: "trinken", hungarian: "inni", example: "Nach dem anstrengenden Sport trinke ich am liebsten kühles Wasser." },
  { german: "schlafen", hungarian: "aludni", example: "Ich muss heute unbedingt acht Stunden schlafen, weil ich müde bin." },
  { german: "kaufen", hungarian: "venni (vásárolni)", example: "Wir müssen heute Nachmittag noch Brot und frische Äpfel kaufen." },
  { german: "kochen", hungarian: "főzni", example: "Meine liebe Mutter kocht heute am Abend eine sehr leckere Suppe." },
  { german: "heiß", hungarian: "forró", example: "Vorsicht beim Essen, diese Gemüsesuppe ist noch extrem heiß!" },
  { german: "kalt", hungarian: "hideg", example: "Im Dezember und Januar ist es hier in den Bergen sehr kalt." },
  { german: "neu", hungarian: "új", example: "Mein komplett neues Fahrrad war teuer, aber es ist sehr schnell." },
  { german: "alt", hungarian: "régi / öreg", example: "Dieses alte und historische Haus im Stadtzentrum ist wunderschön." },

  // --- QUIZ 4: A2 Family & People ---
  { german: "die Familie, die Familien", hungarian: "a család", example: "Meine große Familie lebt schon immer in Süddeutschland." },
  { german: "die Eltern (Pl.)", hungarian: "a szülők", example: "Meine Eltern kommen am kommenden Wochenende endlich zu Besuch." },
  { german: "der Vater, die Väter", hungarian: "az apa", example: "Mein Vater arbeitet als freundlicher Lehrer in der Grundschule." },
  { german: "die Mutter, die Mütter", hungarian: "az anya", example: "Meine Mutter kocht immer das beste und leckerste Essen für uns." },
  { german: "der Bruder, die Brüder", hungarian: "a fiútestvér", example: "Mein jüngerer Bruder spielt jeden Sonntag sehr gerne Fußball." },
  { german: "die Schwester, die Schwestern", hungarian: "a lánytestvér", example: "Meine ältere Schwester studiert derzeit erfolgreich Medizin in Wien." },
  { german: "der Arzt, die Ärzte", hungarian: "az orvos", example: "Der Arzt sagt, ich bin krank und muss unbedingt im Bett bleiben." },
  { german: "das Krankenhaus, die Krankenhäuser", hungarian: "a kórház", example: "Das komplett neu gebaute Krankenhaus in der Stadt ist sehr modern." },
  { german: "das Medikament, die Medikamente", hungarian: "a gyógyszer", example: "Du musst dieses starke Medikament dreimal täglich nach dem Essen nehmen." },
  { german: "der Schmerz, die Schmerzen", hungarian: "a fájdalom", example: "Der starke Schmerz in meinem Knie ist heute glücklicherweise besser." },
  { german: "wohnen", hungarian: "lakni", example: "Wir wohnen zusammen in einer gemütlichen Wohnung direkt im Zentrum." },
  { german: "leben", hungarian: "élni", example: "Wie viele unterschiedliche Menschen leben heute eigentlich in dieser Stadt?" },
  { german: "helfen", hungarian: "segíteni", example: "Könntest du mir bitte kurz bei dieser schwierigen Hausaufgabe helfen?" },
  { german: "danken", hungarian: "megköszönni", example: "Ich danke Ihnen vielmals für Ihre überaus schnelle und gute Hilfe." },
  { german: "brauchen", hungarian: "szüksége van vmire", example: "Ich brauche unbedingt ein komplett neues Handy für meine Arbeit." },
  { german: "krank", hungarian: "beteg", example: "Er kann heute leider nicht zur Arbeit kommen, weil er stark krank ist." },
  { german: "gesund", hungarian: "egészséges", example: "Nach einer langen Woche im Bett bin ich jetzt endlich wieder gesund." },
  { german: "glücklich", hungarian: "boldog", example: "Das kleine Kind ist wirklich extrem glücklich mit seinem neuen Spielzeug." },
  { german: "traurig", hungarian: "szomorú", example: "Warum bist du heute eigentlich so nachdenklich und furchtbar traurig?" },
  { german: "müde", hungarian: "fáradt", example: "Nach der langen und anstrengenden Arbeit bin ich am Abend extrem müde." },

  // --- QUIZ 5: A2 Communication ---
  { german: "die Frage, die Fragen", hungarian: "a kérdés", example: "Entschuldigung, ich habe eine sehr wichtige und eilige Frage an Sie." },
  { german: "die Antwort, die Antworten", hungarian: "a válasz", example: "Weißt du vielleicht die absolut richtige Antwort auf diese Frage?" },
  { german: "das Wort, die Wörter", hungarian: "a szó", example: "Könnten Sie mir bitte erklären, wie man dieses deutsche Wort schreibt?" },
  { german: "der Satz, die Sätze", hungarian: "a mondat", example: "Bitte bilden Sie im Test einen vollständigen Satz mit diesem Wort." },
  { german: "die Sprache, die Sprachen", hungarian: "a nyelv", example: "Welche fremde Sprache sprichst du normalerweise mit deiner Familie zu Hause?" },
  { german: "der Brief, die Briefe", hungarian: "a levél", example: "Ich schreibe heute Nachmittag einen langen Brief an meine Großeltern." },
  { german: "das Telefon, die Telefone", hungarian: "a telefon", example: "Das alte Telefon im Flur klingelt nun schon seit fünf Minuten." },
  { german: "die Nummer, die Nummern", hungarian: "a szám", example: "Könntest du mir bitte deine aktuelle Telefonnummer für WhatsApp geben?" },
  { german: "fragen", hungarian: "kérdezni", example: "Darf ich Sie vielleicht etwas Wichtiges zu diesem neuen Thema fragen?" },
  { german: "antworten", hungarian: "válaszolni", example: "Leider antwortet er fast nie auf meine zahlreichen und wichtigen E-Mails." },
  { german: "sprechen", hungarian: "beszélni", example: "Sprechen Sie vielleicht auch ein bisschen Englisch, Herr Müller?" },
  { german: "sagen", hungarian: "mondani", example: "Ich habe leider nicht genau verstanden, was du gerade zu mir gesagt hast." },
  { german: "lernen", hungarian: "tanulni", example: "Wir lernen nun schon seit fast zwei Jahren gemeinsam die deutsche Sprache." },
  { german: "verstehen", hungarian: "megérteni", example: "Es tut mir leid, aber ich verstehe diesen komplizierten Text überhaupt nicht." },
  { german: "lesen", hungarian: "olvasni", example: "Mein Vater liest jeden Morgen entspannt die Zeitung beim Frühstück." },
  { german: "schreiben", hungarian: "írni", example: "Bitte schreiben Sie Ihren vollständigen Namen unten auf dieses Papier." },
  { german: "wichtig", hungarian: "fontos", example: "Es ist wirklich extrem wichtig, jeden Tag fleißig neue Vokabeln zu lernen." },
  { german: "richtig", hungarian: "helyes", example: "Das ist absolut die richtige Antwort, du hast das Thema sehr gut verstanden!" },
  { german: "falsch", hungarian: "hamis / rossz", example: "Diese Information im Internet ist leider komplett und eindeutig falsch." },
  { german: "einfach", hungarian: "egyszerű", example: "Diese kleine Grammatikübung ist wirklich sehr einfach und schnell zu lösen." },

  // --- QUIZ 6: A2 Directions & Places ---
  { german: "der Weg, die Wege", hungarian: "az út", example: "Könnten Sie mir bitte kurz den genauen Weg zum Hauptbahnhof zeigen?" },
  { german: "der Platz, die Plätze", hungarian: "a tér / a hely", example: "Dieser schöne Platz am Fenster ist leider schon für jemanden reserviert." },
  { german: "die Brücke, die Brücken", hungarian: "a híd", example: "Wir fahren gleich mit dem Auto über die große und sehr alte Brücke." },
  { german: "das Gebäude, die Gebäude", hungarian: "az épület", example: "Dieses alte und historische Gebäude direkt im Zentrum ist eine Bibliothek." },
  { german: "der Berg, die Berge", hungarian: "a hegy", example: "Am kommenden Wochenende wandern wir gemeinsam auf den höchsten Berg." },
  { german: "der Fluss, die Flüsse", hungarian: "a folyó", example: "Dieser extrem lange Fluss fließt wunderschön durch die ganze Stadt." },
  { german: "der Wald, die Wälder", hungarian: "az erdő", example: "Besonders im Herbst ist der große Wald hier sehr bunt und extrem schön." },
  { german: "die Karte, die Karten", hungarian: "a térkép / a jegy", example: "Zeig mir bitte genau auf der Karte, wo wir uns momentan befinden." },
  { german: "das Flugzeug, die Flugzeuge", hungarian: "a repülőgép", example: "Das große Flugzeug nach Berlin startet pünktlich um zehn Uhr am Vormittag." },
  { german: "der Flughafen, die Flughäfen", hungarian: "a repülőtér", example: "Der neu gebaute Flughafen außerhalb der Stadt ist wirklich sehr modern." },
  { german: "fliegen", hungarian: "repülni", example: "Nächste Woche fliegen wir endlich in den wohlverdienten Urlaub nach Spanien." },
  { german: "fahren", hungarian: "utazni / vezetni", example: "Wir fahren heute bei dem schönen Wetter mit dem Auto direkt ans Meer." },
  { german: "suchen", hungarian: "keresni", example: "Ich suche schon den ganzen Morgen meinen Schlüssel, hast du ihn gesehen?" },
  { german: "finden", hungarian: "találni", example: "Ich kann mein wichtiges rotes Notizbuch heute leider absolut nicht finden." },
  { german: "warten", hungarian: "várni", example: "Wir warten hier im Regen nun schon seit fast zwanzig Minuten auf den Bus." },
  { german: "links", hungarian: "balra", example: "Gehen Sie an der nächsten großen Kreuzung bitte sofort nach links." },
  { german: "rechts", hungarian: "jobbra", example: "Die gesuchte Apotheke befindet sich gleich vorne auf der rechten Seite." },
  { german: "geradeaus", hungarian: "egyenesen", example: "Gehen Sie einfach immer geradeaus weiter, bis Sie die alte Kirche sehen." },
  { german: "weit", hungarian: "messze", example: "Entschuldigung, ist der Weg bis zum nächsten großen Supermarkt noch sehr weit?" },
  { german: "nah", hungarian: "közel", example: "Zum großen Glück ist die nächste U-Bahn-Station wirklich sehr nah von hier." },

  // --- QUIZ 7: B1 Shopping & Objects ---
  { german: "das Geschäft, die Geschäfte", hungarian: "az üzlet", example: "Dieses kleine, aber sehr beliebte Geschäft öffnet jeden Morgen um acht Uhr." },
  { german: "der Preis, die Preise", hungarian: "az ár", example: "Die normalen Preise in diesem großen Supermarkt sind wirklich sehr niedrig." },
  { german: "die Kleidung, die Kleidungen", hungarian: "a ruházat", example: "Ich brauche dringend neue und warme Kleidung für den extrem kalten Winter." },
  { german: "der Schuh, die Schuhe", hungarian: "a cipő", example: "Diese teuren schwarzen Lederschuhe sind beim Laufen wirklich sehr bequem." },
  { german: "die Tasche, die Taschen", hungarian: "a táska", example: "Entschuldigung, hast du meine dunkelblaue Tasche irgendwo auf dem Tisch gesehen?" },
  { german: "das Geschenk, die Geschenke", hungarian: "az ajándék", example: "Dieses wunderschöne und sehr persönliche Geschenk ist speziell für deinen Geburtstag." },
  { german: "der Fehler, die Fehler", hungarian: "a hiba", example: "Ich habe heute leider einen kleinen, aber dummen Fehler im Text gemacht." },
  { german: "der Computer, die Computer", hungarian: "a számítógép", example: "Mein komplett neuer Computer für die Arbeit ist extrem schnell und leise." },
  { german: "das Bild, die Bilder", hungarian: "a kép", example: "Dieses sehr alte und wertvolle Bild hängt schon lange dort an der Wand." },
  { german: "die Farbe, die Farben", hungarian: "a szín", example: "Blau ist schon seit vielen Jahren meine absolute und einzige Lieblingsfarbe." },
  { german: "bezahlen", hungarian: "fizetni", example: "Möchten Sie den Betrag lieber bar bezahlen oder doch lieber mit Karte?" },
  { german: "kosten", hungarian: "kerül vmibe", example: "Könnten Sie mir sagen, wie viel dieses interessante Buch über Geschichte kostet?" },
  { german: "tragen", hungarian: "hordani / viselni", example: "Er trägt heute für das wichtige Treffen einen sehr eleganten schwarzen Anzug." },
  { german: "waschen", hungarian: "mosni", example: "Ich muss heute unbedingt am Nachmittag mein schmutziges Auto gründlich waschen." },
  { german: "öffnen", hungarian: "kinyitni", example: "Könnten Sie bitte das große Fenster ein kleines bisschen für frische Luft öffnen?" },
  { german: "schließen", hungarian: "bezárni", example: "Bitte schließen Sie die Tür schnell wieder, es ist draußen extrem kalt." },
  { german: "teuer", hungarian: "drága", example: "Dieses komplett neue Restaurant in der Stadtmitte ist leider extrem teuer." },
  { german: "billig", hungarian: "olcsó", example: "Wir haben ein überraschend billiges, aber gutes Hotel für den Urlaub gefunden." },
  { german: "schön", hungarian: "szép", example: "Das Wetter am Strand ist heute unglaublich schön, warm und sehr sonnig." },
  { german: "hässlich", hungarian: "csúnya", example: "Dieses alte und fast kaputte Gebäude in der Innenstadt ist wirklich hässlich." },

  // --- QUIZ 8: B1 Work & Time ---
  { german: "die Zeit, die Zeiten", hungarian: "az idő", example: "Ich habe für dieses neue Hobby momentan leider absolut keine freie Zeit." },
  { german: "die Stunde, die Stunden", hungarian: "az óra (időtartam)", example: "Wir haben noch eine ganze Stunde Zeit, bis unser Zug endlich abfährt." },
  { german: "die Woche, die Wochen", hungarian: "a hét", example: "Nächste Woche fahre ich endlich mit meiner ganzen Familie in den Urlaub." },
  { german: "der Monat, die Monate", hungarian: "a hónap", example: "Der nächste Monat wird aufgrund des großen Projekts sehr stressig bei der Arbeit." },
  { german: "das Jahr, die Jahre", hungarian: "az év", example: "Dieses vergangene Jahr war äußerst erfolgreich für unser komplett neues Unternehmen." },
  { german: "der Beruf, die Berufe", hungarian: "a szakma", example: "Darf ich Sie fragen, was eigentlich Ihr Beruf ist und wo Sie genau arbeiten?" },
  { german: "die Firma, die Firmen", hungarian: "a cég", example: "Unsere große Firma hat unzählige internationale Kunden auf der ganzen Welt." },
  { german: "das Büro, die Büros", hungarian: "az iroda", example: "Mein komplett neues Büro im obersten Stockwerk ist sehr hell und ziemlich groß." },
  { german: "der Kollege, die Kollegen", hungarian: "a kolléga", example: "Mein sehr netter Kollege hilft mir immer sofort bei besonders schwierigen Aufgaben." },
  { german: "der Chef, die Chefs", hungarian: "a főnök", example: "Der Chef ist heute leider nicht im Haus, er ist auf einer wichtigen Konferenz." },
  { german: "beginnen", hungarian: "elkezdeni", example: "Das spannende und sehr erwartete Konzert beginnt pünktlich um zwanzig Uhr." },
  { german: "enden", hungarian: "befejezni", example: "Der wirklich interessante und lange Film endet leider erst sehr spät in der Nacht." },
  { german: "arbeiten", hungarian: "dolgozni", example: "Ich arbeite jeden Tag hart von acht Uhr morgens bis siebzehn Uhr am Nachmittag." },
  { german: "verdienen", hungarian: "pénzt keresni", example: "In diesem spannenden neuen Job verdiene ich glücklicherweise wirklich sehr gutes Geld." },
  { german: "verkaufen", hungarian: "eladni", example: "Wir verkaufen unser altes Auto nächste Woche, weil wir uns ein komplett neues kaufen." },
  { german: "früh", hungarian: "korán", example: "Ich muss morgen extrem früh aus dem Bett aufstehen und schnell zur Arbeit fahren." },
  { german: "spät", hungarian: "késő", example: "Es ist schon verdammt spät geworden, wir müssen jetzt wirklich langsam nach Hause gehen." },
  { german: "oft", hungarian: "gyakran", example: "Ich gehe am Wochenende sehr oft und sehr gerne mit meinen besten Freunden ins Kino." },
  { german: "selten", hungarian: "ritkán", example: "Ich trinke leider nur noch sehr selten eine Tasse starken Kaffee am späten Nachmittag." },
  { german: "immer", hungarian: "mindig", example: "Er kommt wirklich fast immer fünf Minuten zu spät zu unseren sehr wichtigen Treffen." },

  // --- QUIZ 9: B1 Nature & Weather ---
  { german: "das Wetter, -", hungarian: "az időjárás", example: "Das sonnige Wetter in Spanien ist im Sommer wirklich fast immer fantastisch." },
  { german: "die Sonne, die Sonnen", hungarian: "a nap (égitest)", example: "Die warme Sonne scheint hell und der weite Himmel ist heute komplett blau." },
  { german: "der Regen, -", hungarian: "az eső", example: "Wegen des anhaltend starken Regens bleiben wir heute Nachmittag lieber gemütlich zu Hause." },
  { german: "der Schnee, -", hungarian: "a hó", example: "Im kalten Winter gibt es in den hohen Bergen der Alpen oft sehr viel Schnee." },
  { german: "der Wind, die Winde", hungarian: "a szél", example: "Der kalte Wind weht heute extrem stark und unangenehm direkt von der Küste." },
  { german: "die Natur, -", hungarian: "a természet", example: "Die absolut wilde Natur in diesem unberührten Nationalpark ist atemberaubend schön." },
  { german: "der Baum, die Bäume", hungarian: "a fa", example: "Dieser riesige und alte Baum in unserem Garten ist bereits über hundert Jahre alt." },
  { german: "die Blume, die Blumen", hungarian: "a virág", example: "Diese wunderschönen roten Blumen duften im warmen Frühling wirklich ganz hervorragend." },
  { german: "das Meer, die Meere", hungarian: "a tenger", example: "Wir fahren fast jeden warmen Sommer mit unserem Auto ans blaue und weite Meer." },
  { german: "der Strand, die Strände", hungarian: "a strand", example: "Der lange weiße Strand war heute voll von fröhlichen und entspannten Touristen." },
  { german: "scheinen", hungarian: "süt (a nap)", example: "Die angenehm warme Sonne scheint heute schon den ganzen Tag über der großen Stadt." },
  { german: "regnen", hungarian: "esik (az eső)", example: "Es wird laut Wetterbericht morgen wahrscheinlich den ganzen langen Nachmittag regnen." },
  { german: "schneien", hungarian: "esik (a hó)", example: "Im Dezember schneit es hier oben in den dunklen Wäldern fast jeden einzelnen Tag." },
  { german: "wachsen", hungarian: "nőni", example: "Die grünen Pflanzen wachsen im sonnigen Frühling nach dem Regen besonders schnell." },
  { german: "bleiben", hungarian: "maradni", example: "Wir bleiben heute Abend alle zusammen sehr gemütlich zu Hause auf dem warmen Sofa." },
  { german: "warm", hungarian: "meleg", example: "Heute ist es überraschend angenehm warm und wunderschön sonnig draußen im Park." },
  { german: "kühl", hungarian: "hűvös", example: "Am späten Abend wird es hier am dunklen Waldrand oft ein kleines bisschen kühl." },
  { german: "stark", hungarian: "erős", example: "Er ist ein wirklich sehr starker, gesunder und extrem sportlicher junger Mann." },
  { german: "schwach", hungarian: "gyenge", example: "Nach der langen und extrem schweren Krankheit fühlte sie sich noch ziemlich schwach." },
  { german: "dunkel", hungarian: "sötét", example: "Im kalten und unangenehmen Winter wird es am Nachmittag leider immer sehr früh dunkel." },

  // --- QUIZ 10: B1 Daily Interactions ---
  { german: "der Fehler, die Fehler", hungarian: "a hiba", example: "Es ist absolut normal und menschlich, beim Sprachenlernen kleine Fehler zu machen." },
  { german: "die Lösung, die Lösungen", hungarian: "a megoldás", example: "Wir müssen alle zusammen dringend eine richtig gute Lösung für dieses Problem finden." },
  { german: "die Einladung, die Einladungen", hungarian: "a meghívás", example: "Vielen herzlichen Dank für die sehr nette und überraschende Einladung zu deiner großen Party." },
  { german: "das Fest, die Feste", hungarian: "az ünnep", example: "Das riesige Fest am Wochenende war ein voller Erfolg für alle anwesenden Gäste." },
  { german: "die Hilfe, -", hungarian: "a segítség", example: "Ich brauche unbedingt heute noch deine Hilfe bei dieser extrem schwierigen Aufgabe." },
  { german: "die Meinung, die Meinungen", hungarian: "a vélemény", example: "Meiner komplett ehrlichen Meinung nach ist das leider gar keine so gute Idee." },
  { german: "das Gefühl, die Gefühle", hungarian: "az érzés", example: "Ich habe einfach von Anfang an ein sehr gutes Gefühl bei dieser wichtigen und großen Sache." },
  { german: "die Angst, die Ängste", hungarian: "a félelem", example: "Das kleine Kind hat sehr große Angst vor dem lauten und großen Hund auf der Straße." },
  { german: "die Freude, die Freuden", hungarian: "az öröm", example: "Er machte diese körperlich sehr harte Arbeit überraschenderweise mit unglaublich großer Freude." },
  { german: "der Traum, die Träume", hungarian: "az álom", example: "Es ist schon lange mein absolut größter Traum, einmal um die ganze weite Welt zu reisen." },
  { german: "glauben", hungarian: "hinni", example: "Ich glaube ganz fest daran, dass es morgen am Nachmittag stark regnen wird." },
  { german: "denken", hungarian: "gondolni", example: "Was genau denkst du eigentlich über diese völlig neue und sehr interessante Idee?" },
  { german: "wissen", hungarian: "tudni", example: "Ich weiß leider überhaupt nicht, wie dieses teure und komplizierte Gerät genau funktioniert." },
  { german: "hoffen", hungarian: "remélni", example: "Ich hoffe wirklich sehr, dass wir uns ganz bald wieder persönlich zum Kaffee sehen können." },
  { german: "fühlen", hungarian: "érezni", example: "Nach dem langen und sehr erholsamen Schlaf am Wochenende fühle ich mich wieder richtig fit." },
  { german: "lustig", hungarian: "vicces", example: "Dieser komplett neue Film im Kino ist unglaublich lustig und wirklich hervorragend unterhaltsam." },
  { german: "ernst", hungarian: "komoly", example: "Die aktuelle finanzielle Situation in unserer alten Firma ist leider derzeit sehr ernst." },
  { german: "wütend", hungarian: "mérges", example: "Der strenge Chef war extrem wütend über diesen kleinen, aber wirklich sehr dummen Fehler." },
  { german: "zufrieden", hungarian: "elégedett", example: "Ich bin heute sehr glücklich und extrem zufrieden mit dem tollen Ergebnis meiner Sprachprüfung." },
  { german: "sicher", hungarian: "biztos", example: "Bist du dir absolut hundertprozentig sicher, dass du heute Abend um acht Uhr kommen kannst?" },

  // --- QUIZ 11: B2 Advanced Concepts ---
  { german: "die Entwicklung, die Entwicklungen", hungarian: "a fejlődés", example: "Die technische Entwicklung in den letzten Jahren ist wirklich beeindruckend." },
  { german: "die Erfahrung, die Erfahrungen", hungarian: "a tapasztalat", example: "Für diesen Job braucht man sehr viel berufliche Erfahrung." },
  { german: "die Gesellschaft, die Gesellschaften", hungarian: "a társadalom", example: "Die moderne Gesellschaft steht vor vielen neuen Herausforderungen." },
  { german: "der Zustand, die Zustände", hungarian: "az állapot", example: "Das alte Auto ist in einem erstaunlich guten Zustand." },
  { german: "die Bedingung, die Bedingungen", hungarian: "a feltétel", example: "Unter diesen Bedingungen kann ich den Vertrag nicht unterschreiben." },
  { german: "die Bedeutung, die Bedeutungen", hungarian: "a jelentés", example: "Was ist die genaue Bedeutung von diesem komplizierten Wort?" },
  { german: "die Möglichkeit, die Möglichkeiten", hungarian: "a lehetőség", example: "Es gibt viele Möglichkeiten, um eine neue Sprache zu lernen." },
  { german: "das Ergebnis, die Ergebnisse", hungarian: "az eredmény", example: "Das Ergebnis der Prüfung war viel besser als erwartet." },
  { german: "das Ziel, die Ziele", hungarian: "a cél", example: "Mein Ziel ist es, fließend Deutsch sprechen zu können." },
  { german: "der Grund, die Gründe", hungarian: "az ok", example: "Was ist der eigentliche Grund für deine Entscheidung?" },
  { german: "entstehen", hungarian: "keletkezik / létrejön", example: "Wie ist das Universum ursprünglich eigentlich entstanden?" },
  { german: "verändern", hungarian: "megváltoztat", example: "Man kann die Vergangenheit leider nicht mehr verändern." },
  { german: "verbessern", hungarian: "javít", example: "Ich möchte meine Aussprache im Deutschen deutlich verbessern." },
  { german: "vergleichen", hungarian: "összehasonlít", example: "Man sollte nicht immer die eigenen Leistungen mit anderen vergleichen." },
  { german: "erreichen", hungarian: "elér (célt)", example: "Mit harter Arbeit kann man fast jedes Ziel im Leben erreichen." },
  { german: "verschieden", hungarian: "különböző", example: "Wir haben sehr verschiedene Meinungen zu diesem politischen Thema." },
  { german: "ähnlich", hungarian: "hasonló", example: "Die beiden Schwestern sehen sich unglaublich ähnlich." },
  { german: "besonders", hungarian: "különösen", example: "Dieser Wein schmeckt besonders gut zu dem kräftigen Käse." },
  { german: "wahrscheinlich", hungarian: "valószínűleg", example: "Er kommt wahrscheinlich ein bisschen später zur Party." },
  { german: "vielleicht", hungarian: "talán", example: "Vielleicht können wir uns morgen Nachmittag auf einen Kaffee treffen." },

  // --- QUIZ 12: B2 Media & Information ---
  { german: "die Nachricht, die Nachrichten", hungarian: "a hír", example: "Ich habe gerade eine wichtige Nachricht von meinem Chef bekommen." },
  { german: "der Bericht, die Berichte", hungarian: "a jelentés (beszámoló)", example: "Der ausführliche Bericht über den Unfall wird morgen veröffentlicht." },
  { german: "der Artikel, die Artikel", hungarian: "a cikk", example: "Hast du den interessanten Artikel über den Klimawandel gelesen?" },
  { german: "der Autor, die Autoren", hungarian: "a szerző", example: "Der Autor dieses Buches ist international sehr bekannt und erfolgreich." },
  { german: "die Meinung, die Meinungen", hungarian: "a vélemény", example: "Jeder hat das Recht auf eine eigene freie Meinung." },
  { german: "die Wahrheit, die Wahrheiten", hungarian: "az igazság", example: "Es ist manchmal schwer, die ganze Wahrheit zu akzeptieren." },
  { german: "das Geheimnis, die Geheimnisse", hungarian: "a titok", example: "Kannst du bitte dieses kleine Geheimnis für dich behalten?" },
  { german: "der Beweis, die Beweise", hungarian: "a bizonyíték", example: "Die Polizei hat einen klaren Beweis für seine Schuld gefunden." },
  { german: "die Forschung, die Forschungen", hungarian: "a kutatás", example: "Die wissenschaftliche Forschung in diesem Bereich ist sehr wichtig." },
  { german: "die Quelle, die Quellen", hungarian: "die forrás", example: "Man sollte immer die Quelle seiner Informationen überprüfen." },
  { german: "berichten", hungarian: "beszámol", example: "Die Zeitung berichtet ausführlich über die politischen Ereignisse." },
  { german: "erklären", hungarian: "elmagyaráz", example: "Kannst du mir bitte erklären, wie dieses komplizierte Gerät funktioniert?" },
  { german: "beschreiben", hungarian: "leír (jellemez)", example: "Er konnte den Täter sehr genau und detailliert beschreiben." },
  { german: "diskutieren", hungarian: "megvitat", example: "Wir haben lange über dieses kontroverse Thema diskutiert." },
  { german: "behaupten", hungarian: "állít vmit", example: "Er behauptet, er habe von der ganzen Sache nichts gewusst." },
  { german: "aktuell", hungarian: "aktuális", example: "Die aktuellen Nachrichten sind leider oft sehr beunruhigend." },
  { german: "öffentlich", hungarian: "nyilvános", example: "Diese wichtige Information wurde gestern öffentlich gemacht." },
  { german: "privat", hungarian: "privát", example: "Das ist eine private Angelegenheit, über die ich nicht sprechen möchte." },
  { german: "deutlich", hungarian: "egyértelmű", example: "Er hat seine Meinung sehr deutlich und unmissverständlich gesagt." },
  { german: "heimlich", hungarian: "titkos", example: "Sie haben sich heimlich in der Nacht getroffen, ohne dass es jemand wusste." },

  // --- QUIZ 13: B2 Work & Economy ---
  { german: "die Wirtschaft, die Wirtschaften", hungarian: "a gazdaság", example: "Die globale Wirtschaft steht vor großen und unsicheren Herausforderungen." },
  { german: "das Unternehmen, die Unternehmen", hungarian: "a vállalat", example: "Dieses große internationale Unternehmen hat weltweit Tausende von Mitarbeitern." },
  { german: "der Vertrag, die Verträge", hungarian: "a szerződés", example: "Bitte lesen Sie den gesamten Vertrag sorgfältig durch, bevor Sie ihn unterschreiben." },
  { german: "der Erfolg, die Erfolge", hungarian: "a siker", example: "Der große Erfolg des Projekts war das Ergebnis harter Teamarbeit." },
  { german: "der Verlust, die Verluste", hungarian: "a veszteség", example: "Die Firma musste im letzten Quartal einen erheblichen finanziellen Verlust hinnehmen." },
  { german: "die Steuer, die Steuern", hungarian: "az adó", example: "Jeder Bürger ist gesetzlich verpflichtet, seine Steuern pünktlich zu zahlen." },
  { german: "die Versicherung, die Versicherungen", hungarian: "die biztosítás", example: "Eine gute Krankenversicherung ist in Deutschland absolut unerlässlich." },
  { german: "die Leistung, die Leistungen", hungarian: "a teljesítmény", example: "Die sportliche Leistung des Athleten war einfach nur phänomenal." },
  { german: "die Aufgabe, die Aufgaben", hungarian: "a feladat", example: "Meine Hauptaufgabe in diesem Projekt ist die Koordination des gesamten Teams." },
  { german: "der Beruf, die Berufe", hungarian: "a hivatás", example: "Die Wahl des richtigen Berufs ist eine sehr wichtige Entscheidung im Leben." },
  { german: "verhandeln", hungarian: "tárgyalni", example: "Die beiden Parteien verhandeln schon seit Wochen über einen neuen Vertrag." },
  { german: "unterschreiben", hungarian: "aláírni", example: "Nach langem Zögern hat er den Arbeitsvertrag endlich unterschrieben." },
  { german: "produzieren", hungarian: "termelni", example: "Diese moderne Fabrik produziert täglich über tausend Autos." },
  { german: "anbieten", hungarian: "kínálni", example: "Das Hotel bietet seinen Gästen einen exzellenten und umfassenden Service." },
  { german: "bestellen", hungarian: "megrendelni", example: "Ich habe mir gestern Abend online ein neues und spannendes Buch bestellt." },
  { german: "erfolgreich", hungarian: "sikeres", example: "Sie ist eine sehr erfolgreiche Geschäftsfrau mit vielen internationalen Kontakten." },
  { german: "beruflich", hungarian: "szakmai", example: "Was sind Ihre langfristigen beruflichen Ziele für die nächsten fünf Jahre?" },
  { german: "finanziell", hungarian: "pénzügyi", example: "Aufgrund der Krise ist die finanzielle Situation der Firma sehr angespannt." },
  { german: "abhängig", hungarian: "függő", example: "Der Erfolg des Projekts ist stark von der externen Finanzierung abhängig." },
  { german: "unabhängig", hungarian: "független", example: "Sie ist eine finanziell unabhängige Frau, die ihre eigenen Entscheidungen trifft." },

  // --- QUIZ 14: B2 Health & Body ---
  { german: "die Gesundheit, -", hungarian: "az egészség", example: "Regelmäßiger Sport und eine ausgewogene Ernährung sind wichtig für die Gesundheit." },
  { german: "die Krankheit, die Krankheiten", hungarian: "a betegség", example: "Nach einer langen und schweren Krankheit ist er nun endlich wieder auf dem Weg der Besserung." },
  { german: "die Untersuchung, die Untersuchungen", hungarian: "a vizsgálat", example: "Die ärztliche Untersuchung ergab, dass glücklicherweise alles in bester Ordnung ist." },
  { german: "die Behandlung, die Behandlungen", hungarian: "a kezelés", example: "Die medizinische Behandlung in diesem Krankenhaus ist wirklich erstklassig." },
  { german: "das Gehirn, die Gehirne", hungarian: "az agy", example: "Das menschliche Gehirn ist ein unglaublich komplexes und faszinierendes Organ." },
  { german: "das Herz, die Herzen", hungarian: "a szív", example: "Vor Aufregung schlug ihr das Herz bis zum Hals." },
  { german: "das Blut, -", hungarian: "a vér", example: "Bei der Untersuchung wurde ihm eine kleine Menge Blut abgenommen." },
  { german: "der Muskel, die Muskeln", hungarian: "az izom", example: "Nach dem intensiven Training hatte er einen starken Muskelkater." },
  { german: "der Knochen, die Knochen", hungarian: "a csont", example: "Bei dem Unfall hat er sich leider einen Knochen im Arm gebrochen." },
  { german: "die Ernährung, -", hungarian: "a táplálkozás", example: "Eine gesunde und ausgewogene Ernährung ist die Basis für ein langes Leben." },
  { german: "untersuchen", hungarian: "megvizsgál", example: "Der Arzt wird Sie gründlich untersuchen, um die Ursache zu finden." },
  { german: "behandeln", hungarian: "kezelni", example: "Welcher Arzt wird Sie während Ihres Krankenhausaufenthalts behandeln?" },
  { german: "heilen", hungarian: "gyógyítani", example: "Diese moderne Medizin kann die Krankheit vollständig heilen." },
  { german: "leiden (an)", hungarian: "szenvedni vmitől", example: "Er leidet seit seiner Kindheit an einer seltenen Allergie." },
  { german: "pflegen", hungarian: "ápolni", example: "Die Krankenschwester pflegt die Patienten mit großer Sorgfalt und Hingabe." },
  { german: "gesund", hungarian: "egészséges", example: "Um gesund zu bleiben, sollte man sich viel bewegen und gut ernähren." },
  { german: "schädlich", hungarian: "káros", example: "Rauchen ist äußerst schädlich für die Lunge und die allgemeine Gesundheit." },
  { german: "tödlich", hungarian: "halálos", example: "Der Biss dieser exotischen Schlange kann für Menschen tödlich sein." },
  { german: "körperlich", hungarian: "testi", example: "Die körperliche Anstrengung bei diesem Marathon war enorm." },
  { german: "geistig", hungarian: "szellemi", example: "Regelmäßiges Lesen und Lernen hält den Geist fit und aktiv." },

  // --- QUIZ 15: C1 Abstract & Science ---
  { german: "die Erkenntnis, die Erkenntnisse", hungarian: "a felismerés", example: "Die wichtigste Erkenntnis aus der Studie war, dass die Methode funktioniert." },
  { german: "die Annahme, die Annahmen", hungarian: "a feltételezés", example: "Unsere ursprüngliche Annahme hat sich im Laufe der Forschung als falsch erwiesen." },
  { german: "der Beweis, die Beweise", hungarian: "a bizonyíték", example: "Trotz intensiver Suche konnte kein eindeutiger Beweis für seine Theorie gefunden werden." },
  { german: "die Ursache, die Ursachen", hungarian: "az ok (kiváltó)", example: "Die genaue Ursache für den plötzlichen Systemabsturz ist bisher noch unklar." },
  { german: "die Auswirkung, die Auswirkungen", hungarian: "a kihatás / következmény", example: "Die langfristige Auswirkung dieser Entscheidung ist schwer vorherzusagen." },
  { german: "der Zusammenhang, die Zusammenhänge", hungarian: "az összefüggés", example: "Es besteht ein klarer Zusammenhang zwischen Bildung und Einkommen." },
  { german: "der Prozess, die Prozesse", hungarian: "a folyamat", example: "Der gesamte Herstellungsprozess wird streng überwacht und kontrolliert." },
  { german: "die Struktur, die Strukturen", hungarian: "a szerkezet", example: "Die komplexe Struktur dieses Moleküls ist für Wissenschaftler faszinierend." },
  { german: "die Methode, die Methoden", hungarian: "a módszer", example: "Wir müssen eine effektivere Methode zur Lösung dieses Problems entwickeln." },
  { german: "das Phänomen, die Phänomene", hungarian: "a jelenség", example: "Dieses seltene astronomische Phänomen kann man nur alle hundert Jahre beobachten." },
  { german: "beweisen", hungarian: "bizonyítani", example: "Der Anwalt konnte die Unschuld seines Mandanten zweifelsfrei beweisen." },
  { german: "widerlegen", hungarian: "megcáfolni", example: "Neue Daten haben die alte wissenschaftliche Theorie vollständig widerlegt." },
  { german: "bestätigen", hungarian: "megerősíteni", example: "Können Sie bitte bestätigen, dass Sie meine E-Mail erhalten haben?" },
  { german: "beobachten", hungarian: "megfigyelni", example: "Astronomen beobachten die Bewegung der Sterne mit großen Teleskopen." },
  { german: "analysieren", hungarian: "elemezni", example: "Die Experten werden die gesammelten Daten nun sorgfältig analysieren." },
  { german: "komplex", hungarian: "bonyolult", example: "Die Regeln der deutschen Grammatik können manchmal sehr komplex sein." },
  { german: "grundlegend", hungarian: "alapvető", example: "Ein grundlegendes Verständnis der Mathematik ist für diesen Beruf unerlässlich." },
  { german: "wesentlich", hungarian: "lényeges", example: "Die Kommunikation ist ein wesentlicher Bestandteil einer guten Beziehung." },
  { german: "ursprünglich", hungarian: "eredeti", example: "Das Gebäude wurde restauriert, aber die ursprüngliche Fassade blieb erhalten." },
  { german: "tatsächlich", hungarian: "tényleges", example: "Ich dachte, er macht einen Witz, aber er hat es tatsächlich getan." },

  // --- QUIZ 16: C1 Politics & Law ---
  { german: "die Regierung, die Regierungen", hungarian: "a kormány", example: "Die neue Regierung hat weitreichende politische Reformen angekündigt." },
  { german: "das Gesetz, die Gesetze", hungarian: "a törvény", example: "Das Parlament hat gestern ein umstrittenes neues Gesetz verabschiedet." },
  { german: "die Wahl, die Wahlen", hungarian: "a választás", example: "Die nächste Wahl zum Bundestag findet in vier Jahren statt." },
  { german: "die Partei, die Parteien", hungarian: "a párt", example: "Welche politische Partei vertritt am besten Ihre Interessen?" },
  { german: "der Bürger, die Bürger", hungarian: "die polgár", example: "Jeder Bürger hat das Recht, an der politischen Diskussion teilzunehmen." },
  { german: "die Mehrheit, die Mehrheiten", hungarian: "a többség", example: "Die Mehrheit der Abgeordneten stimmte für den Gesetzesentwurf." },
  { german: "die Minderheit, die Minderheiten", hungarian: "a kisebbség", example: "Die Rechte der nationalen Minderheit müssen geschützt werden." },
  { german: "die Reform, die Reformen", hungarian: "a reform", example: "Die geplante Steuerreform wird viele Bürger finanziell entlasten." },
  { german: "der Kompromiss, die Kompromisse", hungarian: "a kompromisszum", example: "Nach langen Verhandlungen fanden die Parteien einen akzeptablen Kompromiss." },
  { german: "das Recht, die Rechte", hungarian: "a jog", example: "Das Recht auf freie Meinungsäußerung ist ein grundlegendes Menschenrecht." },
  { german: "wählen", hungarian: "választani", example: "In einer Demokratie können die Bürger ihre Vertreter frei wählen." },
  { german: "beschließen", hungarian: "elhatározni / dönteni", example: "Der Stadtrat hat beschlossen, eine neue Brücke zu bauen." },
  { german: "fordern", hungarian: "követelni", example: "Die Demonstranten fordern höhere Löhne und bessere Arbeitsbedingungen." },
  { german: "unterstützen", hungarian: "támogatni", example: "Viele Organisationen unterstützen die Initiative für mehr Umweltschutz." },
  { german: "ablehnen", hungarian: "elutasítani", example: "Die Opposition hat den Vorschlag der Regierung entschieden abgelehnt." },
  { german: "gesetzlich", hungarian: "törvényes", example: "Es gibt eine gesetzliche Verpflichtung, Kindern eine Schulbildung zu ermöglichen." },
  { german: "gerecht", hungarian: "igazságos", example: "Eine gerechte Gesellschaft sollte allen die gleichen Chancen bieten." },
  { german: "demokratisch", hungarian: "demokratikus", example: "Die Entscheidung wurde auf eine demokratische Weise durch eine Abstimmung getroffen." },
  { german: "konservativ", hungarian: "konzervatív", example: "Die konservative Partei setzt auf traditionelle Werte und wirtschaftliche Stabilität." },
  { german: "liberal", hungarian: "liberális", example: "Die liberale Politik betont die individuelle Freiheit und die Marktwirtschaft." },

  // --- QUIZ 17: C1 Environment & Technology ---
  { german: "die Umwelt, -", hungarian: "a környezet", example: "Der Schutz unserer Umwelt ist eine der größten Herausforderungen unserer Zeit." },
  { german: "der Klimawandel, -", hungarian: "a klímaváltozás", example: "Der Klimawandel führt zu immer extremeren Wetterereignissen weltweit." },
  { german: "die Ressource, die Ressourcen", hungarian: "az erőforrás", example: "Wir müssen sorgfältig mit den natürlichen Ressourcen unseres Planeten umgehen." },
  { german: "die Energie, die Energien", hungarian: "az energia", example: "Die Umstellung auf erneuerbare Energiequellen ist für die Zukunft entscheidend." },
  { german: "die Verschmutzung, die Verschmutzungen", hungarian: "a szennyezés", example: "Die Verschmutzung der Meere durch Plastikmüll ist ein globales Problem." },
  { german: "die Erfindung, die Erfindungen", hungarian: "a találmány", example: "Die Erfindung des Internets hat die Welt grundlegend verändert." },
  { german: "das Gerät, die Geräte", hungarian: "a készülék", example: "Dieses multifunktionale Gerät kann sowohl drucken als auch scannen." },
  { german: "der Fortschritt, die Fortschritte", hungarian: "a haladás", example: "Der medizinische Fortschritt hat die Lebenserwartung deutlich erhöht." },
  { german: "die Vernetzung, die Vernetzungen", hungarian: "die hálózatba kötés", example: "Die globale Vernetzung ermöglicht eine schnelle Kommunikation über Kontinente hinweg." },
  { german: "die Maßnahme, die Maßnahmen", hungarian: "az intézkedés", example: "Die Regierung hat neue Maßnahmen zum Schutz der Bevölkerung ergriffen." },
  { german: "schützen", hungarian: "védeni", example: "Wir müssen die bedrohten Tierarten vor dem Aussterben schützen." },
  { german: "verschmutzen", hungarian: "szennyezni", example: "Industrielle Abfälle dürfen die Flüsse und Seen nicht verschmutzen." },
  { german: "erfinden", hungarian: "feltalálni", example: "Wer hat eigentlich das Telefon erfunden, Alexander Graham Bell oder ein anderer?" },
  { german: "entwickeln", hungarian: "fejleszteni", example: "Das Unternehmen entwickelt eine neue Software zur Datenanalyse." },
  { german: "speichern", hungarian: "tárolni", example: "Vergiss nicht, deine Arbeit regelmäßig auf der Festplatte zu speichern." },
  { german: "nachhaltig", hungarian: "fenntartható", example: "Eine nachhaltige Landwirtschaft schont die Umwelt und die natürlichen Ressourcen." },
  { german: "effektiv", hungarian: "hatékony", example: "Diese neue Methode ist wesentlich effektiver als das alte Verfahren." },
  { german: "innovativ", hungarian: "innovatív", example: "Das Unternehmen ist bekannt für seine innovativen Produkte und Technologien." },
  { german: "künstlich", hungarian: "mesterséges", example: "Künstliche Intelligenz wird in immer mehr Lebensbereichen eingesetzt." },
  { german: "natürlich", hungarian: "természetes", example: "Dieser Saft enthält keine künstlichen Zusatzstoffe, sondern nur natürliche Zutaten." },

  // --- QUIZ 18: C1 Advanced Verbs ---
  { german: "die Entscheidung, die Entscheidungen", hungarian: "a döntés", example: "Die endgültige Entscheidung über das Projekt wird nächste Woche getroffen." },
  { german: "der Eindruck, die Eindrücke", hungarian: "a benyomás", example: "Der erste Eindruck, den ein Bewerber hinterlässt, ist oft entscheidend." },
  { german: "der Zweifel, die Zweifel", hungarian: "a kétség", example: "Trotz einiger Zweifel hat er das riskante Unternehmen gestartet." },
  { german: "die Überzeugung, die Überzeugungen", hungarian: "a meggyőződés", example: "Er handelte aus tiefer politischer Überzeugung und nicht aus Eigennutz." },
  { german: "die Behauptung, die Behauptungen", hungarian: "az állítás", example: "Seine kühne Behauptung konnte er nicht mit Fakten untermauern." },
  { german: "die Forderung, die Forderungen", hungarian: "a követelés", example: "Die Forderung der Gewerkschaft nach höheren Löhnen wurde abgelehnt." },
  { german: "die Ablehnung, die Ablehnungen", hungarian: "az elutasítás", example: "Die Ablehnung seines Antrags hat ihn tief enttäuscht." },
  { german: "die Erwartung, die Erwartungen", hungarian: "az elvárás", example: "Die Erwartungen an den neuen Film waren hoch, wurden aber nicht erfüllt." },
  { german: "der Vorschlag, die Vorschläge", hungarian: "a javaslat", example: "Ich möchte einen konstruktiven Vorschlag zur Verbesserung der Situation machen." },
  { german: "die Umsetzung, die Umsetzungen", hungarian: "a megvalósítás", example: "Die Planung ist abgeschlossen, jetzt geht es an die praktische Umsetzung." },
  { german: "vermeiden", hungarian: "elkerülni", example: "Um Konflikte zu vermeiden, sollten wir offen miteinander kommunizieren." },
  { german: "verursachen", hungarian: "okozni", example: "Der schwere Sturm hat in der gesamten Region erhebliche Schäden verursacht." },
  { german: "verzichten (auf)", hungarian: "lemondani vmiről", example: "Aus gesundheitlichen Gründen muss er vorübergehend auf Zucker verzichten." },
  { german: "verbergen", hungarian: "eltitkolni", example: "Sie versuchte, ihre wahre Enttäuschung hinter einem Lächeln zu verbergen." },
  { german: "vermuten", hungarian: "gyanítani / sejteni", example: "Ich vermute, dass er nicht die ganze Wahrheit gesagt hat." },
  { german: "zögern", hungarian: "habozni", example: "Er zögerte einen Moment, bevor er die schwierige Frage beantwortete." },
  { german: "bestätigen", hungarian: "igazolni", example: "Der Zeuge konnte die Aussage des Angeklagten vollständig bestätigen." },
  { german: "zweifeln", hungarian: "kételkedni", example: "Ich zweifle stark daran, dass diese unüberlegte Strategie zum Erfolg führen wird." },
  { german: "bewerten", hungarian: "értékelni", example: "Die Lehrerin wird die Aufsätze der Schüler nach klaren Kriterien bewerten." },
  { german: "erkennen", hungarian: "felismerni", example: "Ich habe ihn an seiner markanten Stimme sofort wieder erkannt." },

  // --- QUIZ 19: C1 Advanced Adjectives & Adverbs ---
  { german: "der Schwerpunkt, die Schwerpunkte", hungarian: "a súlypont", example: "Der Schwerpunkt dieser Konferenz liegt auf dem Thema künstliche Intelligenz." },
  { german: "der Einfluss, die Einflüsse", hungarian: "die befolyás", example: "Die Medien haben einen großen Einfluss auf die öffentliche Meinung." },
  { german: "der Gegensatz, die Gegensätze", hungarian: "az ellentét", example: "Im Gegensatz zu seinem Bruder ist er sehr ruhig und zurückhaltend." },
  { german: "die Ausnahme, die Ausnahmen", hungarian: "a kivétel", example: "Normalerweise ist das Museum montags geschlossen, aber heute ist eine Ausnahme." },
  { german: "die Regel, die Regeln", hungarian: "a szabály", example: "In der Regel beginnt der Unterricht pünktlich um acht Uhr morgens." },
  { german: "der Ablauf, die Abläufe", hungarian: "a lefolyás (folyamat)", example: "Der genaue Ablauf der Veranstaltung wird noch bekannt gegeben." },
  { german: "die Hinsicht, die Hinsichten", hungarian: "a tekintet (vmilyen szempontból)", example: "In dieser Hinsicht stimme ich Ihnen vollkommen zu." },
  { german: "der Umfang, die Umfänge", hungarian: "a terjedelem", example: "Der Umfang dieses Buches ist mit über tausend Seiten beachtlich." },
  { german: "die Eigenschaft, die Eigenschaften", hungarian: "die tulajdonság", example: "Geduld ist eine sehr wichtige Eigenschaft für einen guten Lehrer." },
  { german: "der Mangel, die Mängel", hungarian: "a hiány", example: "Ein Mangel an Vitamin D kann im Winter zu Müdigkeit führen." },
  { german: "erheblich", hungarian: "jelentős", example: "Die neuen Maßnahmen haben zu einer erheblichen Verbesserung der Situation geführt." },
  { german: "zunehmend", hungarian: "egyre növekvő", example: "Die Bedeutung des Online-Handels nimmt in den letzten Jahren zunehmend zu." },
  { german: "ausführlich", hungarian: "részletes", example: "Er gab uns eine sehr ausführliche Beschreibung des gesamten Vorfalls." },
  { german: "vergeblich", hungarian: "hiába", example: "Alle Versuche, das alte Auto zu reparieren, waren leider vergeblich." },
  { german: "allmählich", hungarian: "fokozatosan", example: "Nach dem langen Winter wird es draußen allmählich wieder wärmer." },
  { german: "zufällig", hungarian: "véletlenül", example: "Ich habe meinen alten Schulfreund gestern zufällig in der Stadt getroffen." },
  {  german: "absichtlich", hungarian: "szándékosan", example: "Er hat die Vase nicht absichtlich fallen lassen, es war ein Versehen." },
  { german: "offensichtlich", hungarian: "nyilvánvalóan", example: "Er hat offensichtlich kein Interesse an diesem Thema, da er ständig auf sein Handy schaut." },
  { german: "vermeintlich", hungarian: "állítólagos", example: "Der vermeintlich sichere Weg erwies sich als gefährliche Falle." },
  { german: "tatsächlich", hungarian: "valójában", example: "Ich dachte, es wäre schwierig, aber es war tatsächlich ganz einfach." },

  // --- QUIZ 20: C1 Mastery Expressions ---
  { german: "die Rücksicht, -", hungarian: "a tekintet / tapintat", example: "In einer Partnerschaft ist gegenseitige Rücksicht sehr wichtig." },
  { german: "die Zuverlässigkeit, -", hungarian: "a megbízhatóság", example: "Zuverlässigkeit ist eine der wichtigsten Eigenschaften eines guten Mitarbeiters." },
  { german: "die Verantwortung, die Verantwortungen", hungarian: "a felelősség", example: "Als Elternteil trägt man eine große Verantwortung für seine Kinder." },
  { german: "die Voraussetzung, die Voraussetzungen", hungarian: "az előfeltétel", example: "Gute Sprachkenntnisse sind eine wichtige Voraussetzung für diesen Job." },
  { german: "die Leidenschaft, die Leidenschaften", hungarian: "a szenvedély", example: "Er verfolgt sein Hobby, die Fotografie, mit großer Leidenschaft." },
  { german: "die Geduld, -", hungarian: "a türelem", example: "Beim Erlernen eines Instruments braucht man sehr viel Geduld." },
  { german: "das Vertrauen, -", hungarian: "a bizalom", example: "Vertrauen ist die Grundlage jeder funktionierenden Beziehung." },
  { german: "das Verständnis, -", hungarian: "a megértés", example: "Ich bitte um Ihr Verständnis für die kurzfristige Planänderung." },
  { german: "das Verhalten, -", hungarian: "a viselkedés", example: "Sein unhöfliches Verhalten gegenüber den Gästen war inakzeptabel." },
  { german: "das Bewusstsein, -", hungarian: "a tudatosság", example: "Ein starkes Umweltbewusstsein wird in der heutigen Gesellschaft immer wichtiger." },
  { german: "berücksichtigen", hungarian: "figyelembe vesz", example: "Bei der Planung müssen wir die Wünsche aller Beteiligten berücksichtigen." },
  { german: "vernachlässigen", hungarian: "elhanyagol", example: "Man sollte seine Gesundheit auf keinen Fall vernachlässigen." },
  { german: "rechtfertigen", hungarian: "igazol / megindokol", example: "Er versuchte, sein Fehlverhalten mit fadenscheinigen Ausreden zu rechtfertigen." },
  { german: "beeinflussen", hungarian: "befolyásol", example: "Lassen Sie sich bei Ihrer Entscheidung nicht von anderen beeinflussen." },
  { german: "gewährleisten", hungarian: "garantál", example: "Der Hersteller muss die Sicherheit des Produkts jederzeit gewährleisten." },
  { german: "unvermeidlich", hungarian: "elkerülhetetlen", example: "Aufgrund des starken Schneefalls waren Verspätungen leider unvermeidlich." },
  { german: "unberechenbar", hungarian: "kiszámíthatatlan", example: "Das Wetter in den Bergen ist oft sehr unberechenbar und kann sich schnell ändern." },
  { german: "überwiegend", hungarian: "túlnyomórészt", example: "Die Teilnehmer der Konferenz waren überwiegend Wissenschaftler aus Europa." },
  { german: "ausschließlich", hungarian: "kizárólag", example: "Dieses Angebot gilt ausschließlich für Neukunden des Unternehmens." },
  { german: "schlussendlich", hungarian: "végül is", example: "Nach langem Überlegen hat er sich schlussendlich doch für das andere Modell entschieden." },

  // --- QUIZ 21: B1 Home & Furniture ---
  { german: "die Wand, die Wände", hungarian: "a fal" },
  { german: "der Boden, die Böden", hungarian: "a padló" },
  { german: "die Decke, die Decken", hungarian: "a mennyezet / takaró" },
  { german: "das Dach, die Dächer", hungarian: "a tető" },
  { german: "der Schrank, die Schränke", hungarian: "a szekrény" },
  { german: "das Regal, die Regale", hungarian: "a polc" },
  { german: "der Sessel, die Sessel", hungarian: "a fotel" },
  { german: "das Sofa, die Sofas", hungarian: "a kanapé" },
  { german: "der Teppich, die Teppiche", hungarian: "a szőnyeg" },
  { german: "der Spiegel, die Spiegel", hungarian: "a tükör" },
  { german: "das Handtuch, die Handtücher", hungarian: "a törölköző" },
  { german: "die Seife, die Seifen", hungarian: "a szappan" },
  { german: "die Dusche, die Duschen", hungarian: "a zuhany" },
  { german: "die Badewanne, die Badewannen", hungarian: "a fürdőkád" },
  { german: "die Küche, die Küchen", hungarian: "a konyha" },
  { german: "der Herd, die Herde", hungarian: "a tűzhely" },
  { german: "der Kühlschrank, die Kühlschränke", hungarian: "a hűtőszekrény" },
  { german: "die Spülmaschine, die Spülmaschinen", hungarian: "a mosogatógép" },
  { german: "der Teller, die Teller", hungarian: "a tányér" },
  { german: "die Tasse, die Tassen", hungarian: "a csésze" },

  // --- QUIZ 22: B1 Clothes & Accessories ---
  { german: "die Hose, die Hosen", hungarian: "a nadrág" },
  { german: "die Jacke, die Jacken", hungarian: "a dzseki" },
  { german: "der Mantel, die Mäntel", hungarian: "a kabát" },
  { german: "das Hemd, die Hemden", hungarian: "az ing" },
  { german: "das T-Shirt, die T-Shirts", hungarian: "a póló" },
  { german: "der Pullover, die Pullover", hungarian: "a pulóver" },
  { german: "der Schuh, die Schuhe", hungarian: "a cipő" },
  { german: "der Stiefel, die Stiefel", hungarian: "a csizma" },
  { german: "der Socken, die Socken", hungarian: "a zokni" },
  { german: "der Rock, die Röcke", hungarian: "a szoknya" },
  { german: "das Kleid, die Kleider", hungarian: "a ruha (női)" },
  { german: "der Anzug, die Anzüge", hungarian: "az öltöny" },
  { german: "die Krawatte, die Krawatten", hungarian: "a nyakkendő" },
  { german: "der Gürtel, die Gürtel", hungarian: "az öv" },
  { german: "die Mütze, die Mützen", hungarian: "a sapka" },
  { german: "der Hut, die Hüte", hungarian: "a kalap" },
  { german: "der Schal, die Schals", hungarian: "a sál" },
  { german: "der Handschuh, die Handschuhe", hungarian: "a kesztyű" },
  { german: "die Brille, die Brillen", hungarian: "a szemüveg" },
  { german: "die Tasche, die Taschen", hungarian: "a táska" },

  // --- QUIZ 23: B1 Body Parts ---
  { german: "der Körper, die Körper", hungarian: "a test" },
  { german: "das Haar, die Haare", hungarian: "a haj" },
  { german: "der Kopf, die Köpfe", hungarian: "a fej" },
  { german: "das Auge, die Augen", hungarian: "a szem" },
  { german: "das Ohr, die Ohren", hungarian: "a fül" },
  { german: "die Nase, die Nasen", hungarian: "az orr" },
  { german: "der Mund, die Münder", hungarian: "a száj" },
  { german: "der Zahn, die Zähne", hungarian: "a fog" },
  { german: "die Lippe, die Lippen", hungarian: "az ajak" },
  { german: "die Zunge, die Zungen", hungarian: "a nyelv (testrész)" },
  { german: "der Hals, die Hälse", hungarian: "a nyak" },
  { german: "die Schulter, die Schultern", hungarian: "a váll" },
  { german: "der Arm, die Arme", hungarian: "a kar" },
  { german: "die Hand, die Hände", hungarian: "a kéz" },
  { german: "der Finger, die Finger", hungarian: "az ujj" },
  { german: "die Brust, die Brüste", hungarian: "a mell" },
  { german: "der Rücken, die Rücken", hungarian: "a hát" },
  { german: "der Bauch, die Bäuche", hungarian: "a has" },
  { german: "das Bein, die Beine", hungarian: "a láb(szár)" },
  { german: "der Fuß, die Füße", hungarian: "a láb(fej)" },

  // --- QUIZ 24: B1 Food & Kitchen ---
  { german: "die Gabel, die Gabeln", hungarian: "a villa" },
  { german: "das Messer, die Messer", hungarian: "a kés" },
  { german: "der Löffel, die Löffel", hungarian: "a kanál" },
  { german: "das Glas, die Gläser", hungarian: "a pohár" },
  { german: "die Flasche, die Flaschen", hungarian: "az üveg / palack" },
  { german: "der Topf, die Töpfe", hungarian: "a fazék" },
  { german: "die Pfanne, die Pfannen", hungarian: "a serpenyő" },
  { german: "das Gemüse, die Gemüse", hungarian: "a zöldség" },
  { german: "das Obst, -", hungarian: "a gyümölcs" },
  { german: "die Kartoffel, die Kartoffeln", hungarian: "a krumpli" },
  { german: "die Tomate, die Tomaten", hungarian: "a paradicsom" },
  { german: "die Zwiebel, die Zwiebeln", hungarian: "a hagyma" },
  { german: "der Knoblauch, die Knoblauche", hungarian: "a fokhagyma" },
  { german: "die Karotte, die Karotten", hungarian: "a répa" },
  { german: "der Salat, die Salate", hungarian: "a saláta" },
  { german: "die Suppe, die Suppen", hungarian: "a leves" },
  { german: "das Fleisch, -", hungarian: "a hús" },
  { german: "der Fisch, die Fische", hungarian: "a hal" },
  { german: "das Hähnchen, die Hähnchen", hungarian: "a csirke" },
  { german: "die Wurst, die Würste", hungarian: "a kolbász" },

  // --- QUIZ 25: B1 Animals ---
  { german: "das Tier, die Tiere", hungarian: "az állat" },
  { german: "das Haustier, die Haustiere", hungarian: "a háziállat" },
  { german: "der Vogel, die Vögel", hungarian: "a madár" },
  { german: "der Fisch, die Fische", hungarian: "a hal" },
  { german: "das Insekt, die Insekten", hungarian: "a rovar" },
  { german: "die Spinne, die Spinnen", hungarian: "a pók" },
  { german: "die Fliege, die Fliegen", hungarian: "a légy" },
  { german: "die Mücke, die Mücken", hungarian: "a szúnyog" },
  { german: "die Biene, die Bienen", hungarian: "a méh" },
  { german: "der Schmetterling, die Schmetterlinge", hungarian: "a pillangó" },
  { german: "die Maus, die Mäuse", hungarian: "az egér" },
  { german: "die Ratte, die Ratten", hungarian: "a patkány" },
  { german: "der Bär, die Bären", hungarian: "a medve" },
  { german: "der Wolf, die Wölfe", hungarian: "a farkas" },
  { german: "der Fuchs, die Füchse", hungarian: "a róka" },
  { german: "der Hase, die Hasen", hungarian: "a nyúl" },
  { german: "das Kaninchen, die Kaninchen", hungarian: "a házinyúl" },
  { german: "der Affe, die Affen", hungarian: "a majom" },
  { german: "der Elefant, die Elefanten", hungarian: "az elefánt" },
  { german: "der Löwe, die Löwen", hungarian: "az oroszlán" },

  // --- QUIZ 26: B1 City & Transport ---
  { german: "die Ampel, die Ampeln", hungarian: "a közlekedési lámpa" },
  { german: "die Kreuzung, die Kreuzungen", hungarian: "a kereszteződés" },
  { german: "die Ecke, die Ecken", hungarian: "a sarok" },
  { german: "der Bürgersteig, die Bürgersteige", hungarian: "a járda" },
  { german: "der Fußgänger, die Fußgänger", hungarian: "a gyalogos" },
  { german: "der Verkehr, -", hungarian: "a forgalom" },
  { german: "der Stau, die Staus", hungarian: "a dugó" },
  { german: "der Unfall, die Unfälle", hungarian: "a baleset" },
  { german: "die Haltestelle, die Haltestellen", hungarian: "a megálló" },
  { german: "die Station, die Stationen", hungarian: "az állomás" },
  { german: "die Fahrkarte, die Fahrkarten", hungarian: "a menetjegy" },
  { german: "der Automat, die Automaten", hungarian: "az automata" },
  { german: "der Fahrplan, die Fahrpläne", hungarian: "a menetrend" },
  { german: "das Gleis, die Gleise", hungarian: "a vágány" },
  { german: "der Bahnsteig, die Bahnsteige", hungarian: "a peron" },
  { german: "der Passagier, die Passagiere", hungarian: "az utas" },
  { german: "das Gepäck, -", hungarian: "a csomag / poggyász" },
  { german: "der Koffer, die Koffer", hungarian: "a bőrönd" },
  { german: "die Tasche, die Taschen", hungarian: "a táska" },
  { german: "der Rucksack, die Rucksäcke", hungarian: "a hátizsák" },

  // --- QUIZ 27: B2 Professions & Work ---
  { german: "der Mitarbeiter, die Mitarbeiter", hungarian: "a munkatárs" },
  { german: "die Besprechung, die Besprechungen", hungarian: "a megbeszélés" },
  { german: "der Termin, die Termine", hungarian: "az időpont" },
  { german: "das Gehalt, die Gehälter", hungarian: "a fizetés" },
  { german: "der Lohn, die Löhne", hungarian: "a bér" },
  { german: "die Steuer, die Steuern", hungarian: "az adó" },
  { german: "die Bewerbung, die Bewerbungen", hungarian: "a pályázat" },
  { german: "der Lebenslauf, die Lebensläufe", hungarian: "az önéletrajz" },
  { german: "das Vorstellungsgespräch, die Vorstellungsgespräche", hungarian: "az állásinterjú" },
  { german: "der Urlaub, die Urlaube", hungarian: "a szabadság" },
  { german: "der Feierabend, die Feierabende", hungarian: "a munkaidő vége" },
  { german: "die Rente, die Renten", hungarian: "a nyugdíj" },
  { german: "der Arzt, die Ärzte", hungarian: "az orvos" },
  { german: "die Krankenschwester, die Krankenschwestern", hungarian: "az ápolónő" },
  { german: "der Polizist, die Polizisten", hungarian: "a rendőr" },
  { german: "der Anwalt, die Anwälte", hungarian: "az ügyvéd" },
  { german: "der Richter, die Richter", hungarian: "a bíró" },
  { german: "der Mechaniker, die Mechaniker", hungarian: "a szerelő" },
  { german: "der Ingenieur, die Ingenieure", hungarian: "a mérnök" },
  { german: "der Architekt, die Architekten", hungarian: "az építész" },

  // --- QUIZ 28: B2 Education ---
  { german: "die Vorlesung, die Vorlesungen", hungarian: "az előadás (egyetemi)" },
  { german: "das Seminar, die Seminare", hungarian: "a szeminárium" },
  { german: "die Bibliothek, die Bibliotheken", hungarian: "a könyvtár" },
  { german: "die Mensa, die Mensen", hungarian: "az egyetemi menza" },
  { german: "der Dozent, die Dozenten", hungarian: "az egyetemi oktató" },
  { german: "das Semester, die Semester", hungarian: "a félév" },
  { german: "die Klausur, die Klausuren", hungarian: "a zárthelyi dolgozat" },
  { german: "das Zeugnis, die Zeugnisse", hungarian: "a bizonyítvány" },
  { german: "der Abschluss, die Abschlüsse", hungarian: "a végzettség" },
  { german: "die Ausbildung, die Ausbildungen", hungarian: "a képzés / szakmunkásképzés" },
  { german: "die Lehre, die Lehren", hungarian: "a tanítás / inaskodás" },
  { german: "der Meister, die Meister", hungarian: "a mester" },
  { german: "der Anfänger, die Anfänger", hungarian: "a kezdő" },
  { german: "der Fortgeschrittene, die Fortgeschrittenen", hungarian: "a haladó" },
  { german: "der Kurs, die Kurse", hungarian: "a tanfolyam" },
  { german: "die Übung, die Übungen", hungarian: "a gyakorlat" },
  { german: "das Vokabular, die Vokabulare", hungarian: "a szókincs" },
  { german: "die Grammatik, die Grammatiken", hungarian: "a nyelvtan" },
  { german: "die Aussprache, die Aussprachen", hungarian: "a kiejtés" },
  { german: "die Regel, die Regeln", hungarian: "a szabály" },

  // --- QUIZ 29: B2 Abstract & Concepts ---
  { german: "das System, die Systeme", hungarian: "a rendszer" },
  { german: "die Methode, die Methoden", hungarian: "a módszer" },
  { german: "die Funktion, die Funktionen", hungarian: "a funkció" },
  { german: "die Qualität, die Qualitäten", hungarian: "a minőség" },
  { german: "die Quantität, die Quantitäten", hungarian: "a mennyiség" },
  { german: "die Form, die Formen", hungarian: "a forma" },
  { german: "die Art, die Arten", hungarian: "a fajta" },
  { german: "die Weise, die Weisen", hungarian: "a mód" },
  { german: "der Typ, die Typen", hungarian: "a típus" },
  { german: "das Detail, die Details", hungarian: "a részlet" },
  { german: "die Struktur, die Strukturen", hungarian: "a szerkezet" },
  { german: "die Basis, die Basen", hungarian: "az alap" },
  { german: "der Inhalt, die Inhalte", hungarian: "a tartalom" },
  { german: "das Material, die Materialien", hungarian: "az anyag" },
  { german: "der Stoff, die Stoffe", hungarian: "a tananyag / anyag" },
  { german: "die Ebene, die Ebenen", hungarian: "a szint / sík" },
  { german: "das Niveau, die Niveaus", hungarian: "a színvonal" },
  { german: "der Standard, die Standards", hungarian: "a standard / mérce" },
  { german: "die Norm, die Normen", hungarian: "a norma" },
  { german: "der Wert, die Werte", hungarian: "az érték" },

  // --- QUIZ 30: B2 Communication & Media ---
  { german: "der Bildschirm, die Bildschirme", hungarian: "a képernyő" },
  { german: "die Tastatur, die Tastaturen", hungarian: "a billentyűzet" },
  { german: "die Maus, die Mäuse", hungarian: "az egér (számítógép)" },
  { german: "der Drucker, die Drucker", hungarian: "a nyomtató" },
  { german: "die Datei, die Dateien", hungarian: "a fájl" },
  { german: "das Programm, die Programme", hungarian: "a program" },
  { german: "die App, die Apps", hungarian: "az alkalmazás" },
  { german: "die Webseite, die Webseiten", hungarian: "a weboldal" },
  { german: "der Link, die Links", hungarian: "a hivatkozás" },
  { german: "das Passwort, die Passwörter", hungarian: "a jelszó" },
  { german: "das Konto, die Konten", hungarian: "a fiók / bankszámla" },
  { german: "der Nutzer, die Nutzer", hungarian: "a felhasználó" },
  { german: "das Profil, die Profile", hungarian: "a profil" },
  { german: "der Beitrag, die Beiträge", hungarian: "a bejegyzés / poszt" },
  { german: "der Kommentar, die Kommentare", hungarian: "a komment" },
  { german: "die Nachricht, die Nachrichten", hungarian: "az üzenet" },
  { german: "der Brief, die Briefe", hungarian: "a levél" },
  { german: "das Paket, die Pakete", hungarian: "a csomag" },
  { german: "der Sender, die Sender", hungarian: "a küldő / adó" },
  { german: "der Empfänger, die Empfänger", hungarian: "a címzett" },
];

export const publicPhrases: PublicWord[] = [
  // --- PHRASES QUIZ 1: A1 Greetings & Basics ---
  { german: "Guten Tag!", hungarian: "Jó napot!" },
  { german: "Hallo!", hungarian: "Szia!" },
  { german: "Wie geht es Ihnen?", hungarian: "Hogy van? (formális)" },
  { german: "Wie geht's?", hungarian: "Hogy vagy?" },
  { german: "Mir geht es gut, danke.", hungarian: "Jól vagyok, köszönöm." },
  { german: "Und Ihnen?", hungarian: "És Ön? (formális)" },
  { german: "Bitte.", hungarian: "Kérem. / Szívesen." },
  { german: "Danke schön.", hungarian: "Köszönöm szépen." },
  { german: "Auf Wiedersehen.", hungarian: "Viszontlátásra." },
  { german: "Tschüss!", hungarian: "Szia! (búcsúzás)" },
  { german: "Ja.", hungarian: "Igen." },
  { german: "Nein.", hungarian: "Nem." },
  { german: "Entschuldigung.", hungarian: "Elnézést." },
  { german: "Ich heiße...", hungarian: "A nevem..." },
  { german: "Wie heißen Sie?", hungarian: "Hogy hívják? (formális)" },
  { german: "Ich komme aus Ungarn.", hungarian: "Magyarországról jöttem." },
  { german: "Woher kommen Sie?", hungarian: "Honnan jött?" },
  { german: "Ich spreche ein bisschen Deutsch.", hungarian: "Beszélek egy kicsit németül." },
  { german: "Ich verstehe nicht.", hungarian: "Nem értem." },
  { german: "Gute Nacht.", hungarian: "Jó éjszakát." },

  // --- PHRASES QUIZ 2: A1 Simple Questions ---
  { german: "Was ist das?", hungarian: "Mi ez?" },
  { german: "Wo ist die Toilette?", hungarian: "Hol van a mosdó?" },
  { german: "Wie viel kostet das?", hungarian: "Mennyibe kerül ez?" },
  { german: "Sprechen Sie Englisch?", hungarian: "Beszél angolul?" },
  { german: "Können Sie mir helfen?", hungarian: "Tudna nekem segíteni?" },
  { german: "Ich hätte gern...", hungarian: "Szeretnék..." },
  { german: "Wo ist der Bahnhof?", hungarian: "Hol van a pályaudvar?" },
  { german: "Wann fährt der nächste Zug?", hungarian: "Mikor indul a következő vonat?" },
  { german: "Ein Ticket nach Berlin, bitte.", hungarian: "Egy jegyet Berlinbe, kérem." },
  { german: "Ich bin hungrig.", hungarian: "Éhes vagyok." },
  { german: "Ich bin durstig.", hungarian: "Szomjas vagyok." },
  { german: "Die Rechnung, bitte.", hungarian: "A számlát, kérem." },
  { german: "Es tut mir leid.", hungarian: "Sajnálom." },
  { german: "Kein Problem.", hungarian: "Semmi probléma." },
  { german: "Was möchten Sie trinken?", hungarian: "Mit szeretne inni?" },
  { german: "Ich nehme ein Wasser.", hungarian: "Egy vizet kérek." },
  { german: "Wo wohnen Sie?", hungarian: "Hol lakik?" },
  { german: "Ich wohne in Budapest.", hungarian: "Budapesten lakom." },
  { german: "Was ist Ihr Beruf?", hungarian: "Mi a foglalkozása?" },
  { german: "Guten Appetit!", hungarian: "Jó étvágyat!" },

  // --- PHRASES QUIZ 3: A2 Daily Life ---
  { german: "Wie war Ihr Wochenende?", hungarian: "Milyen volt a hétvégéje?" },
  { german: "Ich muss jetzt gehen.", hungarian: "Most mennem kell." },
  { german: "Bis später!", hungarian: "Később találkozunk!" },
  { german: "Schönes Wochenende!", hungarian: "Szép hétvégét!" },
  { german: "Was machst du heute Abend?", hungarian: "Mit csinálsz ma este?" },
  { german: "Ich habe keine Zeit.", hungarian: "Nincs időm." },
  { german: "Ich bin müde.", hungarian: "Fáradt vagyok." },
  { german: "Ich gehe ins Bett.", hungarian: "Megyek aludni." },
  { german: "Kannst du das wiederholen, bitte?", hungarian: "Meg tudnád ismételni, kérlek?" },
  { german: "Das ist eine gute Idee.", hungarian: "Ez egy jó ötlet." },
  { german: "Ich bin mir nicht sicher.", hungarian: "Nem vagyok benne biztos." },
  { german: "Was ist los?", hungarian: "Mi a baj?" },
  { german: "Alles in Ordnung.", hungarian: "Minden rendben." },
  { german: "Ich rufe dich später an.", hungarian: "Később hívlak." },
  { german: "Lass uns ins Kino gehen.", hungarian: "Menjünk moziba." },
  { german: "Ich freue mich darauf.", hungarian: "Már várom." },
  { german: "Viel Glück!", hungarian: "Sok szerencsét!" },
  { german: "Herzlichen Glückwunsch!", hungarian: "Szívből gratulálok!" },
  { german: "Gesundheit!", hungarian: "Egészségedre! (tüsszentéskor)" },
  { german: "Prost!", hungarian: "Egészségedre! (koccintáskor)" },

  // --- PHRASES QUIZ 4: A2 Opinions & Feelings ---
  { german: "Ich finde das interessant.", hungarian: "Ezt érdekesnek találom." },
  { german: "Das gefällt mir.", hungarian: "Ez tetszik nekem." },
  { german: "Das mag ich nicht.", hungarian: "Ezt nem szeretem." },
  { german: "Meiner Meinung nach...", hungarian: "Véleményem szerint..." },
  { german: "Ich glaube, dass...", hungarian: "Azt hiszem, hogy..." },
  { german: "Ich habe Angst.", hungarian: "Félek." },
  { german: "Ich bin glücklich.", hungarian: "Boldog vagyok." },
  { german: "Ich bin traurig.", hungarian: "Szomorú vagyok." },
  { german: "Ich bin wütend.", hungarian: "Mérges vagyok." },
  { german: "Das ist schade.", hungarian: "Ez kár." },
  { german: "Das ist toll!", hungarian: "Ez nagyszerű!" },
  { german: "Das ist langweilig.", hungarian: "Ez unalmas." },
  { german: "Ich bin einverstanden.", hungarian: "Egyetértek." },
  { german: "Ich bin nicht einverstanden.", hungarian: "Nem értek egyet." },
  { german: "Das stimmt.", hungarian: "Ez igaz." },
  { german: "Das stimmt nicht.", hungarian: "Ez nem igaz." },
  { german: "Was denkst du darüber?", hungarian: "Mit gondolsz erről?" },
  { german: "Ich habe eine Frage.", hungarian: "Van egy kérdésem." },
  { german: "Das ist mir egal.", hungarian: "Nekem mindegy." },
  { german: "Mach dir keine Sorgen.", hungarian: "Ne aggódj." },

  // --- PHRASES QUIZ 5: B1 More Complex Interactions ---
  { german: "Könnten Sie bitte langsamer sprechen?", hungarian: "Tudna kérem lassabban beszélni?" },
  { german: "Wie schreibt man das?", hungarian: "Hogyan írják ezt?" },
  { german: "Ich würde gerne einen Tisch reservieren.", hungarian: "Szeretnék egy asztalt foglalni." },
  { german: "Haben Sie einen Tisch für zwei Personen?", hungarian: "Van asztaluk két személyre?" },
  { german: "Ich bin allergisch gegen Nüsse.", hungarian: "Allergiás vagyok a diófélékre." },
  { german: "Was können Sie empfehlen?", hungarian: "Mit tud ajánlani?" },
  { german: "Ich habe mich verlaufen.", hungarian: "Eltévedtem." },
  { german: "Können Sie mir den Weg zeigen?", hungarian: "Meg tudná mutatni az utat?" },
  { german: "Es kommt darauf an.", hungarian: "Attól függ." },
  { german: "Im Großen und Ganzen...", hungarian: "Nagyjából és egészében..." },
  { german: "Einerseits..., andererseits...", hungarian: "Egyrészről..., másrészről..." },
  { german: "Ich habe den Bus verpasst.", hungarian: "Lekéstem a buszt." },
  { german: "Ich bin zu spät.", hungarian: "Elkéstem." },
  { german: "Das macht nichts.", hungarian: "Nem tesz semmit." },
  { german: "Darf ich Sie etwas fragen?", hungarian: "Kérdezhetek Öntől valamit?" },
  { german: "Ich habe es nicht absichtlich gemacht.", hungarian: "Nem szándékosan csináltam." },
  { german: "Das ist sehr nett von Ihnen.", hungarian: "Ez nagyon kedves Öntől." },
  { german: "Ich wünsche Ihnen einen schönen Tag.", hungarian: "Szép napot kívánok Önnek." },
  { german: "Gleichfalls.", hungarian: "Viszont." },
  { german: "Pass auf dich auf.", hungarian: "Vigyázz magadra." },

  // --- PHRASES QUIZ 6: B1 Idiomatic Expressions ---
  { german: "Ich verstehe nur Bahnhof.", hungarian: "Nekem ez kínai. (szó szerint: Csak pályaudvart értek.)" },
  { german: "Da steppt der Bär.", hungarian: "Ott aztán nagy buli van." },
  { german: "Das ist nicht mein Bier.", hungarian: "Ez nem az én asztalom." },
  { german: "Alles hat ein Ende, nur die Wurst hat zwei.", hungarian: "Mindennek vége szakad egyszer." },
  { german: "Ich drücke dir die Daumen.", hungarian: "Szorítok neked." },
  { german: "Du gehst mir auf den Keks.", hungarian: "Az agyamra mész." },
  { german: "Tomaten auf den Augen haben.", hungarian: "Nem látja a fától az erdőt." },
  { german: "Schwein haben.", hungarian: "Malaca van." },
  { german: "Jetzt mal Butter bei die Fische.", hungarian: "Térjünk a lényegre." },
  { german: "Das ist mir Wurst.", hungarian: "Nekem tök mindegy." },
  { german: "Ich habe die Nase voll.", hungarian: "Torkig vagyok vele." },
  { german: "Das ist Schnee von gestern.", hungarian: "Ez már a múlté." },
  { german: "Er hat nicht alle Tassen im Schrank.", hungarian: "Nincs ki mind a négy kereke." },
  { german: "Das Leben ist kein Ponyhof.", hungarian: "Az élet nem habostorta." },
  { german: "Wer zuerst kommt, mahlt zuerst.", hungarian: "Aki kapja, marja." },
  { german: "Jemandem einen Bären aufbinden.", hungarian: "Behúzni valakit a csőbe." },
  { german: "Die Katze im Sack kaufen.", hungarian: "Zsákbamacskát venni." },
  { german: "Zwei Fliegen mit einer Klappe schlagen.", hungarian: "Két legyet ütni egy csapásra." },
  { german: "Den Nagel auf den Kopf treffen.", hungarian: "Fején találni a szöget." },
  { german: "Aus einer Mücke einen Elefanten machen.", hungarian: "Bolhából elefántot csinálni." },

  // --- PHRASES QUIZ 7: B2 Nuanced Communication ---
  { german: "Ich bin der Meinung, dass...", hungarian: "Azon a véleményen vagyok, hogy..." },
  { german: "Ich stimme Ihnen voll und ganz zu.", hungarian: "Teljesen és egészében egyetértek Önnel." },
  { german: "Das sehe ich anders.", hungarian: "Ezt másképp látom." },
  { german: "Könnten Sie das bitte näher erläutern?", hungarian: "Kifejtené ezt kérem bővebben?" },
  { german: "Ich möchte einen Vorschlag machen.", hungarian: "Szeretnék egy javaslatot tenni." },
  { german: "Was halten Sie davon?", hungarian: "Mit szól hozzá?" },
  { german: "Das kommt nicht in Frage.", hungarian: "Szóba sem jöhet." },
  { german: "Unter vier Augen.", hungarian: "Négyszemközt." },
  { german: "Das lässt zu wünschen übrig.", hungarian: "Ez hagy némi kívánnivalót maga után." },
  { german: "Ich nehme an, dass...", hungarian: "Feltételezem, hogy..." },
  { german: "Es ist offensichtlich, dass...", hungarian: "Nyilvánvaló, hogy..." },
  { german: "Ich bezweifle, dass...", hungarian: "Kétlem, hogy..." },
  { german: "Das spielt keine Rolle.", hungarian: "Ez nem játszik szerepet." },
  { german: "Das ist leichter gesagt als getan.", hungarian: "Ezt könnyebb mondani, mint megtenni." },
  { german: "Ich habe es mir anders überlegt.", hungarian: "Meggondoltam magam." },
  { german: "Das ist eine heikle Angelegenheit.", hungarian: "Ez egy kényes ügy." },
  { german: "Ich stehe Ihnen zur Verfügung.", hungarian: "A rendelkezésére állok." },
  { german: "Lassen Sie mich das klarstellen.", hungarian: "Hadd tisztázzam ezt." },
  { german: "Das führt zu nichts.", hungarian: "Ez nem vezet sehova." },
  { german: "Ich bin mir der Konsequenzen bewusst.", hungarian: "Tudatában vagyok a következményeknek." },

  // --- PHRASES QUIZ 8: B2 Slang & Informal ---
  { german: "Was geht ab?", hungarian: "Mi a pálya? / Mizu?" },
  { german: "Geil!", hungarian: "Szuper! / Király!" },
  { german: "Krass!", hungarian: "Durva!" },
  { german: "Keinen Bock haben.", hungarian: "Nincs kedve valamihez." },
  { german: "Das ist der Hammer!", hungarian: "Ez oltári!" },
  { german: "Läuft bei dir.", hungarian: "Megy neked a szekér." },
  { german: "Ich bin fix und fertig.", hungarian: "Teljesen kivagyok." },
  { german: "Quatsch!", hungarian: "Hülyeség!" },
  { german: "Jain.", hungarian: "Is-is. (Igen is, meg nem is.)" },
  { german: "Alter!", hungarian: "Öreg! (megszólítás)" },
  { german: "Das juckt mich nicht.", hungarian: "Ez nem érdekel." },
  { german: "Null Problemo.", hungarian: "Semmi gond." },
  { german: "Passt schon.", hungarian: "Rendben van." },
  { german: "Genau.", hungarian: "Pontosan." },
  { german: "Echt?", hungarian: "Tényleg?" },
  { german: "Auf jeden Fall.", hungarian: "Mindenképpen." },
  { german: "Auf keinen Fall.", hungarian: "Semmi esetre sem." },
  { german: "Ich kann es nicht fassen.", hungarian: "Nem tudom elhinni." },
  { german: "Das geht gar nicht.", hungarian: "Ez egyáltalán nem elfogadható." },
  { german: "Chill mal!", hungarian: "Nyugi!" },

  // --- PHRASES QUIZ 9: C1 Advanced Idioms ---
  { german: "Etwas durch die Blume sagen.", hungarian: "Célzást tenni valamire." },
  { german: "Jemandem auf den Schlips treten.", hungarian: "Valakinek a tyúkszemére lépni." },
  { german: "Nicht das Gelbe vom Ei sein.", hungarian: "Nem a legjobb megoldás." },
  { german: "Seinen Senf dazugeben.", hungarian: "Mindenbe beleüti az orrát." },
  { german: "Krokodilstränen weinen.", hungarian: "Krokodilkönnyeket sírni." },
  { german: "Ein Brett vor dem Kopf haben.", hungarian: "Nehéz a felfogása." },
  { german: "Haare auf den Zähnen haben.", hungarian: "Harcias természetű." },
  { german: "Jemandem die Daumenschrauben ansetzen.", hungarian: "Nyomást gyakorolni valakire." },
  { german: "Das fünfte Rad am Wagen sein.", hungarian: "Púp a háton." },
  { german: "Sich wie ein Elefant im Porzellanladen benehmen.", hungarian: "Úgy viselkedik, mint elefánt a porcelánboltban." },
  { german: "Den Teufel an die Wand malen.", hungarian: "Az ördögöt a falra festeni." },
  { german: "Das Kind mit dem Bade ausschütten.", hungarian: "A fürdővízzel a gyereket is kiönteni." },
  { german: "Perlen vor die Säue werfen.", hungarian: "Gyöngyöt szórni a disznók elé." },
  { german: "Man soll den Tag nicht vor dem Abend loben.", hungarian: "Ne igyál előre a medve bőrére." },
  { german: "Wo sich Fuchs und Hase gute Nacht sagen.", hungarian: "Az Isten háta mögött." },
  { german: "In den sauren Apfel beißen.", hungarian: "Lenyelni a békát." },
  { german: "Um den heißen Brei herumreden.", hungarian: "Kerülgeti a forró kását." },
  { german: "Etwas auf die lange Bank schieben.", hungarian: "Halogatni valamit." },
  { german: "Ein Tropfen auf den heißen Stein.", hungarian: "Csepp a tengerben." },
  { german: "Mit dem falschen Fuß aufgestanden sein.", hungarian: "Bal lábbal kelt fel." },

  // --- PHRASES QUIZ 10: C1 Formal & Business ---
  { german: "Bezugnehmend auf unser Gespräch...", hungarian: "Hivatkozva a beszélgetésünkre..." },
  { german: "Ich möchte mich nach dem Stand der Dinge erkundigen.", hungarian: "Szeretnék érdeklődni a dolgok állása felől." },
  { german: "Wir müssen die Frist einhalten.", hungarian: "Be kell tartanunk a határidőt." },
  { german: "Ich bin für jeden Vorschlag offen.", hungarian: "Minden javaslatra nyitott vagyok." },
  { german: "Lassen Sie uns die Details besprechen.", hungarian: "Beszéljük meg a részleteket." },
  { german: "Ich werde die Angelegenheit prüfen.", hungarian: "Megvizsgálom az ügyet." },
  { german: "Ich melde mich bei Ihnen.", hungarian: "Jelentkezem Önnél." },
  { german: "Vielen Dank für Ihr Verständnis.", hungarian: "Köszönöm a megértését." },
  { german: "Mit freundlichen Grüßen", hungarian: "Üdvözlettel (levél végén)" },
  { german: "In diesem Zusammenhang...", hungarian: "Ebben az összefüggésben..." },
  { german: "Es ist von entscheidender Bedeutung.", hungarian: "Ez döntő jelentőségű." },
  { german: "Wir müssen Prioritäten setzen.", hungarian: "Prioritásokat kell felállítanunk." },
  { german: "Das übersteigt meine Kompetenzen.", hungarian: "Ez meghaladja a kompetenciámat." },
  { german: "Ich übernehme die Verantwortung.", hungarian: "Vállalom a felelősséget." },
  { german: "Das ist eine Win-Win-Situation.", hungarian: "Ez egy mindenki számára előnyös helyzet." },
  { german: "Wir sollten das Protokoll führen.", hungarian: "Vezetnünk kellene a jegyzőkönyvet." },
  { german: "Ich möchte auf einen Punkt zurückkommen.", hungarian: "Szeretnék visszatérni egy pontra." },
  { german: "Das ist nicht verhandelbar.", hungarian: "Ez nem alku tárgya." },
  { german: "Wir müssen eine Einigung erzielen.", hungarian: "Megegyezésre kell jutnunk." },
  { german: "Ich freue mich auf unsere Zusammenarbeit.", hungarian: "Örömmel várom az együttműködésünket." },

  // --- PHRASES QUIZ 11-20: Add more phrases here to reach 5000 ---
  // For brevity, the next 10 quizzes are placeholders.
  // You can continue this pattern with more specific topics.
  // Example for Quiz 11:
  { german: "Das A und O sein.", hungarian: "A legfontosabb dolog." },
  { german: "Abwarten und Tee trinken.", hungarian: "Türelmesen várni." },
  { german: "Sich aus dem Staub machen.", hungarian: "Felszívódni." },
  { german: "Bahnhof verstehen.", hungarian: "Semmit sem érteni." },
  { german: "Da beißt die Maus keinen Faden ab.", hungarian: "Ezen nincs mit változtatni." },
  { german: "Jemandem einen Korb geben.", hungarian: "Kikosarazni valakit." },
  { german: "Die Kurve kratzen.", hungarian: "Lelépni / elhúzni." },
  { german: "Auf dem Holzweg sein.", hungarian: "Téves úton járni." },
  { german: "Ins Fettnäpfchen treten.", hungarian: "Elkövetni egy baklövést." },
  { german: "Klar wie Kloßbrühe.", hungarian: "Világos, mint a nap." },
  { german: "Schlafen wie ein Murmeltier.", hungarian: "Alszik, mint a bunda." },
  { german: "Schmetterlinge im Bauch haben.", hungarian: "Pillangók vannak a hasában." },
  { german: "Unter einer Decke stecken.", hungarian: "Egy követ fújni." },
  { german: "Ein Auge zudrücken.", hungarian: "Szemet hunyni valami felett." },
  { german: "Die erste Geige spielen.", hungarian: "Övé a főszerep." },
  { german: "Hals- und Beinbruch!", hungarian: "Kéz- és lábtörést!" },
  { german: "Ich bin aus dem Häuschen.", hungarian: "Oda-vissza vagyok a boldogságtól." },
  { german: "Ins kalte Wasser springen.", hungarian: "Mélyvízbe ugrani." },
  { german: "Mein Name ist Hase, ich weiß von nichts.", hungarian: "A nevem nyúl, nem tudok semmiről." },
  { german: "Jemandem auf den Wecker gehen.", hungarian: "Valakinek az idegeire menni." },
  // ... continue for Quiz 12 through 20
];

export const publicArticles: PublicWord[] = [
  { german: "der Mann, die Männer", hungarian: "a férfi", example: "Der Mann arbeitet im Büro." },
  { german: "die Frau, die Frauen", hungarian: "a nő", example: "Die Frau trinkt einen Kaffee." },
  { german: "das Kind, die Kinder", hungarian: "a gyerek", example: "Das Kind spielt im Garten." },
  { german: "das Haus, die Häuser", hungarian: "a ház", example: "Das Haus ist sehr groß." },
  { german: "der Tisch, die Tische", hungarian: "az asztal", example: "Der Tisch ist aus Holz." },
  { german: "der Stuhl, die Stühle", hungarian: "a szék", example: "Der Stuhl ist sehr bequem." },
  { german: "die Sonne, die Sonnen", hungarian: "a nap", example: "Die Sonne scheint heute." },
  { german: "der Mond, die Monde", hungarian: "a hold", example: "Der Mond ist hell." },
  { german: "das Auto, die Autos", hungarian: "az autó", example: "Das Auto fährt schnell." },
  { german: "das Buch, die Bücher", hungarian: "a könyv", example: "Ich lese ein spannendes Buch." },
  { german: "der Apfel, die Äpfel", hungarian: "az alma", example: "Der Apfel ist süß." },
  { german: "die Banane, die Bananen", hungarian: "a banán", example: "Die Banane ist gelb." },
  { german: "das Brot, die Brote", hungarian: "a kenyér", example: "Das Brot ist ganz frisch." },
  { german: "das Wasser, -", hungarian: "a víz", example: "Das Wasser ist eiskalt." },
  { german: "die Milch, -", hungarian: "a tej", example: "Die Milch ist gesund." },
  { german: "der Tag, die Tage", hungarian: "a nap (nappal)", example: "Der Tag ist schön." },
  { german: "die Nacht, die Nächte", hungarian: "az éjszaka", example: "Die Nacht ist dunkel." },
  { german: "die Woche, die Wochen", hungarian: "a hét", example: "Die Woche hat sieben Tage." },
  { german: "das Jahr, die Jahre", hungarian: "az év", example: "Das Jahr ist lang." },
  { german: "der Freund, die Freunde", hungarian: "a barát", example: "Der Freund hilft mir immer." }
];

export const publicPrepositions: PublicWord[] = [
  { german: "mit", hungarian: "val/vel", case: "Dativ", example: "Ich fahre jeden Tag mit dem Auto zur Arbeit." },
  { german: "nach", hungarian: "után", case: "Dativ", example: "Nach der Arbeit gehe ich direkt nach Hause." },
  { german: "aus", hungarian: "ból/ből", case: "Dativ", example: "Sie kommt ursprünglich aus der Türkei." },
  { german: "zu", hungarian: "hoz/hez/höz", case: "Dativ", example: "Wir gehen am Wochenende zu meiner Tante." },
  { german: "von", hungarian: "tól/től", case: "Dativ", example: "Das ist ein sehr schönes Geschenk von meinem Bruder." },
  { german: "bei", hungarian: "nál/nél", case: "Dativ", example: "Er wohnt zurzeit noch bei seinen Eltern in München." },
  { german: "für", hungarian: "ért, számára", case: "Akkusativ", example: "Dieses kleine und besondere Geschenk ist speziell für dich." },
  { german: "um", hungarian: "körül", case: "Akkusativ", example: "Wir sitzen alle gemeinsam um den großen Holztisch." },
  { german: "durch", hungarian: "át, keresztül", case: "Akkusativ", example: "Wir spazieren gemütlich durch den großen und grünen Park." },
  { german: "ohne", hungarian: "nélkül", case: "Akkusativ", example: "Ohne dich gehe ich heute Abend definitiv nicht auf die Party." },
  { german: "gegen", hungarian: "ellen", case: "Akkusativ", example: "Das schnelle Auto fuhr leider direkt gegen den alten Baum." }
];

export const publicFalseFriends: PublicWord[] = [
  { german: "das Gift, die Gifte", hungarian: "a méreg", example: "Dieses Tier produziert ein starkes Gift.", note: "Nem ajándék! (ajándék = das Geschenk)" },
  { german: "bekommen", hungarian: "kapni", example: "Ich habe ein schönes Geschenk bekommen.", note: "Nem 'válni valamivé'! (válni valamivé = werden)" },
  { german: "das Gymnasium, die Gymnasien", hungarian: "a gimnázium", example: "Meine Tochter geht auf das Gymnasium.", note: "Nem edzőterem! (edzőterem = das Fitnessstudio)" },
  { german: "der Chef, die Chefs", hungarian: "a főnök", example: "Der Chef ist heute nicht im Büro.", note: "Nem séf/szakács! (szakács = der Koch)" },
  { german: "die Rente, die Renten", hungarian: "a nyugdíj", example: "Mein Großvater bekommt schon Rente.", note: "Nem bérleti díj! (bérleti díj = die Miete)" }
];

export const WORDS_PER_QUIZ = 20;

/**
 * Returns the total number of quizzes available for a given public topic,
 * based solely on the static data arrays. Custom quizzes return Infinity.
 */
export const getTotalQuizzesForTopic = (topic: string, isCustomQuiz: boolean): number => {
  if (isCustomQuiz) return Infinity;
  if (topic === 'vocabulary') return Math.ceil(publicVocabulary.length / WORDS_PER_QUIZ);
  if (topic === 'phrases') return Math.ceil(publicPhrases.length / WORDS_PER_QUIZ);
  if (topic === 'articles') return Math.ceil(publicArticles.length / WORDS_PER_QUIZ);
  if (topic === 'prepositions') return Math.ceil(publicPrepositions.length / WORDS_PER_QUIZ);
  return Infinity;
};
