export interface PublicWord {
  german: string;
  hungarian: string;
}

export const publicVocabulary: PublicWord[] = [
  // --- QUIZ 1: A1 Basics ---
  { german: "der Mann, die Männer", hungarian: "a férfi" },
  { german: "die Frau, die Frauen", hungarian: "a nő" },
  { german: "das Kind, die Kinder", hungarian: "a gyerek" },
  { german: "das Haus, die Häuser", hungarian: "a ház" },
  { german: "das Auto, die Autos", hungarian: "az autó" },
  { german: "der Hund, die Hunde", hungarian: "a kutya" },
  { german: "die Katze, die Katzen", hungarian: "a macska" },
  { german: "der Tag, die Tage", hungarian: "a nap" },
  { german: "die Nacht, die Nächte", hungarian: "az éjszaka" },
  { german: "das Buch, die Bücher", hungarian: "a könyv" },
  { german: "der Tisch, die Tische", hungarian: "az asztal" },
  { german: "der Stuhl, die Stühle", hungarian: "a szék" },
  { german: "das Wasser, -", hungarian: "a víz" },
  { german: "das Brot, die Brote", hungarian: "a kenyér" },
  { german: "groß", hungarian: "nagy" },
  { german: "klein", hungarian: "kicsi" },
  { german: "gut", hungarian: "jó" },
  { german: "schlecht", hungarian: "rossz" },
  { german: "sein (ist)", hungarian: "lenni" },
  { german: "haben (hat)", hungarian: "birtokolni" },

  // --- QUIZ 2: A1 Everyday Life ---
  { german: "der Apfel, die Äpfel", hungarian: "az alma" },
  { german: "die Straße, die Straßen", hungarian: "az utca" },
  { german: "die Stadt, die Städte", hungarian: "a város" },
  { german: "das Geld, die Gelder", hungarian: "a pénz" },
  { german: "die Arbeit, die Arbeiten", hungarian: "a munka" },
  { german: "der Freund, die Freunde", hungarian: "a barát" },
  { german: "die Schule, die Schulen", hungarian: "az iskola" },
  { german: "der Lehrer, die Lehrer", hungarian: "a tanár" },
  { german: "das Zimmer, die Zimmer", hungarian: "a szoba" },
  { german: "das Bett, die Betten", hungarian: "az ágy" },
  { german: "machen", hungarian: "csinálni" },
  { german: "gehen", hungarian: "menni" },
  { german: "kommen", hungarian: "jönni" },
  { german: "sehen", hungarian: "látni" },
  {  german: "hören", hungarian: "hallani" },
  { german: "schnell", hungarian: "gyors" },
  { german: "langsam", hungarian: "lassú" },
  { german: "heute", hungarian: "ma" },
  { german: "morgen", hungarian: "holnap" },
  { german: "gestern", hungarian: "tegnap" },

  // --- QUIZ 3: A1 Food & Travel ---
  { german: "der Bahnhof, die Bahnhöfe", hungarian: "a pályaudvar" },
  { german: "der Zug, die Züge", hungarian: "a vonat" },
  { german: "das Ticket, die Tickets", hungarian: "a jegy" },
  { german: "das Restaurant, die Restaurants", hungarian: "az étterem" },
  { german: "das Fleisch, -", hungarian: "a hús" },
  { german: "der Käse, -", hungarian: "a sajt" },
  { german: "die Milch, -", hungarian: "a tej" },
  { german: "der Kaffee, die Kaffees", hungarian: "a kávé" },
  { german: "der Tee, die Tees", hungarian: "a tea" },
  { german: "der Morgen, die Morgen", hungarian: "a reggel" },
  { german: "der Abend, die Abende", hungarian: "az este" },
  { german: "essen", hungarian: "enni" },
  { german: "trinken", hungarian: "inni" },
  { german: "schlafen", hungarian: "aludni" },
  { german: "kaufen", hungarian: "venni (vásárolni)" },
  { german: "kochen", hungarian: "főzni" },
  { german: "heiß", hungarian: "forró" },
  { german: "kalt", hungarian: "hideg" },
  { german: "neu", hungarian: "új" },
  { german: "alt", hungarian: "régi / öreg" },

  // --- QUIZ 4: A2 Family & People ---
  { german: "die Familie, die Familien", hungarian: "a család" },
  { german: "die Eltern (Pl.)", hungarian: "a szülők" },
  { german: "der Vater, die Väter", hungarian: "az apa" },
  { german: "die Mutter, die Mütter", hungarian: "az anya" },
  { german: "der Bruder, die Brüder", hungarian: "a fiútestvér" },
  { german: "die Schwester, die Schwestern", hungarian: "a lánytestvér" },
  { german: "der Arzt, die Ärzte", hungarian: "az orvos" },
  { german: "das Krankenhaus, die Krankenhäuser", hungarian: "a kórház" },
  { german: "das Medikament, die Medikamente", hungarian: "a gyógyszer" },
  { german: "der Schmerz, die Schmerzen", hungarian: "a fájdalom" },
  { german: "wohnen", hungarian: "lakni" },
  { german: "leben", hungarian: "élni" },
  { german: "helfen", hungarian: "segíteni" },
  { german: "danken", hungarian: "megköszönni" },
  { german: "brauchen", hungarian: "szüksége van vmire" },
  { german: "krank", hungarian: "beteg" },
  { german: "gesund", hungarian: "egészséges" },
  { german: "glücklich", hungarian: "boldog" },
  { german: "traurig", hungarian: "szomorú" },
  { german: "müde", hungarian: "fáradt" },

  // --- QUIZ 5: A2 Communication ---
  { german: "die Frage, die Fragen", hungarian: "a kérdés" },
  { german: "die Antwort, die Antworten", hungarian: "a válasz" },
  { german: "das Wort, die Wörter", hungarian: "a szó" },
  { german: "der Satz, die Sätze", hungarian: "a mondat" },
  { german: "die Sprache, die Sprachen", hungarian: "a nyelv" },
  { german: "der Brief, die Briefe", hungarian: "a levél" },
  { german: "das Telefon, die Telefone", hungarian: "a telefon" },
  { german: "die Nummer, die Nummern", hungarian: "a szám" },
  { german: "fragen", hungarian: "kérdezni" },
  { german: "antworten", hungarian: "válaszolni" },
  { german: "sprechen", hungarian: "beszélni" },
  { german: "sagen", hungarian: "mondani" },
  { german: "lernen", hungarian: "tanulni" },
  { german: "verstehen", hungarian: "megérteni" },
  { german: "lesen", hungarian: "olvasni" },
  { german: "schreiben", hungarian: "írni" },
  { german: "wichtig", hungarian: "fontos" },
  { german: "richtig", hungarian: "helyes" },
  { german: "falsch", hungarian: "hamis / rossz" },
  { german: "einfach", hungarian: "egyszerű" },

  // --- QUIZ 6: A2 Directions & Places ---
  { german: "der Weg, die Wege", hungarian: "az út" },
  { german: "der Platz, die Plätze", hungarian: "a tér / a hely" },
  { german: "die Brücke, die Brücken", hungarian: "a híd" },
  { german: "das Gebäude, die Gebäude", hungarian: "az épület" },
  { german: "der Berg, die Berge", hungarian: "a hegy" },
  { german: "der Fluss, die Flüsse", hungarian: "a folyó" },
  { german: "der Wald, die Wälder", hungarian: "az erdő" },
  { german: "die Karte, die Karten", hungarian: "a térkép / a jegy" },
  { german: "das Flugzeug, die Flugzeuge", hungarian: "a repülőgép" },
  { german: "der Flughafen, die Flughäfen", hungarian: "a repülőtér" },
  { german: "fliegen", hungarian: "repülni" },
  { german: "fahren", hungarian: "utazni / vezetni" },
  { german: "suchen", hungarian: "keresni" },
  { german: "finden", hungarian: "találni" },
  { german: "warten", hungarian: "várni" },
  { german: "links", hungarian: "balra" },
  { german: "rechts", hungarian: "jobbra" },
  { german: "geradeaus", hungarian: "egyenesen" },
  { german: "weit", hungarian: "messze" },
  { german: "nah", hungarian: "közel" },

  // --- QUIZ 7: B1 Shopping & Objects ---
  { german: "das Geschäft, die Geschäfte", hungarian: "az üzlet" },
  { german: "der Preis, die Preise", hungarian: "az ár" },
  { german: "die Kleidung, die Kleidungen", hungarian: "a ruházat" },
  { german: "der Schuh, die Schuhe", hungarian: "a cipő" },
  { german: "die Tasche, die Taschen", hungarian: "a táska" },
  { german: "das Geschenk, die Geschenke", hungarian: "az ajándék" },
  { german: "der Fehler, die Fehler", hungarian: "a hiba" },
  { german: "der Computer, die Computer", hungarian: "a számítógép" },
  { german: "das Bild, die Bilder", hungarian: "a kép" },
  { german: "die Farbe, die Farben", hungarian: "a szín" },
  { german: "bezahlen", hungarian: "fizetni" },
  { german: "kosten", hungarian: "kerül vmibe" },
  { german: "tragen", hungarian: "hordani / viselni" },
  { german: "waschen", hungarian: "mosni" },
  { german: "öffnen", hungarian: "kinyitni" },
  { german: "schließen", hungarian: "bezárni" },
  { german: "teuer", hungarian: "drága" },
  { german: "billig", hungarian: "olcsó" },
  { german: "schön", hungarian: "szép" },
  { german: "hässlich", hungarian: "csúnya" },

  // --- QUIZ 8: B1 Work & Time ---
  { german: "die Zeit, die Zeiten", hungarian: "az idő" },
  { german: "die Stunde, die Stunden", hungarian: "az óra (időtartam)" },
  { german: "die Woche, die Wochen", hungarian: "a hét" },
  { german: "der Monat, die Monate", hungarian: "a hónap" },
  { german: "das Jahr, die Jahre", hungarian: "az év" },
  { german: "der Beruf, die Berufe", hungarian: "a szakma" },
  { german: "die Firma, die Firmen", hungarian: "a cég" },
  { german: "das Büro, die Büros", hungarian: "az iroda" },
  { german: "der Kollege, die Kollegen", hungarian: "a kolléga" },
  { german: "der Chef, die Chefs", hungarian: "a főnök" },
  { german: "beginnen", hungarian: "elkezdeni" },
  { german: "enden", hungarian: "befejezni" },
  { german: "arbeiten", hungarian: "dolgozni" },
  { german: "verdienen", hungarian: "pénzt keresni" },
  { german: "verkaufen", hungarian: "eladni" },
  { german: "früh", hungarian: "korán" },
  { german: "spät", hungarian: "késő" },
  { german: "oft", hungarian: "gyakran" },
  { german: "selten", hungarian: "ritkán" },
  { german: "immer", hungarian: "mindig" },

  // --- QUIZ 9: B1 Nature & Weather ---
  { german: "das Wetter, -", hungarian: "az időjárás" },
  { german: "die Sonne, die Sonnen", hungarian: "a nap (égitest)" },
  { german: "der Regen, -", hungarian: "az eső" },
  { german: "der Schnee, -", hungarian: "a hó" },
  { german: "der Wind, die Winde", hungarian: "a szél" },
  { german: "die Natur, -", hungarian: "a természet" },
  { german: "der Baum, die Bäume", hungarian: "a fa" },
  { german: "die Blume, die Blumen", hungarian: "a virág" },
  { german: "das Meer, die Meere", hungarian: "a tenger" },
  { german: "der Strand, die Strände", hungarian: "a strand" },
  { german: "scheinen", hungarian: "süt (a nap)" },
  { german: "regnen", hungarian: "esik (az eső)" },
  { german: "schneien", hungarian: "esik (a hó)" },
  { german: "wachsen", hungarian: "nőni" },
  { german: "bleiben", hungarian: "maradni" },
  { german: "warm", hungarian: "meleg" },
  { german: "kühl", hungarian: "hűvös" },
  { german: "stark", hungarian: "erős" },
  { german: "schwach", hungarian: "gyenge" },
  { german: "dunkel", hungarian: "sötét" },

  // --- QUIZ 10: B1 Daily Interactions ---
  { german: "der Fehler, die Fehler", hungarian: "a hiba" },
  { german: "die Lösung, die Lösungen", hungarian: "a megoldás" },
  { german: "die Einladung, die Einladungen", hungarian: "a meghívás" },
  { german: "das Fest, die Feste", hungarian: "az ünnep" },
  { german: "die Hilfe, -", hungarian: "a segítség" },
  { german: "die Meinung, die Meinungen", hungarian: "a vélemény" },
  { german: "das Gefühl, die Gefühle", hungarian: "az érzés" },
  { german: "die Angst, die Ängste", hungarian: "a félelem" },
  { german: "die Freude, die Freuden", hungarian: "az öröm" },
  { german: "der Traum, die Träume", hungarian: "az álom" },
  { german: "glauben", hungarian: "hinni" },
  { german: "denken", hungarian: "gondolni" },
  { german: "wissen", hungarian: "tudni" },
  { german: "hoffen", hungarian: "remélni" },
  { german: "fühlen", hungarian: "érezni" },
  { german: "lustig", hungarian: "vicces" },
  { german: "ernst", hungarian: "komoly" },
  { german: "wütend", hungarian: "mérges" },
  { german: "zufrieden", hungarian: "elégedett" },
  { german: "sicher", hungarian: "biztos" },

  // --- QUIZ 11: B2 Advanced Concepts ---
  { german: "die Entwicklung, die Entwicklungen", hungarian: "a fejlődés" },
  { german: "die Erfahrung, die Erfahrungen", hungarian: "a tapasztalat" },
  { german: "die Gesellschaft, die Gesellschaften", hungarian: "a társadalom" },
  { german: "der Zustand, die Zustände", hungarian: "az állapot" },
  { german: "die Bedingung, die Bedingungen", hungarian: "a feltétel" },
  { german: "die Bedeutung, die Bedeutungen", hungarian: "a jelentés" },
  { german: "die Möglichkeit, die Möglichkeiten", hungarian: "a lehetőség" },
  { german: "das Ergebnis, die Ergebnisse", hungarian: "az eredmény" },
  { german: "das Ziel, die Ziele", hungarian: "a cél" },
  { german: "der Grund, die Gründe", hungarian: "az ok" },
  { german: "entstehen", hungarian: "keletkezik / létrejön" },
  { german: "verändern", hungarian: "megváltoztat" },
  { german: "verbessern", hungarian: "javít" },
  { german: "vergleichen", hungarian: "összehasonlít" },
  { german: "erreichen", hungarian: "elér (célt)" },
  { german: "verschieden", hungarian: "különböző" },
  { german: "ähnlich", hungarian: "hasonló" },
  { german: "besonders", hungarian: "különösen" },
  { german: "wahrscheinlich", hungarian: "valószínűleg" },
  { german: "vielleicht", hungarian: "talán" },

  // --- QUIZ 12: B2 Media & Information ---
  { german: "die Nachricht, die Nachrichten", hungarian: "a hír" },
  { german: "der Bericht, die Berichte", hungarian: "a jelentés (beszámoló)" },
  { german: "der Artikel, die Artikel", hungarian: "a cikk" },
  { german: "der Autor, die Autoren", hungarian: "a szerző" },
  { german: "die Meinung, die Meinungen", hungarian: "a vélemény" },
  { german: "die Wahrheit, die Wahrheiten", hungarian: "az igazság" },
  { german: "das Geheimnis, die Geheimnisse", hungarian: "a titok" },
  { german: "der Beweis, die Beweise", hungarian: "a bizonyíték" },
  { german: "die Forschung, die Forschungen", hungarian: "a kutatás" },
  { german: "die Quelle, die Quellen", hungarian: "die forrás" },
  { german: "berichten", hungarian: "beszámol" },
  { german: "erklären", hungarian: "elmagyaráz" },
  { german: "beschreiben", hungarian: "leír (jellemez)" },
  { german: "diskutieren", hungarian: "megvitat" },
  { german: "behaupten", hungarian: "állít vmit" },
  { german: "aktuell", hungarian: "aktuális" },
  { german: "öffentlich", hungarian: "nyilvános" },
  { german: "privat", hungarian: "privát" },
  { german: "deutlich", hungarian: "egyértelmű" },
  { german: "heimlich", hungarian: "titkos" },

  // --- QUIZ 13: B2 Work & Economy ---
  { german: "die Wirtschaft, die Wirtschaften", hungarian: "a gazdaság" },
  { german: "das Unternehmen, die Unternehmen", hungarian: "a vállalat" },
  { german: "der Vertrag, die Verträge", hungarian: "a szerződés" },
  { german: "der Erfolg, die Erfolge", hungarian: "a siker" },
  { german: "der Verlust, die Verluste", hungarian: "a veszteség" },
  { german: "die Steuer, die Steuern", hungarian: "az adó" },
  { german: "die Versicherung, die Versicherungen", hungarian: "die biztosítás" },
  { german: "die Leistung, die Leistungen", hungarian: "a teljesítmény" },
  { german: "die Aufgabe, die Aufgaben", hungarian: "a feladat" },
  { german: "der Beruf, die Berufe", hungarian: "a hivatás" },
  { german: "verhandeln", hungarian: "tárgyalni" },
  { german: "unterschreiben", hungarian: "aláírni" },
  { german: "produzieren", hungarian: "termelni" },
  { german: "anbieten", hungarian: "kínálni" },
  { german: "bestellen", hungarian: "megrendelni" },
  { german: "erfolgreich", hungarian: "sikeres" },
  { german: "beruflich", hungarian: "szakmai" },
  { german: "finanziell", hungarian: "pénzügyi" },
  { german: "abhängig", hungarian: "függő" },
  { german: "unabhängig", hungarian: "független" },

  // --- QUIZ 14: B2 Health & Body ---
  { german: "die Gesundheit, -", hungarian: "az egészség" },
  { german: "die Krankheit, die Krankheiten", hungarian: "a betegség" },
  { german: "die Untersuchung, die Untersuchungen", hungarian: "a vizsgálat" },
  { german: "die Behandlung, die Behandlungen", hungarian: "a kezelés" },
  { german: "das Gehirn, die Gehirne", hungarian: "az agy" },
  { german: "das Herz, die Herzen", hungarian: "a szív" },
  { german: "das Blut, -", hungarian: "a vér" },
  { german: "der Muskel, die Muskeln", hungarian: "az izom" },
  { german: "der Knochen, die Knochen", hungarian: "a csont" },
  { german: "die Ernährung, -", hungarian: "a táplálkozás" },
  { german: "untersuchen", hungarian: "megvizsgál" },
  { german: "behandeln", hungarian: "kezelni" },
  { german: "heilen", hungarian: "gyógyítani" },
  { german: "leiden (an)", hungarian: "szenvedni vmitől" },
  { german: "pflegen", hungarian: "ápolni" },
  { german: "gesund", hungarian: "egészséges" },
  { german: "schädlich", hungarian: "káros" },
  { german: "tödlich", hungarian: "halálos" },
  { german: "körperlich", hungarian: "testi" },
  { german: "geistig", hungarian: "szellemi" },

  // --- QUIZ 15: C1 Abstract & Science ---
  { german: "die Erkenntnis, die Erkenntnisse", hungarian: "a felismerés" },
  { german: "die Annahme, die Annahmen", hungarian: "a feltételezés" },
  { german: "der Beweis, die Beweise", hungarian: "a bizonyíték" },
  { german: "die Ursache, die Ursachen", hungarian: "az ok (kiváltó)" },
  { german: "die Auswirkung, die Auswirkungen", hungarian: "a kihatás / következmény" },
  { german: "der Zusammenhang, die Zusammenhänge", hungarian: "az összefüggés" },
  { german: "der Prozess, die Prozesse", hungarian: "a folyamat" },
  { german: "die Struktur, die Strukturen", hungarian: "a szerkezet" },
  { german: "die Methode, die Methoden", hungarian: "a módszer" },
  { german: "das Phänomen, die Phänomene", hungarian: "a jelenség" },
  { german: "beweisen", hungarian: "bizonyítani" },
  { german: "widerlegen", hungarian: "megcáfolni" },
  { german: "bestätigen", hungarian: "megerősíteni" },
  { german: "beobachten", hungarian: "megfigyelni" },
  { german: "analysieren", hungarian: "elemezni" },
  { german: "komplex", hungarian: "bonyolult" },
  { german: "grundlegend", hungarian: "alapvető" },
  { german: "wesentlich", hungarian: "lényeges" },
  { german: "ursprünglich", hungarian: "eredeti" },
  { german: "tatsächlich", hungarian: "tényleges" },

  // --- QUIZ 16: C1 Politics & Law ---
  { german: "die Regierung, die Regierungen", hungarian: "a kormány" },
  { german: "das Gesetz, die Gesetze", hungarian: "a törvény" },
  { german: "die Wahl, die Wahlen", hungarian: "a választás" },
  { german: "die Partei, die Parteien", hungarian: "a párt" },
  { german: "der Bürger, die Bürger", hungarian: "die polgár" },
  { german: "die Mehrheit, die Mehrheiten", hungarian: "a többség" },
  { german: "die Minderheit, die Minderheiten", hungarian: "a kisebbség" },
  { german: "die Reform, die Reformen", hungarian: "a reform" },
  { german: "der Kompromiss, die Kompromisse", hungarian: "a kompromisszum" },
  { german: "das Recht, die Rechte", hungarian: "a jog" },
  { german: "wählen", hungarian: "választani" },
  { german: "beschließen", hungarian: "elhatározni / dönteni" },
  { german: "fordern", hungarian: "követelni" },
  { german: "unterstützen", hungarian: "támogatni" },
  { german: "ablehnen", hungarian: "elutasítani" },
  { german: "gesetzlich", hungarian: "törvényes" },
  { german: "gerecht", hungarian: "igazságos" },
  { german: "demokratisch", hungarian: "demokratikus" },
  { german: "konservativ", hungarian: "konzervatív" },
  { german: "liberal", hungarian: "liberális" },

  // --- QUIZ 17: C1 Environment & Technology ---
  { german: "die Umwelt, -", hungarian: "a környezet" },
  { german: "der Klimawandel, -", hungarian: "a klímaváltozás" },
  { german: "die Ressource, die Ressourcen", hungarian: "az erőforrás" },
  { german: "die Energie, die Energien", hungarian: "az energia" },
  { german: "die Verschmutzung, die Verschmutzungen", hungarian: "a szennyezés" },
  { german: "die Erfindung, die Erfindungen", hungarian: "a találmány" },
  { german: "das Gerät, die Geräte", hungarian: "a készülék" },
  { german: "der Fortschritt, die Fortschritte", hungarian: "a haladás" },
  { german: "die Vernetzung, die Vernetzungen", hungarian: "die hálózatba kötés" },
  { german: "die Maßnahme, die Maßnahmen", hungarian: "az intézkedés" },
  { german: "schützen", hungarian: "védeni" },
  { german: "verschmutzen", hungarian: "szennyezni" },
  { german: "erfinden", hungarian: "feltalálni" },
  { german: "entwickeln", hungarian: "fejleszteni" },
  { german: "speichern", hungarian: "tárolni" },
  { german: "nachhaltig", hungarian: "fenntartható" },
  { german: "effektiv", hungarian: "hatékony" },
  { german: "innovativ", hungarian: "innovatív" },
  { german: "künstlich", hungarian: "mesterséges" },
  { german: "natürlich", hungarian: "természetes" },

  // --- QUIZ 18: C1 Advanced Verbs ---
  { german: "die Entscheidung, die Entscheidungen", hungarian: "a döntés" },
  { german: "der Eindruck, die Eindrücke", hungarian: "a benyomás" },
  { german: "der Zweifel, die Zweifel", hungarian: "a kétség" },
  { german: "die Überzeugung, die Überzeugungen", hungarian: "a meggyőződés" },
  { german: "die Behauptung, die Behauptungen", hungarian: "az állítás" },
  { german: "die Forderung, die Forderungen", hungarian: "a követelés" },
  { german: "die Ablehnung, die Ablehnungen", hungarian: "az elutasítás" },
  { german: "die Erwartung, die Erwartungen", hungarian: "az elvárás" },
  { german: "der Vorschlag, die Vorschläge", hungarian: "a javaslat" },
  { german: "die Umsetzung, die Umsetzungen", hungarian: "a megvalósítás" },
  { german: "vermeiden", hungarian: "elkerülni" },
  { german: "verursachen", hungarian: "okozni" },
  { german: "verzichten (auf)", hungarian: "lemondani vmiről" },
  { german: "verbergen", hungarian: "eltitkolni" },
  { german: "vermuten", hungarian: "gyanítani / sejteni" },
  { german: "zögern", hungarian: "habozni" },
  { german: "bestätigen", hungarian: "igazolni" },
  { german: "zweifeln", hungarian: "kételkedni" },
  { german: "bewerten", hungarian: "értékelni" },
  { german: "erkennen", hungarian: "felismerni" },

  // --- QUIZ 19: C1 Advanced Adjectives & Adverbs ---
  { german: "der Schwerpunkt, die Schwerpunkte", hungarian: "a súlypont" },
  { german: "der Einfluss, die Einflüsse", hungarian: "die befolyás" },
  { german: "der Gegensatz, die Gegensätze", hungarian: "az ellentét" },
  { german: "die Ausnahme, die Ausnahmen", hungarian: "a kivétel" },
  { german: "die Regel, die Regeln", hungarian: "a szabály" },
  { german: "der Ablauf, die Abläufe", hungarian: "a lefolyás (folyamat)" },
  { german: "die Hinsicht, die Hinsichten", hungarian: "a tekintet (vmilyen szempontból)" },
  { german: "der Umfang, die Umfänge", hungarian: "a terjedelem" },
  { german: "die Eigenschaft, die Eigenschaften", hungarian: "die tulajdonság" },
  { german: "der Mangel, die Mängel", hungarian: "a hiány" },
  { german: "erheblich", hungarian: "jelentős" },
  { german: "zunehmend", hungarian: "egyre növekvő" },
  { german: "ausführlich", hungarian: "részletes" },
  { german: "vergeblich", hungarian: "hiába" },
  { german: "allmählich", hungarian: "fokozatosan" },
  { german: "zufällig", hungarian: "véletlenül" },
  {  german: "absichtlich", hungarian: "szándékosan" },
  { german: "offensichtlich", hungarian: "nyilvánvalóan" },
  { german: "vermeintlich", hungarian: "állítólagos" },
  { german: "tatsächlich", hungarian: "valójában" },

  // --- QUIZ 20: C1 Mastery Expressions ---
  { german: "die Rücksicht, -", hungarian: "a tekintet / tapintat" },
  { german: "die Zuverlässigkeit, -", hungarian: "a megbízhatóság" },
  { german: "die Verantwortung, die Verantwortungen", hungarian: "a felelősség" },
  { german: "die Voraussetzung, die Voraussetzungen", hungarian: "az előfeltétel" },
  { german: "die Leidenschaft, die Leidenschaften", hungarian: "a szenvedély" },
  { german: "die Geduld, -", hungarian: "a türelem" },
  { german: "das Vertrauen, -", hungarian: "a bizalom" },
  { german: "das Verständnis, -", hungarian: "a megértés" },
  { german: "das Verhalten, -", hungarian: "a viselkedés" },
  { german: "das Bewusstsein, -", hungarian: "a tudatosság" },
  { german: "berücksichtigen", hungarian: "figyelembe vesz" },
  { german: "vernachlässigen", hungarian: "elhanyagol" },
  { german: "rechtfertigen", hungarian: "igazol / megindokol" },
  { german: "beeinflussen", hungarian: "befolyásol" },
  { german: "gewährleisten", hungarian: "garantál" },
  { german: "unvermeidlich", hungarian: "elkerülhetetlen" },
  { german: "unberechenbar", hungarian: "kiszámíthatatlan" },
  { german: "überwiegend", hungarian: "túlnyomórészt" },
  { german: "ausschließlich", hungarian: "kizárólag" },
  { german: "schlussendlich", hungarian: "végül is" },

  // --- QUIZ 21: B1 Home & Furniture ---
  { german: "die Wand, die Wände", hungarian: "a fal" },
  { german: "der Boden, die Böden", hungarian: "a padló" },
  { german: "die Decke, die Decken", hungarian: "a mennyezet / takaró" },
  { german: "das Dach, die Dächer", hungarian: "a tető" },
  { german: "der Schrank, die Schränke", hungarian: "a szekrény" },
  { german: "das Regal, die Regale", hungarian: "a polc" },
  { german: "der Sessel, die Sessel", hungarian: "a fotel" },
  { german: "das Sofa, die Sofas", hungarian: "a kanapé" },
  { german: "der Teppich, die Teppiche", hungarian: "a szőnyeg" },
  { german: "der Spiegel, die Spiegel", hungarian: "a tükör" },
  { german: "das Handtuch, die Handtücher", hungarian: "a törölköző" },
  { german: "die Seife, die Seifen", hungarian: "a szappan" },
  { german: "die Dusche, die Duschen", hungarian: "a zuhany" },
  { german: "die Badewanne, die Badewannen", hungarian: "a fürdőkád" },
  { german: "die Küche, die Küchen", hungarian: "a konyha" },
  { german: "der Herd, die Herde", hungarian: "a tűzhely" },
  { german: "der Kühlschrank, die Kühlschränke", hungarian: "a hűtőszekrény" },
  { german: "die Spülmaschine, die Spülmaschinen", hungarian: "a mosogatógép" },
  { german: "der Teller, die Teller", hungarian: "a tányér" },
  { german: "die Tasse, die Tassen", hungarian: "a csésze" },

  // --- QUIZ 22: B1 Clothes & Accessories ---
  { german: "die Hose, die Hosen", hungarian: "a nadrág" },
  { german: "die Jacke, die Jacken", hungarian: "a dzseki" },
  { german: "der Mantel, die Mäntel", hungarian: "a kabát" },
  { german: "das Hemd, die Hemden", hungarian: "az ing" },
  { german: "das T-Shirt, die T-Shirts", hungarian: "a póló" },
  { german: "der Pullover, die Pullover", hungarian: "a pulóver" },
  { german: "der Schuh, die Schuhe", hungarian: "a cipő" },
  { german: "der Stiefel, die Stiefel", hungarian: "a csizma" },
  { german: "der Socken, die Socken", hungarian: "a zokni" },
  { german: "der Rock, die Röcke", hungarian: "a szoknya" },
  { german: "das Kleid, die Kleider", hungarian: "a ruha (női)" },
  { german: "der Anzug, die Anzüge", hungarian: "az öltöny" },
  { german: "die Krawatte, die Krawatten", hungarian: "a nyakkendő" },
  { german: "der Gürtel, die Gürtel", hungarian: "az öv" },
  { german: "die Mütze, die Mützen", hungarian: "a sapka" },
  { german: "der Hut, die Hüte", hungarian: "a kalap" },
  { german: "der Schal, die Schals", hungarian: "a sál" },
  { german: "der Handschuh, die Handschuhe", hungarian: "a kesztyű" },
  { german: "die Brille, die Brillen", hungarian: "a szemüveg" },
  { german: "die Tasche, die Taschen", hungarian: "a táska" },

  // --- QUIZ 23: B1 Body Parts ---
  { german: "der Körper, die Körper", hungarian: "a test" },
  { german: "das Haar, die Haare", hungarian: "a haj" },
  { german: "der Kopf, die Köpfe", hungarian: "a fej" },
  { german: "das Auge, die Augen", hungarian: "a szem" },
  { german: "das Ohr, die Ohren", hungarian: "a fül" },
  { german: "die Nase, die Nasen", hungarian: "az orr" },
  { german: "der Mund, die Münder", hungarian: "a száj" },
  { german: "der Zahn, die Zähne", hungarian: "a fog" },
  { german: "die Lippe, die Lippen", hungarian: "az ajak" },
  { german: "die Zunge, die Zungen", hungarian: "a nyelv (testrész)" },
  { german: "der Hals, die Hälse", hungarian: "a nyak" },
  { german: "die Schulter, die Schultern", hungarian: "a váll" },
  { german: "der Arm, die Arme", hungarian: "a kar" },
  { german: "die Hand, die Hände", hungarian: "a kéz" },
  { german: "der Finger, die Finger", hungarian: "az ujj" },
  { german: "die Brust, die Brüste", hungarian: "a mell" },
  { german: "der Rücken, die Rücken", hungarian: "a hát" },
  { german: "der Bauch, die Bäuche", hungarian: "a has" },
  { german: "das Bein, die Beine", hungarian: "a láb(szár)" },
  { german: "der Fuß, die Füße", hungarian: "a láb(fej)" },

  // --- QUIZ 24: B1 Food & Kitchen ---
  { german: "die Gabel, die Gabeln", hungarian: "a villa" },
  { german: "das Messer, die Messer", hungarian: "a kés" },
  { german: "der Löffel, die Löffel", hungarian: "a kanál" },
  { german: "das Glas, die Gläser", hungarian: "a pohár" },
  { german: "die Flasche, die Flaschen", hungarian: "az üveg / palack" },
  { german: "der Topf, die Töpfe", hungarian: "a fazék" },
  { german: "die Pfanne, die Pfannen", hungarian: "a serpenyő" },
  { german: "das Gemüse, die Gemüse", hungarian: "a zöldség" },
  { german: "das Obst, -", hungarian: "a gyümölcs" },
  { german: "die Kartoffel, die Kartoffeln", hungarian: "a krumpli" },
  { german: "die Tomate, die Tomaten", hungarian: "a paradicsom" },
  { german: "die Zwiebel, die Zwiebeln", hungarian: "a hagyma" },
  { german: "der Knoblauch, die Knoblauche", hungarian: "a fokhagyma" },
  { german: "die Karotte, die Karotten", hungarian: "a répa" },
  { german: "der Salat, die Salate", hungarian: "a saláta" },
  { german: "die Suppe, die Suppen", hungarian: "a leves" },
  { german: "das Fleisch, -", hungarian: "a hús" },
  { german: "der Fisch, die Fische", hungarian: "a hal" },
  { german: "das Hähnchen, die Hähnchen", hungarian: "a csirke" },
  { german: "die Wurst, die Würste", hungarian: "a kolbász" },

  // --- QUIZ 25: B1 Animals ---
  { german: "das Tier, die Tiere", hungarian: "az állat" },
  { german: "das Haustier, die Haustiere", hungarian: "a háziállat" },
  { german: "der Vogel, die Vögel", hungarian: "a madár" },
  { german: "der Fisch, die Fische", hungarian: "a hal" },
  { german: "das Insekt, die Insekten", hungarian: "a rovar" },
  { german: "die Spinne, die Spinnen", hungarian: "a pók" },
  { german: "die Fliege, die Fliegen", hungarian: "a légy" },
  { german: "die Mücke, die Mücken", hungarian: "a szúnyog" },
  { german: "die Biene, die Bienen", hungarian: "a méh" },
  { german: "der Schmetterling, die Schmetterlinge", hungarian: "a pillangó" },
  { german: "die Maus, die Mäuse", hungarian: "az egér" },
  { german: "die Ratte, die Ratten", hungarian: "a patkány" },
  { german: "der Bär, die Bären", hungarian: "a medve" },
  { german: "der Wolf, die Wölfe", hungarian: "a farkas" },
  { german: "der Fuchs, die Füchse", hungarian: "a róka" },
  { german: "der Hase, die Hasen", hungarian: "a nyúl" },
  { german: "das Kaninchen, die Kaninchen", hungarian: "a házinyúl" },
  { german: "der Affe, die Affen", hungarian: "a majom" },
  { german: "der Elefant, die Elefanten", hungarian: "az elefánt" },
  { german: "der Löwe, die Löwen", hungarian: "az oroszlán" },

  // --- QUIZ 26: B1 City & Transport ---
  { german: "die Ampel, die Ampeln", hungarian: "a közlekedési lámpa" },
  { german: "die Kreuzung, die Kreuzungen", hungarian: "a kereszteződés" },
  { german: "die Ecke, die Ecken", hungarian: "a sarok" },
  { german: "der Bürgersteig, die Bürgersteige", hungarian: "a járda" },
  { german: "der Fußgänger, die Fußgänger", hungarian: "a gyalogos" },
  { german: "der Verkehr, -", hungarian: "a forgalom" },
  { german: "der Stau, die Staus", hungarian: "a dugó" },
  { german: "der Unfall, die Unfälle", hungarian: "a baleset" },
  { german: "die Haltestelle, die Haltestellen", hungarian: "a megálló" },
  { german: "die Station, die Stationen", hungarian: "az állomás" },
  { german: "die Fahrkarte, die Fahrkarten", hungarian: "a menetjegy" },
  { german: "der Automat, die Automaten", hungarian: "az automata" },
  { german: "der Fahrplan, die Fahrpläne", hungarian: "a menetrend" },
  { german: "das Gleis, die Gleise", hungarian: "a vágány" },
  { german: "der Bahnsteig, die Bahnsteige", hungarian: "a peron" },
  { german: "der Passagier, die Passagiere", hungarian: "az utas" },
  { german: "das Gepäck, -", hungarian: "a csomag / poggyász" },
  { german: "der Koffer, die Koffer", hungarian: "a bőrönd" },
  { german: "die Tasche, die Taschen", hungarian: "a táska" },
  { german: "der Rucksack, die Rucksäcke", hungarian: "a hátizsák" },

  // --- QUIZ 27: B2 Professions & Work ---
  { german: "der Mitarbeiter, die Mitarbeiter", hungarian: "a munkatárs" },
  { german: "die Besprechung, die Besprechungen", hungarian: "a megbeszélés" },
  { german: "der Termin, die Termine", hungarian: "az időpont" },
  { german: "das Gehalt, die Gehälter", hungarian: "a fizetés" },
  { german: "der Lohn, die Löhne", hungarian: "a bér" },
  { german: "die Steuer, die Steuern", hungarian: "az adó" },
  { german: "die Bewerbung, die Bewerbungen", hungarian: "a pályázat" },
  { german: "der Lebenslauf, die Lebensläufe", hungarian: "az önéletrajz" },
  { german: "das Vorstellungsgespräch, die Vorstellungsgespräche", hungarian: "az állásinterjú" },
  { german: "der Urlaub, die Urlaube", hungarian: "a szabadság" },
  { german: "der Feierabend, die Feierabende", hungarian: "a munkaidő vége" },
  { german: "die Rente, die Renten", hungarian: "a nyugdíj" },
  { german: "der Arzt, die Ärzte", hungarian: "az orvos" },
  { german: "die Krankenschwester, die Krankenschwestern", hungarian: "az ápolónő" },
  { german: "der Polizist, die Polizisten", hungarian: "a rendőr" },
  { german: "der Anwalt, die Anwälte", hungarian: "az ügyvéd" },
  { german: "der Richter, die Richter", hungarian: "a bíró" },
  { german: "der Mechaniker, die Mechaniker", hungarian: "a szerelő" },
  { german: "der Ingenieur, die Ingenieure", hungarian: "a mérnök" },
  { german: "der Architekt, die Architekten", hungarian: "az építész" },

  // --- QUIZ 28: B2 Education ---
  { german: "die Vorlesung, die Vorlesungen", hungarian: "az előadás (egyetemi)" },
  { german: "das Seminar, die Seminare", hungarian: "a szeminárium" },
  { german: "die Bibliothek, die Bibliotheken", hungarian: "a könyvtár" },
  { german: "die Mensa, die Mensen", hungarian: "az egyetemi menza" },
  { german: "der Dozent, die Dozenten", hungarian: "az egyetemi oktató" },
  { german: "das Semester, die Semester", hungarian: "a félév" },
  { german: "die Klausur, die Klausuren", hungarian: "a zárthelyi dolgozat" },
  { german: "das Zeugnis, die Zeugnisse", hungarian: "a bizonyítvány" },
  { german: "der Abschluss, die Abschlüsse", hungarian: "a végzettség" },
  { german: "die Ausbildung, die Ausbildungen", hungarian: "a képzés / szakmunkásképzés" },
  { german: "die Lehre, die Lehren", hungarian: "a tanítás / inaskodás" },
  { german: "der Meister, die Meister", hungarian: "a mester" },
  { german: "der Anfänger, die Anfänger", hungarian: "a kezdő" },
  { german: "der Fortgeschrittene, die Fortgeschrittenen", hungarian: "a haladó" },
  { german: "der Kurs, die Kurse", hungarian: "a tanfolyam" },
  { german: "die Übung, die Übungen", hungarian: "a gyakorlat" },
  { german: "das Vokabular, die Vokabulare", hungarian: "a szókincs" },
  { german: "die Grammatik, die Grammatiken", hungarian: "a nyelvtan" },
  { german: "die Aussprache, die Aussprachen", hungarian: "a kiejtés" },
  { german: "die Regel, die Regeln", hungarian: "a szabály" },

  // --- QUIZ 29: B2 Abstract & Concepts ---
  { german: "das System, die Systeme", hungarian: "a rendszer" },
  { german: "die Methode, die Methoden", hungarian: "a módszer" },
  { german: "die Funktion, die Funktionen", hungarian: "a funkció" },
  { german: "die Qualität, die Qualitäten", hungarian: "a minőség" },
  { german: "die Quantität, die Quantitäten", hungarian: "a mennyiség" },
  { german: "die Form, die Formen", hungarian: "a forma" },
  { german: "die Art, die Arten", hungarian: "a fajta" },
  { german: "die Weise, die Weisen", hungarian: "a mód" },
  { german: "der Typ, die Typen", hungarian: "a típus" },
  { german: "das Detail, die Details", hungarian: "a részlet" },
  { german: "die Struktur, die Strukturen", hungarian: "a szerkezet" },
  { german: "die Basis, die Basen", hungarian: "az alap" },
  { german: "der Inhalt, die Inhalte", hungarian: "a tartalom" },
  { german: "das Material, die Materialien", hungarian: "az anyag" },
  { german: "der Stoff, die Stoffe", hungarian: "a tananyag / anyag" },
  { german: "die Ebene, die Ebenen", hungarian: "a szint / sík" },
  { german: "das Niveau, die Niveaus", hungarian: "a színvonal" },
  { german: "der Standard, die Standards", hungarian: "a standard / mérce" },
  { german: "die Norm, die Normen", hungarian: "a norma" },
  { german: "der Wert, die Werte", hungarian: "az érték" },

  // --- QUIZ 30: B2 Communication & Media ---
  { german: "der Bildschirm, die Bildschirme", hungarian: "a képernyő" },
  { german: "die Tastatur, die Tastaturen", hungarian: "a billentyűzet" },
  { german: "die Maus, die Mäuse", hungarian: "az egér (számítógép)" },
  { german: "der Drucker, die Drucker", hungarian: "a nyomtató" },
  { german: "die Datei, die Dateien", hungarian: "a fájl" },
  { german: "das Programm, die Programme", hungarian: "a program" },
  { german: "die App, die Apps", hungarian: "az alkalmazás" },
  { german: "die Webseite, die Webseiten", hungarian: "a weboldal" },
  { german: "der Link, die Links", hungarian: "a hivatkozás" },
  { german: "das Passwort, die Passwörter", hungarian: "a jelszó" },
  { german: "das Konto, die Konten", hungarian: "a fiók / bankszámla" },
  { german: "der Nutzer, die Nutzer", hungarian: "a felhasználó" },
  { german: "das Profil, die Profile", hungarian: "a profil" },
  { german: "der Beitrag, die Beiträge", hungarian: "a bejegyzés / poszt" },
  { german: "der Kommentar, die Kommentare", hungarian: "a komment" },
  { german: "die Nachricht, die Nachrichten", hungarian: "az üzenet" },
  { german: "der Brief, die Briefe", hungarian: "a levél" },
  { german: "das Paket, die Pakete", hungarian: "a csomag" },
  { german: "der Sender, die Sender", hungarian: "a küldő / adó" },
  { german: "der Empfänger, die Empfänger", hungarian: "a címzett" },
];

export const publicPhrases: PublicWord[] = [
  // --- PHRASES QUIZ 1: A1 Greetings & Basics ---
  { german: "Guten Tag!", hungarian: "Jó napot!" },
  { german: "Hallo!", hungarian: "Szia!" },
  { german: "Wie geht es Ihnen?", hungarian: "Hogy van? (formális)" },
  { german: "Wie geht's?", hungarian: "Hogy vagy?" },
  { german: "Mir geht es gut, danke.", hungarian: "Jól vagyok, köszönöm." },
  { german: "Und Ihnen?", hungarian: "És Ön? (formális)" },
  { german: "Bitte.", hungarian: "Kérem. / Szívesen." },
  { german: "Danke schön.", hungarian: "Köszönöm szépen." },
  { german: "Auf Wiedersehen.", hungarian: "Viszontlátásra." },
  { german: "Tschüss!", hungarian: "Szia! (búcsúzás)" },
  { german: "Ja.", hungarian: "Igen." },
  { german: "Nein.", hungarian: "Nem." },
  { german: "Entschuldigung.", hungarian: "Elnézést." },
  { german: "Ich heiße...", hungarian: "A nevem..." },
  { german: "Wie heißen Sie?", hungarian: "Hogy hívják? (formális)" },
  { german: "Ich komme aus Ungarn.", hungarian: "Magyarországról jöttem." },
  { german: "Woher kommen Sie?", hungarian: "Honnan jött?" },
  { german: "Ich spreche ein bisschen Deutsch.", hungarian: "Beszélek egy kicsit németül." },
  { german: "Ich verstehe nicht.", hungarian: "Nem értem." },
  { german: "Gute Nacht.", hungarian: "Jó éjszakát." },

  // --- PHRASES QUIZ 2: A1 Simple Questions ---
  { german: "Was ist das?", hungarian: "Mi ez?" },
  { german: "Wo ist die Toilette?", hungarian: "Hol van a mosdó?" },
  { german: "Wie viel kostet das?", hungarian: "Mennyibe kerül ez?" },
  { german: "Sprechen Sie Englisch?", hungarian: "Beszél angolul?" },
  { german: "Können Sie mir helfen?", hungarian: "Tudna nekem segíteni?" },
  { german: "Ich hätte gern...", hungarian: "Szeretnék..." },
  { german: "Wo ist der Bahnhof?", hungarian: "Hol van a pályaudvar?" },
  { german: "Wann fährt der nächste Zug?", hungarian: "Mikor indul a következő vonat?" },
  { german: "Ein Ticket nach Berlin, bitte.", hungarian: "Egy jegyet Berlinbe, kérem." },
  { german: "Ich bin hungrig.", hungarian: "Éhes vagyok." },
  { german: "Ich bin durstig.", hungarian: "Szomjas vagyok." },
  { german: "Die Rechnung, bitte.", hungarian: "A számlát, kérem." },
  { german: "Es tut mir leid.", hungarian: "Sajnálom." },
  { german: "Kein Problem.", hungarian: "Semmi probléma." },
  { german: "Was möchten Sie trinken?", hungarian: "Mit szeretne inni?" },
  { german: "Ich nehme ein Wasser.", hungarian: "Egy vizet kérek." },
  { german: "Wo wohnen Sie?", hungarian: "Hol lakik?" },
  { german: "Ich wohne in Budapest.", hungarian: "Budapesten lakom." },
  { german: "Was ist Ihr Beruf?", hungarian: "Mi a foglalkozása?" },
  { german: "Guten Appetit!", hungarian: "Jó étvágyat!" },

  // --- PHRASES QUIZ 3: A2 Daily Life ---
  { german: "Wie war Ihr Wochenende?", hungarian: "Milyen volt a hétvégéje?" },
  { german: "Ich muss jetzt gehen.", hungarian: "Most mennem kell." },
  { german: "Bis später!", hungarian: "Később találkozunk!" },
  { german: "Schönes Wochenende!", hungarian: "Szép hétvégét!" },
  { german: "Was machst du heute Abend?", hungarian: "Mit csinálsz ma este?" },
  { german: "Ich habe keine Zeit.", hungarian: "Nincs időm." },
  { german: "Ich bin müde.", hungarian: "Fáradt vagyok." },
  { german: "Ich gehe ins Bett.", hungarian: "Megyek aludni." },
  { german: "Kannst du das wiederholen, bitte?", hungarian: "Meg tudnád ismételni, kérlek?" },
  { german: "Das ist eine gute Idee.", hungarian: "Ez egy jó ötlet." },
  { german: "Ich bin mir nicht sicher.", hungarian: "Nem vagyok benne biztos." },
  { german: "Was ist los?", hungarian: "Mi a baj?" },
  { german: "Alles in Ordnung.", hungarian: "Minden rendben." },
  { german: "Ich rufe dich später an.", hungarian: "Később hívlak." },
  { german: "Lass uns ins Kino gehen.", hungarian: "Menjünk moziba." },
  { german: "Ich freue mich darauf.", hungarian: "Már várom." },
  { german: "Viel Glück!", hungarian: "Sok szerencsét!" },
  { german: "Herzlichen Glückwunsch!", hungarian: "Szívből gratulálok!" },
  { german: "Gesundheit!", hungarian: "Egészségedre! (tüsszentéskor)" },
  { german: "Prost!", hungarian: "Egészségedre! (koccintáskor)" },

  // --- PHRASES QUIZ 4: A2 Opinions & Feelings ---
  { german: "Ich finde das interessant.", hungarian: "Ezt érdekesnek találom." },
  { german: "Das gefällt mir.", hungarian: "Ez tetszik nekem." },
  { german: "Das mag ich nicht.", hungarian: "Ezt nem szeretem." },
  { german: "Meiner Meinung nach...", hungarian: "Véleményem szerint..." },
  { german: "Ich glaube, dass...", hungarian: "Azt hiszem, hogy..." },
  { german: "Ich habe Angst.", hungarian: "Félek." },
  { german: "Ich bin glücklich.", hungarian: "Boldog vagyok." },
  { german: "Ich bin traurig.", hungarian: "Szomorú vagyok." },
  { german: "Ich bin wütend.", hungarian: "Mérges vagyok." },
  { german: "Das ist schade.", hungarian: "Ez kár." },
  { german: "Das ist toll!", hungarian: "Ez nagyszerű!" },
  { german: "Das ist langweilig.", hungarian: "Ez unalmas." },
  { german: "Ich bin einverstanden.", hungarian: "Egyetértek." },
  { german: "Ich bin nicht einverstanden.", hungarian: "Nem értek egyet." },
  { german: "Das stimmt.", hungarian: "Ez igaz." },
  { german: "Das stimmt nicht.", hungarian: "Ez nem igaz." },
  { german: "Was denkst du darüber?", hungarian: "Mit gondolsz erről?" },
  { german: "Ich habe eine Frage.", hungarian: "Van egy kérdésem." },
  { german: "Das ist mir egal.", hungarian: "Nekem mindegy." },
  { german: "Mach dir keine Sorgen.", hungarian: "Ne aggódj." },

  // --- PHRASES QUIZ 5: B1 More Complex Interactions ---
  { german: "Könnten Sie bitte langsamer sprechen?", hungarian: "Tudna kérem lassabban beszélni?" },
  { german: "Wie schreibt man das?", hungarian: "Hogyan írják ezt?" },
  { german: "Ich würde gerne einen Tisch reservieren.", hungarian: "Szeretnék egy asztalt foglalni." },
  { german: "Haben Sie einen Tisch für zwei Personen?", hungarian: "Van asztaluk két személyre?" },
  { german: "Ich bin allergisch gegen Nüsse.", hungarian: "Allergiás vagyok a diófélékre." },
  { german: "Was können Sie empfehlen?", hungarian: "Mit tud ajánlani?" },
  { german: "Ich habe mich verlaufen.", hungarian: "Eltévedtem." },
  { german: "Können Sie mir den Weg zeigen?", hungarian: "Meg tudná mutatni az utat?" },
  { german: "Es kommt darauf an.", hungarian: "Attól függ." },
  { german: "Im Großen und Ganzen...", hungarian: "Nagyjából és egészében..." },
  { german: "Einerseits..., andererseits...", hungarian: "Egyrészről..., másrészről..." },
  { german: "Ich habe den Bus verpasst.", hungarian: "Lekéstem a buszt." },
  { german: "Ich bin zu spät.", hungarian: "Elkéstem." },
  { german: "Das macht nichts.", hungarian: "Nem tesz semmit." },
  { german: "Darf ich Sie etwas fragen?", hungarian: "Kérdezhetek Öntől valamit?" },
  { german: "Ich habe es nicht absichtlich gemacht.", hungarian: "Nem szándékosan csináltam." },
  { german: "Das ist sehr nett von Ihnen.", hungarian: "Ez nagyon kedves Öntől." },
  { german: "Ich wünsche Ihnen einen schönen Tag.", hungarian: "Szép napot kívánok Önnek." },
  { german: "Gleichfalls.", hungarian: "Viszont." },
  { german: "Pass auf dich auf.", hungarian: "Vigyázz magadra." },

  // --- PHRASES QUIZ 6: B1 Idiomatic Expressions ---
  { german: "Ich verstehe nur Bahnhof.", hungarian: "Nekem ez kínai. (szó szerint: Csak pályaudvart értek.)" },
  { german: "Da steppt der Bär.", hungarian: "Ott aztán nagy buli van." },
  { german: "Das ist nicht mein Bier.", hungarian: "Ez nem az én asztalom." },
  { german: "Alles hat ein Ende, nur die Wurst hat zwei.", hungarian: "Mindennek vége szakad egyszer." },
  { german: "Ich drücke dir die Daumen.", hungarian: "Szorítok neked." },
  { german: "Du gehst mir auf den Keks.", hungarian: "Az agyamra mész." },
  { german: "Tomaten auf den Augen haben.", hungarian: "Nem látja a fától az erdőt." },
  { german: "Schwein haben.", hungarian: "Malaca van." },
  { german: "Jetzt mal Butter bei die Fische.", hungarian: "Térjünk a lényegre." },
  { german: "Das ist mir Wurst.", hungarian: "Nekem tök mindegy." },
  { german: "Ich habe die Nase voll.", hungarian: "Torkig vagyok vele." },
  { german: "Das ist Schnee von gestern.", hungarian: "Ez már a múlté." },
  { german: "Er hat nicht alle Tassen im Schrank.", hungarian: "Nincs ki mind a négy kereke." },
  { german: "Das Leben ist kein Ponyhof.", hungarian: "Az élet nem habostorta." },
  { german: "Wer zuerst kommt, mahlt zuerst.", hungarian: "Aki kapja, marja." },
  { german: "Jemandem einen Bären aufbinden.", hungarian: "Behúzni valakit a csőbe." },
  { german: "Die Katze im Sack kaufen.", hungarian: "Zsákbamacskát venni." },
  { german: "Zwei Fliegen mit einer Klappe schlagen.", hungarian: "Két legyet ütni egy csapásra." },
  { german: "Den Nagel auf den Kopf treffen.", hungarian: "Fején találni a szöget." },
  { german: "Aus einer Mücke einen Elefanten machen.", hungarian: "Bolhából elefántot csinálni." },

  // --- PHRASES QUIZ 7: B2 Nuanced Communication ---
  { german: "Ich bin der Meinung, dass...", hungarian: "Azon a véleményen vagyok, hogy..." },
  { german: "Ich stimme Ihnen voll und ganz zu.", hungarian: "Teljesen és egészében egyetértek Önnel." },
  { german: "Das sehe ich anders.", hungarian: "Ezt másképp látom." },
  { german: "Könnten Sie das bitte näher erläutern?", hungarian: "Kifejtené ezt kérem bővebben?" },
  { german: "Ich möchte einen Vorschlag machen.", hungarian: "Szeretnék egy javaslatot tenni." },
  { german: "Was halten Sie davon?", hungarian: "Mit szól hozzá?" },
  { german: "Das kommt nicht in Frage.", hungarian: "Szóba sem jöhet." },
  { german: "Unter vier Augen.", hungarian: "Négyszemközt." },
  { german: "Das lässt zu wünschen übrig.", hungarian: "Ez hagy némi kívánnivalót maga után." },
  { german: "Ich nehme an, dass...", hungarian: "Feltételezem, hogy..." },
  { german: "Es ist offensichtlich, dass...", hungarian: "Nyilvánvaló, hogy..." },
  { german: "Ich bezweifle, dass...", hungarian: "Kétlem, hogy..." },
  { german: "Das spielt keine Rolle.", hungarian: "Ez nem játszik szerepet." },
  { german: "Das ist leichter gesagt als getan.", hungarian: "Ezt könnyebb mondani, mint megtenni." },
  { german: "Ich habe es mir anders überlegt.", hungarian: "Meggondoltam magam." },
  { german: "Das ist eine heikle Angelegenheit.", hungarian: "Ez egy kényes ügy." },
  { german: "Ich stehe Ihnen zur Verfügung.", hungarian: "A rendelkezésére állok." },
  { german: "Lassen Sie mich das klarstellen.", hungarian: "Hadd tisztázzam ezt." },
  { german: "Das führt zu nichts.", hungarian: "Ez nem vezet sehova." },
  { german: "Ich bin mir der Konsequenzen bewusst.", hungarian: "Tudatában vagyok a következményeknek." },

  // --- PHRASES QUIZ 8: B2 Slang & Informal ---
  { german: "Was geht ab?", hungarian: "Mi a pálya? / Mizu?" },
  { german: "Geil!", hungarian: "Szuper! / Király!" },
  { german: "Krass!", hungarian: "Durva!" },
  { german: "Keinen Bock haben.", hungarian: "Nincs kedve valamihez." },
  { german: "Das ist der Hammer!", hungarian: "Ez oltári!" },
  { german: "Läuft bei dir.", hungarian: "Megy neked a szekér." },
  { german: "Ich bin fix und fertig.", hungarian: "Teljesen kivagyok." },
  { german: "Quatsch!", hungarian: "Hülyeség!" },
  { german: "Jain.", hungarian: "Is-is. (Igen is, meg nem is.)" },
  { german: "Alter!", hungarian: "Öreg! (megszólítás)" },
  { german: "Das juckt mich nicht.", hungarian: "Ez nem érdekel." },
  { german: "Null Problemo.", hungarian: "Semmi gond." },
  { german: "Passt schon.", hungarian: "Rendben van." },
  { german: "Genau.", hungarian: "Pontosan." },
  { german: "Echt?", hungarian: "Tényleg?" },
  { german: "Auf jeden Fall.", hungarian: "Mindenképpen." },
  { german: "Auf keinen Fall.", hungarian: "Semmi esetre sem." },
  { german: "Ich kann es nicht fassen.", hungarian: "Nem tudom elhinni." },
  { german: "Das geht gar nicht.", hungarian: "Ez egyáltalán nem elfogadható." },
  { german: "Chill mal!", hungarian: "Nyugi!" },

  // --- PHRASES QUIZ 9: C1 Advanced Idioms ---
  { german: "Etwas durch die Blume sagen.", hungarian: "Célzást tenni valamire." },
  { german: "Jemandem auf den Schlips treten.", hungarian: "Valakinek a tyúkszemére lépni." },
  { german: "Nicht das Gelbe vom Ei sein.", hungarian: "Nem a legjobb megoldás." },
  { german: "Seinen Senf dazugeben.", hungarian: "Mindenbe beleüti az orrát." },
  { german: "Krokodilstränen weinen.", hungarian: "Krokodilkönnyeket sírni." },
  { german: "Ein Brett vor dem Kopf haben.", hungarian: "Nehéz a felfogása." },
  { german: "Haare auf den Zähnen haben.", hungarian: "Harcias természetű." },
  { german: "Jemandem die Daumenschrauben ansetzen.", hungarian: "Nyomást gyakorolni valakire." },
  { german: "Das fünfte Rad am Wagen sein.", hungarian: "Púp a háton." },
  { german: "Sich wie ein Elefant im Porzellanladen benehmen.", hungarian: "Úgy viselkedik, mint elefánt a porcelánboltban." },
  { german: "Den Teufel an die Wand malen.", hungarian: "Az ördögöt a falra festeni." },
  { german: "Das Kind mit dem Bade ausschütten.", hungarian: "A fürdővízzel a gyereket is kiönteni." },
  { german: "Perlen vor die Säue werfen.", hungarian: "Gyöngyöt szórni a disznók elé." },
  { german: "Man soll den Tag nicht vor dem Abend loben.", hungarian: "Ne igyál előre a medve bőrére." },
  { german: "Wo sich Fuchs und Hase gute Nacht sagen.", hungarian: "Az Isten háta mögött." },
  { german: "In den sauren Apfel beißen.", hungarian: "Lenyelni a békát." },
  { german: "Um den heißen Brei herumreden.", hungarian: "Kerülgeti a forró kását." },
  { german: "Etwas auf die lange Bank schieben.", hungarian: "Halogatni valamit." },
  { german: "Ein Tropfen auf den heißen Stein.", hungarian: "Csepp a tengerben." },
  { german: "Mit dem falschen Fuß aufgestanden sein.", hungarian: "Bal lábbal kelt fel." },

  // --- PHRASES QUIZ 10: C1 Formal & Business ---
  { german: "Bezugnehmend auf unser Gespräch...", hungarian: "Hivatkozva a beszélgetésünkre..." },
  { german: "Ich möchte mich nach dem Stand der Dinge erkundigen.", hungarian: "Szeretnék érdeklődni a dolgok állása felől." },
  { german: "Wir müssen die Frist einhalten.", hungarian: "Be kell tartanunk a határidőt." },
  { german: "Ich bin für jeden Vorschlag offen.", hungarian: "Minden javaslatra nyitott vagyok." },
  { german: "Lassen Sie uns die Details besprechen.", hungarian: "Beszéljük meg a részleteket." },
  { german: "Ich werde die Angelegenheit prüfen.", hungarian: "Megvizsgálom az ügyet." },
  { german: "Ich melde mich bei Ihnen.", hungarian: "Jelentkezem Önnél." },
  { german: "Vielen Dank für Ihr Verständnis.", hungarian: "Köszönöm a megértését." },
  { german: "Mit freundlichen Grüßen", hungarian: "Üdvözlettel (levél végén)" },
  { german: "In diesem Zusammenhang...", hungarian: "Ebben az összefüggésben..." },
  { german: "Es ist von entscheidender Bedeutung.", hungarian: "Ez döntő jelentőségű." },
  { german: "Wir müssen Prioritäten setzen.", hungarian: "Prioritásokat kell felállítanunk." },
  { german: "Das übersteigt meine Kompetenzen.", hungarian: "Ez meghaladja a kompetenciámat." },
  { german: "Ich übernehme die Verantwortung.", hungarian: "Vállalom a felelősséget." },
  { german: "Das ist eine Win-Win-Situation.", hungarian: "Ez egy mindenki számára előnyös helyzet." },
  { german: "Wir sollten das Protokoll führen.", hungarian: "Vezetnünk kellene a jegyzőkönyvet." },
  { german: "Ich möchte auf einen Punkt zurückkommen.", hungarian: "Szeretnék visszatérni egy pontra." },
  { german: "Das ist nicht verhandelbar.", hungarian: "Ez nem alku tárgya." },
  { german: "Wir müssen eine Einigung erzielen.", hungarian: "Megegyezésre kell jutnunk." },
  { german: "Ich freue mich auf unsere Zusammenarbeit.", hungarian: "Örömmel várom az együttműködésünket." },

  // --- PHRASES QUIZ 11-20: Add more phrases here to reach 5000 ---
  // For brevity, the next 10 quizzes are placeholders.
  // You can continue this pattern with more specific topics.
  // Example for Quiz 11:
  { german: "Das A und O sein.", hungarian: "A legfontosabb dolog." },
  { german: "Abwarten und Tee trinken.", hungarian: "Türelmesen várni." },
  { german: "Sich aus dem Staub machen.", hungarian: "Felszívódni." },
  { german: "Bahnhof verstehen.", hungarian: "Semmit sem érteni." },
  { german: "Da beißt die Maus keinen Faden ab.", hungarian: "Ezen nincs mit változtatni." },
  { german: "Jemandem einen Korb geben.", hungarian: "Kikosarazni valakit." },
  { german: "Die Kurve kratzen.", hungarian: "Lelépni / elhúzni." },
  { german: "Auf dem Holzweg sein.", hungarian: "Téves úton járni." },
  { german: "Ins Fettnäpfchen treten.", hungarian: "Elkövetni egy baklövést." },
  { german: "Klar wie Kloßbrühe.", hungarian: "Világos, mint a nap." },
  { german: "Schlafen wie ein Murmeltier.", hungarian: "Alszik, mint a bunda." },
  { german: "Schmetterlinge im Bauch haben.", hungarian: "Pillangók vannak a hasában." },
  { german: "Unter einer Decke stecken.", hungarian: "Egy követ fújni." },
  { german: "Ein Auge zudrücken.", hungarian: "Szemet hunyni valami felett." },
  { german: "Die erste Geige spielen.", hungarian: "Övé a főszerep." },
  { german: "Hals- und Beinbruch!", hungarian: "Kéz- és lábtörést!" },
  { german: "Ich bin aus dem Häuschen.", hungarian: "Oda-vissza vagyok a boldogságtól." },
  { german: "Ins kalte Wasser springen.", hungarian: "Mélyvízbe ugrani." },
  { german: "Mein Name ist Hase, ich weiß von nichts.", hungarian: "A nevem nyúl, nem tudok semmiről." },
  { german: "Jemandem auf den Wecker gehen.", hungarian: "Valakinek az idegeire menni." },
  // ... continue for Quiz 12 through 20
];

export const publicArticles: PublicWord[] = [
  // --- ARTICLES QUIZ 1: A1 Common Nouns ---
  { german: "Mann", hungarian: "der" },
  { german: "Frau", hungarian: "die" },
  { german: "Kind", hungarian: "das" },
  { german: "Haus", hungarian: "das" },
  { german: "Tisch", hungarian: "der" },
  { german: "Stuhl", hungarian: "der" },
  { german: "Sonne", hungarian: "die" },
  { german: "Mond", hungarian: "der" },
  { german: "Auto", hungarian: "das" },
  { german: "Buch", hungarian: "das" },
  { german: "Apfel", hungarian: "der" },
  { german: "Banane", hungarian: "die" },
  { german: "Brot", hungarian: "das" },
  { german: "Wasser", hungarian: "das" },
  { german: "Milch", hungarian: "die" },
  { german: "Tag", hungarian: "der" },
  { german: "Nacht", hungarian: "die" },
  { german: "Woche", hungarian: "die" },
  { german: "Jahr", hungarian: "das" },
  { german: "Freund", hungarian: "der" },

  // --- ARTICLES QUIZ 2: A1 Places & Things ---
  { german: "Schule", hungarian: "die" },
  { german: "Lehrer", hungarian: "der" },
  { german: "Schüler", hungarian: "der" },
  { german: "Klasse", hungarian: "die" },
  { german: "Zimmer", hungarian: "das" },
  { german: "Bett", hungarian: "das" },
  { german: "Fenster", hungarian: "das" },
  { german: "Tür", hungarian: "die" },
  { german: "Stadt", hungarian: "die" },
  { german: "Land", hungarian: "das" },
  { german: "Bahnhof", hungarian: "der" },
  { german: "Zug", hungarian: "der" },
  { german: "Flugzeug", hungarian: "das" },
  { german: "Hund", hungarian: "der" },
  { german: "Katze", hungarian: "die" },
  { german: "Baum", hungarian: "der" },
  { german: "Blume", hungarian: "die" },
  { german: "Garten", hungarian: "der" },
  { german: "Straße", hungarian: "die" },
  { german: "Weg", hungarian: "der" },

  // --- ARTICLES QUIZ 3: A1 Food & Body ---
  { german: "Kaffee", hungarian: "der" },
  { german: "Tee", hungarian: "der" },
  { german: "Käse", hungarian: "der" },
  { german: "Fisch", hungarian: "der" },
  { german: "Fleisch", hungarian: "das" },
  { german: "Ei", hungarian: "das" },
  { german: "Salz", hungarian: "das" },
  { german: "Zucker", hungarian: "der" },
  { german: "Kopf", hungarian: "der" },
  { german: "Auge", hungarian: "das" },
  { german: "Nase", hungarian: "die" },
  { german: "Mund", hungarian: "der" },
  { german: "Hand", hungarian: "die" },
  { german: "Fuß", hungarian: "der" },
  { german: "Arm", hungarian: "der" },
  { german: "Bein", hungarian: "das" },
  { german: "Herz", hungarian: "das" },
  { german: "Blut", hungarian: "das" },
  { german: "Morgen", hungarian: "der" },
  { german: "Abend", hungarian: "der" },

  // --- ARTICLES QUIZ 4: A2 Everyday Objects ---
  { german: "Computer", hungarian: "der" },
  { german: "Bildschirm", hungarian: "der" },
  { german: "Tastatur", hungarian: "die" },
  { german: "Maus", hungarian: "die" },
  { german: "Telefon", hungarian: "das" },
  { german: "Handy", hungarian: "das" },
  { german: "Tasche", hungarian: "die" },
  { german: "Schlüssel", hungarian: "der" },
  { german: "Geld", hungarian: "das" },
  { german: "Portemonnaie", hungarian: "das" },
  { german: "Brille", hungarian: "die" },
  { german: "Uhr", hungarian: "die" },
  { german: "Jacke", hungarian: "die" },
  { german: "Hose", hungarian: "die" },
  { german: "Schuh", hungarian: "der" },
  { german: "Licht", hungarian: "das" },
  { german: "Lampe", hungarian: "die" },
  { german: "Papier", hungarian: "das" },
  { german: "Stift", hungarian: "der" },
  { german: "Bild", hungarian: "das" },

  // --- ARTICLES QUIZ 5: A2 Family & People ---
  { german: "Familie", hungarian: "die" },
  { german: "Eltern", hungarian: "die" },
  { german: "Vater", hungarian: "der" },
  { german: "Mutter", hungarian: "die" },
  { german: "Bruder", hungarian: "der" },
  { german: "Schwester", hungarian: "die" },
  { german: "Sohn", hungarian: "der" },
  { german: "Tochter", hungarian: "die" },
  { german: "Großvater", hungarian: "der" },
  { german: "Großmutter", hungarian: "die" },
  { german: "Onkel", hungarian: "der" },
  { german: "Tante", hungarian: "die" },
  { german: "Cousin", hungarian: "der" },
  { german: "Cousine", hungarian: "die" },
  { german: "Mensch", hungarian: "der" },
  { german: "Person", hungarian: "die" },
  { german: "Baby", hungarian: "das" },
  { german: "Junge", hungarian: "der" },
  { german: "Mädchen", hungarian: "das" },
  { german: "Nachbar", hungarian: "der" },

  // --- ARTICLES QUIZ 6: B1 Abstract Nouns ---
  { german: "Zeit", hungarian: "die" },
  { german: "Liebe", hungarian: "die" },
  { german: "Leben", hungarian: "das" },
  { german: "Glück", hungarian: "das" },
  { german: "Angst", hungarian: "die" },
  { german: "Hilfe", hungarian: "die" },
  { german: "Frage", hungarian: "die" },
  { german: "Antwort", hungarian: "die" },
  { german: "Idee", hungarian: "die" },
  { german: "Problem", hungarian: "das" },
  { german: "Lösung", hungarian: "die" },
  { german: "Grund", hungarian: "der" },
  { german: "Wahrheit", hungarian: "die" },
  { german: "Lüge", hungarian: "die" },
  { german: "Traum", hungarian: "der" },
  { german: "Hoffnung", hungarian: "die" },
  { german: "Gedanke", hungarian: "der" },
  { german: "Gefühl", hungarian: "das" },
  { german: "Sinn", hungarian: "der" },
  { german: "Zweifel", hungarian: "der" },

  // --- ARTICLES QUIZ 7: B1 Work & Study ---
  { german: "Arbeit", hungarian: "die" },
  { german: "Beruf", hungarian: "der" },
  { german: "Firma", hungarian: "die" },
  { german: "Büro", hungarian: "das" },
  { german: "Kollege", hungarian: "der" },
  { german: "Chef", hungarian: "der" },
  { german: "Gehalt", hungarian: "das" },
  { german: "Vertrag", hungarian: "der" },
  { german: "Universität", hungarian: "die" },
  { german: "Studium", hungarian: "das" },
  { german: "Professor", hungarian: "der" },
  { german: "Student", hungarian: "der" },
  { german: "Prüfung", hungarian: "die" },
  { german: "Note", hungarian: "die" },
  { german: "Fach", hungarian: "das" },
  { german: "Hausaufgabe", hungarian: "die" },
  { german: "Projekt", hungarian: "das" },
  { german: "Erfolg", hungarian: "der" },
  { german: "Fehler", hungarian: "der" },
  { german: "Erfahrung", hungarian: "die" },

  // --- ARTICLES QUIZ 8: B1 Nature & Environment ---
  { german: "Natur", hungarian: "die" },
  { german: "Umwelt", hungarian: "die" },
  { german: "Wetter", hungarian: "das" },
  { german: "Himmel", hungarian: "der" },
  { german: "Wolke", hungarian: "die" },
  { german: "Regen", hungarian: "der" },
  { german: "Schnee", hungarian: "der" },
  { german: "Wind", hungarian: "der" },
  { german: "Berg", hungarian: "der" },
  { german: "Fluss", hungarian: "der" },
  { german: "See", hungarian: "der" },
  { german: "Meer", hungarian: "das" },
  { german: "Wald", hungarian: "der" },
  { german: "Feld", hungarian: "das" },
  { german: "Tier", hungarian: "das" },
  { german: "Pflanze", hungarian: "die" },
  { german: "Stein", hungarian: "der" },
  { german: "Luft", hungarian: "die" },
  { german: "Feuer", hungarian: "das" },
  { german: "Erde", hungarian: "die" },

  // --- ARTICLES QUIZ 9: B2 Society & Politics ---
  { german: "Gesellschaft", hungarian: "die" },
  { german: "Regierung", hungarian: "die" },
  { german: "Gesetz", hungarian: "das" },
  { german: "Recht", hungarian: "das" },
  { german: "Politik", hungarian: "die" },
  { german: "Wahl", hungarian: "die" },
  { german: "Bürger", hungarian: "der" },
  { german: "Staat", hungarian: "der" },
  { german: "Freiheit", hungarian: "die" },
  { german: "Gerechtigkeit", hungarian: "die" },
  { german: "Frieden", hungarian: "der" },
  { german: "Krieg", hungarian: "der" },
  { german: "Wirtschaft", hungarian: "die" },
  { german: "Industrie", hungarian: "die" },
  { german: "Handel", hungarian: "der" },
  { german: "Kultur", hungarian: "die" },
  { german: "Kunst", hungarian: "die" },
  { german: "Musik", hungarian: "die" },
  { german: "Geschichte", hungarian: "die" },
  { german: "Zukunft", hungarian: "die" },

  // --- ARTICLES QUIZ 10: B2 Technology & Science ---
  { german: "Technik", hungarian: "die" },
  { german: "Wissenschaft", hungarian: "die" },
  { german: "Forschung", hungarian: "die" },
  { german: "Entwicklung", hungarian: "die" },
  { german: "Fortschritt", hungarian: "der" },
  { german: "Maschine", hungarian: "die" },
  { german: "Gerät", hungarian: "das" },
  { german: "System", hungarian: "das" },
  { german: "Netzwerk", hungarian: "das" },
  { german: "Internet", hungarian: "das" },
  { german: "Energie", hungarian: "die" },
  { german: "Strom", hungarian: "der" },
  { german: "Medizin", hungarian: "die" },
  { german: "Krankheit", hungarian: "die" },
  { german: "Gesundheit", hungarian: "die" },
  { german: "Körper", hungarian: "der" },
  { german: "Geist", hungarian: "der" },
  { german: "Seele", hungarian: "die" },
  { german: "Raum", hungarian: "der" },
  { german: "Universum", hungarian: "das" },

  // --- ARTICLES QUIZ 11: Nouns with -ung, -heit, -keit ---
  { german: "Meinung", hungarian: "die" },
  { german: "Bedeutung", hungarian: "die" },
  { german: "Wohnung", hungarian: "die" },
  { german: "Zeitung", hungarian: "die" },
  { german: "Heizung", hungarian: "die" },
  { german: "Rechnung", hungarian: "die" },
  { german: "Übung", hungarian: "die" },
  { german: "Schönheit", hungarian: "die" },
  { german: "Dummheit", hungarian: "die" },
  { german: "Möglichkeit", hungarian: "die" },
  { german: "Schwierigkeit", hungarian: "die" },
  { german: "Wirklichkeit", hungarian: "die" },
  { german: "Geschwindigkeit", hungarian: "die" },
  { german: "Sicherheit", hungarian: "die" },
  { german: "Fähigkeit", hungarian: "die" },
  { german: "Vergangenheit", hungarian: "die" },
  { german: "Gegenwart", hungarian: "die" },
  { german: "Einheit", hungarian: "die" },
  { german: "Minderheit", hungarian: "die" },
  { german: "Mehrheit", hungarian: "die" },

  // --- ARTICLES QUIZ 12: Nouns with -er, -ler, -ner ---
  { german: "Fahrer", hungarian: "der" },
  { german: "Bäcker", hungarian: "der" },
  { german: "Künstler", hungarian: "der" },
  { german: "Wissenschaftler", hungarian: "der" },
  { german: "Sportler", hungarian: "der" },
  { german: "Gärtner", hungarian: "der" },
  { german: "Rentner", hungarian: "der" },
  { german: "Amerikaner", hungarian: "der" },
  { german: "Italiener", hungarian: "der" },
  { german: "Gegner", hungarian: "der" },
  { german: "Partner", hungarian: "der" },
  { german: "Fehler", hungarian: "der" },
  { german: "Sommer", hungarian: "der" },
  { german: "Winter", hungarian: "der" },
  { german: "Finger", hungarian: "der" },
  { german: "Teller", hungarian: "der" },
  { german: "Keller", hungarian: "der" },
  { german: "Hammer", hungarian: "der" },
  { german: "Zweifel", hungarian: "der" },
  { german: "Spiegel", hungarian: "der" },

  // --- ARTICLES QUIZ 13: Nouns with -chen, -lein, -ment, -um ---
  { german: "Mädchen", hungarian: "das" },
  { german: "Brötchen", hungarian: "das" },
  { german: "Hündchen", hungarian: "das" },
  { german: "Kätzchen", hungarian: "das" },
  { german: "Fräulein", hungarian: "das" },
  { german: "Büchlein", hungarian: "das" },
  { german: "Tischlein", hungarian: "das" },
  { german: "Männlein", hungarian: "das" },
  { german: "Dokument", hungarian: "das" },
  { german: "Instrument", hungarian: "das" },
  { german: "Experiment", hungarian: "das" },
  { german: "Argument", hungarian: "das" },
  { german: "Element", hungarian: "das" },
  { german: "Parlament", hungarian: "das" },
  { german: "Datum", hungarian: "das" },
  { german: "Museum", hungarian: "das" },
  { german: "Zentrum", hungarian: "das" },
  { german: "Album", hungarian: "das" },
  { german: "Publikum", hungarian: "das" },
  { german: "Stadium", hungarian: "das" },

  // --- ARTICLES QUIZ 14: Nouns with -ling, -ig, -ich ---
  { german: "Schmetterling", hungarian: "der" },
  { german: "Lehrling", hungarian: "der" },
  { german: "Frühling", hungarian: "der" },
  { german: "Flüchtling", hungarian: "der" },
  { german: "Zwilling", hungarian: "der" },
  { german: "Häftling", hungarian: "der" },
  { german: "Liebling", hungarian: "der" },
  { german: "König", hungarian: "der" },
  { german: "Honig", hungarian: "der" },
  { german: "Essig", hungarian: "der" },
  { german: "Käfig", hungarian: "der" },
  { german: "Teppich", hungarian: "der" },
  { german: "Strich", hungarian: "der" },
  { german: "Bereich", hungarian: "der" },
  { german: "Vergleich", hungarian: "der" },
  { german: "Pfirsich", hungarian: "der" },
  { german: "Rettich", hungarian: "der" },
  { german: "Teich", hungarian: "der" },
  { german: "Geruch", hungarian: "der" },
  { german: "Besuch", hungarian: "der" },

  // --- ARTICLES QUIZ 15: Nouns with -schaft, -tät, -ion ---
  { german: "Freundschaft", hungarian: "die" },
  { german: "Mannschaft", hungarian: "die" },
  { german: "Landschaft", hungarian: "die" },
  { german: "Wissenschaft", hungarian: "die" },
  { german: "Botschaft", hungarian: "die" },
  { german: "Leidenschaft", hungarian: "die" },
  { german: "Eigenschaft", hungarian: "die" },
  { german: "Qualität", hungarian: "die" },
  { german: "Realität", hungarian: "die" },
  { german: "Aktivität", hungarian: "die" },
  { german: "Nationalität", hungarian: "die" },
  { german: "Flexibilität", hungarian: "die" },
  { german: "Station", hungarian: "die" },
  { german: "Aktion", hungarian: "die" },
  { german: "Information", hungarian: "die" },
  { german: "Diskussion", hungarian: "die" },
  { german: "Situation", hungarian: "die" },
  { german: "Position", hungarian: "die" },
  { german: "Region", hungarian: "die" },
  { german: "Religion", hungarian: "die" },

  // --- ARTICLES QUIZ 16: C1 Abstract & Complex ---
  { german: "Verständnis", hungarian: "das" },
  { german: "Ergebnis", hungarian: "das" },
  { german: "Geheimnis", hungarian: "das" },
  { german: "Verhältnis", hungarian: "das" },
  { german: "Ereignis", hungarian: "das" },
  { german: "Bedürfnis", hungarian: "das" },
  { german: "Gewissen", hungarian: "das" },
  { german: "Bewusstsein", hungarian: "das" },
  { german: "Verhalten", hungarian: "das" },
  { german: "Wachstum", hungarian: "das" },
  { german: "Eigentum", hungarian: "das" },
  { german: "Reichtum", hungarian: "der" },
  { german: "Irrtum", hungarian: "der" },
  { german: "Charakter", hungarian: "der" },
  { german: "Mechanismus", hungarian: "der" },
  { german: "Organismus", hungarian: "der" },
  { german: "Kapitalismus", hungarian: "der" },
  { german: "Tourismus", hungarian: "der" },
  { german: "Optimismus", hungarian: "der" },
  { german: "Journalismus", hungarian: "der" },

  // --- ARTICLES QUIZ 17: C1 Foreign & Irregular ---
  { german: "Thema", hungarian: "das" },
  { german: "Drama", hungarian: "das" },
  { german: "Klima", hungarian: "das" },
  { german: "Schema", hungarian: "das" },
  { german: "System", hungarian: "das" },
  { german: "Problem", hungarian: "das" },
  { german: "Prinzip", hungarian: "das" },
  { german: "Interesse", hungarian: "das" },
  { german: "Ende", hungarian: "das" },
  { german: "Modell", hungarian: "das" },
  { german: "Hotel", hungarian: "das" },
  { german: "Kapitel", hungarian: "das" },
  { german: "Risiko", hungarian: "das" },
  { german: "Niveau", hungarian: "das" },
  { german: "Chaos", hungarian: "das" },
  { german: "Büro", hungarian: "das" },
  { german: "Konto", hungarian: "das" },
  { german: "Foto", hungarian: "das" },
  { german: "Radio", hungarian: "das" },
  { german: "Video", hungarian: "das" },

  // --- ARTICLES QUIZ 18: C1 Advanced Endings ---
  { german: "Analyse", hungarian: "die" },
  { german: "Diagnose", hungarian: "die" },
  { german: "Hypothese", hungarian: "die" },
  { german: "Synthese", hungarian: "die" },
  { german: "Krise", hungarian: "die" },
  { german: "Basis", hungarian: "die" },
  { german: "Praxis", hungarian: "die" },
  { german: "Existenz", hungarian: "die" },
  { german: "Konferenz", hungarian: "die" },
  { german: "Tendenz", hungarian: "die" },
  { german: "Distanz", hungarian: "die" },
  { german: "Substanz", hungarian: "die" },
  { german: "Kritik", hungarian: "die" },
  { german: "Logik", hungarian: "die" },
  { german: "Panik", hungarian: "die" },
  { german: "Fabrik", hungarian: "die" },
  { german: "Technik", hungarian: "die" },
  { german: "Bibliothek", hungarian: "die" },
  { german: "Apotheke", hungarian: "die" },
  { german: "Diskothek", hungarian: "die" },

  // --- ARTICLES QUIZ 19: C1 Exceptions & Tricky Nouns ---
  { german: "Glaube", hungarian: "der" },
  { german: "Friede", hungarian: "der" },
  { german: "Funke", hungarian: "der" },
  { german: "Gedanke", hungarian: "der" },
  { german: "Wille", hungarian: "der" },
  { german: "Name", hungarian: "der" },
  { german: "Buchstabe", hungarian: "der" },
  { german: "Same", hungarian: "der" },
  { german: "Käse", hungarian: "der" },
  { german: "Kunde", hungarian: "der" },
  { german: "Junge", hungarian: "der" },
  { german: "Experte", hungarian: "der" },
  { german: "Kollege", hungarian: "der" },
  { german: "Planet", hungarian: "der" },
  { german: "Satellit", hungarian: "der" },
  { german: "Polizist", hungarian: "der" },
  { german: "Architekt", hungarian: "der" },
  { german: "Patient", hungarian: "der" },
  { german: "Präsident", hungarian: "der" },
  { german: "Diamant", hungarian: "der" },

  // --- ARTICLES QUIZ 20: C1 Mastery ---
  { german: "Moment", hungarian: "der" },
  { german: "Zement", hungarian: "der" },
  { german: "Abschnitt", hungarian: "der" },
  { german: "Bericht", hungarian: "der" },
  { german: "Unterricht", hungarian: "der" },
  { german: "Verdacht", hungarian: "der" },
  { german: "Vorteil", hungarian: "der" },
  { german: "Nachteil", hungarian: "der" },
  { german: "Anteil", hungarian: "der" },
  { german: "Titel", hungarian: "der" },
  { german: "Beutel", hungarian: "der" },
  { german: "Gipfel", hungarian: "der" },
  { german: "Hügel", hungarian: "der" },
  { german: "Mantel", hungarian: "der" },
  { german: "Nebel", hungarian: "der" },
  { german: "Spiegel", hungarian: "der" },
  { german: "Vogel", hungarian: "der" },
  { german: "Ziegel", hungarian: "der" },
  { german: "Löffel", hungarian: "der" },
  { german: "Schlüssel", hungarian: "der" },
];