export const de = {
  title: "Deutsch lernen — Selbstlern-Quizze",
  home_h1: "Deutsch lernen: Quizze, Grammatik & Wortschatz",

  // Settings
  settings_title: "Einstellungen",
  settings_subtitle: "Verwalte dein Konto und die Anwendungseinstellungen.",
  language_preferences: "Spracheinstellungen",
  language_preferences_subtitle: "Wähle die Anwendungssprache aus.",
  app_language: "App-Sprache",
  english: "Englisch",
  german: "Deutsch",
  hungarian: "Ungarisch",
  practice_settings: "Übungseinstellungen",
  practice_settings_subtitle: "Passe dein Quiz-Erlebnis an.",
  show_example_sentences: "Beispielsätze anzeigen",
  show_example_sentences_subtitle: "Zeige Beispielsätze nach der Beantwortung einer Frage an.",
  save_preferences: "Einstellungen speichern",
  saving_preferences: "Speichern...",
  save_button: "Speichern",
  data_management: "Datenverwaltung",
  data_management_subtitle: "Verwalte deinen gespeicherten Fortschritt und lokale Daten.",
  clear_local_data: "Lokalen Fortschritt löschen",
  confirm_clear_data: "Bist du sicher, dass du deinen lokalen Fortschritt löschen möchtest? Dies kann nicht rückgängig gemacht werden.",
  data_cleared: "Lokaler Fortschritt erfolgreich gelöscht.",
  confirm_reset_library: "Bist du sicher, dass du alle persönlichen Bibliotheksartikel löschen möchtest? Dies kann nicht rückgängig gemacht werden.",
  library_wiped: "Persönliche Bibliothek erfolgreich gelöscht.",
  wipe_error: "Fehler beim Löschen der persönlichen Bibliothek. Bitte versuche es erneut.",
  saved: "Gespeichert!",
  developer_tools: "Entwicklerwerkzeuge",
  developer_tools_subtitle: "Verwende diese Schaltfläche, um deine persönlichen Cloud-Daten vollständig zurückzusetzen. (Dies löscht NICHT die öffentliche Gastbibliothek). Lösche dies vor der Bereitstellung aus dem Code.",
  wiping_data: "Daten werden gelöscht...",
  hard_reset_database: "Datenbank hart zurücksetzen",
  hard_reset_warning: "⚠️ WARNUNG: Bist du SICHER, dass du ALLE deine persönlich importierten Vokabeln vollständig löschen möchtest? (Die öffentliche offene Bibliothek ist NICHT betroffen). Dies kann nicht rückgängig gemacht werden!",
  hard_reset_success: "Datenbank vollständig gelöscht! Du hast einen Neuanfang.",
  reset_personal_library: "Persönliche Bibliothek zurücksetzen",
  reset_personal_library_desc: "Lösche dauerhaft alle deine benutzerdefinierten importierten Wörter und Grammatikmaterialien aus der Cloud. Dies kann nicht rückgängig gemacht werden.",
  clear_local_data_desc: "Lösche lokale Quiz-Ergebnisse und Fortschritte. Löscht keine Cloud-Vokabeln.",

  // Quizzes
  quizzes_title: "Deutsch-Quizze",
  quizzes_subtitle: "Kostenlose Deutsch-Quizze zu Wortschatz, Artikeln (der, die, das), Verben, Adjektiven, Redewendungen und Präpositionen.",
  test_your_knowledge: "Teste dein Deutsch",
  test_your_knowledge_subtitle: "Übe mit unserer öffentlichen Deutsch-Quiz-Bibliothek.",
  vocabulary: "Wortschatz",
  vocabulary_quiz_subtitle: "Lerne deutschen Wortschatz mit interaktiven Wort-Quizzen.",
  articles_quiz: "Artikel (der, die, das)",
  articles_quiz_subtitle: "Übe deutsche Artikel der, die, das und das Genus der Nomen.",
  phrases_quiz: "Redewendungen und Sätze",
  phrases_quiz_subtitle: "Nützliche alltägliche deutsche Redewendungen und Sätze.",
  phrases_sentences_quiz: "Redewendungen und Sätze",
  prepositions_quiz: "Präpositionen",
  prepositions_quiz_subtitle: "Übe deutsche Präpositionen und Fälle (Dativ, Akkusativ).",
  verbs_quiz: "Deutsche Verben",
  verbs_quiz_subtitle: "Übe deutsche Verben, Konjugation und Vergangenheitsformen.",
  create_your_own_quizzes: "Benutzerdefinierte Quizze",
  create_your_own_quizzes_subtitle_loggedin: "Übe mit deinen eigenen importierten Wörtern.",
  vocabulary_quiz: "Wortschatz",
  create_your_own_quizzes_subtitle_loggedout: "Melde dich an, um benutzerdefinierte Quizze zu erstellen.",
  login_to_create_quizzes: "Anmelden",
  question_of: "Frage: {current} / {total}",
  choose_correct_one: "Wähle die richtige Lösung!",
  custom_vocab_desc: "Übe Wortübersetzungen aus deiner persönlichen Bibliothek.",
  custom_articles_desc: "Übe 'der, die, das' mit deinen eigenen Substantiven.",
  custom_phrases_desc: "Teste dein Wissen über benutzerdefinierte Redewendungen und Sätze.",
  custom_prepositions_desc: "Übe Fälle für Präpositionen, die du importiert hast.",
  custom_verbs_desc: "Deine persönlichen Verben.",

  // Navigation & Layout
  home: "Startseite",
  import: "Importieren",
  quizzes: "Quizze",
  grammar: "Grammatik",
  statistics: "Statistiken",
  settings: "Einstellungen",
  sign_out: "Abmelden",
  login: "Anmelden",
  vocabulary_short: "Vokabeln",
  support_micalingo: "MicaLingo unterstützen",
  support_desc: "Wähle einen Betrag, um unser Projekt zu unterstützen. Jeder Beitrag hilft!",
  support_tier_1: "Kaffee",
  support_tier_2: "Snack",
  support_tier_3: "Mittagessen",
  support_tier_4: "Held 🚀",
  enjoying_micalingo_title: "Gefällt dir MicaLingo?",
  consider_donation_desc: "Bitte erwäge, das Projekt zu unterstützen, damit es weiterlaufen kann und werbefrei bleibt.",
  yes_support: "Ja, zeig es mir!",
  maybe_later: "Vielleicht später",

  // Home
  welcome_back: "Willkommen, schön dich hier zu sehen!",
  ready_to_learn: "Lerne Deutsch online mit kostenlosen Deutsch–Ungarisch-Quizzen zu Wortschatz, Grammatik, Artikeln (der, die, das) und Verben. Mit Google-Konto baust du eine private Bibliothek in beliebigen Sprachen und eigene Quizze.",
  import_data: "Daten importieren und verwalten",
  upload_new_materials: "Neue Wörter und Sätze hochladen.",
  login_required: "Anmeldung erforderlich",
  to_create_new_quizzes_login_required: "Anmeldung erforderlich, um benutzerdefinierte Quizze zu erstellen",
  learn_new_words_from_library: "Durchsuche die Bibliothek oder deine eigenen Wörter.",
  login_to_create_quizzes_desc: "Wenn du deinen eigenen Wortschatz und eigene Quizze erstellen möchtest, melde dich bitte an!",
  for_extending_login_required: "Anmeldung für ein persönliches Wörterbuch erforderlich",
  coming_soon: "Demnächst",
  review_grammar_topics: "Grammatikregeln und Erklärungen.",
  track_your_progress: "Verfolge deinen Lernfortschritt.",
  download_android: "Hol dir die Android-App",
  download_android_desc: "Nimm dein MicaLingo mit! Lade sie direkt auf dein Handy herunter.",
  download_apk: "Herunterladen",
  android_install_note: "Hinweis: Da diese App direkt heruntergeladen wird, zeigt Ihr Telefon möglicherweise eine Sicherheitswarnung an. Klicken Sie auf 'Weitere Details' und dann auf 'Trotzdem installieren', um fortzufahren.",

  // Import
  import_title: "Dateien importieren",
  accepted_format_guide: "Akzeptierte Formate",
  vocab_phrases: "Wortschatz (Lesen oder Quiz) / Redewendungen-Quiz:",
  format_vocab_phrases: "Spalte A = Deutsch (Phrase/Satz), Spalte B = Ungarisch (Bedeutung), Spalte C = Beispiel (Optional).",
  verbs_quiz_format_title: "Verben-Quiz:",
  verbs_quiz_format_desc: "Spalte A = Deutsch (Verb), Spalte B = Ungarisch (Bedeutung), Spalte C = Vergangenheitsformen oder Beispiele.",
  prepositions_quiz_format_title: "Präpositionen-Quiz:",
  prepositions_quiz_format_desc: "Spalte A: Deutsches Verb + ungarische Bedeutung, Spalte B: Präposition + Fall, Spalte C: Beispielsatz.",
  articles_quiz_label: "Artikel-Quiz:",
  format_articles: "Spalte A = Artikel, Spalte B = Substantiv, Spalte C = Ungarisch, Spalte D = Beispiel.",
  need_starting_point: "Brauchen Sie einen Ausgangspunkt?",
  download_template_desc: "Lade eine Excel-Vorlage herunter.",
  vocab_template: "Wortschatz-Vorlage (Lesen oder Quiz)",
  articles_template: "Vorlage für Quiz-Artikel",
  verbs_template: "Vorlage für Quiz-Verben",
  prepositions_template: "Vorlage für Quiz-Präpositionen",
  template_german_verb_header: "Deutsches Verb + Ungarisch",
  template_prep_case_header: "Präposition + Fall",
  template_meaning_example_header: "Beispielsatz",
  drag_and_drop: "Drag & Drop oder Klicken zum Durchsuchen",
  supported_files: "Unterstützt Excel, Word, PDF, CSV und TXT",
  preview_filename: "Vorschau: {filename}",
  items_detected: "{count} Elemente erkannt",
  article: "Artikel", noun: "Substantiv + Plural", example: "Beispiel", column_a: "Spalte A", column_b: "Spalte B", column_c: "Spalte C", column_c_d: "Spalte C/D", column_d: "Spalte D",
  invalid_columns: "Gültige Spalten konnten nicht erkannt werden.",
  invalid_columns_desc: "Stelle sicher, dass die Datei Tabulatoren (Excel), Semikolons oder Kommas zur Trennung verwendet.",
  save_to: "Speichern in:",
  cancel: "Abbrechen",
  saving: "Speichern...",
  save_import: "Import speichern",
  manage_imported_files: "Importierte Dateien verwalten",
  manage_imported_files_desc: "Das Löschen einer Datei entfernt alle daraus importierten Wörter aus deinen Quizzen.",
  search_files: "Dateien oder Schlüsselwörter suchen...",
  files_selected: "{count} Dateien ausgewählt",
  download_selected: "Ausgewählte herunterladen",
  delete_selected: "Ausgewählte löschen",
  file_name: "Dateiname",
  format: "Format",
  used_in: "Verwendet in",
  items: "Elemente",
  action: "Aktion",
  download: "Herunterladen",
  delete: "Löschen",
  hint: "Tipp / Vergangenheitsform",
  confirm_delete_file: "Bist du sicher, dass du \"{fileName}\" löschen möchtest? Dadurch werden alle {count} Wörter dauerhaft entfernt.",
  error_delete_file_desc: "Beim Löschen ist ein Fehler aufgetreten.",
  confirm_bulk_delete: "Bist du sicher, dass du {count} Dateien löschen möchtest?",
  error_bulk_delete_desc: "Beim Löschen der Dateien ist ein Fehler aufgetreten.",
  no_items_export: "Keine Elemente zum Exportieren gefunden.",
  no_items_save: "Keine gültigen Vokabeln zum Speichern oder Benutzer nicht angemeldet.",
  import_success_with_duplicates: "Import abgeschlossen! {saved} neue Elemente gespeichert. {duplicates} Duplikate übersprungen.",
  import_success: "Import abgeschlossen! {saved} neue Elemente gespeichert.",
  import_overwritten: "{count} vorhandene Elemente überschrieben.",
  import_skipped: "{count} doppelte Elemente übersprungen.",
  overwrite_confirm_title: "Duplikate überschreiben?",
  overwrite_confirm_desc: "{count} bereits vorhandene Elemente gefunden. Möchten Sie sie mit den Daten aus Ihrer Datei überschreiben?",
  overwrite_button: "Überschreiben",
  skip_button: "Duplikate überspringen",
  error_saving_db: "Beim Speichern in der Datenbank ist ein Fehler aufgetreten.",

  // Vocabulary Page
  vocab_title: "Wortschatz",
  vocab_subtitle: "Deutsche Wortlisten durchsuchen und Vokabeln verwalten.",
  add_word: "Wort hinzufügen",
  open_library: "Offene Bibliothek",
  personalized_space: "Privater Bereich",
  marked_words: "Markierte Wörter",
  marked_words_subtitle: "Übe Wörter, die du nach einer falschen Antwort markiert hast.",
  marked_words_description: "Bei einer falschen Antwort tippe auf den Stern, um das Wort hier zu speichern. Übe sie als gemischtes Quiz oder entferne Wörter einzeln.",
  marked_words_empty: "Noch keine markierten Wörter",
  marked_words_empty_desc: "Beantworte eine Quizfrage falsch und tippe dann oben rechts auf den Stern, um das Wort hier zu speichern.",
  marked_words_practice: "Markierte Wörter üben",
  marked_words_manage: "Bibliothek verwalten",
  marked_words_manage_desc: "Entferne Wörter einzeln nur aus deiner markierten Liste. Die öffentliche Bibliothek bleibt unverändert.",
  mark_word: "Wort markieren",
  unmark_word: "Markierung entfernen",
  word_marked: "Wort markiert",
  quiz_title_marked: "Markierte-Wörter-Quiz {id}",
  personalized_space_empty: "Dein privater Bereich ist leer",
  search_vocabulary: "Wortschatz durchsuchen...",
  words_found: "{count} Wörter gefunden",
  words_count: "{count} Wörter",
  no_words_match_search: "Keine Wörter entsprechen deiner Suche.",
  checking_account: "Konto wird überprüft...",
  personalized_space_description: "Melde dich einfach sicher mit deinem Google-Konto an, um deinen privaten Wortschatz zu erstellen.",
  login_with_google: "Mit Google anmelden",
  loading_vocabulary: "Ihr Wortschatz wird geladen...",
  words_selected: "{count} Wörter ausgewählt",
  delete_selected_words: "Ausgewählte löschen",
  edit_word: "Bearbeiten",
  delete_word: "Wort löschen",
  modal_edit_word_title: "Wort bearbeiten",
  modal_add_word_title: "Neues Wort hinzufügen",
  modal_category_label: "Kategorie",
  modal_german_label: "Deutsch (mit Artikel & Plural) *",
  modal_german_placeholder: "z.B. der Apfel",
  modal_article_label: "Artikel *",
  modal_noun_label: "Substantiv (mit Plural) *",
  modal_noun_placeholder: "z.B. Mann, die Männer",
  modal_german_phrase_label: "Deutsche Phrase/Satz *",
  modal_german_phrase_placeholder: "z.B. Wie geht es Ihnen?",
  modal_hungarian_phrase_placeholder: "z.B. Hogy van?",
  modal_german_prep_label: "Deutsche Präposition *",
  modal_german_prep_placeholder: "z.B. mit",
  modal_hungarian_prep_placeholder: "z.B. val/vel",
  prep_case_label: "Präposition + Fall *",
  modal_prep_case_placeholder: "z.B. auf + Akk.",
  meaning_example_label: "Beispielsatz",
  meaning_example_placeholder: "z.B. Ich verzichte auf das Angebot.",
  modal_german_prep_verb_label: "Deutsches Verb + Ungarisch *",
  modal_german_prep_verb_placeholder: "z.B. verzichten, lemondani valamiről/felhagyni valamivel",
  modal_german_verb_label: "Deutsches Verb *",
  modal_german_verb_placeholder: "z.B. machen",
  modal_hungarian_verb_placeholder: "z.B. csinálni",
  modal_german_ff_label: "Falscher Freund (Deutsch) *",
  modal_german_ff_placeholder: "z.B. das Gift, die Gifte",
  modal_hungarian_ff_placeholder: "z.B. a méreg",
  modal_hungarian_label: "Ungarisch *",
  modal_hungarian_placeholder: "z.B. alma",
  modal_example_label: "Beispiel / Kommentar",
  modal_example_placeholder: "z.B. Ich esse einen Apfel.",
  modal_save_changes: "Änderungen speichern",
  modal_save_word: "Wort speichern",
  alert_fill_fields_login: "Bitte fülle mindestens die deutschen und ungarischen Felder aus.",
  alert_confirm_delete_word: "Bist du sicher, dass du dieses Wort löschen möchtest?",
  alert_confirm_bulk_delete_words: "Bist du sicher, dass du {count} Wörter löschen möchtest?",
  alert_login_failed: "Anmeldung mit Google fehlgeschlagen.",
  alert_word_exists: "Dieses Wort existiert bereits in deinem '{category}'!",
  duplicates_found_title: "Duplikate gefunden",
  duplicates_found_subtitle: "Diese Elemente existieren bereits am Zielort und wurden nicht verschoben.",
  all_categories: "Alle Kategorien",

  // Dropdown Categories
  dropdown_vocabulary: "Wortschatz-Quiz",
  dropdown_reading: "Wortschatz (zum Lesen)",
  vocab_reading_subtitle: "Deutsche Wörter zum Lesen und Wiederholen — getrennt von den Quiz-Bibliotheken.",
  copy_to_quiz: "Auch zum Quiz hinzufügen...",
  copy_to_quiz_hint: "Erstellt eine separate Quiz-Kopie. Das Wort bleibt in Wortschatz (zum Lesen).",
  category_separation_hint: "Lese- und Quiz-Bibliotheken sind getrennt — dasselbe Wort kann in beiden vorkommen.",
  dropdown_articles: "Artikel-Quiz",
  dropdown_phrases: "Ausdrücke und Sätze Quiz",
  dropdown_prepositions: "Präpositionen-Quiz",
  dropdown_adjectives: "Adjektive-Quiz",
  dropdown_verbs: "Verben-Quiz",
  dropdown_false_friends: "Falsche Freunde",

  // Quiz Page
  loading_questions: "Ihre Fragen werden geladen...",
  not_enough_words: "Nicht genügend Wörter",
  not_enough_words_desc: "Du hast nicht genügend Wörter für ein {topic}-Quiz.",
  need_more_items: "Du benötigst mindestens 4 Elemente für '{topic}'.",
  import_more_words: "Mehr Wörter importieren",
  quiz_complete: "Quiz abgeschlossen!",
  no_more_quizzes: "Du hast alle verfügbaren Quizzes für dieses Thema abgeschlossen!",
  great_job: "Toll gemacht – weiter so!",
  your_score: "Deine Punktzahl:",
  back_to_quizzes: "Zurück zu den Quizzen",
  retry_quiz: "Quiz wiederholen",
  go_to_level: "Gehe zu Level {level}",
  next_question: "Nächste Frage",
  finish_quiz: "Quiz beenden",
  back_button: "← Zurück",
  next_quiz_button: "Nächstes Quiz →",
  example_label: "Beispiel",
  quiz_title_public: "{topic} Quiz {id}",
  quiz_title_custom: "Benutzerdefiniertes {topic} Quiz {id}",
  quiz_title_personal: "Privates Quiz",
  items_count: "{count} Elemente",
  quit_quiz_title: "Quiz beenden?",
  quit_quiz_desc: "Ihr Fortschritt wurde automatisch gespeichert.",
  quit: "Beenden",

  // Topic Quizzes
  topic_not_found: "Thema nicht gefunden",
  return_to_quizzes: "Zurück zu den Quizzen",
  select_level_to_start: "Wähle ein Level aus.",
  level_id: "Level {id}",
  start_button: "Start →",
  continue_button: "Weiter →",
  personalized_quizzes: "Private Quizze",
  personalized_quizzes_desc: "Kein separates Konto erforderlich! Melde dich an.",
  your_custom_quizzes: "Deine benutzerdefinierten Quizze",
  custom_quizzes_count_desc: "Du hast derzeit {count} Elemente gespeichert.",
  start_custom_quiz: "Benutzerdefiniertes Quiz starten",
  import_more_data: "Mehr Daten importieren",

  // Create Quiz
  create_custom_quiz_title: "Ein benutzerdefiniertes {topic}-Quiz erstellen",
  choose_data_source: "Wähle deine Datenquelle.",
  use_personal_library: "Persönliche Bibliothek verwenden",
  use_personal_library_desc: "Erstelle ein Quiz aus deinen eigenen Wörtern.",
  upload_new_file: "Neue Datei hochladen",
  upload_new_file_desc: "Importieren Sie eine neue Datei für diesen Quiz-Typ.",
  required_format: "Erforderliches Format:",
  download_template: "Vorlage herunterladen",
  go_to_import_page: "Zur Importseite gehen →",
  instructions_articles: "Spalte A = Artikel ('der', 'die', 'das') — Quiz-Antwort. Spalte B = Substantiv; Spalte C = ungarische Bedeutung — zusammen als Frage (z. B. Mann (a férfi)). Spalte D = optionaler Beispielsatz als Hinweis, wenn Beispiele aktiv sind.",
  instructions_prepositions: "Spalte A = Präposition, Spalte B = Ungarisch.",
  instructions_vocabulary: "Spalte A = Deutsch, Spalte B = Ungarisch.",
  instructions_phrases: "Spalte A = Phrase, Spalte B = Ungarisch.",
  template_article_header: "Artikel (A)",
  template_noun_header: "Substantiv + Plural (B)",
  template_hungarian_header: "Ungarisch (C)",
  template_example_header: "Beispiel (D)",
  template_german_header: "Deutsch",
  template_german_mandatory_header: "Deutsch (Erforderlich, z.B. mit Artikel/Plural)",
  template_hungarian_mandatory_header: "Ungarisch (Erforderlich)",
  template_example_optional_header: "Beispiel (Optional)",

  // Grammar & Statistics
  grammar_page_title: "Deutsche Grammatik",
  grammar_page_subtitle: "Lerne deutsche Fälle, Zeitformen, Artikel (der, die, das), Adjektivendungen, Präpositionen und Satzbau.",
  grammar_cases: "Fälle (Kasus)",
  grammar_tenses: "Zeitformen (Tempora)",
  grammar_articles: "Artikel & Geschlechter",
  grammar_adjectives: "Adjektivdeklination",
  grammar_prepositions: "Präpositionen",
  grammar_sentence_structure: "Satzbau",
  add_grammar_rule: "Grammatikregel hinzufügen",
  edit_grammar_rule: "Grammatikregel bearbeiten",
  delete_grammar_rule: "Grammatikregel löschen",
  grammar_rule_title: "Titel der Regel",
  grammar_rule_content: "Grammatikerklärung",
  fetch_content: "Inhalt abrufen",
  fetch_error: "Inhalt konnte nicht abgerufen werden. Bitte URL prüfen oder manuell einfügen.",
  bullet_list: "• Aufzählungsliste",
  undo_button: "↩ Rückgängig",
  no_items: "Noch keine Einträge.",
  confirm_delete_grammar: "Möchtest du diese Grammatikregel wirklich löschen?",
  statistics_page_title: "Statistiken",
  statistics_page_subtitle: "Verfolge deinen Lernfortschritt.",
  page_under_construction: "Diese Seite befindet sich im Aufbau.",
  check_back_later: "Bitte schauen Sie später wieder vorbei!",
  guest_warning_stats: "Melde dich an, um den Fortschritt zu speichern ",
  guest_warning_stats_link: "hier!",
  quizzes_solved: "Quizze gelöst",
  materials_read: "Materialien gelesen",
  no_quizzes_solved: "Du hast noch keine Quizze abgeschlossen.",
  no_materials_read: "Du hast noch keine Materialien gelesen.",
  select_all: "Alle auswählen",
  stats_quiz: "Quiz",
  stats_score: "Punktzahl",
  stats_actions: "Aktionen",
  admin_target: "Admin-Ziel",
  public_library_target: "Öffentliche Bibliothek",
  personal_library_target: "Persönliche Bibliothek",
  review_button: "Überprüfen",
  download_button: "Herunterladen",
  redo_button: "Wiederholen",
  correct_answer: "Richtige Antwort",
  your_answer: "Deine Antwort",
  csv_question: "Frage",
  csv_result: "Ergebnis",
  result: "Ergebnis",
  status_excellent: "Ausgezeichnet",
  status_good: "Gut",
  status_needs_practice: "Übung nötig",
  csv_correct: "Richtig",
  csv_incorrect: "Falsch",
  delete_selected_records: "Ausgewählte löschen",
  confirm_delete_record: "Möchtest du dieses Ergebnis wirklich löschen?",
  confirm_bulk_delete_records: "Möchtest du {count} Ergebnisse löschen?",
  records_selected: "{count} Ergebnisse ausgewählt",

  // Login Page
  login_page_title: "Anmelden",
  login_page_subtitle: "Melde dich sicher mit deinem Google-Konto an.",

  // Results Page
  results_page_title: "Quiz-Ergebnisse",
  results_page_subtitle: "Überprüfe deine Antworten.",
  review_answers: "Antworten überprüfen",
  retry_mistakes: "Fehler wiederholen",
  close: "Schließen",
  expand_table: "Tabelle vergrößern",
  table_preview: "Tabellenvorschau",

  // Library & Learning Materials
  library: "Deutsch-Bibliothek",
  library_subtitle: "Öffentliche Deutsch–Ungarisch-Wortschatzlisten sowie Lese- und Hörmaterialien. Nach dem Google-Login kann deine private Bibliothek beliebige Sprachen nutzen.",
  learning_materials: "Deutsch Lernmaterialien",
  learning_materials_subtitle: "Deutsch lesen und hören: Artikel, Redewendungen, Bücher, Musik und Podcasts.",
  read_materials: "Lesen",
  read_materials_desc: "Texte, Artikel und Geschichten lesen.",
  listen_materials: "Hören",
  listen_materials_desc: "Audiospuren und Podcasts hören.",
  save_to_reading: "Lesematerial",
  save_to_listening: "Hörmaterial",
  interesting_section: "Interessant",
  articles_section: "Artikel",
  books_section: "Bücher",
  music_section: "Musik",
  podcasts_section: "Podcasts",
  audiobooks_section: "Hörbücher",
  history: "Geschichte",
  history_desc: "Historische Ereignisse und Persönlichkeiten.",
  animals: "Tiere",
  animals_desc: "Tierwelt und Natur.",
  music: "Musik",
  music_desc: "Komponisten, Instrumente und Genres.",
  culture: "Kultur",
  culture_desc: "Kunst, Konzerte und Ausstellungen.",
  politics: "Politik",
  politics_desc: "Regierung und Gesellschaft.",
  science: "Wissenschaft",
  science_desc: "Entdeckungen und Forschung.",
  celebrities: "Prominente",
  celebrities_desc: "Berühmte Personen und Popkultur.",
  classic_literature: "Klassische Literatur",
  classic_literature_desc: "Lies die Meisterwerke.",
  short_stories: "Kurzgeschichten",
  short_stories_desc: "Kurze Texte für das tägliche Üben.",
  pop: "Pop",
  pop_desc: "Beliebte Musikhits.",
  rock: "Rock",
  rock_desc: "Rock und alternative Musik.",
  other_music: "Andere",
  other_music_desc: "Verschiedene andere Genres.",
  travel: "Reisen",
  travel_desc: "Geschichten und Tipps aus aller Welt.",
  psychology: "Psychologie",
  psychology_desc: "Geist, Verhalten und psychische Gesundheit.",
  other_podcasts: "Andere",
  other_podcasts_desc: "Verschiedene andere Podcast-Themen.",
  fiction: "Fiktion",
  fiction_desc: "Romane und Geschichten.",
  non_fiction: "Sachbücher",
  non_fiction_desc: "Faktisch und lehrreich.",
  other_audiobooks: "Andere",
  other_audiobooks_desc: "Verschiedene andere Hörbücher.",

  // Protected Route / Login Prompt
  protected_space_title: "Privater Bereich",
  protected_space_desc_1: "Melde dich sicher mit deinem Google-Konto an.",
  protected_space_desc_2: "Melde dich an, um fortzufahren!",
  continue_with_google: "Mit Google fortfahren",

  // Admin
  admin_mode: "Admin-Modus",
  admin_mode_desc: "Du bist als Administrator angemeldet.",
  switch_to_normal_user: "Zu normalem Benutzer wechseln",
  switch_to_admin: "Zum Admin-Modus wechseln",
  admin_prompt_title: "Willkommen, Admin!",
  admin_prompt_desc: "Wähle, wie du die Anwendung nutzen möchtest.",
  admin_mode_dev: "Entwicklermodus",
  admin_mode_normal: "Normaler Benutzermodus",

  // False Friends
  false_friends: "Falsche Freunde",
  false_friends_desc: "Wörter, die ähnlich aussehen oder klingen.",
  false_friends_template: "Falsche Freunde Vorlage (lesen)",
  template_note_header: "Notiz (D)",
  note: "Notiz / Bedeutung",
  admin_save_public: "Admin: In öffentlicher Bibliothek speichern",
  media_player: "Media-Player",
  play_content: "Inhalt abspielen",
  fetch_error_audio: "Audiodetails konnten nicht abgerufen werden. Bitte überprüfe die URL oder füge sie manuell ein.",
  save_error_audio: "Fehler beim Speichern des Audios. Stelle sicher, dass du angemeldet bist.",
  delete_error_audio: "Fehler beim Löschen des Audios.",
  confirm_delete_audio: "Bist du sicher, dass du dieses Audio löschen möchtest?",
  add_audio: "Audio hinzufügen",
  audio_url: "Audio/Video-URL",
  fetch_audio: "Inhalt abrufen",
  audio_title: "Audiotitel",
  audio_content: "Audiobeschreibung / Inhalt",
  audio_source: "Künstler / Quelle",
  audio_source_placeholder: "z.B. Rammstein",
  save_audio: "Audio speichern",
  edit_audio: "Audio bearbeiten",
  delete_audio: "Audio löschen",
  audio_url_note: "Hinweis: YouTube- und Spotify-URLs generieren automatisch einen eingebetteten Player!",
  add_article: "Artikel hinzufügen",
  article_url: "Artikel URL",
  fetch_article: "Inhalt abrufen",
  article_title: "Artikel Titel",
  article_content: "Artikel Inhalt",
  article_source: "Quelle",
  article_source_placeholder: "z.B. Der Standard",
  save_article: "Artikel speichern",
  edit_article: "Artikel bearbeiten",
  delete_article: "Artikel löschen",
  confirm_delete_article: "Bist du sicher, dass du diesen Artikel löschen möchtest?",
  add_book: "Buch hinzufügen",
  book_url: "Buch-URL",
  fetch_book: "Inhalt abrufen",
  book_title: "Buchtitel",
  book_content: "Buchinhalt",
  book_source: "Autor / Quelle",
  book_source_placeholder: "z. B. Lehrbuch",
  save_book: "Buch speichern",
  edit_book: "Buch bearbeiten",
  delete_book: "Buch löschen",
  confirm_delete_book: "Bist du sicher, dass du dieses Buch löschen möchtest?",
  bookmark_instructions_logged_in: "Markiere während des Lesens einen beliebigen Text, um ein Lesezeichen zu speichern oder den markierten Text direkt in deine persönliche Vokabel-Datenbank oder in deine Quizze aufzunehmen!",
  bookmark_instructions_guest: "Markiere während des Lesens einen beliebigen Text, um ein Lesezeichen zu speichern oder den markierten Text direkt in deine persönliche Vokabel-Datenbank oder in deine Quizze aufzunehmen! (Diese Funktion ist exklusiv für angemeldete Benutzer verfügbar. Melde dich an, um sie zu nutzen!)",
  save_bookmark: "Lesezeichen",
  continue_from: "Weiterlesen ab:",
  no_audio_yet: "Noch keine Audioinhalte.",
  no_audio_yet_admin: "Noch keine Inhalte hier. Klicke oben auf '+ Audio hinzufügen', um den ersten Titel hinzuzufügen!",
  private_reading_hint: "Erstelle deine eigenen Lesekategorien, um deine Texte, Artikel oder Bücher zu organisieren.",
  private_listening_hint: "Erstelle Kategorien wie Musikstil oder gruppiere deine Lieblingslieder nach Künstlern oder Jahren.",
  private_grammar_hint: "Erstelle eigene Grammatikkategorien, um deine Notizen zu ordnen.",
  private_category_1: "Kategorie 1",
  private_category_2: "Kategorie 2",
  private_category_3: "Kategorie 3",
  private_category_4: "Kategorie 4",
  private_category_5: "Kategorie 5",
  edit_category: "Kategorie bearbeiten",
  adjectives_quiz: 'Deutsche Adjektive',
  adjectives_quiz_subtitle: 'Übe deutsche Adjektivendungen, Deklination und Steigerung.',
  custom_adjectives_desc: 'Deine persönlichen Adjektive.',
  template_adjective_header: 'Adjektiv (erforderlich)',
  template_levels_header: 'Steigerung (z.B. besser, am besten)',
  adjectives_quiz_label: 'Adjektive-Quiz:',
  format_adjectives: 'Spalte A: Deutsch, Spalte B: Ungarisch, Spalte C: Steigerung (z.B. besser, am besten) oder Beispielsatz.',
  adjectives_template: 'Vorlage für Quiz-Adjektive',
  adjective: 'Adjektiv',
  levels: 'Steigerung',
  url_optional: "URL (Optional)",
  title_label: "Titel",
  source_author: "Quelle / Autor",
  source_artist: "Quelle / Künstler",
  content_label: "Inhalt",
  fetch_note: "Hinweis: Das Abrufen erfolgt über einen Proxy. Komplexe Websites blockieren möglicherweise die Extraktion. Du kannst Inhalte jederzeit manuell einfügen.",
  no_items_left: "Keine Elemente mehr. Speichern, um alle zu löschen.",
  original_source: "Originalquelle",
  add_interesting: "Interessanten Inhalt hinzufügen",
  edit_interesting: "Interessanten Inhalt bearbeiten",
  delete_interesting: "Inhalt löschen",
  confirm_delete_interesting: "Möchtest du diesen Inhalt wirklich löschen?",
  interesting_url: "Inhalts-URL",
  fetch_interesting: "Inhalt abrufen",
  interesting_title: "Titel",
  interesting_source: "Quelle",
  interesting_source_placeholder: "z.B. Wikipedia",
  interesting_content: "Inhalt",
  save_interesting: "Inhalt speichern",
  fun_facts: "Fakten",
  fun_facts_desc: "Interessante Fakten und Wissenswertes.",
  idioms: "Redewendungen",
  idioms_desc: "Häufige Redewendungen und Sprichwörter.",
  save_to_vocabulary: "Wort speichern",
  add_content: "Inhalt hinzufügen",
  add_image: "Bild hinzufügen",
  explanation_label: "Erklärung",
  explanation_placeholder: "Erklärung",
  add_idiom: "Redewendung hinzufügen",
  edit_idiom: "Redewendung bearbeiten",
  idiom_german_label: "Deutsche Redewendung *",
  idiom_german_placeholder: "z.B. Ich verstehe nur Bahnhof",
  idiom_hungarian_label: "Ungarische Bedeutung *",
  idiom_hungarian_placeholder: "z.B. Nekem ez kínai",
  idiom_note_label: "Notiz (Erklärung)",
  idiom_note_placeholder: "Wörtliche Bedeutung...",
  save_content: "Inhalt speichern",
  confirm_delete_idiom: "Bist du sicher, dass du diese Redewendung löschen möchtest?",
  confirm_delete_ff: "Bist du sicher, dass du diesen falschen Freund löschen möchtest?",
  ff_note_placeholder: "z.B. Falscher Freund: gift != ajándék",
  alert_fill_fields_admin: "Bitte fülle mindestens die deutschen und ungarischen Felder aus.",
  confirm_exit_app: "Möchten Sie die App wirklich beenden?",

  // Footer & legal pages
  footer_privacy: "Datenschutzerklärung",
  footer_terms: "Nutzungsbedingungen",
  footer_about: "Über uns & Kontakt",
  footer_cookies: "Cookie-Richtlinie",
  footer_impressum: "Impressum",
  footer_cookie_settings: "Cookie-Einstellungen",
  footer_rights: "Alle Rechte vorbehalten.",
  last_updated: "Zuletzt aktualisiert: 18. August 2026",

  privacy_title: "Datenschutzerklärung",
  privacy_intro: "Diese Datenschutzerklärung erläutert, wie MicaLingo („wir“, „uns“ oder „unser“) personenbezogene Daten verarbeitet, wenn Sie unsere Website micalingo.com und unsere mobile Anwendung (zusammen der „Dienst“) nutzen. Wir verarbeiten personenbezogene Daten gemäß der EU-Datenschutz-Grundverordnung (DSGVO) und den geltenden Datenschutzgesetzen. Angaben zum Betreiber finden Sie im Impressum.",
  privacy_s1_title: "1. Verantwortlicher",
  privacy_s1_body: "Verantwortlicher für Ihre personenbezogenen Daten im Zusammenhang mit dem Dienst ist MicaLingo, Betreiber von https://micalingo.com und der mobilen Anwendung MicaLingo. Für datenschutzbezogene Anfragen kontaktieren Sie uns unter support.micalingo@gmail.com. Weitere Angaben zum Betreiber stehen im Impressum.",
  privacy_s2_title: "2. Welche Informationen wir verarbeiten",
  privacy_s2_body: "Die Anmeldung erfolgt ausschließlich über Google Sign-In (Google Authentication). Wenn Sie sich anmelden, kann Google gemäß den Google-Authentifizierungs-APIs und Ihren Google-Kontoeinstellungen eine begrenzte Menge an Kontoinformationen mit uns teilen (z. B. Google-Konto-ID, Anzeigename, Profilbild-URL und E-Mail-Adresse). Wir betreiben kein eigenständiges passwortbasiertes Kontosystem und haben keinen Einblick in Ihr Google-Passwort oder den vollständigen Inhalt Ihres Google-Kontos. Wir speichern möglicherweise auch Lernfortschritt, importierten Wortschatz und ähnliche Inhalte, die Sie freiwillig im Dienst erstellen oder hochladen, verknüpft mit Ihrem authentifizierten Konto.",
  privacy_s3_title: "3. Cookies und ähnliche Technologien",
  privacy_s3_body: "Der Dienst verwendet Cookies und ähnliche Speichertechnologien (z. B. localStorage) auf der Website und in der mobilen Anwendung.\n\nNotwendige Cookies und lokale Speicherung: Wir speichern ausschließlich Informationen, die für die Funktion des Dienstes erforderlich sind, einschließlich Ihrer Spracheinstellung, Ihrer Cookie-Einwilligung sowie Sitzungs- oder Anmeldestatus. Diese sind zur Bereitstellung des von Ihnen angeforderten Dienstes notwendig und bedürfen keiner Einwilligung.\n\nWerbe-Cookies (Google): Ein Dritter — Google — verwendet Cookies, um über Google AdSense (und verwandte Google-Werbedienste) Werbung auszuspielen. Diese Cookies können genutzt werden, um Anzeigen zu zeigen, auch auf Grundlage früherer Besuche dieser oder anderer Websites, und können Daten wie IP-Adresse, Geräte- und Browserinformationen sowie Interaktionen mit Anzeigen erfassen.\n\nWerbe-Cookies werden nur verwendet, wenn Sie im Cookie-Banner (oder später in den Cookie-Einstellungen) einwilligen. Sie können die Einwilligung jederzeit widerrufen. Personalisierte Werbung können Sie in den Google-Anzeigeneinstellungen deaktivieren: https://www.google.com/settings/ads\nGoogle erläutert die Nutzung von Daten von Partnerseiten hier: https://policies.google.com/technologies/partner-sites\nWeitere Einzelheiten stehen in unserer Cookie-Richtlinie.",
  privacy_s4_title: "4. Zweck der Verarbeitung und Rechtsgrundlage",
  privacy_s4_body: "Wir verarbeiten personenbezogene Daten, um den Dienst bereitzustellen und zu sichern, Nutzer über Google Sign-In zu authentifizieren, Ihre Lernmaterialien und Ihren Fortschritt gegebenenfalls geräteübergreifend zu synchronisieren, Supportanfragen zu beantworten und — sofern Sie einwilligen — Werbung anzuzeigen, die hilft, den Dienst kostenlos zu halten. Je nach Verarbeitungstätigkeit kann die Rechtsgrundlage nach der DSGVO sein: Vertragserfüllung (Art. 6 Abs. 1 lit. b DSGVO), unsere berechtigten Interessen am Betrieb und an der Verbesserung eines sicheren Lerndienstes (Art. 6 Abs. 1 lit. f DSGVO) sowie Ihre Einwilligung, soweit sie für nicht notwendige Cookies und Werbung erforderlich ist (Art. 6 Abs. 1 lit. a DSGVO).",
  privacy_s5_title: "5. Keine Marketingnutzung von E-Mail-Adressen",
  privacy_s5_body: "Wir verwenden Ihre E-Mail-Adresse nicht zu Marketingzwecken. Wir versenden keine Newsletter, Werbekampagnen oder Werbe-E-Mails. Ihre E-Mail-Adresse wird – sofern wir sie über Google Sign-In erhalten – nur verwendet, soweit dies für den Betrieb Ihres Kontos und für die Kommunikation mit Ihnen über den Dienst erforderlich ist, wenn Sie uns kontaktieren oder wenn eine solche Kommunikation zur Bereitstellung des Dienstes notwendig ist. Werbung erscheint, sofern sie angezeigt wird, innerhalb des Dienstes selbst und wird nicht an Ihr Postfach gesendet.",
  privacy_s6_title: "6. Drittanbieterdienste (Google)",
  privacy_s6_body: "Wir nutzen Google für (a) die Authentifizierung über Google Sign-In und (b) Werbung über Google AdSense. Die Nutzung dieser Google-Dienste unterliegt auch der Datenschutzerklärung und den Nutzungsbedingungen von Google. Google kann bestimmte Daten gemäß seinen eigenen Richtlinien als unabhängiger Verantwortlicher verarbeiten, einschließlich durch Cookies zur Anzeige von Werbung.\n\nDie Verwendung von Werbe-Cookies durch Google ermöglicht es Google und seinen Partnern, Anzeigen auf Grundlage Ihres Besuchs dieser und/oder anderer Websites auszuspielen. Personalisierte Werbung können Sie unter https://www.google.com/settings/ads oder über https://www.aboutads.info deaktivieren.\nWie Google Informationen von Websites oder Apps verwendet, die Google-Dienste nutzen: https://policies.google.com/technologies/partner-sites\nDie Nutzung von Informationen, die MicaLingo über Google-APIs erhält, entspricht – soweit anwendbar – der Google API Services User Data Policy, einschließlich der Limited-Use-Anforderungen.",
  privacy_s7_title: "7. Speicherdauer",
  privacy_s7_body: "Wir speichern kontobezogene und von Nutzern erstellte Lerndaten so lange, wie Ihr Konto aktiv ist oder wie es zur Bereitstellung des Dienstes erforderlich ist. Sie können die Löschung Ihrer personenbezogenen Daten verlangen, vorbehaltlich gesetzlicher Aufbewahrungspflichten. Lokal auf Ihrem Gerät gespeicherter Fortschritt kann in der Regel im Einstellungsbereich der App gelöscht werden. Ihre Cookie-Entscheidung bleibt auf Ihrem Gerät gespeichert, bis Sie sie ändern oder die Website-Daten löschen.",
  privacy_s8_title: "8. Ihre Rechte (EU / EWR)",
  privacy_s8_body: "Wenn Sie sich in der Europäischen Union oder im Europäischen Wirtschaftsraum befinden, haben Sie das Recht, Auskunft über, Berichtigung, Löschung oder Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen; das Recht auf Datenübertragbarkeit, soweit anwendbar; das Recht, einer auf berechtigten Interessen beruhenden Verarbeitung zu widersprechen; sowie das Recht, eine Einwilligung zu widerrufen, soweit die Verarbeitung auf Einwilligung beruht — einschließlich Werbe-Cookies — ohne dass die Rechtmäßigkeit der Verarbeitung vor dem Widerruf berührt wird. Sie haben außerdem das Recht, eine Beschwerde bei Ihrer örtlichen Aufsichtsbehörde einzureichen. Zur Ausübung Ihrer Rechte kontaktieren Sie uns unter der unten genannten E-Mail-Adresse. Cookie-Einstellungen können Sie auch über die Cookie-Einstellungen in der Fußzeile oder in den App-Einstellungen ändern.",
  privacy_s9_title: "9. Internationale Übermittlungen",
  privacy_s9_body: "Da wir Google-Authentifizierung, Google-Werbung und Cloud-Infrastruktur nutzen, können personenbezogene Daten in Ländern außerhalb Ihres Wohnsitzlandes verarbeitet werden, einschließlich außerhalb der EU/des EWR. Soweit erforderlich, erfolgen solche Übermittlungen mit angemessenen Garantien im Einklang mit dem geltenden Recht (z. B. Standardvertragsklauseln der jeweiligen Anbieter).",
  privacy_s10_title: "10. Datenschutz von Kindern",
  privacy_s10_body: "Der Dienst richtet sich an Nutzer, die gemäß den Google-Bedingungen und dem geltenden Recht ein Google-Konto erstellen oder nutzen können. Wenn Sie der Ansicht sind, dass ein Kind uns unter Verstoß gegen geltende Regeln personenbezogene Daten übermittelt hat, kontaktieren Sie uns bitte, damit wir geeignete Maßnahmen ergreifen können.",
  privacy_s11_title: "11. Änderungen dieser Erklärung",
  privacy_s11_body: "Wir können diese Datenschutzerklärung von Zeit zu Zeit aktualisieren, um Änderungen unserer Praktiken oder gesetzlicher Anforderungen widerzuspiegeln. Das Datum „Zuletzt aktualisiert“ oben auf dieser Seite gibt an, wann diese Erklärung zuletzt überarbeitet wurde. Die fortgesetzte Nutzung des Dienstes nach einer Aktualisierung gilt – soweit gesetzlich zulässig – als Kenntnisnahme der überarbeiteten Erklärung.",
  privacy_s12_title: "12. Kontakt",
  privacy_s12_body: "Bei Datenschutzfragen oder Betroffenenanfragen kontaktieren Sie: support.micalingo@gmail.com. Website: https://micalingo.com. Angaben zum Betreiber: siehe Impressum.",
  privacy_s13_title: "13. Werbung (Google AdSense)",
  privacy_s13_body: "Damit Website und App kostenlos bleiben können, zeigen wir Werbung von Google AdSense. Dritte, einschließlich Google, verwenden Cookies, um Anzeigen im Dienst auszuspielen. Die Verwendung von Werbe-Cookies durch Google ermöglicht es Google und seinen Partnern, Ihnen Anzeigen auf Grundlage Ihres Besuchs dieser und/oder anderer Websites zu zeigen.\n\nIm Europäischen Wirtschaftsraum, im Vereinigten Königreich und in der Schweiz werden Cookies für personalisierte Werbung nur mit Ihrer vorherigen Einwilligung verwendet. Wenn Sie Werbe-Cookies ablehnen, bleibt der Dienst verfügbar; Google kann dann nicht personalisierte Anzeigen oder weniger Anzeigen zeigen, abhängig von den Systemen von Google.\n\nPersonalisierte Werbung können Sie in den Google-Anzeigeneinstellungen deaktivieren: https://www.google.com/settings/ads\nAlternativ können Sie die Verwendung von Cookies durch Drittanbieter für personalisierte Werbung unter https://www.aboutads.info deaktivieren.\nOffenlegung zu Partnerseiten von Google: https://policies.google.com/technologies/partner-sites",

  terms_title: "Nutzungsbedingungen",
  terms_intro: "Diese Nutzungsbedingungen („Bedingungen“) regeln Ihren Zugang zu und die Nutzung der Website von MicaLingo unter micalingo.com sowie unserer mobilen Anwendung (der „Dienst“). Durch den Zugriff auf oder die Nutzung des Dienstes erklären Sie sich mit diesen Bedingungen einverstanden. Wenn Sie nicht einverstanden sind, nutzen Sie den Dienst nicht.",
  terms_s1_title: "1. Beschreibung des Dienstes",
  terms_s1_body: "MicaLingo ist eine Bildungsanwendung zum Selbstlernen. Die öffentliche Bibliothek bietet Deutsch–Ungarisch-Quizze, Wortschatzübungen, Grammatikmaterialien sowie Lese- und Hörressourcen. Nach der Anmeldung mit einem Google-Konto kannst du eine private Bibliothek in beliebigen Sprachen einrichten und eigene Quizze erzeugen. Der Dienst ist als Website und als mobile Anwendung verfügbar. Um den Dienst kostenlos zu halten, kann Werbung angezeigt werden (einschließlich Google AdSense).",
  terms_s2_title: "2. Berechtigung und Konten",
  terms_s2_body: "Für den Zugriff auf personalisierte Funktionen benötigen Sie möglicherweise ein Google-Konto. Sie sind für die Sicherheit Ihres Google-Kontos und für alle Aktivitäten unter Ihrer authentifizierten Sitzung verantwortlich. Sie verpflichten sich, den Dienst nur gemäß diesen Bedingungen, den Nutzungsbedingungen von Google und dem geltenden Recht zu nutzen.",
  terms_s3_title: "3. Zulässige Nutzung und ethisches Verhalten",
  terms_s3_body: "Sie verpflichten sich, den Dienst nur mit ethischer Haltung und ausschließlich zu rechtmäßigen Sprachlernzwecken zu nutzen. Sie dürfen den Dienst nicht verwenden, um Wörter, Phrasen, Sätze oder andere Inhalte im Zusammenhang mit Hassrede, Diskriminierung, Belästigung, Gewalt, Terrorismus, Extremismus, kriminellen Handlungen oder sonstigen rechtswidrigen Inhalten – oder Inhalten, die gegen die Nutzungsbedingungen oder Richtlinien von Google verstoßen – zu lernen, zu erstellen, hochzuladen, zu speichern, zu teilen oder zu üben. Sie dürfen den Dienst nicht missbrauchen, um anderen zu schaden, Sicherheitsmaßnahmen zu umgehen, unsere Systeme auszuschöpfen oder den Zugang anderer Nutzer zu stören.",
  terms_s4_title: "4. Nutzerinhalte",
  terms_s4_body: "Sie behalten das Eigentum an Wortschatz, Notizen und anderen Materialien, die Sie importieren oder erstellen („Nutzerinhalte“). Durch das Einreichen von Nutzerinhalten gewähren Sie uns eine beschränkte Lizenz, diese Inhalte ausschließlich so zu hosten, zu speichern und anzuzeigen, wie es für den Betrieb des Dienstes für Sie erforderlich ist. Sie versichern, dass Sie die erforderlichen Rechte zur Einreichung von Nutzerinhalten haben und dass diese keine Rechte Dritter oder diese Bedingungen verletzen.",
  terms_s5_title: "5. Geistiges Eigentum",
  terms_s5_body: "Der Dienst einschließlich Markenauftritt, Design, von uns bereitgestellter öffentlicher Lernmaterialien und Software ist durch Gesetze zum Schutz geistigen Eigentums geschützt. Mit Ausnahme Ihrer Nutzerinhalte dürfen Sie den Dienst ohne unsere vorherige schriftliche Genehmigung nicht kopieren, ändern, verbreiten, verkaufen oder davon abgeleitete Werke erstellen, außer soweit zwingendes Recht dies erlaubt.",
  terms_s6_title: "6. Drittanbieterdienste",
  terms_s6_body: "Der Dienst stützt sich auf Drittanbieter, einschließlich Google für die Authentifizierung (Google Sign-In) und Google AdSense für die Anzeige von Werbung. Google und seine Partner können Cookies setzen, wie in unserer Datenschutzerklärung und Cookie-Richtlinie beschrieben. Ihre Nutzung der Google-Dienste unterliegt auch den Nutzungsbedingungen und der Datenschutzerklärung von Google. Wir sind nicht verantwortlich für Drittanbieterdienste außerhalb unserer zumutbaren Kontrolle. Werbe-Cookies können Sie über unser Cookie-Banner, die Cookie-Einstellungen in der Fußzeile oder die App-Einstellungen verwalten.",
  terms_s7_title: "7. Gewährleistungsausschluss",
  terms_s7_body: "Der Dienst wird „wie besehen“ und „wie verfügbar“ ohne jegliche ausdrückliche oder stillschweigende Gewährleistung bereitgestellt, einschließlich stillschweigender Gewährleistungen der Marktgängigkeit, der Eignung für einen bestimmten Zweck und der Nichtverletzung von Rechten, soweit das geltende Recht dies zulässt. Wir garantieren keine ununterbrochene Verfügbarkeit, fehlerfreien Betrieb oder bestimmte Lernergebnisse.",
  terms_s8_title: "8. Haftungsbeschränkung",
  terms_s8_body: "Soweit nach geltendem EU- und nationalem Recht zulässig, haften MicaLingo und seine Betreiber nicht für indirekte, zufällige, besondere, Folgeschäden oder Strafschäden sowie nicht für Daten-, Gewinn- oder Goodwill-Verluste, die aus Ihrer Nutzung des Dienstes entstehen. Nichts in diesen Bedingungen schließt eine Haftung aus oder beschränkt sie, die nach geltendem Recht nicht ausgeschlossen oder beschränkt werden kann, einschließlich der Haftung für Tod oder Körperverletzung durch Fahrlässigkeit oder für Betrug.",
  terms_s9_title: "9. Aussetzung und Kündigung",
  terms_s9_body: "Wir können den Zugang zum Dienst aussetzen oder beenden, wenn Sie diese Bedingungen verletzen, den Dienst missbrauchen oder wenn dies aus Sicherheits- oder Rechtsgründen erforderlich ist. Sie können die Nutzung des Dienstes jederzeit einstellen. Bestimmungen, die ihrer Natur nach die Beendigung überdauern sollen, bleiben bestehen.",
  terms_s10_title: "10. Änderungen der Bedingungen",
  terms_s10_body: "Wir können diese Bedingungen von Zeit zu Zeit aktualisieren. Das Datum „Zuletzt aktualisiert“ gibt die letzte Überarbeitung an. Die fortgesetzte Nutzung des Dienstes nach Wirksamwerden von Änderungen gilt – soweit gesetzlich zulässig – als Annahme der aktualisierten Bedingungen.",
  terms_s11_title: "11. Anwendbares Recht",
  terms_s11_body: "Diese Bedingungen unterliegen dem in der Europäischen Union anwendbaren Recht sowie den für Verbraucher geltenden Vorschriften der jeweiligen Mitgliedstaaten, unbeschadet zwingender Verbraucherschutzvorschriften Ihres Wohnsitzlandes.",
  terms_s12_title: "12. Kontakt",
  terms_s12_body: "Bei Fragen zu diesen Bedingungen kontaktieren Sie: support.micalingo@gmail.com. Website: https://micalingo.com. Angaben zum Betreiber: siehe Impressum.",

  about_title: "Über uns & Kontakt",
  about_heading: "Über MicaLingo",
  about_body: "MicaLingo ist eine App und Website (micalingo.com) zum Selbstlernen. Die öffentlichen Quizze und die Bibliothek sind für Ungarisch sprechende Deutschlernende eingerichtet: Wortschatz, Grammatik, Quizze sowie Lese- und Hörmaterialien auf Deutsch–Ungarisch. Mit einem Google-Konto baust du eine private Bibliothek in beliebigen Sprachen — oder sogar ganz anderen Themen. Teste dein Wissen mit historischen Jahreszahlen, Hauptstädten und Ländernnamen, oder erstelle dir selbst Mathematikaufgaben. Die Website und die Android-App sind derzeit kostenlos nutzbar, aber du kannst die Entwicklerin mit einem beliebigen Betrag unterstützen ({support_link}). Damit der Dienst vorerst kostenlos bleiben kann, haben wir Werbung freigeschaltet. Vielen Dank für dein Verständnis!",
  about_mission: "Unser Ziel ist es, Selbstlernende mit wiederholbarem Üben zu unterstützen: eine fertige Deutsch–Ungarisch-Bibliothek, und ein privater Bereich, den du selbst einrichtest.",
  contact_heading: "Kontakt & Support",
  contact_body: "Hast du eine Frage, Feedback oder brauchst du Hilfe? Wir freuen uns von dir zu hören.",
  contact_support_label: "Support & Feedback",
  contact_website_label: "Website",

  cookies_title: "Cookie-Richtlinie",
  cookies_intro: "Diese Cookie-Richtlinie erläutert, wie MicaLingo Cookies und ähnliche Technologien auf der Website https://micalingo.com und in der mobilen Anwendung MicaLingo verwendet. Sie ist zusammen mit unserer Datenschutzerklärung zu lesen.",
  cookies_s1_title: "1. Was sind Cookies?",
  cookies_s1_body: "Cookies sind kleine Textdateien, die auf Ihrem Gerät gespeichert werden, wenn Sie eine Website besuchen. Ähnliche Technologien sind localStorage und sessionStorage im Browser oder in der In-App-WebView. Sie können First-Party-Cookies (von MicaLingo gesetzt) oder Third-Party-Cookies (von einer anderen Organisation, z. B. Google, gesetzt) sein.",
  cookies_s2_title: "2. Notwendige Cookies",
  cookies_s2_body: "Diese sind für die Funktion des Dienstes erforderlich und können nicht deaktiviert werden. Dazu gehören: Spracheinstellung (micalingo_language), Ihre Cookie-Entscheidung (micalingo_cookie_consent) sowie technischer Sitzungs- oder Anmeldestatus, der für Google Sign-In und die App-Funktion nötig ist. Rechtsgrundlage: Art. 6 Abs. 1 lit. b und/oder f DSGVO sowie die ePrivacy-Ausnahme für unbedingt erforderliche Speicherung.",
  cookies_s3_title: "3. Werbe-Cookies (Google AdSense)",
  cookies_s3_body: "Wenn Sie einwilligen, verwendet Google — ein Dritter — Cookies, um Werbung im Dienst auszuspielen. Googles Werbe-Cookies können genutzt werden, um Anzeigen auf Grundlage Ihrer Besuche dieser und anderer Websites zu zeigen, die Leistung von Anzeigen zu messen und die Häufigkeit von Anzeigen zu begrenzen. Typische Daten können IP-Adresse, Gerätekennungen, Browsertyp und Interaktion mit Anzeigen umfassen.\n\nDiese Cookies werden für Werbung erst gesetzt, wenn Sie sie im Cookie-Banner akzeptieren. Rechtsgrundlage: Ihre Einwilligung (Art. 6 Abs. 1 lit. a DSGVO).",
  cookies_s4_title: "4. Wie Google Daten verwendet",
  cookies_s4_body: "Google erläutert, wie Informationen von Websites oder Apps verwendet werden, die Google-Dienste nutzen: https://policies.google.com/technologies/partner-sites\nPersonalisierte Anzeigen verwalten Sie in den Google-Anzeigeneinstellungen: https://www.google.com/settings/ads\nUnter https://www.aboutads.info können Sie bestimmte Werbe-Cookies von Drittanbietern deaktivieren.",
  cookies_s5_title: "5. Einwilligung verwalten und widerrufen",
  cookies_s5_body: "Beim ersten Besuch zeigen wir ein Cookie-Banner. Sie können alle Cookies akzeptieren, nicht notwendige Cookies ablehnen oder Kategorien wählen. Sie können Ihre Wahl jederzeit über die Cookie-Einstellungen in der Fußzeile, in den App-Einstellungen oder durch erneutes Öffnen des Banners ändern. Der Widerruf berührt nicht die Rechtmäßigkeit der zuvor erfolgten Verarbeitung.",
  cookies_s6_title: "6. Browser- und Geräteeinstellungen",
  cookies_s6_body: "Sie können Cookies auch in Ihren Browser- oder Geräteeinstellungen löschen oder blockieren. Das Blockieren aller Cookies kann Anmeldung, Sprache oder andere Funktionen des Dienstes beeinträchtigen.",
  cookies_s7_title: "7. Kontakt",
  cookies_s7_body: "Fragen zu Cookies: support.micalingo@gmail.com. Website: https://micalingo.com.",

  impressum_title: "Impressum",
  impressum_intro: "Dieses Impressum nennt, wer die MicaLingo-Website und die mobile Anwendung betreibt.",
  impressum_s1_title: "1. Betreiber",
  impressum_s1_body: "Dienstname: MicaLingo\nWebsite: https://micalingo.com\nMobile App: MicaLingo (Android-/iOS-WebView desselben Dienstes)\nBetreiber: MicaLingo, ein unabhängig betriebenes Bildungsprojekt.",
  impressum_s2_title: "2. Kontakt",
  impressum_s2_body: "E-Mail: support.micalingo@gmail.com\nWebsite: https://micalingo.com\nDies ist die Kontaktadresse für Nutzer, Datenschutzanfragen und rechtliche Mitteilungen.",
  impressum_s3_title: "3. Art des Dienstes",
  impressum_s3_body: "MicaLingo ist eine Website und Anwendung zum Selbstlernen. Die öffentliche Bibliothek bietet Deutsch–Ungarisch-Quizze, Wortschatz, Grammatik sowie Lese- und Hörmaterialien. Nach der Google-Anmeldung können Nutzer eine private Bibliothek in beliebigen Sprachen einrichten und eigene Quizze erzeugen. Der Dienst ist derzeit kostenlos nutzbar und kann Werbung (Google AdSense) anzeigen, um Betriebskosten zu decken. Zusätzlich können freiwillige Spenden zur Unterstützung der Entwicklung angeboten werden.",
  impressum_s4_title: "4. Verantwortlichkeit für Inhalte",
  impressum_s4_body: "Der Betreiber ist für die redaktionellen Inhalte des Dienstes verantwortlich. Werbung Dritter und verlinkte externe Websites liegen in der Verantwortung der jeweiligen Anbieter. Von Nutzern hochgeladene Lerninhalte bleiben in der Verantwortung des jeweiligen Nutzers.",
  impressum_s5_title: "5. Online-Streitbeilegung der EU",
  impressum_s5_body: "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: https://ec.europa.eu/consumers/odr\nWir klären Anliegen bevorzugt direkt unter support.micalingo@gmail.com.",
  impressum_s6_title: "6. Weitere rechtliche Seiten",
  impressum_s6_body: "Datenschutzerklärung, Nutzungsbedingungen, Cookie-Richtlinie sowie Über uns & Kontakt sind in der Fußzeile der Website und der App verlinkt.",

  cookie_banner_title: "Wir verwenden Cookies",
  cookie_banner_body: "Wir verwenden notwendige Cookies, damit MicaLingo funktioniert. Mit Ihrer Einwilligung verwendet außerdem ein Dritter — Google — Cookies, um Werbung (Google AdSense) anzuzeigen, auch auf Grundlage Ihrer Besuche dieser und anderer Websites. Sie können zustimmen, ablehnen oder anpassen.",
  cookie_banner_accept: "Alle akzeptieren",
  cookie_banner_reject: "Nur notwendige",
  cookie_banner_customize: "Anpassen",
  cookie_banner_save: "Auswahl speichern",
  cookie_banner_necessary: "Notwendig",
  cookie_banner_necessary_desc: "Erforderlich für Website und App (Sprache, Anmeldung, Speichern Ihrer Cookie-Wahl).",
  cookie_banner_ads: "Werbung (Google)",
  cookie_banner_ads_desc: "Ermöglicht Google AdSense, Cookies zu verwenden, um Anzeigen — einschließlich personalisierter Anzeigen — zu zeigen.",
  cookie_banner_always_on: "Immer aktiv",
  cookie_settings_title: "Cookie-Einstellungen",
  cookie_settings_desc: "Legen Sie fest, ob Google auf der Website und in der App Werbe-Cookies verwenden darf.",
  cookie_settings_manage: "Cookie-Einstellungen ändern",
  cookie_settings_status_accepted: "Werbe-Cookies: erlaubt",
  cookie_settings_status_rejected: "Werbe-Cookies: blockiert",
  cookie_settings_status_unset: "Sie haben noch keine Cookie-Auswahl getroffen.",

  seo_practice_heading: "Deutsch üben",
  seo_intro_quizzes: "Wähle ein Deutsch-Quiz: Wortschatz, Artikel (der, die, das), Verben, Adjektive, Redewendungen oder Präpositionen.",
  seo_intro_vocabulary: "Wortschatz-Quizze mit Übersetzungen und Beispielsätzen. Lerne deutsche Wörter nach Level.",
  seo_intro_articles: "Artikel-Quiz für der, die, das. Übe das Genus deutscher Nomen und bestimmte Artikel.",
  seo_intro_verbs: "Verben-Quiz: Konjugation, Präsens, Präteritum, Perfekt und häufige unregelmäßige Verben.",
  seo_intro_phrases: "Deutsche Redewendungen und Sätze für Alltag und Reise.",
  seo_intro_prepositions: "Präpositionen-Quiz zu Akkusativ, Dativ und Wechselpräpositionen.",
  seo_intro_adjectives: "Adjektive-Quiz: Endungen, Deklination und Steigerung.",
  seo_faq_heading: "Häufige Fragen zum Deutschlernen",
  seo_faq_q1: "Wie kann ich bei MicaLingo kostenlos Deutsch lernen?",
  seo_faq_a1: "Nutze kostenlose Quizze zu Wortschatz, Grammatik, Artikeln (der, die, das), Verben, Adjektiven und Präpositionen sowie Lese- und Hörmaterialien.",
  seo_faq_q2: "Wie übe ich deutsche Artikel der, die, das?",
  seo_faq_a2: "Öffne Quizze und starte das Artikel-Quiz, um der, die, das und das Genus zu trainieren.",
  seo_faq_q3: "Gibt es Quizze zu Verben und Grammatik?",
  seo_faq_a3: "Ja. Übe deutsche Verben (Konjugation und Vergangenheit) und lerne Grammatik: Fälle, Zeitformen, Adjektive, Präpositionen und Satzbau.",
  seo_faq_q4: "Sind die öffentlichen Quizze nur Deutsch–Ungarisch?",
  seo_faq_a4: "Ja. Die offene Bibliothek ist für Ungarisch sprechende Deutschlernende. Mit Google-Konto baust du eine private Bibliothek in beliebigen Sprachen und erzeugst eigene Quizze.",
  seo_faq_q5: "Brauche ich ein Konto zum Üben?",
  seo_faq_a5: "Nein. Öffentliche DE–HU-Quizze, Grammatik-Primer und Ratgeber funktionieren ohne Login. Ein Google-Konto braucht es nur für private Bibliothek, markierte Wörter und Importe.",
  seo_faq_q6: "In welchen Sprachen gibt es MicaLingo?",
  seo_faq_a6: "Die Oberfläche ist Englisch, Deutsch und Ungarisch. Öffentlich übst du Deutsch mit ungarischer Bedeutung. Nach dem Google-Login können deine privaten Listen jedes Sprachenpaar sein.",

  learn_hub_title: "Deutsch-Lernratgeber",
  learn_hub_intro: "Eigene Ratgeber zum Selbstlernen: öffentliche Deutsch–Ungarisch-Bibliothek vs. eigene Quizze, der/die/das und deutsche Fälle. Erst lesen, dann die Quizze nutzen.",
  learn_read_time: "{minutes} Min. Lesezeit",
  learn_byline: "MicaLingo-Ratgeber · etwa {minutes} Minuten",
  learn_more_guides: "Weitere Ratgeber",
  learn_card_title: "Lernratgeber",
  learn_card_subtitle: "Öffentlich vs privat, Artikel und Fälle.",
  home_how_heading: "So lernst du Deutsch auf MicaLingo",
  home_quiet_blurb: "Lernratgeber, wenn du die Methode hinter den Quizzen willst:",
  grammar_primer_heading: "Hier anfangen",
  grammar_more_notes_later: "Längere Notizen aus der öffentlichen Bibliothek erscheinen hier, sobald sie veröffentlicht sind. Die Erklärung oben reicht zum Starten.",
  sample_words_heading: "Beispielwörter in dieser Bibliothek",
  sample_words_intro: "Einige Einträge, die dir in den öffentlichen Quizzen zu diesem Thema begegnen.",

  about_who_heading: "Wer betreibt MicaLingo",
  about_who_body: "MicaLingo ist ein unabhängig betriebenes Bildungsprojekt für Selbstlernende. Es ist kein Prüfungszentrum. Website und Android-App werden als ein kostenloses Lernwerkzeug gepflegt. Fragen an support.micalingo@gmail.com.",
  about_how_heading: "Wie die Materialien entstehen",
  about_how_body: "Öffentliche Quizze basieren auf kuratierten deutsch–ungarischen Wort- und Phrasenlisten zu Alltagsthemen wie Wohnen, Reisen, Arbeit und Essen. Grammatikseiten beginnen mit eigenen Primern, die ohne Klick sichtbar bleiben, plus längeren Notizen in der öffentlichen Bibliothek. Mit Google-Konto importierst du eigene Listen in beliebigen Sprachen und erzeugst eigene Quizze. Die Erklärungen auf dieser Seite sind für MicaLingo geschrieben und nicht aus anderen Lehrbüchern kopiert.",
  about_for_heading: "Für wen die Seite ist",
  about_for_body: "Die Oberfläche ist Englisch, Deutsch und Ungarisch, weil viele Besucher Ungarisch sprechende Deutschlernende sind (oder Englisch als Brücke nutzen). Öffentlich übst du dieses DE–HU-Paar. Nach dem Google-Login können Lehrkräfte und Selbstlernende eine private Bibliothek einrichten, wie sie wollen. Private Listen bleiben beim angemeldeten Konto.",

  footer_tagline: "Deutsch lernen mit Quizzen, Grammatik, Wortschatz, Artikeln (der, die, das) und Verben. Learn German. Német tanulás.",
};
