export const de = {
  title: "Deutschprüfung Vorbereitung",

  // Settings
  settings_title: "Einstellungen",
  settings_subtitle: "Verwalte dein Konto und die Anwendungseinstellungen.",
  language_preferences: "Spracheinstellungen",
  language_preferences_subtitle: "Wähle die Anwendungssprache aus.",
  app_language: "App-Sprache",
  english: "Englisch",
  german: "Deutsch",
  hungarian: "Ungarisch",
  practice_settings: "Übungseinstellungen",
  practice_settings_subtitle: "Passe dein Quiz-Erlebnis an.",
  show_example_sentences: "Beispielsätze anzeigen",
  show_example_sentences_subtitle: "Zeige Beispielsätze nach der Beantwortung einer Frage an.",
  save_preferences: "Einstellungen speichern",
  saving_preferences: "Speichern...",
  save_button: "Speichern",
  data_management: "Datenverwaltung",
  data_management_subtitle: "Verwalte deinen gespeicherten Fortschritt und lokale Daten.",
  clear_local_data: "Lokalen Fortschritt löschen",
  confirm_clear_data: "Bist du sicher, dass du deinen lokalen Fortschritt löschen möchtest? Dies kann nicht rückgängig gemacht werden.",
  data_cleared: "Lokaler Fortschritt erfolgreich gelöscht.",
  confirm_reset_library: "Bist du sicher, dass du alle persönlichen Bibliotheksartikel löschen möchtest? Dies kann nicht rückgängig gemacht werden.",
  library_wiped: "Persönliche Bibliothek erfolgreich gelöscht.",
  wipe_error: "Fehler beim Löschen der persönlichen Bibliothek. Bitte versuche es erneut.",
  saved: "Gespeichert!",
  developer_tools: "Entwicklerwerkzeuge",
  developer_tools_subtitle: "Verwende diese Schaltfläche, um deine persönlichen Cloud-Daten vollständig zurückzusetzen. (Dies löscht NICHT die öffentliche Gastbibliothek). Lösche dies vor der Bereitstellung aus dem Code.",
  wiping_data: "Daten werden gelöscht...",
  hard_reset_database: "Datenbank hart zurücksetzen",
  hard_reset_warning: "⚠️ WARNUNG: Bist du SICHER, dass du ALLE deine persönlich importierten Vokabeln vollständig löschen möchtest? (Die öffentliche offene Bibliothek ist NICHT betroffen). Dies kann nicht rückgängig gemacht werden!",
  hard_reset_success: "Datenbank vollständig gelöscht! Du hast einen Neuanfang.",
  reset_personal_library: "Persönliche Bibliothek zurücksetzen",
  reset_personal_library_desc: "Lösche dauerhaft alle deine benutzerdefinierten importierten Wörter und Grammatikmaterialien aus der Cloud. Dies kann nicht rückgängig gemacht werden.",
  clear_local_data_desc: "Lösche lokale Quiz-Ergebnisse und Fortschritte. Löscht keine Cloud-Vokabeln.",

  // Quizzes
  quizzes_title: "Quizze",
  quizzes_subtitle: "Wähle ein Thema zum Üben.",
  test_your_knowledge: "Teste dein Wissen",
  test_your_knowledge_subtitle: "Übe mit unserer öffentlichen Datenbank.",
  vocabulary: "Wortschatz",
  vocabulary_quiz_subtitle: "Übe wesentliche Wörter.",
  articles_quiz: "Artikel",
  articles_quiz_subtitle: "Übe der, die, das.",
  phrases_quiz: "Redewendungen und Sätze",
  phrases_quiz_subtitle: "Nützliche alltägliche Redewendungen und Sätze.",
  phrases_sentences_quiz: "Redewendungen und Sätze",
  prepositions_quiz: "Präpositionen",
  prepositions_quiz_subtitle: "Übe Präpositionen und Fälle.",
  verbs_quiz: "Verben",
  verbs_quiz_subtitle: "Übe deutsche Verben und Vergangenheitsformen.",
  create_your_own_quizzes: "Benutzerdefinierte Quizze",
  create_your_own_quizzes_subtitle_loggedin: "Übe mit deinen eigenen importierten Wörtern.",
  vocabulary_quiz: "Wortschatz",
  create_your_own_quizzes_subtitle_loggedout: "Melde dich an, um benutzerdefinierte Quizze zu erstellen.",
  login_to_create_quizzes: "Anmelden",
  question_of: "Frage: {current} / {total}",
  choose_correct_one: "Wähle die richtige Lösung!",
  custom_vocab_desc: "Übe Wortübersetzungen aus deiner persönlichen Bibliothek.",
  custom_articles_desc: "Übe 'der, die, das' mit deinen eigenen Substantiven.",
  custom_phrases_desc: "Teste dein Wissen über benutzerdefinierte Redewendungen und Sätze.",
  custom_prepositions_desc: "Übe Fälle für Präpositionen, die du importiert hast.",
  custom_verbs_desc: "Deine persönlichen Verben.",

  // Navigation & Layout
  home: "Startseite",
  import: "Importieren",
  quizzes: "Quizze",
  grammar: "Grammatik",
  statistics: "Statistiken",
  settings: "Einstellungen",
  sign_out: "Abmelden",
  login: "Anmelden",
  vocabulary_short: "Vokabeln",
  support_micalingo: "MicaLingo unterstützen",
  support_desc: "Wähle einen Betrag, um unser Projekt zu unterstützen. Jeder Beitrag hilft!",
  support_tier_1: "Kaffee",
  support_tier_2: "Snack",
  support_tier_3: "Mittagessen",
  support_tier_4: "Held 🚀",
  enjoying_micalingo_title: "Gefällt dir MicaLingo?",
  consider_donation_desc: "Bitte erwäge, das Projekt zu unterstützen, damit es weiterlaufen kann und werbefrei bleibt.",
  yes_support: "Ja, zeig es mir!",
  maybe_later: "Vielleicht später",

  // Home
  welcome_back: "Willkommen, schön dich hier zu sehen!",
  ready_to_learn: "Bereit, dein Deutsch zu verbessern? Erstelle deine eigene Bibliothek, Quizze und Lernmaterialien, teste jetzt dein Wissen!",
  import_data: "Daten importieren und verwalten",
  upload_new_materials: "Neue Wörter und Sätze hochladen.",
  login_required: "Anmeldung erforderlich",
  to_create_new_quizzes_login_required: "Anmeldung erforderlich, um benutzerdefinierte Quizze zu erstellen",
  learn_new_words_from_library: "Durchsuche die Bibliothek oder deine eigenen Wörter.",
  login_to_create_quizzes_desc: "Wenn du deinen eigenen Wortschatz und eigene Quizze erstellen möchtest, melde dich bitte an!",
  for_extending_login_required: "Anmeldung für ein persönliches Wörterbuch erforderlich",
  coming_soon: "Demnächst",
  review_grammar_topics: "Grammatikregeln und Erklärungen.",
  track_your_progress: "Verfolge deinen Lernfortschritt.",
  download_android: "Hol dir die Android-App",
  download_android_desc: "Nimm dein MicaLingo mit! Lade sie direkt auf dein Handy herunter.",
  download_apk: "Herunterladen",
  android_install_note: "Hinweis: Da diese App direkt heruntergeladen wird, zeigt Ihr Telefon möglicherweise eine Sicherheitswarnung an. Klicken Sie auf 'Weitere Details' und dann auf 'Trotzdem installieren', um fortzufahren.",

  // Import
  import_title: "Dateien importieren",
  accepted_format_guide: "Akzeptierte Formate",
  vocab_phrases: "Wortschatz (Lesen oder Quiz) / Redewendungen-Quiz:",
  format_vocab_phrases: "Spalte A = Deutsch (Phrase/Satz), Spalte B = Ungarisch (Bedeutung), Spalte C = Beispiel (Optional).",
  verbs_quiz_format_title: "Verben-Quiz:",
  verbs_quiz_format_desc: "Spalte A = Deutsch (Verb), Spalte B = Ungarisch (Bedeutung), Spalte C = Vergangenheitsformen oder Beispiele.",
  prepositions_quiz_format_title: "Präpositionen-Quiz:",
  prepositions_quiz_format_desc: "Spalte A: Deutsches Verb + ungarische Bedeutung, Spalte B: Präposition + Fall, Spalte C: Beispielsatz.",
  articles_quiz_label: "Artikel-Quiz:",
  format_articles: "Spalte A = Artikel, Spalte B = Substantiv, Spalte C = Ungarisch, Spalte D = Beispiel.",
  need_starting_point: "Brauchen Sie einen Ausgangspunkt?",
  download_template_desc: "Lade eine Excel-Vorlage herunter.",
  vocab_template: "Wortschatz-Vorlage (Lesen oder Quiz)",
  articles_template: "Vorlage für Quiz-Artikel",
  verbs_template: "Vorlage für Quiz-Verben",
  prepositions_template: "Vorlage für Quiz-Präpositionen",
  template_german_verb_header: "Deutsches Verb + Ungarisch",
  template_prep_case_header: "Präposition + Fall",
  template_meaning_example_header: "Beispielsatz",
  drag_and_drop: "Drag & Drop oder Klicken zum Durchsuchen",
  supported_files: "Unterstützt Excel, Word, PDF, CSV und TXT",
  preview_filename: "Vorschau: {filename}",
  items_detected: "{count} Elemente erkannt",
  article: "Artikel", noun: "Substantiv + Plural", example: "Beispiel", column_a: "Spalte A", column_b: "Spalte B", column_c: "Spalte C", column_c_d: "Spalte C/D", column_d: "Spalte D",
  invalid_columns: "Gültige Spalten konnten nicht erkannt werden.",
  invalid_columns_desc: "Stelle sicher, dass die Datei Tabulatoren (Excel), Semikolons oder Kommas zur Trennung verwendet.",
  save_to: "Speichern in:",
  cancel: "Abbrechen",
  saving: "Speichern...",
  save_import: "Import speichern",
  manage_imported_files: "Importierte Dateien verwalten",
  manage_imported_files_desc: "Das Löschen einer Datei entfernt alle daraus importierten Wörter aus deinen Quizzen.",
  search_files: "Dateien oder Schlüsselwörter suchen...",
  files_selected: "{count} Dateien ausgewählt",
  download_selected: "Ausgewählte herunterladen",
  delete_selected: "Ausgewählte löschen",
  file_name: "Dateiname",
  format: "Format",
  used_in: "Verwendet in",
  items: "Elemente",
  action: "Aktion",
  download: "Herunterladen",
  delete: "Löschen",
  hint: "Tipp / Vergangenheitsform",
  confirm_delete_file: "Bist du sicher, dass du \"{fileName}\" löschen möchtest? Dadurch werden alle {count} Wörter dauerhaft entfernt.",
  error_delete_file_desc: "Beim Löschen ist ein Fehler aufgetreten.",
  confirm_bulk_delete: "Bist du sicher, dass du {count} Dateien löschen möchtest?",
  error_bulk_delete_desc: "Beim Löschen der Dateien ist ein Fehler aufgetreten.",
  no_items_export: "Keine Elemente zum Exportieren gefunden.",
  no_items_save: "Keine gültigen Vokabeln zum Speichern oder Benutzer nicht angemeldet.",
  import_success_with_duplicates: "Import abgeschlossen! {saved} neue Elemente gespeichert. {duplicates} Duplikate übersprungen.",
  import_success: "Import abgeschlossen! {saved} neue Elemente gespeichert.",
  import_overwritten: "{count} vorhandene Elemente überschrieben.",
  import_skipped: "{count} doppelte Elemente übersprungen.",
  overwrite_confirm_title: "Duplikate überschreiben?",
  overwrite_confirm_desc: "{count} bereits vorhandene Elemente gefunden. Möchten Sie sie mit den Daten aus Ihrer Datei überschreiben?",
  overwrite_button: "Überschreiben",
  skip_button: "Duplikate überspringen",
  error_saving_db: "Beim Speichern in der Datenbank ist ein Fehler aufgetreten.",

  // Vocabulary Page
  vocab_title: "Wortschatz",
  vocab_subtitle: "Durchsuche und verwalte deine gelernten Wörter.",
  add_word: "Wort hinzufügen",
  open_library: "Offene Bibliothek",
  personalized_space: "Privater Bereich",
  marked_words: "Markierte Wörter",
  marked_words_subtitle: "Übe Wörter, die du nach einer falschen Antwort markiert hast.",
  marked_words_description: "Bei einer falschen Antwort tippe auf den Stern, um das Wort hier zu speichern. Übe sie als gemischtes Quiz oder entferne Wörter einzeln.",
  marked_words_empty: "Noch keine markierten Wörter",
  marked_words_empty_desc: "Beantworte eine Quizfrage falsch und tippe dann oben rechts auf den Stern, um das Wort hier zu speichern.",
  marked_words_practice: "Markierte Wörter üben",
  marked_words_manage: "Bibliothek verwalten",
  marked_words_manage_desc: "Entferne Wörter einzeln nur aus deiner markierten Liste. Die öffentliche Bibliothek bleibt unverändert.",
  mark_word: "Wort markieren",
  unmark_word: "Markierung entfernen",
  word_marked: "Wort markiert",
  quiz_title_marked: "Markierte-Wörter-Quiz {id}",
  personalized_space_empty: "Dein privater Bereich ist leer",
  search_vocabulary: "Wortschatz durchsuchen...",
  words_found: "{count} Wörter gefunden",
  words_count: "{count} Wörter",
  no_words_match_search: "Keine Wörter entsprechen deiner Suche.",
  checking_account: "Konto wird überprüft...",
  personalized_space_description: "Melde dich einfach sicher mit deinem Google-Konto an, um deinen privaten Wortschatz zu erstellen.",
  login_with_google: "Mit Google anmelden",
  loading_vocabulary: "Ihr Wortschatz wird geladen...",
  words_selected: "{count} Wörter ausgewählt",
  delete_selected_words: "Ausgewählte löschen",
  edit_word: "Bearbeiten",
  delete_word: "Wort löschen",
  modal_edit_word_title: "Wort bearbeiten",
  modal_add_word_title: "Neues Wort hinzufügen",
  modal_category_label: "Kategorie",
  modal_german_label: "Deutsch (mit Artikel & Plural) *",
  modal_german_placeholder: "z.B. der Apfel",
  modal_article_label: "Artikel *",
  modal_noun_label: "Substantiv (mit Plural) *",
  modal_noun_placeholder: "z.B. Mann, die Männer",
  modal_german_phrase_label: "Deutsche Phrase/Satz *",
  modal_german_phrase_placeholder: "z.B. Wie geht es Ihnen?",
  modal_hungarian_phrase_placeholder: "z.B. Hogy van?",
  modal_german_prep_label: "Deutsche Präposition *",
  modal_german_prep_placeholder: "z.B. mit",
  modal_hungarian_prep_placeholder: "z.B. val/vel",
  prep_case_label: "Präposition + Fall *",
  modal_prep_case_placeholder: "z.B. auf + Akk.",
  meaning_example_label: "Beispielsatz",
  meaning_example_placeholder: "z.B. Ich verzichte auf das Angebot.",
  modal_german_prep_verb_label: "Deutsches Verb + Ungarisch *",
  modal_german_prep_verb_placeholder: "z.B. verzichten, lemondani valamiről/felhagyni valamivel",
  modal_german_verb_label: "Deutsches Verb *",
  modal_german_verb_placeholder: "z.B. machen",
  modal_hungarian_verb_placeholder: "z.B. csinálni",
  modal_german_ff_label: "Falscher Freund (Deutsch) *",
  modal_german_ff_placeholder: "z.B. das Gift, die Gifte",
  modal_hungarian_ff_placeholder: "z.B. a méreg",
  modal_hungarian_label: "Ungarisch *",
  modal_hungarian_placeholder: "z.B. alma",
  modal_example_label: "Beispiel / Kommentar",
  modal_example_placeholder: "z.B. Ich esse einen Apfel.",
  modal_save_changes: "Änderungen speichern",
  modal_save_word: "Wort speichern",
  alert_fill_fields_login: "Bitte fülle mindestens die deutschen und ungarischen Felder aus.",
  alert_confirm_delete_word: "Bist du sicher, dass du dieses Wort löschen möchtest?",
  alert_confirm_bulk_delete_words: "Bist du sicher, dass du {count} Wörter löschen möchtest?",
  alert_login_failed: "Anmeldung mit Google fehlgeschlagen.",
  alert_word_exists: "Dieses Wort existiert bereits in deinem '{category}'!",
  duplicates_found_title: "Duplikate gefunden",
  duplicates_found_subtitle: "Diese Elemente existieren bereits am Zielort und wurden nicht verschoben.",
  all_categories: "Alle Kategorien",

  // Dropdown Categories
  dropdown_vocabulary: "Wortschatz-Quiz",
  dropdown_reading: "Wortschatz (zum Lesen)",
  vocab_reading_subtitle: "Nur zum Lesen hochgeladene Wörter — getrennt von den Quiz-Bibliotheken.",
  copy_to_quiz: "Auch zum Quiz hinzufügen...",
  copy_to_quiz_hint: "Erstellt eine separate Quiz-Kopie. Das Wort bleibt in Wortschatz (zum Lesen).",
  category_separation_hint: "Lese- und Quiz-Bibliotheken sind getrennt — dasselbe Wort kann in beiden vorkommen.",
  dropdown_articles: "Artikel-Quiz",
  dropdown_phrases: "Ausdrücke und Sätze Quiz",
  dropdown_prepositions: "Präpositionen-Quiz",
  dropdown_adjectives: "Adjektive-Quiz",
  dropdown_verbs: "Verben-Quiz",
  dropdown_false_friends: "Falsche Freunde",

  // Quiz Page
  loading_questions: "Ihre Fragen werden geladen...",
  not_enough_words: "Nicht genügend Wörter",
  not_enough_words_desc: "Du hast nicht genügend Wörter für ein {topic}-Quiz.",
  need_more_items: "Du benötigst mindestens 4 Elemente für '{topic}'.",
  import_more_words: "Mehr Wörter importieren",
  quiz_complete: "Quiz abgeschlossen!",
  no_more_quizzes: "Du hast alle verfügbaren Quizzes für dieses Thema abgeschlossen!",
  great_job: "Toll gemacht – weiter so!",
  your_score: "Deine Punktzahl:",
  back_to_quizzes: "Zurück zu den Quizzen",
  retry_quiz: "Quiz wiederholen",
  go_to_level: "Gehe zu Level {level}",
  next_question: "Nächste Frage",
  finish_quiz: "Quiz beenden",
  back_button: "← Zurück",
  next_quiz_button: "Nächstes Quiz →",
  example_label: "Beispiel",
  quiz_title_public: "{topic} Quiz {id}",
  quiz_title_custom: "Benutzerdefiniertes {topic} Quiz {id}",
  quiz_title_personal: "Privates Quiz",
  items_count: "{count} Elemente",
  quit_quiz_title: "Quiz beenden?",
  quit_quiz_desc: "Ihr Fortschritt wurde automatisch gespeichert.",
  quit: "Beenden",

  // Topic Quizzes
  topic_not_found: "Thema nicht gefunden",
  return_to_quizzes: "Zurück zu den Quizzen",
  select_level_to_start: "Wähle ein Level aus.",
  level_id: "Level {id}",
  start_button: "Start →",
  continue_button: "Weiter →",
  personalized_quizzes: "Private Quizze",
  personalized_quizzes_desc: "Kein separates Konto erforderlich! Melde dich an.",
  your_custom_quizzes: "Deine benutzerdefinierten Quizze",
  custom_quizzes_count_desc: "Du hast derzeit {count} Elemente gespeichert.",
  start_custom_quiz: "Benutzerdefiniertes Quiz starten",
  import_more_data: "Mehr Daten importieren",

  // Create Quiz
  create_custom_quiz_title: "Ein benutzerdefiniertes {topic}-Quiz erstellen",
  choose_data_source: "Wähle deine Datenquelle.",
  use_personal_library: "Persönliche Bibliothek verwenden",
  use_personal_library_desc: "Erstelle ein Quiz aus deinen eigenen Wörtern.",
  upload_new_file: "Neue Datei hochladen",
  upload_new_file_desc: "Importieren Sie eine neue Datei für diesen Quiz-Typ.",
  required_format: "Erforderliches Format:",
  download_template: "Vorlage herunterladen",
  go_to_import_page: "Zur Importseite gehen →",
  instructions_articles: "Spalte A = Artikel, Spalte B = Substantiv, Spalte C = Ungarisch.",
  instructions_prepositions: "Spalte A = Präposition, Spalte B = Ungarisch.",
  instructions_vocabulary: "Spalte A = Deutsch, Spalte B = Ungarisch.",
  instructions_phrases: "Spalte A = Phrase, Spalte B = Ungarisch.",
  template_article_header: "Artikel (A)",
  template_noun_header: "Substantiv + Plural (B)",
  template_hungarian_header: "Ungarisch (C)",
  template_example_header: "Beispiel (D)",
  template_german_header: "Deutsch",
  template_german_mandatory_header: "Deutsch (Erforderlich, z.B. mit Artikel/Plural)",
  template_hungarian_mandatory_header: "Ungarisch (Erforderlich)",
  template_example_optional_header: "Beispiel (Optional)",

  // Grammar & Statistics
  grammar_page_title: "Grammatik",
  grammar_page_subtitle: "Grammatikregeln und Erklärungen.",
  grammar_cases: "Fälle (Kasus)",
  grammar_tenses: "Zeitformen (Tempora)",
  grammar_articles: "Artikel & Geschlechter",
  grammar_adjectives: "Adjektivdeklination",
  grammar_prepositions: "Präpositionen",
  grammar_sentence_structure: "Satzbau",
  add_grammar_rule: "Grammatikregel hinzufügen",
  edit_grammar_rule: "Grammatikregel bearbeiten",
  delete_grammar_rule: "Grammatikregel löschen",
  grammar_rule_title: "Titel der Regel",
  grammar_rule_content: "Grammatikerklärung",
  fetch_content: "Inhalt abrufen",
  fetch_error: "Inhalt konnte nicht abgerufen werden. Bitte URL prüfen oder manuell einfügen.",
  bullet_list: "• Aufzählungsliste",
  undo_button: "↩ Rückgängig",
  no_items: "Noch keine Einträge.",
  confirm_delete_grammar: "Möchtest du diese Grammatikregel wirklich löschen?",
  statistics_page_title: "Statistiken",
  statistics_page_subtitle: "Verfolge deinen Lernfortschritt.",
  page_under_construction: "Diese Seite befindet sich im Aufbau.",
  check_back_later: "Bitte schauen Sie später wieder vorbei!",
  guest_warning_stats: "Melde dich an, um den Fortschritt zu speichern ",
  guest_warning_stats_link: "hier!",
  quizzes_solved: "Quizze gelöst",
  materials_read: "Materialien gelesen",
  no_quizzes_solved: "Du hast noch keine Quizze abgeschlossen.",
  no_materials_read: "Du hast noch keine Materialien gelesen.",
  select_all: "Alle auswählen",
  stats_quiz: "Quiz",
  stats_score: "Punktzahl",
  stats_actions: "Aktionen",
  admin_target: "Admin-Ziel",
  public_library_target: "Öffentliche Bibliothek",
  personal_library_target: "Persönliche Bibliothek",
  review_button: "Überprüfen",
  download_button: "Herunterladen",
  redo_button: "Wiederholen",
  correct_answer: "Richtige Antwort",
  your_answer: "Deine Antwort",
  csv_question: "Frage",
  csv_result: "Ergebnis",
  result: "Ergebnis",
  status_excellent: "Ausgezeichnet",
  status_good: "Gut",
  status_needs_practice: "Übung nötig",
  csv_correct: "Richtig",
  csv_incorrect: "Falsch",
  delete_selected_records: "Ausgewählte löschen",
  confirm_delete_record: "Möchtest du dieses Ergebnis wirklich löschen?",
  confirm_bulk_delete_records: "Möchtest du {count} Ergebnisse löschen?",
  records_selected: "{count} Ergebnisse ausgewählt",

  // Login Page
  login_page_title: "Anmelden",
  login_page_subtitle: "Melde dich sicher mit deinem Google-Konto an.",

  // Results Page
  results_page_title: "Quiz-Ergebnisse",
  results_page_subtitle: "Überprüfe deine Antworten.",
  review_answers: "Antworten überprüfen",
  retry_mistakes: "Fehler wiederholen",
  close: "Schließen",
  expand_table: "Tabelle vergrößern",
  table_preview: "Tabellenvorschau",

  // Library & Learning Materials
  library: "Bibliothek",
  library_subtitle: "Greife auf deine Vokabeln zu.",
  learning_materials: "Die Unterlagen",
  learning_materials_subtitle: "Texte lesen, Audio hören.",
  read_materials: "Lesen",
  read_materials_desc: "Texte, Artikel und Geschichten lesen.",
  listen_materials: "Hören",
  listen_materials_desc: "Audiospuren und Podcasts hören.",
  save_to_reading: "Lesematerial",
  save_to_listening: "Hörmaterial",
  interesting_section: "Interessant",
  articles_section: "Artikel",
  books_section: "Bücher",
  music_section: "Musik",
  podcasts_section: "Podcasts",
  audiobooks_section: "Hörbücher",
  history: "Geschichte",
  history_desc: "Historische Ereignisse und Persönlichkeiten.",
  animals: "Tiere",
  animals_desc: "Tierwelt und Natur.",
  music: "Musik",
  music_desc: "Komponisten, Instrumente und Genres.",
  culture: "Kultur",
  culture_desc: "Kunst, Konzerte und Ausstellungen.",
  politics: "Politik",
  politics_desc: "Regierung und Gesellschaft.",
  science: "Wissenschaft",
  science_desc: "Entdeckungen und Forschung.",
  celebrities: "Prominente",
  celebrities_desc: "Berühmte Personen und Popkultur.",
  classic_literature: "Klassische Literatur",
  classic_literature_desc: "Lies die Meisterwerke.",
  short_stories: "Kurzgeschichten",
  short_stories_desc: "Kurze Texte für das tägliche Üben.",
  pop: "Pop",
  pop_desc: "Beliebte Musikhits.",
  rock: "Rock",
  rock_desc: "Rock und alternative Musik.",
  other_music: "Andere",
  other_music_desc: "Verschiedene andere Genres.",
  travel: "Reisen",
  travel_desc: "Geschichten und Tipps aus aller Welt.",
  psychology: "Psychologie",
  psychology_desc: "Geist, Verhalten und psychische Gesundheit.",
  other_podcasts: "Andere",
  other_podcasts_desc: "Verschiedene andere Podcast-Themen.",
  fiction: "Fiktion",
  fiction_desc: "Romane und Geschichten.",
  non_fiction: "Sachbücher",
  non_fiction_desc: "Faktisch und lehrreich.",
  other_audiobooks: "Andere",
  other_audiobooks_desc: "Verschiedene andere Hörbücher.",

  // Protected Route / Login Prompt
  protected_space_title: "Privater Bereich",
  protected_space_desc_1: "Melde dich sicher mit deinem Google-Konto an.",
  protected_space_desc_2: "Melde dich an, um fortzufahren!",
  continue_with_google: "Mit Google fortfahren",

  // Admin
  admin_mode: "Admin-Modus",
  admin_mode_desc: "Du bist als Administrator angemeldet.",
  switch_to_normal_user: "Zu normalem Benutzer wechseln",
  switch_to_admin: "Zum Admin-Modus wechseln",
  admin_prompt_title: "Willkommen, Admin!",
  admin_prompt_desc: "Wähle, wie du die Anwendung nutzen möchtest.",
  admin_mode_dev: "Entwicklermodus",
  admin_mode_normal: "Normaler Benutzermodus",

  // False Friends
  false_friends: "Falsche Freunde",
  false_friends_desc: "Wörter, die ähnlich aussehen oder klingen.",
  false_friends_template: "Falsche Freunde Vorlage (lesen)",
  template_note_header: "Notiz (D)",
  note: "Notiz / Bedeutung",
  admin_save_public: "Admin: In öffentlicher Bibliothek speichern",
  media_player: "Media-Player",
  play_content: "Inhalt abspielen",
  fetch_error_audio: "Audiodetails konnten nicht abgerufen werden. Bitte überprüfe die URL oder füge sie manuell ein.",
  save_error_audio: "Fehler beim Speichern des Audios. Stelle sicher, dass du angemeldet bist.",
  delete_error_audio: "Fehler beim Löschen des Audios.",
  confirm_delete_audio: "Bist du sicher, dass du dieses Audio löschen möchtest?",
  add_audio: "Audio hinzufügen",
  audio_url: "Audio/Video-URL",
  fetch_audio: "Inhalt abrufen",
  audio_title: "Audiotitel",
  audio_content: "Audiobeschreibung / Inhalt",
  audio_source: "Künstler / Quelle",
  audio_source_placeholder: "z.B. Rammstein",
  save_audio: "Audio speichern",
  edit_audio: "Audio bearbeiten",
  delete_audio: "Audio löschen",
  audio_url_note: "Hinweis: YouTube- und Spotify-URLs generieren automatisch einen eingebetteten Player!",
  add_article: "Artikel hinzufügen",
  article_url: "Artikel URL",
  fetch_article: "Inhalt abrufen",
  article_title: "Artikel Titel",
  article_content: "Artikel Inhalt",
  article_source: "Quelle",
  article_source_placeholder: "z.B. Der Standard",
  save_article: "Artikel speichern",
  edit_article: "Artikel bearbeiten",
  delete_article: "Artikel löschen",
  confirm_delete_article: "Bist du sicher, dass du diesen Artikel löschen möchtest?",
  add_book: "Buch hinzufügen",
  book_url: "Buch-URL",
  fetch_book: "Inhalt abrufen",
  book_title: "Buchtitel",
  book_content: "Buchinhalt",
  book_source: "Autor / Quelle",
  book_source_placeholder: "z.B. Goethe",
  save_book: "Buch speichern",
  edit_book: "Buch bearbeiten",
  delete_book: "Buch löschen",
  confirm_delete_book: "Bist du sicher, dass du dieses Buch löschen möchtest?",
  bookmark_instructions_logged_in: "Markiere während des Lesens einen beliebigen Text, um ein Lesezeichen zu speichern oder den markierten Text direkt in deine persönliche Vokabel-Datenbank oder in deine Quizze aufzunehmen!",
  bookmark_instructions_guest: "Markiere während des Lesens einen beliebigen Text, um ein Lesezeichen zu speichern oder den markierten Text direkt in deine persönliche Vokabel-Datenbank oder in deine Quizze aufzunehmen! (Diese Funktion ist exklusiv für angemeldete Benutzer verfügbar. Melde dich an, um sie zu nutzen!)",
  save_bookmark: "Lesezeichen",
  continue_from: "Weiterlesen ab:",
  no_audio_yet: "Noch keine Audioinhalte.",
  no_audio_yet_admin: "Noch keine Inhalte hier. Klicke oben auf '+ Audio hinzufügen', um den ersten Titel hinzuzufügen!",
  private_reading_hint: "Erstelle deine eigenen Lesekategorien, um deine Texte, Artikel oder Bücher zu organisieren.",
  private_listening_hint: "Erstelle Kategorien wie Musikstil oder gruppiere deine Lieblingslieder nach Künstlern oder Jahren.",
  private_grammar_hint: "Erstelle eigene Grammatikkategorien, um deine Notizen zu ordnen.",
  private_category_1: "Kategorie 1",
  private_category_2: "Kategorie 2",
  private_category_3: "Kategorie 3",
  private_category_4: "Kategorie 4",
  private_category_5: "Kategorie 5",
  edit_category: "Kategorie bearbeiten",
  adjectives_quiz: 'Adjektive',
  adjectives_quiz_subtitle: 'Übe deutsche Adjektive.',
  custom_adjectives_desc: 'Deine persönlichen Adjektive.',
  template_adjective_header: 'Adjektiv (erforderlich)',
  template_levels_header: 'Steigerung (z.B. besser, am besten)',
  adjectives_quiz_label: 'Adjektive-Quiz:',
  format_adjectives: 'Spalte A: Deutsch, Spalte B: Ungarisch, Spalte C: Steigerung (z.B. besser, am besten) oder Beispielsatz.',
  adjectives_template: 'Vorlage für Quiz-Adjektive',
  adjective: 'Adjektiv',
  levels: 'Steigerung',
  url_optional: "URL (Optional)",
  title_label: "Titel",
  source_author: "Quelle / Autor",
  source_artist: "Quelle / Künstler",
  content_label: "Inhalt",
  fetch_note: "Hinweis: Das Abrufen erfolgt über einen Proxy. Komplexe Websites blockieren möglicherweise die Extraktion. Du kannst Inhalte jederzeit manuell einfügen.",
  no_items_left: "Keine Elemente mehr. Speichern, um alle zu löschen.",
  original_source: "Originalquelle",
  add_interesting: "Interessanten Inhalt hinzufügen",
  edit_interesting: "Interessanten Inhalt bearbeiten",
  delete_interesting: "Inhalt löschen",
  confirm_delete_interesting: "Möchtest du diesen Inhalt wirklich löschen?",
  interesting_url: "Inhalts-URL",
  fetch_interesting: "Inhalt abrufen",
  interesting_title: "Titel",
  interesting_source: "Quelle",
  interesting_source_placeholder: "z.B. Wikipedia",
  interesting_content: "Inhalt",
  save_interesting: "Inhalt speichern",
  fun_facts: "Fakten",
  fun_facts_desc: "Interessante Fakten und Wissenswertes.",
  idioms: "Redewendungen",
  idioms_desc: "Häufige Redewendungen und Sprichwörter.",
  save_to_vocabulary: "Wort speichern",
  add_content: "Inhalt hinzufügen",
  add_image: "Bild hinzufügen",
  explanation_label: "Erklärung",
  explanation_placeholder: "Erklärung",
  add_idiom: "Redewendung hinzufügen",
  edit_idiom: "Redewendung bearbeiten",
  idiom_german_label: "Deutsche Redewendung *",
  idiom_german_placeholder: "z.B. Ich verstehe nur Bahnhof",
  idiom_hungarian_label: "Ungarische Bedeutung *",
  idiom_hungarian_placeholder: "z.B. Nekem ez kínai",
  idiom_note_label: "Notiz (Erklärung)",
  idiom_note_placeholder: "Wörtliche Bedeutung...",
  save_content: "Inhalt speichern",
  confirm_delete_idiom: "Bist du sicher, dass du diese Redewendung löschen möchtest?",
  confirm_delete_ff: "Bist du sicher, dass du diesen falschen Freund löschen möchtest?",
  ff_note_placeholder: "z.B. Falscher Freund: gift != ajándék",
  alert_fill_fields_admin: "Bitte fülle mindestens die deutschen und ungarischen Felder aus.",
  confirm_exit_app: "Möchten Sie die App wirklich beenden?",
};
