export const de = {
  title: "Deutschprüfung Vorbereitung",

  // Settings
  settings_title: "Einstellungen",
  settings_subtitle: "Verwalten Sie Ihr Konto und die Anwendungseinstellungen.",
  language_preferences: "Spracheinstellungen",
  language_preferences_subtitle: "Wählen Sie die Anwendungssprache aus.",
  app_language: "App-Sprache",
  english: "Englisch",
  german: "Deutsch",
  hungarian: "Ungarisch",
  practice_settings: "Übungseinstellungen",
  practice_settings_subtitle: "Passen Sie Ihr Quiz-Erlebnis an.",
  show_example_sentences: "Beispielsätze anzeigen",
  show_example_sentences_subtitle: "Zeigen Sie Beispielsätze nach der Beantwortung einer Frage an.",
  save_preferences: "Einstellungen speichern",
  saving_preferences: "Speichern...",
  save_button: "Speichern",
  data_management: "Datenverwaltung",
  data_management_subtitle: "Verwalten Sie Ihren gespeicherten Fortschritt und lokale Daten.",
  clear_local_data: "Lokalen Fortschritt löschen",
  confirm_clear_data: "Sind Sie sicher, dass Sie allen lokalen Fortschritt löschen möchten? Dies kann nicht rückgängig gemacht werden.",
  data_cleared: "Lokaler Fortschritt erfolgreich gelöscht.",
  confirm_reset_library: "Sind Sie sicher, dass Sie alle persönlichen Bibliotheksartikel löschen möchten? Dies kann nicht rückgängig gemacht werden.",
  library_wiped: "Persönliche Bibliothek erfolgreich gelöscht.",
  wipe_error: "Fehler beim Löschen der persönlichen Bibliothek. Bitte versuchen Sie es erneut.",
  saved: "Gespeichert!",
  developer_tools: "Entwicklerwerkzeuge",
  developer_tools_subtitle: "Verwenden Sie diese Schaltfläche, um Ihre persönlichen Cloud-Daten vollständig zurückzusetzen. (Dies löscht NICHT die öffentliche Gastbibliothek). Löschen Sie dies vor der Bereitstellung aus dem Code.",
  wiping_data: "Daten werden gelöscht...",
  hard_reset_database: "Datenbank hart zurücksetzen",
  hard_reset_warning: "⚠️ WARNUNG: Sind Sie SICHER, dass Sie ALLE Ihre persönlich importierten Vokabeln vollständig löschen möchten? (Die öffentliche offene Bibliothek ist NICHT betroffen). Dies kann nicht rückgängig gemacht werden!",
  hard_reset_success: "Datenbank vollständig gelöscht! Sie haben einen Neuanfang.",
  reset_personal_library: "Persönliche Bibliothek zurücksetzen",
  reset_personal_library_desc: "Löschen Sie dauerhaft alle Ihre benutzerdefinierten importierten Wörter und Grammatikmaterialien aus der Cloud. Dies kann nicht rückgängig gemacht werden.",
  clear_local_data_desc: "Löschen Sie lokale Quiz-Ergebnisse und Fortschritte. Löscht keine Cloud-Vokabeln.",

  // Quizzes
  quizzes_title: "Quizze",
  quizzes_subtitle: "Wählen Sie ein Thema zum Üben.",
  test_your_knowledge: "Testen Sie Ihr Wissen",
  test_your_knowledge_subtitle: "Üben Sie mit unserer öffentlichen Datenbank.",
  vocabulary: "Wortschatz",
  vocabulary_quiz_subtitle: "Üben Sie wesentliche Wörter.",
  articles_quiz: "Artikel",
  articles_quiz_subtitle: "Üben Sie der, die, das.",
  phrases_quiz: "Redewendungen und Sätze",
  phrases_quiz_subtitle: "Nützliche alltägliche Redewendungen und Sätze.",
  prepositions_quiz: "Präpositionen",
  prepositions_quiz_subtitle: "Üben Sie Präpositionen und Fälle.",
  create_your_own_quizzes: "Benutzerdefinierte Quizze",
  create_your_own_quizzes_subtitle_loggedin: "Üben Sie mit Ihren eigenen importierten Wörtern.",
  vocabulary_quiz: "Wortschatz-Quiz",
  create_your_own_quizzes_subtitle_loggedout: "Melden Sie sich an, um benutzerdefinierte Quizze zu erstellen.",
  login_to_create_quizzes: "Anmelden",
  question_of: "Frage: {current} / {total}",
  choose_correct_one: "Wählen Sie die richtige Lösung!",
  custom_vocab_desc: "Üben Sie Wortübersetzungen aus Ihrer persönlichen Bibliothek.",
  custom_articles_desc: "Üben Sie 'der, die, das' mit Ihren eigenen Substantiven.",
  custom_phrases_desc: "Testen Sie Ihr Wissen über benutzerdefinierte Redewendungen und Sätze.",
  custom_prepositions_desc: "Üben Sie Fälle für Präpositionen, die Sie importiert haben.",

  // Navigation & Layout
  home: "Startseite",
  import: "Importieren",
  quizzes: "Quizze",
  grammar: "Grammatik",
  statistics: "Statistiken",
  settings: "Einstellungen",
  sign_out: "Abmelden",
  login: "Anmelden",
  vocabulary_short: "Vokabeln",

  // Home
  welcome_back: "Willkommen, schön dich hier zu sehen!",
  ready_to_learn: "Bereit, Ihr Deutsch zu verbessern? Erstellen Sie Ihre eigene Bibliothek, Quizze und Lernmaterialien, testen Sie jetzt Ihr Wissen!",
  import_data: "Daten importieren",
  upload_new_materials: "Neue Wörter und Sätze hochladen.",
  login_required: "Anmeldung erforderlich",
  to_create_new_quizzes_login_required: "Anmeldung erforderlich, um benutzerdefinierte Quizze zu erstellen",
  learn_new_words_from_library: "Durchsuchen Sie die Bibliothek oder Ihre eigenen Wörter.",
  for_extending_login_required: "Anmeldung für ein persönliches Wörterbuch erforderlich",
  coming_soon: "Demnächst",
  review_grammar_topics: "Grammatikregeln und Erklärungen.",
  track_your_progress: "Verfolgen Sie Ihren Lernfortschritt.",

  // Import
  import_title: "Dateien importieren",
  accepted_format_guide: "Akzeptierte Formate",
  vocab_phrases: "Wortschatz / Redewendungen und Sätze:",
  format_vocab_phrases: "Spalte A = Deutsch (Phrase/Satz), Spalte B = Ungarisch (Bedeutung), Spalte C = Beispiel (Optional).",
  articles_quiz_label: "Artikel-Quiz:",
  format_articles: "Spalte A = Artikel, Spalte B = Substantiv, Spalte C = Ungarisch, Spalte D = Beispiel.",
  text_copy_paste: "Text / Kopieren & Einfügen:",
  format_text: "Trennen Sie Deutsch und Ungarisch mit einem Tabulator, Semikolon (;) oder Komma (,).",
  need_starting_point: "Brauchen Sie einen Ausgangspunkt?",
  download_template_desc: "Laden Sie eine Excel-Vorlage herunter.",
  vocab_template: "Wortschatz-Vorlage",
  articles_template: "Artikel-Vorlage",
  drag_and_drop: "Drag & Drop oder Klicken zum Durchsuchen",
  supported_files: "Unterstützt Excel, Word, PDF, CSV und TXT",
  preview_filename: "Vorschau: {filename}",
  items_detected: "{count} Elemente erkannt",
  article: "Artikel", noun: "Substantiv + Plural", example: "Beispiel", column_a: "Spalte A", column_b: "Spalte B", column_c: "Spalte C", column_c_d: "Spalte C/D", column_d: "Spalte D",
  invalid_columns: "Gültige Spalten konnten nicht erkannt werden.",
  invalid_columns_desc: "Stellen Sie sicher, dass die Datei Tabulatoren (Excel), Semikolons oder Kommas zur Trennung verwendet.",
  save_to: "Speichern in:",
  cancel: "Abbrechen",
  saving: "Speichern...",
  save_import: "Import speichern",
  manage_imported_files: "Importierte Dateien verwalten",
  manage_imported_files_desc: "Das Löschen einer Datei entfernt alle daraus importierten Wörter aus Ihren Quizzen.",
  search_files: "Dateien oder Schlüsselwörter suchen...",
  files_selected: "{count} Dateien ausgewählt",
  download_selected: "Ausgewählte herunterladen",
  delete_selected: "Ausgewählte löschen",
  file_name: "Dateiname",
  format: "Format",
  used_in: "Verwendet in",
  items: "Elemente",
  action: "Aktion",
  download: "Herunterladen",
  delete: "Löschen",
  confirm_delete_file: "Sind Sie sicher, dass Sie \"{fileName}\" löschen möchten? Dadurch werden alle {count} Wörter dauerhaft entfernt.",
  error_delete_file_desc: "Beim Löschen ist ein Fehler aufgetreten.",
  confirm_bulk_delete: "Sind Sie sicher, dass Sie {count} Dateien löschen möchten?",
  error_bulk_delete_desc: "Beim Löschen der Dateien ist ein Fehler aufgetreten.",
  no_items_export: "Keine Elemente zum Exportieren gefunden.",
  no_items_save: "Keine gültigen Vokabeln zum Speichern oder Benutzer nicht angemeldet.",
  import_success_with_duplicates: "Import abgeschlossen! {saved} neue Elemente gespeichert. {duplicates} Duplikate übersprungen.",
  import_success: "Import abgeschlossen! {saved} neue Elemente gespeichert.",
  error_saving_db: "Beim Speichern in der Datenbank ist ein Fehler aufgetreten.",

  // Vocabulary Page
  vocab_title: "Wortschatz",
  vocab_subtitle: "Durchsuchen und verwalten Sie Ihre gelernten Wörter.",
  add_word: "Wort hinzufügen",
  open_library: "Offene Bibliothek",
  personalized_space: "Privater Bereich",
  search_vocabulary: "Wortschatz durchsuchen...",
  words_found: "{count} Wörter gefunden",
  words_count: "{count} Wörter",
  no_words_match_search: "Keine Wörter entsprechen Ihrer Suche.",
  checking_account: "Konto wird überprüft...",
  personalized_space_description: "Melden Sie sich einfach sicher mit Ihrem Google-Konto an, um Ihren privaten Wortschatz zu erstellen.",
  login_with_google: "Mit Google anmelden",
  loading_vocabulary: "Ihr Wortschatz wird geladen...",
  words_selected: "{count} Wörter ausgewählt",
  delete_selected_words: "Ausgewählte löschen",
  edit_word: "Wort bearbeiten",
  delete_word: "Wort löschen",
  modal_edit_word_title: "Wort bearbeiten",
  modal_add_word_title: "Neues Wort hinzufügen",
  modal_category_label: "Kategorie",
  modal_german_label: "Deutsch (mit Artikel & Plural) *",
  modal_german_placeholder: "z.B. der Apfel",
  modal_article_label: "Artikel *",
  modal_noun_label: "Substantiv (mit Plural) *",
  modal_noun_placeholder: "z.B. Mann, die Männer",
  modal_german_phrase_label: "Deutsche Phrase/Satz *",
  modal_german_phrase_placeholder: "z.B. Wie geht es Ihnen?",
  modal_hungarian_phrase_placeholder: "z.B. Hogy van?",
  modal_german_prep_label: "Deutsche Präposition *",
  modal_german_prep_placeholder: "z.B. mit",
  modal_hungarian_prep_placeholder: "z.B. val/vel",
  modal_german_ff_label: "Falscher Freund (Deutsch) *",
  modal_german_ff_placeholder: "z.B. das Gift, die Gifte",
  modal_hungarian_ff_placeholder: "z.B. a méreg",
  modal_hungarian_label: "Ungarisch *",
  modal_hungarian_placeholder: "z.B. alma",
  modal_example_label: "Beispiel / Kommentar",
  modal_example_placeholder: "z.B. Ich esse einen Apfel.",
  modal_save_changes: "Änderungen speichern",
  modal_save_word: "Wort speichern",
  alert_fill_fields_login: "Bitte füllen Sie mindestens die deutschen und ungarischen Felder aus.",
  alert_confirm_delete_word: "Sind Sie sicher, dass Sie dieses Wort löschen möchten?",
  alert_confirm_bulk_delete_words: "Sind Sie sicher, dass Sie {count} Wörter löschen möchten?",
  alert_login_failed: "Anmeldung mit Google fehlgeschlagen.",
  all_categories: "Alle Kategorien",

  // Quiz Page
  loading_questions: "Ihre Fragen werden geladen...",
  not_enough_words: "Nicht genügend Wörter",
  not_enough_words_desc: "Sie haben nicht genügend Wörter für ein {topic}-Quiz.",
  need_more_items: "Sie benötigen mindestens 4 Elemente für '{topic}'.",
  import_more_words: "Mehr Wörter importieren",
  quiz_complete: "Quiz abgeschlossen!",
  your_score: "Ihre Punktzahl:",
  back_to_quizzes: "Zurück zu den Quizzen",
  retry_quiz: "Quiz wiederholen",
  go_to_level: "Gehe zu Level {level}",
  next_question: "Nächste Frage",
  finish_quiz: "Quiz beenden",
  back_button: "← Zurück",
  next_quiz_button: "Nächstes Quiz →",
  example_label: "Beispiel",
  quiz_title_public: "{topic} Quiz {id}",
  quiz_title_custom: "Benutzerdefiniertes {topic} Quiz {id}",
  quiz_title_personal: "Privates Quiz",
  items_count: "{count} Elemente",
  quit_quiz_title: "Quiz beenden?",
  quit_quiz_desc: "Ihr Fortschritt wurde automatisch gespeichert.",
  quit: "Beenden",

  // Topic Quizzes
  topic_not_found: "Thema nicht gefunden",
  return_to_quizzes: "Zurück zu den Quizzen",
  select_level_to_start: "Wählen Sie ein Level aus.",
  level_id: "Level {id}",
  start_button: "Start →",
  continue_button: "Weiter →",
  personalized_quizzes: "Private Quizze",
  personalized_quizzes_desc: "Kein separates Konto erforderlich! Melden Sie sich an.",
  your_custom_quizzes: "Ihre benutzerdefinierten Quizze",
  custom_quizzes_count_desc: "Sie haben derzeit {count} Elemente gespeichert.",
  start_custom_quiz: "Benutzerdefiniertes Quiz starten",
  import_more_data: "Mehr Daten importieren",

  // Create Quiz
  create_custom_quiz_title: "Ein benutzerdefiniertes {topic}-Quiz erstellen",
  choose_data_source: "Wählen Sie Ihre Datenquelle.",
  use_personal_library: "Persönliche Bibliothek verwenden",
  use_personal_library_desc: "Erstellen Sie ein Quiz aus Ihren eigenen Wörtern.",
  upload_new_file: "Neue Datei hochladen",
  upload_new_file_desc: "Importieren Sie eine neue Datei für diesen Quiz-Typ.",
  required_format: "Erforderliches Format:",
  download_template: "Vorlage herunterladen",
  go_to_import_page: "Zur Importseite gehen →",
  instructions_articles: "Spalte A = Artikel, Spalte B = Substantiv, Spalte C = Ungarisch.",
  instructions_prepositions: "Spalte A = Präposition, Spalte B = Ungarisch.",
  instructions_vocabulary: "Spalte A = Deutsch, Spalte B = Ungarisch.",
  instructions_phrases: "Spalte A = Phrase, Spalte B = Ungarisch.",
  template_article_header: "Artikel (A)",
  template_noun_header: "Substantiv + Plural (B)",
  template_hungarian_header: "Ungarisch (C)",
  template_example_header: "Beispiel (D)",
  template_german_header: "Deutsch",
  template_german_mandatory_header: "Deutsch (Kötelező)",
  template_hungarian_mandatory_header: "Ungarisch (Kötelező)",
  template_example_optional_header: "Beispiel (Optional)",

  // Grammar & Statistics
  grammar_page_title: "Grammatik",
  grammar_page_subtitle: "Grammatikregeln und Erklärungen.",
  statistics_page_title: "Statistiken",
  statistics_page_subtitle: "Verfolgen Sie Ihren Lernfortschritt.",
  page_under_construction: "Diese Seite befindet sich im Aufbau.",
  check_back_later: "Bitte schauen Sie später wieder vorbei!",
  guest_warning_stats: "Melden Sie sich an, um den Fortschritt zu speichern ",
  guest_warning_stats_link: "hier",
  quizzes_solved: "Quizze gelöst",
  materials_read: "Materialien gelesen",
  no_quizzes_solved: "Sie haben noch keine Quizze abgeschlossen.",
  no_materials_read: "Sie haben noch keine Materialien gelesen.",
  review_button: "Überprüfen",
  download_button: "Herunterladen",
  redo_button: "Wiederholen",
  correct_answer: "Richtige Antwort",
  your_answer: "Ihre Antwort",
  csv_question: "Frage",
  csv_result: "Ergebnis",
  result: "Ergebnis",
  status_excellent: "Ausgezeichnet",
  status_good: "Gut",
  status_needs_practice: "Übung nötig",
  csv_correct: "Richtig",
  csv_incorrect: "Falsch",
  delete_selected_records: "Ausgewählte löschen",
  confirm_delete_record: "Möchten Sie dieses Ergebnis wirklich löschen?",
  confirm_bulk_delete_records: "Möchten Sie {count} Ergebnisse löschen?",
  records_selected: "{count} Ergebnisse ausgewählt",

  // Login Page
  login_page_title: "Anmelden",
  login_page_subtitle: "Melden Sie sich sicher mit Ihrem Google-Konto an.",

  // Results Page
  results_page_title: "Quiz-Ergebnisse",
  results_page_subtitle: "Überprüfen Sie Ihre Antworten.",
  review_answers: "Antworten überprüfen",
  retry_mistakes: "Fehler wiederholen",
  close: "Schließen",

  // Library & Learning Materials
  library: "Bibliothek",
  library_subtitle: "Greifen Sie auf Ihre Vokabeln zu.",
  learning_materials: "Lernmaterialien",
  learning_materials_subtitle: "Texte lesen, Audio hören.",
  read_materials: "Lesen",
  read_materials_desc: "Texte, Artikel und Geschichten lesen.",
  listen_materials: "Hören",
  listen_materials_desc: "Audiospuren und Podcasts hören.",
  save_to_reading: "Lesematerial",
  save_to_listening: "Hörmaterial",
  interesting_section: "Interessant",
  articles_section: "Artikel",
  books_section: "Bücher",
  music_section: "Musik",
  podcasts_section: "Podcasts",
  audiobooks_section: "Hörbücher",
  history: "Geschichte",
  history_desc: "Historische Ereignisse und Persönlichkeiten.",
  animals: "Tiere",
  animals_desc: "Tierwelt und Natur.",
  music: "Musik",
  music_desc: "Komponisten, Instrumente und Genres.",
  culture: "Kultur",
  culture_desc: "Kunst, Konzerte und Ausstellungen.",
  politics: "Politik",
  politics_desc: "Regierung und Gesellschaft.",
  science: "Wissenschaft",
  science_desc: "Entdeckungen und Forschung.",
  celebrities: "Prominente",
  celebrities_desc: "Berühmte Personen und Popkultur.",
  classic_literature: "Klassische Literatur",
  classic_literature_desc: "Lesen Sie die Meisterwerke.",
  short_stories: "Kurzgeschichten",
  short_stories_desc: "Kurze Texte für das tägliche Üben.",
  pop: "Pop",
  pop_desc: "Beliebte Musikhits.",
  rock: "Rock",
  rock_desc: "Rock und alternative Musik.",
  other_music: "Andere",
  other_music_desc: "Verschiedene andere Genres.",
  travel: "Reisen",
  travel_desc: "Geschichten und Tipps aus aller Welt.",
  psychology: "Psychologie",
  psychology_desc: "Geist, Verhalten und psychische Gesundheit.",
  other_podcasts: "Andere",
  other_podcasts_desc: "Verschiedene andere Podcast-Themen.",
  fiction: "Fiktion",
  fiction_desc: "Romane und Geschichten.",
  non_fiction: "Sachbücher",
  non_fiction_desc: "Faktisch und lehrreich.",
  other_audiobooks: "Andere",
  other_audiobooks_desc: "Verschiedene andere Hörbücher.",

  // Protected Route / Login Prompt
  protected_space_title: "Privater Bereich",
  protected_space_desc_1: "Melden Sie sich sicher mit Ihrem Google-Konto an.",
  protected_space_desc_2: "Melden Sie sich an, um fortzufahren!",
  continue_with_google: "Mit Google fortfahren",

  // Admin
  admin_mode: "Admin-Modus",
  admin_mode_desc: "Sie sind als Administrator angemeldet.",
  switch_to_normal_user: "Zu normalem Benutzer wechseln",
  switch_to_admin: "Zum Admin-Modus wechseln",
  admin_prompt_title: "Willkommen, Admin!",
  admin_prompt_desc: "Wählen Sie, wie Sie die Anwendung nutzen möchten.",
  admin_mode_dev: "Entwicklermodus",
  admin_mode_normal: "Normaler Benutzermodus",

  // False Friends
  false_friends: "Falsche Freunde",
  false_friends_desc: "Wörter, die ähnlich aussehen oder klingen.",
  false_friends_label: "Falsche Freunde:",
  format_false_friends: "Spalte A = Deutsch, Spalte B = Ungarisch.",
  false_friends_template: "Falsche Freunde Vorlage",
  template_note_header: "Notiz (D)",
  note: "Notiz / Bedeutung",
  admin_save_public: "Admin: In öffentlicher Bibliothek speichern",
  media_player: "Media-Player",
  play_content: "Inhalt abspielen",
  fetch_error_audio: "Audiodetails konnten nicht abgerufen werden. Bitte überprüfen Sie die URL oder fügen Sie sie manuell ein.",
  save_error_audio: "Fehler beim Speichern des Audios. Stellen Sie sicher, dass Sie angemeldet sind.",
  delete_error_audio: "Fehler beim Löschen des Audios.",
  confirm_delete_audio: "Sind Sie sicher, dass Sie dieses Audio löschen möchten?",
  add_audio: "Audio hinzufügen",
  audio_url: "Audio/Video-URL",
  fetch_audio: "Inhalt abrufen",
  audio_title: "Audiotitel",
  audio_content: "Audiobeschreibung / Inhalt",
  audio_source: "Künstler / Quelle",
  audio_source_placeholder: "z.B. Rammstein",
  save_audio: "Audio speichern",
  edit_audio: "Audio bearbeiten",
  delete_audio: "Audio löschen",
  audio_url_note: "Hinweis: YouTube- und Spotify-URLs generieren automatisch einen eingebetteten Player!",
  add_article: "Artikel hinzufügen",
  article_url: "Artikel URL",
  fetch_article: "Inhalt abrufen",
  article_title: "Artikel Titel",
  article_content: "Artikel Inhalt",
  article_source: "Quelle",
  article_source_placeholder: "z.B. Der Standard",
  save_article: "Artikel speichern",
  edit_article: "Artikel bearbeiten",
  delete_article: "Artikel löschen",
  confirm_delete_article: "Sind Sie sicher, dass Sie diesen Artikel löschen möchten?",
  add_book: "Buch hinzufügen",
  book_url: "Buch-URL",
  fetch_book: "Inhalt abrufen",
  book_title: "Buchtitel",
  book_content: "Buchinhalt",
  book_source: "Autor / Quelle",
  book_source_placeholder: "z.B. Goethe",
  save_book: "Buch speichern",
  edit_book: "Buch bearbeiten",
  delete_book: "Buch löschen",
  confirm_delete_book: "Sind Sie sicher, dass Sie dieses Buch löschen möchten?",
  bookmark_instructions: "Markieren Sie während des Lesens einen beliebigen Text, um ein Lesezeichen zu speichern.",
  bookmark_guest_warning: "Die Lesezeichen-Option ist nur für angemeldete Benutzer verfügbar. Melden Sie sich an, um Ihren Fortschritt zu speichern!",
  save_bookmark: "Lesezeichen",
  continue_from: "Weiterlesen ab:",
  no_audio_yet: "Noch keine Audioinhalte.",
  no_audio_yet_admin: "Noch keine Inhalte hier. Klicken Sie oben auf '+ Audio hinzufügen', um den ersten Titel hinzuzufügen!",
  private_reading_hint: "Erstellen Sie Ihre eigenen Lesekategorien, um Ihre Texte, Artikel oder Bücher zu organisieren.",
  private_listening_hint: "Erstellen Sie Kategorien wie Musikstil oder gruppieren Sie Ihre Lieblingslieder nach Künstlern oder Jahren.",
  edit_category: "Kategorie bearbeiten"
};
