export const en = {
  title: "German Exam Preparation",

  // Settings
  settings_title: "Settings",
  settings_subtitle: "Manage your account and application settings.",
  language_preferences: "Language Preferences",
  language_preferences_subtitle: "Select the application language.",
  app_language: "App Language",
  english: "English",
  german: "German",
  hungarian: "Hungarian",
  practice_settings: "Practice Settings",
  practice_settings_subtitle: "Customize your quiz experience.",
  show_example_sentences: "Show Example Sentences",
  show_example_sentences_subtitle: "Display example sentences after answering a question.",
  developer_tools: "Developer Tools",
  developer_tools_subtitle: "Use this button to completely reset your personal cloud data. (This does NOT delete the public guest library). Delete this from the code before deploying.",
  wiping_data: "Wiping Data...",
  hard_reset_database: "Hard Reset Database",
  hard_reset_warning: "⚠️ WARNING: Are you SURE you want to completely wipe ALL your personal imported vocabulary? (The public open library will NOT be affected). This cannot be undone!",
  hard_reset_success: "Database completely wiped! You have a fresh start.",

  // Quizzes
  quizzes_title: "Quizzes",
  quizzes_subtitle: "Choose a topic to practice.",
  test_your_knowledge: "Test your knowledge",
  test_your_knowledge_subtitle: "Practice with our public database.",
  vocabulary: "Vocabulary",
  vocabulary_quiz_subtitle: "Practice essential words.",
  articles_quiz: "Articles",
  articles_quiz_subtitle: "Practice der, die, das.",
  phrases_quiz: "Phrases and sentences",
  phrases_quiz_subtitle: "Useful everyday phrases and sentences.",
  prepositions_quiz: "Prepositions",
  prepositions_quiz_subtitle: "Practice prepositions and cases.",
  create_your_own_quizzes: "Custom Quizzes",
  create_your_own_quizzes_subtitle_loggedin: "Practice with your own imported words.",
  vocabulary_quiz: "Vocabulary Quiz",
  create_your_own_quizzes_subtitle_loggedout: "Log in to create custom quizzes.",
  login_to_create_quizzes: "Log in",
  question_of: "Question: {current} / {total}",
  choose_correct_one: "Choose the correct solution!",
  custom_vocab_desc: "Practice word translations from your personal library.",
  custom_articles_desc: "Practice 'der, die, das' with your own nouns.",
  custom_phrases_desc: "Test your knowledge of custom phrases and sentences.",
  custom_prepositions_desc: "Practice cases for prepositions you've imported.",

  // Navigation & Layout
  home: "Home",
  import: "Import",
  quizzes: "Quizzes",
  grammar: "Grammar",
  statistics: "Statistics",
  settings: "Settings",
  sign_out: "Sign Out",
  login: "Log in",
  vocabulary_short: "Vocab",

  // Home
  welcome_back: "Welcome, nice to see you here!",
  ready_to_learn: "Ready to improve your German? Create your own library, quizzes and learning materials, test your knowledge now!",
  import_data: "Import Data",
  upload_new_materials: "Upload new words and phrases.",
  login_required: "Login required",
  to_create_new_quizzes_login_required: "Login required to create custom quizzes",
  learn_new_words_from_library: "Browse the library or your own words.",
  for_extending_login_required: "Login required for a personal dictionary",
  coming_soon: "Coming soon",
  review_grammar_topics: "Grammar rules and explanations.",
  track_your_progress: "Track your progress over time.",

  // Import
  import_title: "Import Files",
  accepted_format_guide: "Accepted Format Guide",
  vocab_phrases: "Vocabulary / Phrases and sentences:",
  format_vocab_phrases: "Column A = German (Phrase/Sentence), Column B = Hungarian (Meaning), Column C = Example (Optional).",
  articles_quiz_label: "Articles Quiz:",
  format_articles: "Column A = Article, Column B = Noun, Column C = Hungarian, Column D = Example.",
  text_copy_paste: "Text / Copy-Paste:",
  format_text: "Separate German and Hungarian with a Tab, Semicolon (;), or Comma (,).",
  need_starting_point: "Need a starting point?",
  download_template_desc: "Download an Excel template to easily fill in your data.",
  vocab_template: "Vocabulary Template",
  articles_template: "Articles Template",
  drag_and_drop: "Drag & Drop or Click to browse",
  supported_files: "Supports Excel, Word, PDF, CSV, and TXT files",
  preview_filename: "Preview: {filename}",
  items_detected: "{count} items detected",
  article: "Article", noun: "Noun", example: "Example", column_a: "Column A", column_b: "Column B", column_c: "Column C", column_c_d: "Column C/D", column_d: "Column D",
  invalid_columns: "Could not detect valid columns.",
  invalid_columns_desc: "Make sure the file uses Tabs (Excel), Semicolons, or Commas to separate the words.",
  save_to: "Save to:",
  cancel: "Cancel",
  saving: "Saving...",
  save_import: "Save Import",
  manage_imported_files: "Manage Imported Files",
  manage_imported_files_desc: "Deleting a file will remove all words imported from it across your quizzes and vocabulary.",
  search_files: "Search files or keywords...",
  files_selected: "{count} files selected",
  download_selected: "Download Selected",
  delete_selected: "Delete Selected",
  file_name: "File Name",
  format: "Format",
  used_in: "Used In",
  items: "Items",
  action: "Action",
  download: "Download",
  delete: "Delete",
  confirm_delete_file: "Are you sure you want to delete \"{fileName}\"? This will permanently remove all {count} words associated with it.",
  error_delete_file_desc: "An error occurred while deleting the file items.",
  confirm_bulk_delete: "Are you sure you want to delete {count} files? All associated words will be removed.",
  error_bulk_delete_desc: "An error occurred while deleting the files.",
  no_items_export: "No items found to export.",
  no_items_save: "No valid vocabulary items to save or user not logged in.",
  import_success_with_duplicates: "Import complete! Saved {saved} new items. Skipped {duplicates} duplicates.",
  import_success: "Import complete! Saved {saved} new items.",
  error_saving_db: "An error occurred while saving to the database.",

  // Vocabulary Page
  vocab_title: "Vocabulary",
  vocab_subtitle: "Browse and manage your learned words.",
  add_word: "Add Word",
  open_library: "Open Library",
  personalized_space: "Personalized Space",
  search_vocabulary: "Search vocabulary...",
  words_found: "{count} words found",
  words_count: "{count} words",
  no_words_match_search: "No words match your search.",
  checking_account: "Checking account...",
  personalized_space_description: "Log in with your Google account to create your own vocabulary, collections, and quizzes, and to save your progress.",
  login_with_google: "Log in with Google",
  loading_vocabulary: "Loading your vocabulary...",
  words_selected: "{count} words selected",
  delete_selected_words: "Delete Selected",
  edit_word: "Edit word",
  delete_word: "Delete word",
  modal_edit_word_title: "Edit Word",
  modal_add_word_title: "Add New Word",
  modal_german_label: "German *",
  modal_german_placeholder: "e.g. der Apfel",
  modal_hungarian_label: "Hungarian *",
  modal_hungarian_placeholder: "e.g. alma",
  modal_example_label: "Example / Comment",
  modal_example_placeholder: "e.g. Ich esse einen Apfel.",
  modal_save_changes: "Save Changes",
  modal_save_word: "Save Word",
  alert_fill_fields_login: "Please fill in at least the German and Hungarian fields. Make sure you are logged in.",
  alert_confirm_delete_word: "Are you sure you want to delete this word?",
  alert_confirm_bulk_delete_words: "Are you sure you want to delete {count} selected words?",
  alert_login_failed: "Failed to log in with Google.",
  all_categories: "All Categories",

  // Quiz Page
  loading_questions: "Loading your questions...",
  not_enough_words: "Not Enough Words",
  not_enough_words_desc: "You don't have enough words in your personal library for a {topic} quiz.",
  need_more_items: "You need at least 4 items categorized as '{topic}'.",
  import_more_words: "Import More Words",
  quiz_complete: "Quiz Complete!",
  your_score: "Your score:",
  back_to_quizzes: "Back to Quizzes",
  retry_quiz: "Retry Quiz",
  go_to_level: "Go to Level {level}",
  next_question: "Next Question",
  finish_quiz: "Finish Quiz",
  back_button: "← Back",
  next_quiz_button: "Next Quiz →",
  example_label: "Example",
  quiz_title_public: "{topic} Quiz {id}",
  quiz_title_custom: "Custom {topic} Quiz {id}",
  quiz_title_personal: "Personal Quiz",
  items_count: "{count} items",
  quit_quiz_title: "Quit Quiz?",
  quit_quiz_desc: "Your progress has been saved automatically. You can continue later from where you left off.",
  quit: "Quit",

  // Topic Quizzes
  topic_not_found: "Topic not found",
  return_to_quizzes: "Return to Quizzes",
  select_level_to_start: "Select a level to start practicing.",
  level_id: "Level {id}",
  start_button: "Start →",
  continue_button: "Continue →",
  personalized_quizzes: "Personalized Quizzes",
  personalized_quizzes_desc: "Log in with your Google account to create your own vocabulary, collections, and quizzes, and to save your progress.",
  your_custom_quizzes: "Your Custom Quizzes",
  custom_quizzes_count_desc: "You currently have {count} items saved for this topic.",
  start_custom_quiz: "Start Custom Quiz",
  import_more_data: "Import More Data",

  // Create Quiz
  create_custom_quiz_title: "Create a Custom {topic} Quiz",
  choose_data_source: "Choose your data source to begin.",
  use_personal_library: "Use Personal Library",
  use_personal_library_desc: "Generate a quiz from words you've already imported and categorized as '{topic}'.",
  upload_new_file: "Upload a New File",
  upload_new_file_desc: "Import a new file specifically for this quiz type.",
  required_format: "Required Format:",
  download_template: "Download Template",
  go_to_import_page: "Go to Import Page →",
  instructions_articles: "Column A should be the article ('der', 'die', 'das'). Column B should be the noun. Column C is the Hungarian meaning. Column D is optional for example sentences.",
  instructions_prepositions: "Column A should be the German preposition, Column B the Hungarian meaning. These are mandatory. Column C is optional for examples.",
  instructions_vocabulary: "Column A should be the German Word (you can add with plural, in the same column, e.g., 'das Haus, die Häuser'). Column B is the Hungarian meaning. These are mandatory fields. Column C is optional for example sentences.",
  instructions_phrases: "Column A should be the German sentence or phrase. Column B is the Hungarian meaning. These are mandatory fields. Column C is optional for example sentences.",
  template_article_header: "Article (A)",
  template_noun_header: "Noun (B)",
  template_hungarian_header: "Hungarian (C)",
  template_example_header: "Example (D)",
  template_german_header: "German",
  template_german_mandatory_header: "German (Mandatory, incl. article/plural)",
  template_hungarian_mandatory_header: "Hungarian (Mandatory)",
  template_example_optional_header: "Example (Optional)",

  // Grammar & Statistics
  grammar_page_title: "Grammar",
  grammar_page_subtitle: "Review grammar rules and explanations.",
  statistics_page_title: "Statistics",
  statistics_page_subtitle: "Track your learning progress over time.",
  page_under_construction: "This page is currently under construction.",
  check_back_later: "Please check back later!",
  guest_warning_stats: "As a guest user, your results will appear here until you close the website/app. If you want to keep your progress saved, log in ",
  guest_warning_stats_link: "here",
  quizzes_solved: "Quizzes Solved",
  materials_read: "Materials Read",
  no_quizzes_solved: "You haven't completed any quizzes yet.",
  no_materials_read: "You haven't read any materials yet.",
  review_button: "Review",
  download_button: "Download",
  redo_button: "Redo",
  correct_answer: "Correct Answer",
  your_answer: "Your Answer",
  csv_question: "Question",
  csv_result: "Result",
  csv_correct: "Correct",
  csv_incorrect: "Incorrect",
  delete_selected_records: "Delete Selected",
  confirm_delete_record: "Are you sure you want to delete this record?",
  confirm_bulk_delete_records: "Are you sure you want to delete {count} selected records?",
  records_selected: "{count} records selected",

  // Login Page
  login_page_title: "Log In",
  login_page_subtitle: "Log in to access your personalized vocabulary and track your progress.",

  // Results Page
  results_page_title: "Quiz Results",
  results_page_subtitle: "Review your answers from the last session.",
  review_answers: "Review Answers",
  retry_mistakes: "Retry Mistakes",
  close: "Close",

  // Library & Learning Materials
  library: "Library",
  library_subtitle: "Access your vocabulary and learning resources.",
  learning_materials: "Learning Materials",
  learning_materials_subtitle: "Read texts, listen to audio, and more.",
  read_materials: "Reading",
  read_materials_desc: "Read texts, articles, and stories.",
  listen_materials: "Listening",
  listen_materials_desc: "Listen to audio tracks and podcasts.",
  save_to_reading: "Reading Material",
  save_to_listening: "Listening Material",

  // Protected Route / Login Prompt
  protected_space_title: "Personalized space",
  protected_space_desc_1: "Log in with your Google account to create your own vocabulary, collections, and quizzes, and to save your progress.",
  protected_space_desc_2: "Log in to continue!",
  continue_with_google: "Continue with Google",

  // Admin
  admin_mode: "Admin Mode",
  admin_mode_desc: "You are logged in as an administrator. You can add materials to the public library.",
  switch_to_normal_user: "Switch to Normal User",
  switch_to_admin: "Switch to Admin Mode",
  admin_prompt_title: "Welcome, Admin!",
  admin_prompt_desc: "Choose how you want to use the application for this session.",
  admin_mode_dev: "Developer Mode (Edit Public Library)",
  admin_mode_normal: "Normal User Mode (Private Only)",

  // False Friends
  false_friends: "False Friends",
  false_friends_desc: "Words that look or sound similar and sometimes even mean the same both in German and Hungarian. Easy to remember these!",
  false_friends_label: "False Friends:",
  format_false_friends: "Column A = German, Column B = Hungarian, Column C = Example, Column D = Note/Meaning.",
  false_friends_template: "False Friends Template",
  template_note_header: "Note (D)",
  note: "Note",
  admin_save_public: "Admin: Save to Public Library"
};