export const en = {
  title: "German Exam Preparation",

  // Settings
  settings_title: "Settings",
  settings_subtitle: "Manage your account and application settings.",
  language_preferences: "Language Preferences",
  language_preferences_subtitle: "Select the application language.",
  app_language: "App Language",
  english: "English",
  german: "German",
  hungarian: "Hungarian",
  practice_settings: "Practice Settings",
  practice_settings_subtitle: "Customize your quiz experience.",
  show_example_sentences: "Show Example Sentences",
  show_example_sentences_subtitle: "Display example sentences after answering a question.",
  save_preferences: "Save Preferences",
  saving_preferences: "Saving...",
  save_button: "Save",
  data_management: "Data Management",
  data_management_subtitle: "Manage your saved progress and local data.",
  clear_local_data: "Clear Local Progress",
  confirm_clear_data: "Are you sure you want to clear all local progress? This cannot be undone.",
  data_cleared: "Local progress cleared successfully.",
  confirm_reset_library: "Are you sure you want to delete all personal library items? This cannot be undone.",
  library_wiped: "Personal library wiped successfully.",
  wipe_error: "Failed to wipe personal library. Please try again.",
  saved: "Saved!",
  developer_tools: "Developer Tools",
  developer_tools_subtitle: "Use this button to completely reset your personal cloud data. (This does NOT delete the public guest library). Delete this from the code before deploying.",
  wiping_data: "Wiping Data...",
  hard_reset_database: "Hard Reset Database",
  hard_reset_warning: "⚠️ WARNING: Are you SURE you want to completely wipe ALL your personal imported vocabulary? (The public open library will NOT be affected). This cannot be undone!",
  hard_reset_success: "Database completely wiped! You have a fresh start.",
  reset_personal_library: "Reset Personal Library",
  reset_personal_library_desc: "Permanently delete all your custom imported words and grammar materials from the cloud. This cannot be undone.",
  clear_local_data_desc: "Wipe local quiz scores and progress. Does not delete cloud vocabulary.",

  // Quizzes
  quizzes_title: "Quizzes",
  quizzes_subtitle: "Choose a topic to practice.",
  test_your_knowledge: "Test your knowledge",
  test_your_knowledge_subtitle: "Practice with our public database.",
  vocabulary: "Vocabulary",
  vocabulary_quiz_subtitle: "Practice essential words.",
  articles_quiz: "Articles",
  articles_quiz_subtitle: "Practice der, die, das.",
  phrases_quiz: "Phrases and sentences",
  phrases_quiz_subtitle: "Useful everyday phrases and sentences.",
  phrases_sentences_quiz: "Phrases and sentences",
  prepositions_quiz: "Prepositions",
  prepositions_quiz_subtitle: "Practice prepositions and cases.",
  verbs_quiz: "Verbs",
  verbs_quiz_subtitle: "Practice German verbs and past forms.",
  create_your_own_quizzes: "Custom Quizzes",
  create_your_own_quizzes_subtitle_loggedin: "Practice with your own imported words.",
  vocabulary_quiz: "Vocabulary",
  create_your_own_quizzes_subtitle_loggedout: "Log in to create custom quizzes.",
  login_to_create_quizzes: "Log in",
  question_of: "Question: {current} / {total}",
  choose_correct_one: "Choose the correct solution!",
  custom_vocab_desc: "Practice word translations from your personal library.",
  custom_articles_desc: "Practice 'der, die, das' with your own nouns.",
  custom_phrases_desc: "Test your knowledge of custom phrases and sentences.",
  custom_prepositions_desc: "Practice cases for prepositions you've imported.",
  custom_verbs_desc: "Your personal verbs.",

  // Navigation & Layout
  home: "Home",
  import: "Import",
  quizzes: "Quizzes",
  grammar: "Grammar",
  statistics: "Statistics",
  settings: "Settings",
  sign_out: "Sign Out",
  login: "Log in",
  vocabulary_short: "Vocab",
  support_micalingo: "Support MicaLingo",
  support_desc: "Choose an amount to support our project. Every contribution helps!",
  support_tier_1: "Coffee Tier",
  support_tier_2: "Snack Tier",
  support_tier_3: "Lunch Tier",
  support_tier_4: "Hero Tier 🚀",
  enjoying_micalingo_title: "Enjoying MicaLingo?",
  consider_donation_desc: "Please consider supporting the project to keep it running and ad-free.",
  yes_support: "Yes, show me how!",
  maybe_later: "Maybe later",

  // Home
  welcome_back: "Welcome, nice to see you here!",
  ready_to_learn: "Ready to improve your German? Create your own library, quizzes and learning materials, test your knowledge now!",
  import_data: "Import and manage data",
  upload_new_materials: "Upload new words and phrases.",
  login_required: "Login required",
  to_create_new_quizzes_login_required: "Login required to create custom quizzes",
  learn_new_words_from_library: "Browse the library or your own words.",
  login_to_create_quizzes_desc: "If you wish to create your own vocabulary and quizzes, please log in!",
  for_extending_login_required: "Login required for a personal dictionary",
  coming_soon: "Coming soon",
  review_grammar_topics: "Grammar rules and explanations.",
  track_your_progress: "Track your progress over time.",
  download_android: "Get the Android App",
  download_android_desc: "Take your MicaLingo on the go. Download directly to your phone.",
  download_apk: "Download",
  android_install_note: "Note: Since this app is downloaded directly, your phone may show a security warning. Click 'More details' then 'Install anyway' to proceed.",

  // Import
  import_title: "Import Files",
  accepted_format_guide: "Accepted Format Guide",
  vocab_phrases: "Vocabulary (Read or Quiz) / Phrases Quiz:",
  format_vocab_phrases: "Column A = German (Phrase/Sentence), Column B = Hungarian (Meaning), Column C = Example (Optional).",
  verbs_quiz_format_title: "Verbs Quiz:",
  verbs_quiz_format_desc: "Column A = German (verb), Column B = Hungarian (Meaning), Column C = Past forms or Examples.",
  prepositions_quiz_format_title: "Prepositions Quiz:",
  prepositions_quiz_format_desc: "Column A: German verb + Hungarian meaning, Column B: preposition + case, Column C: Example sentence.",
  articles_quiz_label: "Articles Quiz:",
  format_articles: "Column A = Article, Column B = Noun, Column C = Hungarian, Column D = Example.",
  need_starting_point: "Need a starting point?",
  download_template_desc: "Download an Excel template to easily fill in your data.",
  vocab_template: "Vocabulary reading/quiz template",
  articles_template: "Articles quiz template",
  verbs_template: "Verbsquiz template",
  prepositions_template: "Prepositions quiz template",
  template_german_verb_header: "German Verb + Hungarian",
  template_prep_case_header: "Preposition + Case",
  template_meaning_example_header: "Example Sentence",
  drag_and_drop: "Drag & Drop or Click to browse",
  supported_files: "Supports Excel, Word, PDF, CSV, and TXT files",
  preview_filename: "Preview: {filename}",
  items_detected: "{count} items detected",
  article: "Article", noun: "Noun + Plural", example: "Example", column_a: "Column A", column_b: "Column B", column_c: "Column C", column_c_d: "Column C/D", column_d: "Column D",
  invalid_columns: "Could not detect valid columns.",
  invalid_columns_desc: "Make sure the file uses Tabs (Excel), Semicolons, or Commas to separate the words.",
  save_to: "Save to:",
  cancel: "Cancel",
  saving: "Saving...",
  save_import: "Save Import",
  manage_imported_files: "Manage Imported Files",
  manage_imported_files_desc: "Deleting a file will remove all words imported from it across your quizzes and vocabulary.",
  search_files: "Search files or keywords...",
  files_selected: "{count} files selected",
  download_selected: "Download Selected",
  delete_selected: "Delete Selected",
  file_name: "File Name",
  format: "Format",
  used_in: "Used In",
  items: "Items",
  action: "Action",
  download: "Download",
  delete: "Delete",
  hint: "Hint / Past Form",
  confirm_delete_file: "Are you sure you want to delete \"{fileName}\"? This will permanently remove all {count} words associated with it.",
  error_delete_file_desc: "An error occurred while deleting the file items.",
  confirm_bulk_delete: "Are you sure you want to delete {count} files? All associated words will be removed.",
  error_bulk_delete_desc: "An error occurred while deleting the files.",
  no_items_export: "No items found to export.",
  no_items_save: "No valid vocabulary items to save or user not logged in.",
  import_success_with_duplicates: "Import complete! Saved {saved} new items. Skipped {duplicates} duplicates.",
  import_success: "Import complete! Saved {saved} new items.",
  import_overwritten: "Overwrote {count} existing items.",
  import_skipped: "Skipped {count} duplicate items.",
  overwrite_confirm_title: "Overwrite Duplicates?",
  overwrite_confirm_desc: "Found {count} items that already exist. Do you want to overwrite them with the data from your file?",
  overwrite_button: "Overwrite",
  skip_button: "Skip Duplicates",
  error_saving_db: "An error occurred while saving to the database.",

  // Vocabulary Page
  vocab_title: "Vocabulary",
  vocab_subtitle: "Browse and manage your learned words.",
  add_word: "Add Word",
  open_library: "Open Library",
  personalized_space: "Private Space",
  marked_words: "Marked words",
  marked_words_subtitle: "Practice words you starred after a wrong answer.",
  marked_words_description: "When you miss a quiz question, tap the star to save that word here. Practice them as a mixed quiz, or remove words one by one.",
  marked_words_empty: "No marked words yet",
  marked_words_empty_desc: "Miss a question in any quiz, then tap the star in the top-right corner to save it here.",
  marked_words_practice: "Practice marked words",
  marked_words_manage: "Manage library",
  marked_words_manage_desc: "Remove words one by one from your marked list only. Public library quizzes are never changed.",
  mark_word: "Mark word",
  unmark_word: "Remove mark",
  word_marked: "Word marked",
  quiz_title_marked: "Marked words quiz {id}",
  personalized_space_empty: "Your Private Space is Empty",
  search_vocabulary: "Search vocabulary...",
  words_found: "{count} words found",
  words_count: "{count} words",
  no_words_match_search: "No words match your search.",
  checking_account: "Checking account...",
  personalized_space_description: "No separate account is needed! Just log in securely with your Google account to create your own private vocabulary, collections, and quizzes, and to save your progress.",
  login_with_google: "Log in with Google",
  loading_vocabulary: "Loading your vocabulary...",
  words_selected: "{count} words selected",
  delete_selected_words: "Delete Selected",
  edit_word: "Edit",
  delete_word: "Delete word",
  modal_edit_word_title: "Edit Word",
  modal_add_word_title: "Add New Word",
  modal_category_label: "Category",
  modal_german_label: "German (with article & plural) *",
  modal_german_placeholder: "e.g. der Apfel",
  modal_article_label: "Article *",
  modal_noun_label: "Noun (with plural) *",
  modal_noun_placeholder: "e.g. Mann, die Männer",
  modal_german_phrase_label: "German Phrase/Sentence *",
  modal_german_phrase_placeholder: "e.g. Wie geht es Ihnen?",
  modal_hungarian_phrase_placeholder: "e.g. Hogy van?",
  modal_german_prep_label: "German Preposition *",
  modal_german_prep_placeholder: "e.g. mit",
  modal_hungarian_prep_placeholder: "e.g. val/vel",
  prep_case_label: "Preposition + Case *",
  modal_prep_case_placeholder: "e.g. auf + Akk.",
  meaning_example_label: "Example Sentence",
  meaning_example_placeholder: "e.g. Ich verzichte auf das Angebot.",
  modal_german_prep_verb_label: "German Verb + Hungarian *",
  modal_german_prep_verb_placeholder: "e.g. verzichten, lemondani valamiről/felhagyni valamivel",
  modal_german_verb_label: "German Verb *",
  modal_german_verb_placeholder: "e.g. machen",
  modal_hungarian_verb_placeholder: "e.g. csinálni",
  modal_german_ff_label: "German False Friend *",
  modal_german_ff_placeholder: "e.g. das Gift, die Gifte",
  modal_hungarian_ff_placeholder: "e.g. a méreg",
  modal_hungarian_label: "Hungarian *",
  modal_hungarian_placeholder: "e.g. alma",
  modal_example_label: "Example / Comment",
  modal_example_placeholder: "e.g. Ich esse einen Apfel.",
  modal_save_changes: "Save Changes",
  modal_save_word: "Save Word",
  alert_fill_fields_login: "Please fill in at least the German and Hungarian fields. Make sure you are logged in.",
  alert_confirm_delete_word: "Are you sure you want to delete this word?",
  alert_confirm_bulk_delete_words: "Are you sure you want to delete {count} selected words?",
  alert_login_failed: "Failed to log in with Google.",
  alert_word_exists: "This word already exists in your '{category}'!",
  duplicates_found_title: "Duplicates Found",
  duplicates_found_subtitle: "These items already exist in the target location and were not moved.",
  all_categories: "All Categories",

  // Dropdown Categories
  dropdown_vocabulary: "Vocabulary Quiz",
  dropdown_reading: "Vocabulary (to read)",
  vocab_reading_subtitle: "Words uploaded for reading only — separate from quiz libraries.",
  copy_to_quiz: "Also add to quiz...",
  copy_to_quiz_hint: "Creates a separate quiz copy. The word stays in Vocabulary (to read).",
  category_separation_hint: "Reading and quiz libraries are separate — the same word can exist in both.",
  dropdown_articles: "Articles Quiz",
  dropdown_phrases: "Phrases and Sentences Quiz",
  dropdown_prepositions: "Prepositions Quiz",
  dropdown_adjectives: "Adjectives Quiz",
  dropdown_verbs: "Verbs Quiz",
  dropdown_false_friends: "False Friends",

  // Quiz Page
  loading_questions: "Loading your questions...",
  not_enough_words: "Not Enough Words",
  not_enough_words_desc: "You don't have enough words in your personal library for a {topic} quiz.",
  need_more_items: "You need at least 4 items categorized as '{topic}'.",
  import_more_words: "Import More Words",
  quiz_complete: "Quiz Complete!",
  no_more_quizzes: "You have completed all available quizzes for this topic!",
  great_job: "Great job with your progress!",
  your_score: "Your score:",
  back_to_quizzes: "Back to Quizzes",
  retry_quiz: "Retry Quiz",
  go_to_level: "Go to Level {level}",
  next_question: "Next Question",
  finish_quiz: "Finish Quiz",
  back_button: "← Back",
  next_quiz_button: "Next Quiz →",
  example_label: "Example",
  quiz_title_public: "{topic} Quiz {id}",
  quiz_title_custom: "Custom {topic} Quiz {id}",
  quiz_title_personal: "Private Quiz",
  items_count: "{count} items",
  quit_quiz_title: "Quit Quiz?",
  quit_quiz_desc: "Your progress has been saved automatically. You can continue later from where you left off.",
  quit: "Quit",

  // Topic Quizzes
  topic_not_found: "Topic not found",
  return_to_quizzes: "Return to Quizzes",
  select_level_to_start: "Select a level to start practicing.",
  level_id: "Level {id}",
  start_button: "Start →",
  continue_button: "Continue →",
  personalized_quizzes: "Private Quizzes",
  personalized_quizzes_desc: "No separate account is needed! Just log in securely with your Google account to create your own private vocabulary, collections, and quizzes, and to save your progress.",
  your_custom_quizzes: "Your Custom Quizzes",
  custom_quizzes_count_desc: "You currently have {count} items saved for this topic.",
  start_custom_quiz: "Start Custom Quiz",
  import_more_data: "Import More Data",

  // Create Quiz
  create_custom_quiz_title: "Create a Custom {topic} Quiz",
  choose_data_source: "Choose your data source to begin.",
  use_personal_library: "Use Personal Library",
  use_personal_library_desc: "Generate a quiz from words you've already imported and categorized as '{topic}'.",
  upload_new_file: "Upload a New File",
  upload_new_file_desc: "Import a new file specifically for this quiz type.",
  required_format: "Required Format:",
  download_template: "Download Template",
  go_to_import_page: "Go to Import Page →",
  instructions_articles: "Column A = article ('der', 'die', 'das') — the quiz answer. Column B = noun; column C = Hungarian meaning — shown together as the question (e.g. Mann (a férfi)). Column D = optional example sentence shown as a hint when examples are enabled.",
  instructions_prepositions: "Column A should be the German preposition, Column B the Hungarian meaning. These are mandatory. Column C is optional for examples.",
  instructions_vocabulary: "Column A should be the German Word (you can add with plural, in the same column, e.g., 'das Haus, die Häuser'). Column B is the Hungarian meaning. These are mandatory fields. Column C is optional for example sentences.",
  instructions_phrases: "Column A should be the German sentence or phrase. Column B is the Hungarian meaning. These are mandatory fields. Column C is optional for example sentences.",
  template_article_header: "Article (A)",
  template_noun_header: "Noun + Plural (B)",
  template_hungarian_header: "Hungarian (C)",
  template_example_header: "Example (D)",
  template_german_header: "German",
  template_german_mandatory_header: "German (Mandatory, incl. article/plural)",
  template_hungarian_mandatory_header: "Hungarian (Mandatory)",
  template_example_optional_header: "Example (Optional)",

  // Grammar & Statistics
  grammar_page_title: "Grammar",
  grammar_page_subtitle: "Review grammar rules and explanations.",
  grammar_cases: "Cases (Fälle)",
  grammar_tenses: "Tenses (Zeitformen)",
  grammar_articles: "Articles & Genders",
  grammar_adjectives: "Adjective Declension",
  grammar_prepositions: "Prepositions",
  grammar_sentence_structure: "Sentence Structure",
  add_grammar_rule: "Add Grammar Rule",
  edit_grammar_rule: "Edit Grammar Rule",
  delete_grammar_rule: "Delete Grammar Rule",
  grammar_rule_title: "Rule Title",
  grammar_rule_content: "Grammar Explanation",
  fetch_content: "Fetch Content",
  fetch_error: "Failed to fetch content. Please check the URL or paste manually.",
  bullet_list: "• Bullet List",
  undo_button: "↩ Undo",
  no_items: "No items yet.",
  confirm_delete_grammar: "Are you sure you want to delete this grammar rule?",
  statistics_page_title: "Statistics",
  statistics_page_subtitle: "Track your learning progress over time.",
  page_under_construction: "This page is currently under construction.",
  check_back_later: "Please check back later!",
  guest_warning_stats: "As a guest user, your results will appear here until you close the website/app. If you want to keep your progress saved, log in ",
  guest_warning_stats_link: "here!",
  quizzes_solved: "Quizzes Solved",
  materials_read: "Materials Read",
  no_quizzes_solved: "You haven't completed any quizzes yet.",
  no_materials_read: "You haven't read any materials yet.",
  select_all: "Select all",
  stats_quiz: "Quiz",
  stats_score: "Score",
  stats_actions: "Actions",
  admin_target: "Admin target",
  public_library_target: "Public library",
  personal_library_target: "Personal library",
  review_button: "Review",
  download_button: "Download",
  redo_button: "Redo",
  correct_answer: "Correct Answer",
  your_answer: "Your Answer",
  csv_question: "Question",
  csv_result: "Result",
  result: "Result",
  status_excellent: "Excellent",
  status_good: "Good",
  status_needs_practice: "Needs Practice",
  csv_correct: "Correct",
  csv_incorrect: "Incorrect",
  delete_selected_records: "Delete Selected",
  confirm_delete_record: "Are you sure you want to delete this record?",
  confirm_bulk_delete_records: "Are you sure you want to delete {count} selected records?",
  records_selected: "{count} records selected",

  // Login Page
  login_page_title: "Log In",
  login_page_subtitle: "No separate account is needed! Just log in securely with your Google account to access your private vocabulary and track your progress.",

  // Results Page
  results_page_title: "Quiz Results",
  results_page_subtitle: "Review your answers from the last session.",
  review_answers: "Review Answers",
  retry_mistakes: "Retry Mistakes",
  close: "Close",
  expand_table: "Expand table",
  table_preview: "Table preview",

  // Library & Learning Materials
  library: "Library",
  library_subtitle: "Access your vocabulary and learning resources.",
  learning_materials: "Resources",
  learning_materials_subtitle: "Read texts, listen to audio, and more.",
  read_materials: "Reading",
  read_materials_desc: "Read texts, articles, and stories.",
  listen_materials: "Listening",
  listen_materials_desc: "Listen to audio tracks and podcasts.",
  save_to_reading: "Reading Material",
  save_to_listening: "Listening Material",
  interesting_section: "Interesting",
  articles_section: "Articles",
  books_section: "Books",
  music_section: "Music",
  podcasts_section: "Podcasts",
  audiobooks_section: "Audiobooks",
  history: "History",
  history_desc: "Historical events and figures.",
  animals: "Animals",
  animals_desc: "Wildlife and nature.",
  music: "Music",
  music_desc: "Composers, instruments, and genres.",
  culture: "Culture",
  culture_desc: "Art, concerts, and exhibitions.",
  politics: "Politics",
  politics_desc: "Government and society.",
  science: "Science",
  science_desc: "Discoveries and research.",
  celebrities: "Celebrities",
  celebrities_desc: "Famous people and pop culture.",
  classic_literature: "Classic Literature",
  classic_literature_desc: "Read the masterpieces.",
  short_stories: "Short Stories",
  short_stories_desc: "Quick reads for daily practice.",
  pop: "Pop",
  pop_desc: "Popular music hits.",
  rock: "Rock",
  rock_desc: "Rock and alternative music.",
  other_music: "Other",
  other_music_desc: "Various other genres.",
  travel: "Travel",
  travel_desc: "Stories and tips from around the world.",
  psychology: "Psychology",
  psychology_desc: "Mind, behavior, and mental health.",
  other_podcasts: "Other",
  other_podcasts_desc: "Various other podcast topics.",
  fiction: "Fiction",
  fiction_desc: "Novels and stories.",
  non_fiction: "Non-Fiction",
  non_fiction_desc: "Factual and educational.",
  other_audiobooks: "Other",
  other_audiobooks_desc: "Various other audiobooks.",

  // Protected Route / Login Prompt
  protected_space_title: "Private Space",
  protected_space_desc_1: "No separate account is needed! Just log in securely with your Google account to access your private vocabulary, exercises, and progress.",
  protected_space_desc_2: "Log in to continue!",
  continue_with_google: "Continue with Google",

  // Admin
  admin_mode: "Admin Mode",
  admin_mode_desc: "You are logged in as an administrator. You can add materials to the public library.",
  switch_to_normal_user: "Switch to Normal User",
  switch_to_admin: "Switch to Admin Mode",
  admin_prompt_title: "Welcome, Admin!",
  admin_prompt_desc: "Choose how you want to use the application for this session.",
  admin_mode_dev: "Developer Mode (Edit Public Library)",
  admin_mode_normal: "Normal User Mode (Private Only)",

  // False Friends
  false_friends: "False Friends",
  false_friends_desc: "Words that look or sound similar and sometimes even mean the same both in German and Hungarian. Easy to remember these!",
  false_friends_template: "False Friends Template (read)",
  template_note_header: "Note (D)",
  note: "Note / Meaning",
  admin_save_public: "Admin: Save to Public Library",
  media_player: "Media Player",
  play_content: "Play Content",
  fetch_error_audio: "Failed to fetch audio details. Please check the URL or paste manually.",
  save_error_audio: "Failed to save audio. Make sure you are logged in.",
  delete_error_audio: "Failed to delete audio.",
  confirm_delete_audio: "Are you sure you want to delete this audio?",
  add_audio: "Add Audio",
  audio_url: "Audio/Video URL",
  fetch_audio: "Fetch Content",
  audio_title: "Audio Title",
  audio_content: "Audio Description / Content",
  audio_source: "Artist / Source",
  audio_source_placeholder: "e.g. Rammstein",
  save_audio: "Save Audio",
  edit_audio: "Edit Audio",
  delete_audio: "Delete Audio",
  audio_url_note: "Note: YouTube and Spotify URLs will automatically generate an embedded player!",
  add_article: "Add Article",
  article_url: "Article URL",
  fetch_article: "Fetch Content",
  article_title: "Article Title",
  article_content: "Article Content",
  article_source: "Source",
  article_source_placeholder: "e.g. Der Standard",
  save_article: "Save Article",
  edit_article: "Edit Article",
  delete_article: "Delete Article",
  confirm_delete_article: "Are you sure you want to delete this article?",
  add_book: "Add Book",
  book_url: "Book URL",
  fetch_book: "Fetch Content",
  book_title: "Book Title",
  book_content: "Book Content",
  book_source: "Author / Source",
  book_source_placeholder: "e.g. Goethe",
  save_book: "Save Book",
  edit_book: "Edit Book",
  delete_book: "Delete Book",
  confirm_delete_book: "Are you sure you want to delete this book?",
  bookmark_instructions_logged_in: "Highlight any text while reading to save a bookmark, or save the highlighted text directly to your personal vocabulary database or into your quizzes!",
  bookmark_instructions_guest: "Highlight any text while reading to save a bookmark, or save the highlighted text directly to your personal vocabulary database or into your quizzes! (This feature is exclusively available for logged-in users. Log in to use it!)",
  save_bookmark: "Bookmark",
  continue_from: "Continue from:",
  no_audio_yet: "No audio content yet.",
  no_audio_yet_admin: "No content here yet. Click '+ Add Audio' above to add the first track!",
  private_reading_hint: "Create your own reading categories to organize your texts, articles, or books.",
  private_listening_hint: "Create categories like music style or group your favorite songs by artists. Save audiobooks or your favourite podcasts.",
  private_grammar_hint: "Create your own grammar categories to organize your notes.",
  private_category_1: "Category 1",
  private_category_2: "Category 2",
  private_category_3: "Category 3",
  private_category_4: "Category 4",
  private_category_5: "Category 5",
  edit_category: "Edit Category",
  adjectives_quiz: 'Adjectives',
  adjectives_quiz_subtitle: 'Practice German adjectives.',
  custom_adjectives_desc: 'Your personal adjectives.',
  template_adjective_header: 'Adjective (mandatory)',
  template_levels_header: 'Levels (e.g., besser, am besten)',
  adjectives_quiz_label: 'Adjectives Quiz:',
  format_adjectives: 'Column A: German, Column B: Hungarian, Column C: Levels (e.g., besser, am besten) or Example sentence.',
  adjectives_template: 'Adjectives quiz template',
  adjective: 'Adjective',
  levels: 'Levels',
  url_optional: "URL (Optional)",
  title_label: "Title",
  source_author: "Source / Author",
  source_artist: "Source / Artist",
  content_label: "Content",
  fetch_note: "Note: Fetching works via a proxy. Complex sites might block extraction. You can always paste content manually.",
  no_items_left: "No items left. Save to delete all.",
  original_source: "Original source",
  add_interesting: "Add Interesting Content",
  edit_interesting: "Edit Interesting Content",
  delete_interesting: "Delete Content",
  confirm_delete_interesting: "Are you sure you want to delete this content?",
  interesting_url: "Content URL",
  fetch_interesting: "Fetch Content",
  interesting_title: "Title",
  interesting_source: "Source",
  interesting_source_placeholder: "e.g. Wikipedia",
  interesting_content: "Content",
  save_interesting: "Save Content",
  fun_facts: "Fun Facts",
  fun_facts_desc: "Interesting facts and trivia.",
  idioms: "Idioms",
  idioms_desc: "Common sayings and idioms.",
  save_to_vocabulary: "Save Word",
  add_content: "Add Content",
  add_image: "Add Image",
  explanation_label: "Explanation",
  explanation_placeholder: "Explanation",
  add_idiom: "Add Idiom",
  edit_idiom: "Edit Idiom",
  idiom_german_label: "German Idiom *",
  idiom_german_placeholder: "e.g. Ich verstehe nur Bahnhof",
  idiom_hungarian_label: "Hungarian Meaning *",
  idiom_hungarian_placeholder: "e.g. Nekem ez kínai",
  idiom_note_label: "Note (Explanation)",
  idiom_note_placeholder: "Literal meaning...",
  save_content: "Save Content",
  confirm_delete_idiom: "Are you sure you want to delete this idiom?",
  confirm_delete_ff: "Are you sure you want to delete this false friend?",
  ff_note_placeholder: "e.g. False friend: gift != ajándék",
  alert_fill_fields_admin: "Please fill in at least the German and Hungarian fields.",
  confirm_exit_app: "Are you sure you want to exit the app?",

  // Footer & legal pages
  footer_privacy: "Privacy Policy",
  footer_terms: "Terms of Service",
  footer_about: "About & Contact",
  footer_rights: "All rights reserved.",
  last_updated: "Last updated: July 29, 2026",

  privacy_title: "Privacy Policy",
  privacy_intro: "This Privacy Policy explains how MicaLingo (\"we\", \"us\", or \"our\") processes personal data when you use our website at micalingo.com and our mobile application (together, the \"Service\"). We process personal data in accordance with the EU General Data Protection Regulation (GDPR) and applicable data-protection laws.",
  privacy_s1_title: "1. Data Controller",
  privacy_s1_body: "The data controller responsible for your personal data in connection with the Service is MicaLingo. For privacy-related requests, contact us at micalingo@gmail.com or support.micalingo@gmail.com.",
  privacy_s2_title: "2. Information We Process",
  privacy_s2_body: "Sign-in is provided exclusively through Google Sign-In (Google Authentication). When you choose to sign in, Google may share with us a limited set of account information (such as your Google account identifier, display name, profile photo URL, and email address) as permitted by Google’s authentication APIs and your Google account settings. We do not operate an independent password-based account system, and we do not have visibility into your Google password or the full contents of your Google account. We may also store learning progress, imported vocabulary, and similar content that you voluntarily create or upload within the Service, linked to your authenticated account.",
  privacy_s3_title: "3. Cookies and Tracking",
  privacy_s3_body: "We do not collect cookies for advertising, analytics, or tracking purposes, and we do not use tracking pixels, fingerprinting, or similar cross-site tracking technologies to monitor your browsing behaviour. Any strictly technical storage required for the Service to function (for example, remembering your language preference or session state in your browser or device) is limited to what is necessary to provide the Service you request.",
  privacy_s4_title: "4. Purpose of Processing and Legal Basis",
  privacy_s4_body: "We process personal data to provide and secure the Service, authenticate users via Google Sign-In, sync your learning materials and progress across devices where applicable, and respond to support requests. Depending on the processing activity, the legal basis under the GDPR may include: performance of a contract (Article 6(1)(b) GDPR), our legitimate interests in operating and improving a secure learning Service (Article 6(1)(f) GDPR), and/or your consent where required (Article 6(1)(a) GDPR).",
  privacy_s5_title: "5. No Marketing Use of Email Addresses",
  privacy_s5_body: "We will not use your email address for marketing purposes. We do not send newsletters, promotional campaigns, or advertising emails. Your email address, if received through Google Sign-In, is used only as needed to operate your account and to communicate with you about the Service when you contact us or when such communication is necessary to provide the Service.",
  privacy_s6_title: "6. Third-Party Services (Google)",
  privacy_s6_body: "Authentication is handled by Google. Use of Google Sign-In is also subject to Google’s Privacy Policy and Terms of Service. Google may process certain data as an independent controller or processor according to its own policies. We encourage you to review Google’s privacy documentation. MicaLingo’s use of information received from Google APIs will adhere to the Google API Services User Data Policy, including the Limited Use requirements, where applicable.",
  privacy_s7_title: "7. Data Retention",
  privacy_s7_body: "We retain account-related and user-generated learning data for as long as your account remains active or as needed to provide the Service. You may request deletion of your personal data subject to legal retention obligations. Local progress stored on your device can typically be cleared from the Settings area of the app.",
  privacy_s8_title: "8. Your Rights (EU / EEA)",
  privacy_s8_body: "If you are located in the European Union or European Economic Area, you have the right to request access to, rectification of, erasure of, or restriction of processing of your personal data; the right to data portability where applicable; the right to object to processing based on legitimate interests; and the right to withdraw consent where processing is based on consent. You also have the right to lodge a complaint with your local supervisory authority. To exercise your rights, contact us at the email addresses listed below.",
  privacy_s9_title: "9. International Transfers",
  privacy_s9_body: "Because we use Google authentication and cloud infrastructure, personal data may be processed in countries outside your country of residence, including outside the EU/EEA. Where required, such transfers are carried out with appropriate safeguards consistent with applicable law (for example, Standard Contractual Clauses used by relevant providers).",
  privacy_s10_title: "10. Children’s Privacy",
  privacy_s10_body: "The Service is intended for users who are able to create or use a Google account in accordance with Google’s terms and applicable law. If you believe a child has provided personal data to us in violation of applicable rules, please contact us so we can take appropriate action.",
  privacy_s11_title: "11. Changes to This Policy",
  privacy_s11_body: "We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. The \"Last updated\" date at the top of this page indicates when this Policy was last revised. Continued use of the Service after an update constitutes acknowledgment of the revised Policy where permitted by law.",
  privacy_s12_title: "12. Contact",
  privacy_s12_body: "For privacy questions or data-subject requests, contact: micalingo@gmail.com or support.micalingo@gmail.com. Website: https://micalingo.com",

  terms_title: "Terms of Service",
  terms_intro: "These Terms of Service (\"Terms\") govern your access to and use of MicaLingo’s website at micalingo.com and our mobile application (the \"Service\"). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.",
  terms_s1_title: "1. Description of the Service",
  terms_s1_body: "MicaLingo is an educational application designed to help users prepare for German language exams through quizzes, vocabulary practice, grammar materials, reading and listening resources, and related learning tools. Certain features may require signing in with a Google account.",
  terms_s2_title: "2. Eligibility and Accounts",
  terms_s2_body: "You may need a Google account to access personalized features. You are responsible for maintaining the security of your Google account and for all activity that occurs under your authenticated session. You agree to use the Service only in accordance with these Terms, Google’s Terms of Service, and applicable law.",
  terms_s3_title: "3. Acceptable Use and Ethical Conduct",
  terms_s3_body: "You agree to use the Service only with an ethical mindset and solely for legitimate language-learning purposes. You must not use the Service to learn, create, upload, store, share, or practice words, phrases, sentences, or other content related to hate speech, discrimination, harassment, violence, terrorism, extremism, criminal activity, or any other content that is unlawful or that violates Google’s Terms of Service or policies. You must not misuse the Service to harm others, circumvent security measures, scrape or abuse our systems, or interfere with other users’ access.",
  terms_s4_title: "4. User Content",
  terms_s4_body: "You retain ownership of vocabulary, notes, and other materials you import or create (\"User Content\"). By submitting User Content, you grant us a limited licence to host, store, and display that content solely as needed to operate the Service for you. You represent that you have the rights necessary to submit User Content and that it does not infringe third-party rights or these Terms.",
  terms_s5_title: "5. Intellectual Property",
  terms_s5_body: "The Service, including its branding, design, public learning materials we provide, and software, is protected by intellectual property laws. Except for your User Content, you may not copy, modify, distribute, sell, or create derivative works from the Service without our prior written permission, except as allowed by mandatory law.",
  terms_s6_title: "6. Third-Party Services",
  terms_s6_body: "The Service relies on third-party providers, including Google for authentication. Your use of Google Sign-In is subject to Google’s Terms of Service and Privacy Policy. We are not responsible for third-party services outside our reasonable control.",
  terms_s7_title: "7. Disclaimer of Warranties",
  terms_s7_body: "The Service is provided on an \"as is\" and \"as available\" basis without warranties of any kind, whether express or implied, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement, to the fullest extent permitted by applicable law. We do not guarantee uninterrupted availability, error-free operation, or specific exam results.",
  terms_s8_title: "8. Limitation of Liability",
  terms_s8_body: "To the maximum extent permitted by applicable EU and national law, MicaLingo and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of data, profits, or goodwill, arising from your use of the Service. Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law, including liability for death or personal injury caused by negligence or for fraud.",
  terms_s9_title: "9. Suspension and Termination",
  terms_s9_body: "We may suspend or terminate access to the Service if you violate these Terms, misuse the Service, or if required for security or legal reasons. You may stop using the Service at any time. Provisions that by their nature should survive termination will survive.",
  terms_s10_title: "10. Changes to the Terms",
  terms_s10_body: "We may update these Terms from time to time. The \"Last updated\" date indicates the latest revision. Continued use of the Service after changes become effective constitutes acceptance of the updated Terms where permitted by law.",
  terms_s11_title: "11. Governing Law",
  terms_s11_body: "These Terms are governed by the laws applicable in the European Union and the relevant Member State laws that apply to consumers, without prejudice to mandatory consumer-protection rules of your country of residence.",
  terms_s12_title: "12. Contact",
  terms_s12_body: "For questions about these Terms, contact: micalingo@gmail.com or support.micalingo@gmail.com. Website: https://micalingo.com",

  about_title: "About & Contact",
  about_heading: "About MicaLingo",
  about_body: "MicaLingo is a German exam preparation app and website (micalingo.com) that helps learners practise vocabulary, grammar, quizzes, reading, and listening materials. Create your own library, track your progress, and study at your own pace — on the web or in the Android app.",
  about_mission: "Our goal is to make structured German learning accessible, practical, and focused on real exam preparation needs.",
  contact_heading: "Contact & Support",
  contact_body: "Have a question, feedback, or need help? We would love to hear from you.",
  contact_general_label: "General contact",
  contact_support_label: "Support & feedback",
  contact_website_label: "Website",
};