export const hu = {
  title: "Német vizsga előkészítő",

  // Settings
  settings_title: "Beállítások",
  settings_subtitle: "Kezeld a fiókod és az alkalmazás beállításait.",
  language_preferences: "Nyelvi beállítások",
  language_preferences_subtitle: "Válaszd ki az alkalmazás nyelvét.",
  app_language: "Alkalmazás nyelve",
  english: "Angol",
  german: "Német",
  hungarian: "Magyar",
  practice_settings: "Gyakorlás beállításai",
  practice_settings_subtitle: "Szabd testre a kvíz élményét.",
  show_example_sentences: "Példamondatok mutatása",
  show_example_sentences_subtitle: "Példamondatok megjelenítése a kérdések megválaszolása után.",
  save_preferences: "Beállítások mentése",
  saving_preferences: "Mentés...",
  save_button: "Mentés",
  saved: "Mentve!",
  data_management: "Adatkezelés",
  data_management_subtitle: "Mentett haladás és helyi adatok kezelése.",
  clear_local_data: "Helyi haladás törlése",
  clear_local_data_desc: "Helyi kvíz eredmények és haladás törlése. A felhőben tárolt szókincset nem törli.",
  confirm_clear_data: "Biztosan törölni szeretné az összes helyi haladást? Ezt nem lehet visszavonni.",
  data_cleared: "A helyi haladás sikeresen törölve.",
  reset_personal_library: "Saját könyvtár visszaállítása",
  reset_personal_library_desc: "Véglegesen törli az összes egyénileg importált szót és nyelvtani anyagot a felhőből. Ezt nem lehet visszavonni.",
  confirm_reset_library: "Biztosan törölni szeretné a saját könyvtár összes elemét? Ezt nem lehet visszavonni.",
  library_wiped: "A saját könyvtár sikeresen törölve.",
  wipe_error: "Nem sikerült törölni a saját könyvtárat. Kérjük, próbálja újra.",
  wiping_data: "Adatok törlése...",
  hard_reset_database: "Könyvtár törlése",
  developer_tools: "Fejlesztői eszközök",
  developer_tools_subtitle: "Használd ezt a gombot a személyes felhőadataid teljes törléséhez. (Ez NEM törli a nyilvános vendégkönyvtárat). Töröld ezt a kódból a közzététel előtt.",
  hard_reset_warning: "⚠️ FIGYELMEZTETÉS: BIZTOSAN törölni akarod az ÖSSZES személyes importált szókincsedet? (A nyilvános könyvtárat ez nem érinti). Ezt nem lehet visszavonni!",
  hard_reset_success: "Adatbázis teljesen törölve! Tiszta lappal kezdesz.",

  // Quizzes
  quizzes_title: "Kvízek",
  quizzes_subtitle: "Válassz egy témát a gyakorláshoz.",
  test_your_knowledge: "Teszteld a tudásod",
  test_your_knowledge_subtitle: "Gyakorolj a nyilvános adatbázisunkkal.",
  vocabulary: "Szókincs",
  vocabulary_quiz_subtitle: "Gyakorold az alapvető szavakat.",
  articles_quiz: "Névelők",
  articles_quiz_subtitle: "Gyakorold a der, die, das névelőket.",
  phrases_quiz: "Kifejezések és mondatok",
  phrases_quiz_subtitle: "Hasznos mindennapi kifejezések és mondatok.",
  prepositions_quiz: "Elöljárószavak",
  prepositions_quiz_subtitle: "Gyakorold az elöljárószavakat és eseteket.",
  create_your_own_quizzes: "Saját kvízek",
  create_your_own_quizzes_subtitle_loggedin: "Gyakorolj a saját importált szavaiddal.",
  vocabulary_quiz: "Szókincs kvíz",
  create_your_own_quizzes_subtitle_loggedout: "Jelentkezz be saját kvízek készítéséhez.",
  login_to_create_quizzes: "Bejelentkezés",
  question_of: "Kérdés: {current} / {total}",
  choose_correct_one: "Válaszd ki a helyes megoldást!",
  custom_vocab_desc: "Gyakorolj szófordításokat a saját szótáradból.",
  custom_articles_desc: "Gyakorold a 'der, die, das' névelőket a saját főneveiddel.",
  custom_phrases_desc: "Teszteld a tudásod a saját kifejezéseiddel és mondataiddal.",
  custom_prepositions_desc: "Gyakorold az eseteket az importált elöljárószavakkal.",

  // Navigation & Layout
  home: "Kezdőlap",
  import: "Importálás",
  quizzes: "Kvízek",
  grammar: "Nyelvtan",
  statistics: "Statisztika",
  settings: "Beállítások",
  sign_out: "Kijelentkezés",
  login: "Bejelentkezés",
  vocabulary_short: "Szótár",

  // Home
  welcome_back: "Üdvözlünk, jó, hogy itt vagy!",
  ready_to_learn: "Készen állsz a német tudásod fejlesztésére? Hozd létre saját könyvtáradat, kvízeidet és tananyagaidat, és teszteld a tudásod most!",
  import_data: "Adatok importálása",
  upload_new_materials: "Tölts fel új szavakat és kifejezéseket.",
  login_required: "Bejelentkezés szükséges",
  to_create_new_quizzes_login_required: "Saját kvízekhez bejelentkezés szükséges",
  learn_new_words_from_library: "Böngéssz a könyvtárban vagy a saját szavaid között.",
  for_extending_login_required: "Saját szótárhoz bejelentkezés szükséges",
  coming_soon: "Hamarosan",
  review_grammar_topics: "Nyelvtani szabályok és magyarázatok.",
  track_your_progress: "Kövesd nyomon a fejlődésedet.",

  // Import
  import_title: "Fájlok importálása",
  accepted_format_guide: "Elfogadott formátumok",
  vocab_phrases: "Szókincs / Kifejezések és mondatok:",
  format_vocab_phrases: "A oszlop = Német (Kifejezés/Mondat), B oszlop = Magyar (Jelentés), C oszlop = Példa (Opcionális).",
  articles_quiz_label: "Névelők Kvíz:",
  format_articles: "A oszlop = Névelő, B oszlop = Főnév, C oszlop = Magyar, D oszlop = Példa.",
  text_copy_paste: "Szöveg / Beillesztés:",
  format_text: "Válaszd el a német és magyar szavakat tabulátorral, pontosvesszővel (;) vagy vesszővel (,).",
  need_starting_point: "Szükséged van egy kiindulópontra?",
  download_template_desc: "Tölts le egy Excel sablont az adatok egyszerű kitöltéséhez.",
  vocab_template: "Szókincs sablon",
  articles_template: "Névelők sablon",
  drag_and_drop: "Húzd ide vagy kattints a tallózáshoz",
  supported_files: "Támogatott fájlok: Excel, Word, PDF, CSV és TXT",
  preview_filename: "Előnézet: {filename}",
  items_detected: "{count} elem észlelve",
  article: "Névelő", noun: "Főnév + Többes", example: "Példa", column_a: "A oszlop", column_b: "B oszlop", column_c: "C oszlop", column_c_d: "C/D oszlop", column_d: "D oszlop",
  invalid_columns: "Nem sikerült érvényes oszlopokat észlelni.",
  invalid_columns_desc: "Ellenőrizd, hogy a fájl tabulátorokat (Excel), pontosvesszőket vagy vesszőket használ a szavak elválasztására.",
  save_to: "Mentés ide:",
  cancel: "Mégse",
  saving: "Mentés...",
  save_import: "Importálás mentése",
  manage_imported_files: "Importált fájlok kezelése",
  manage_imported_files_desc: "Egy fájl törlése eltávolítja az abból importált összes szót a kvízeidből és a szótáradból.",
  search_files: "Fájlok vagy kulcsszavak keresése...",
  files_selected: "{count} fájl kiválasztva",
  download_selected: "Kiválasztottak letöltése",
  delete_selected: "Kiválasztottak törlése",
  file_name: "Fájlnév",
  format: "Formátum",
  used_in: "Használva itt",
  items: "Elemek",
  action: "Művelet",
  download: "Letöltés",
  delete: "Törlés",
  confirm_delete_file: "Biztosan törölni szeretnéd a(z) \"{fileName}\" fájlt? Ez véglegesen eltávolítja a hozzá kapcsolódó {count} szót.",
  error_delete_file_desc: "Hiba történt a fájl elemeinek törlésekor.",
  confirm_bulk_delete: "Biztosan törölni szeretnél {count} fájlt? Minden kapcsolódó szó el lesz távolítva.",
  error_bulk_delete_desc: "Hiba történt a fájlok törlésekor.",
  no_items_export: "Nincsenek exportálható elemek.",
  no_items_save: "Nincsenek érvényes szavak a mentéshez, vagy nem vagy bejelentkezve.",
  import_success_with_duplicates: "Importálás kész! {saved} új elem mentve. {duplicates} duplikátum kihagyva.",
  import_success: "Importálás kész! {saved} új elem mentve.",
  error_saving_db: "Hiba történt az adatbázisba mentés során.",

  // Vocabulary Page
  vocab_title: "Szótár",
  vocab_subtitle: "Böngéssz és kezeld a tanult szavaidat.",
  add_word: "Szó hozzáadása",
  open_library: "Nyilvános könyvtár",
  personalized_space: "Privát tér",
  search_vocabulary: "Keresés a szótárban...",
  words_found: "{count} szó található",
  words_count: "{count} szó",
  no_words_match_search: "Nincs a keresésnek megfelelő szó.",
  checking_account: "Fiók ellenőrzése...",
  personalized_space_description: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal, hogy saját privát szókincset, gyűjteményeket és kvízeket hozhass létre, valamint elmentsd a haladásodat.",
  login_with_google: "Bejelentkezés Google-fiókkal",
  loading_vocabulary: "A szótárad betöltése...",
  words_selected: "{count} szó kiválasztva",
  delete_selected_words: "Kiválasztottak törlése",
  edit_word: "Szó szerkesztése",
  delete_word: "Szó törlése",
  modal_edit_word_title: "Szó szerkesztése",
  modal_add_word_title: "Új szó hozzáadása",
  modal_category_label: "Kategória",
  modal_german_label: "Német (névelővel és többes számmal) *",
  modal_german_placeholder: "pl. der Apfel",
  modal_article_label: "Névelő *",
  modal_noun_label: "Főnév (többes számmal) *",
  modal_noun_placeholder: "pl. Mann, die Männer",
  modal_german_phrase_label: "Német Kifejezés/Mondat *",
  modal_german_phrase_placeholder: "pl. Wie geht es Ihnen?",
  modal_hungarian_phrase_placeholder: "pl. Hogy van?",
  modal_german_prep_label: "Német Elöljárószó *",
  modal_german_prep_placeholder: "pl. mit",
  modal_hungarian_prep_placeholder: "pl. val/vel",
  modal_german_ff_label: "Német Hamis Barát *",
  modal_german_ff_placeholder: "pl. das Gift, die Gifte",
  modal_hungarian_ff_placeholder: "pl. a méreg",
  modal_hungarian_label: "Magyar *",
  modal_hungarian_placeholder: "pl. alma",
  modal_example_label: "Példa / Megjegyzés",
  modal_example_placeholder: "pl. Ich esse einen Apfel.",
  modal_save_changes: "Módosítások mentése",
  modal_save_word: "Szó mentése",
  alert_fill_fields_login: "Kérlek, töltsd ki legalább a német és magyar mezőket. Győződj meg róla, hogy be vagy jelentkezve.",
  alert_confirm_delete_word: "Biztosan törölni szeretnéd ezt a szót?",
  alert_confirm_bulk_delete_words: "Biztosan törölni szeretnél {count} kiválasztott szót?",
  alert_login_failed: "Sikertelen bejelentkezés a Google-fiókkal.",
  all_categories: "Minden kategória",

  // Quiz Page
  loading_questions: "Kérdések betöltése...",
  not_enough_words: "Nincs elég szó",
  not_enough_words_desc: "Nincs elég szó a személyes szótáradban egy {topic} kvízhez.",
  need_more_items: "Legalább 4 '{topic}' kategóriájú elemre van szükség.",
  import_more_words: "További szavak importálása",
  quiz_complete: "Kvíz befejezve!",
  no_more_quizzes: "Az összes kvíz teljesítve!",
  great_job: "Szép munka, gratulálunk a haladáshoz!",
  loading: "Betöltés...",
  here: "itt",
  your_score: "Pontszámod:",
  back_to_quizzes: "Vissza a kvízekhez",
  retry_quiz: "Kvíz újraindítása",
  go_to_level: "Tovább a(z) {level}. szintre",
  next_question: "Következő kérdés",
  finish_quiz: "Kvíz befejezése",
  back_button: "← Vissza",
  next_quiz_button: "Következő kvíz →",
  example_label: "Példa",
  quiz_title_public: "{topic} Kvíz {id}",
  quiz_title_custom: "Saját {topic} Kvíz {id}",
  quiz_title_personal: "Privát Kvíz",
  items_count: "{count} elem",
  quit_quiz_title: "Kilépsz a kvízből?",
  quit_quiz_desc: "A haladásod automatikusan mentve lett. Később onnan folytathatod, ahol abbahagytad.",
  quit: "Kilépés",

  // Topic Quizzes
  topic_not_found: "Téma nem található",
  return_to_quizzes: "Vissza a kvízekhez",
  select_level_to_start: "Válassz egy szintet a gyakorlás megkezdéséhez.",
  level_id: "{id}. Szint",
  start_button: "Indítás →",
  continue_button: "Folytatás →",
  personalized_quizzes: "Privát kvízek",
  personalized_quizzes_desc: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal, hogy saját privát szókincset, gyűjteményeket és kvízeket hozhass létre, valamint elmentsd a haladásodat.",
  your_custom_quizzes: "Saját kvízeid",
  custom_quizzes_count_desc: "Jelenleg {count} elem van elmentve ehhez a témához.",
  start_custom_quiz: "Saját kvíz indítása",
  import_more_data: "További adatok importálása",

  // Create Quiz
  create_custom_quiz_title: "Saját {topic} Kvíz létrehozása",
  choose_data_source: "Válaszd ki az adatforrást a kezdéshez.",
  use_personal_library: "Saját szótár használata",
  use_personal_library_desc: "Készíts kvízt a már importált és '{topic}' kategóriába sorolt szavakból.",
  upload_new_file: "Új fájl feltöltése",
  upload_new_file_desc: "Importálj egy új fájlt kifejezetten ehhez a kvíztípushoz.",
  required_format: "Elvárt formátum:",
  download_template: "Sablon letöltése",
  go_to_import_page: "Tovább az importáláshoz →",
  instructions_articles: "Az A oszlop legyen a névelő ('der', 'die', 'das'). A B oszlop legyen a főnév (és a többes szám, teljesen kiírva névelővel). A C oszlop a magyar jelentés. A D oszlop opcionális a példamondatokhoz.",
  instructions_prepositions: "Az A oszlop legyen a német elöljárószó, a B oszlop a magyar jelentés. Ezek kötelezőek. A C oszlop opcionális a példákhoz.",
  instructions_vocabulary: "Az A oszlop legyen a német szó (hozzáadhatod a többes számot is ugyanabban az oszlopban, pl. 'das Haus, die Häuser'). A B oszlop a magyar jelentés. Ezek kötelező mezők. A C oszlop opcionális a példamondatokhoz.",
  instructions_phrases: "Az A oszlopba a német kifejezés vagy mondat kerüljön. A B oszlop a magyar jelentés. Ezek kötelező mezők. A C oszlop opcionális a példamondatokhoz.",
  template_article_header: "Névelő (A)",
  template_noun_header: "Főnév + Többes sz. (B)",
  template_hungarian_header: "Magyar (C)",
  template_example_header: "Példa (D)",
  template_german_header: "Német",
  template_german_mandatory_header: "Német (Kötelező, névelővel/többes számmal)",
  template_hungarian_mandatory_header: "Magyar (Kötelező)",
  template_example_optional_header: "Példa (Opcionális)",

  // Grammar & Statistics
  grammar_page_title: "Nyelvtan",
  grammar_page_subtitle: "Nyelvtani szabályok és magyarázatok áttekintése.",
  statistics_page_title: "Statisztika",
  statistics_page_subtitle: "Kövesd nyomon a tanulási folyamatodat.",
  page_under_construction: "Ez az oldal jelenleg fejlesztés alatt áll.",
  check_back_later: "Kérlek, nézz vissza később!",
  guest_warning_stats: "Vendégként az eredményeid itt jelennek meg, amíg be nem zárod a weboldalt/alkalmazást. Ha szeretnéd elmenteni a haladásodat, jelentkezz be ",
  guest_warning_stats_link: "itt",
  quizzes_solved: "Megoldott kvízek",
  materials_read: "Elolvasott anyagok",
  no_quizzes_solved: "Még nem fejeztél be egyetlen kvízt sem.",
  no_materials_read: "Még nem olvastál el semmilyen anyagot.",
  review_button: "Áttekintés",
  download_button: "Letöltés",
  redo_button: "Újra",
  correct_answer: "Helyes válasz",
  your_answer: "Saját válaszod",
  csv_question: "Kérdés",
  csv_result: "Eredmény",
  result: "Eredmény",
  status_excellent: "Kiváló",
  status_good: "Jó",
  status_needs_practice: "Gyakorlás szükséges",
  csv_correct: "Helyes",
  csv_incorrect: "Helytelen",
  delete_selected_records: "Kiválasztottak törlése",
  confirm_delete_record: "Biztosan törölni szeretnéd ezt az eredményt?",
  confirm_bulk_delete_records: "Biztosan törölni szeretnél {count} kiválasztott eredményt?",
  records_selected: "{count} eredmény kiválasztva",

  // Login Page
  login_page_title: "Bejelentkezés",
  login_page_subtitle: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal a privát szótárad eléréséhez és a fejlődésed nyomon követéséhez.",

  // Results Page
  results_page_title: "Kvíz eredmények",
  results_page_subtitle: "Nézd át a válaszaidat az utolsó kvízből.",
  review_answers: "Válaszok áttekintése",
  retry_mistakes: "Hibák újrajátszása",
  close: "Bezárás",

  // Library & Learning Materials
  library: "Könyvtár",
  library_subtitle: "Férj hozzá a szótáradhoz és a tananyagaidhoz.",
  learning_materials: "Tananyagok",
  learning_materials_subtitle: "Olvass szövegeket, hallgass hanganyagokat és egyebeket.",
  read_materials: "Olvasás",
  read_materials_desc: "Olvass szövegeket, cikkeket és történeteket.",
  listen_materials: "Hallgatás",
  listen_materials_desc: "Hallgass hanganyagokat és podcastokat.",
  save_to_reading: "Olvasnivaló",
  save_to_listening: "Hallgatnivaló",

  // Protected Route / Login Prompt
  protected_space_title: "Privát tér",
  protected_space_desc_1: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal a privát szókincsed, gyakorlataid és haladásod eléréséhez.",
  protected_space_desc_2: "Jelentkezz be a folytatáshoz!",
  continue_with_google: "Folytatás Google-fiókkal",

  // Admin
  admin_mode: "Admin Mód",
  admin_mode_desc: "Adminisztrátorként vagy bejelentkezve. Hozzáadhatsz anyagokat a nyilvános könyvtárhoz.",
  switch_to_normal_user: "Váltás normál felhasználóra",
  switch_to_admin: "Váltás Admin Módra",
  admin_prompt_title: "Üdvözlünk, Admin!",
  admin_prompt_desc: "Válaszd ki, hogyan szeretnéd használni az alkalmazást ebben a munkamenetben.",
  admin_mode_dev: "Fejlesztői Mód (Nyilvános könyvtár szerkesztése)",
  admin_mode_normal: "Normál Felhasználói Mód (Csak privát)",

  // False Friends
  false_friends: "Hamis barátok",
  false_friends_desc: "Olyan szavak, amelyek hasonlóan néznek ki vagy hangzanak, sőt néha ugyanazt is jelentik németül és magyarul. Könnyű megjegyezni őket!",
  false_friends_label: "Hamis barátok:",
  format_false_friends: "A oszlop = Német, B oszlop = Magyar, C oszlop = Példa, D oszlop = Megjegyzés/Jelentés.",
  false_friends_template: "Hamis barátok sablon",
  template_note_header: "Megjegyzés (D)",
  note: "Megjegyzés / Jelentés",
  admin_save_public: "Admin: Mentés a nyilvános könyvtárba"
};