export const hu = {
  title: "Német vizsga előkészítő",

  // Settings
  settings_title: "Beállítások",
  settings_subtitle: "Kezeld a fiókod és az alkalmazás beállításait.",
  language_preferences: "Nyelvi beállítások",
  language_preferences_subtitle: "Válaszd ki az alkalmazás nyelvét.",
  app_language: "Alkalmazás nyelve",
  english: "Angol",
  german: "Német",
  hungarian: "Magyar",
  practice_settings: "Gyakorlás beállításai",
  practice_settings_subtitle: "Szabd testre a kvíz élményét.",
  show_example_sentences: "Példamondatok mutatása",
  show_example_sentences_subtitle: "Példamondatok megjelenítése a kérdések megválaszolása után.",
  save_preferences: "Beállítások mentése",
  saving_preferences: "Mentés...",
  save_button: "Mentés",
  saved: "Mentve!",
  data_management: "Adatkezelés",
  data_management_subtitle: "Mentett haladás és helyi adatok kezelése.",
  clear_local_data: "Helyi haladás törlése",
  clear_local_data_desc: "Helyi kvíz eredmények és haladás törlése. A felhőben tárolt szókincset nem törli.",
  confirm_clear_data: "Biztosan törölni szeretné az összes helyi haladást? Ezt nem lehet visszavonni.",
  data_cleared: "A helyi haladás sikeresen törölve.",
  reset_personal_library: "Saját könyvtár visszaállítása",
  reset_personal_library_desc: "Véglegesen törli az összes egyénileg importált szót és nyelvtani anyagot a felhőből. Ezt nem lehet visszavonni.",
  confirm_reset_library: "Biztosan törölni szeretné a saját könyvtár összes elemét? Ezt nem lehet visszavonni.",
  library_wiped: "A saját könyvtár sikeresen törölve.",
  wipe_error: "Nem sikerült törölni a saját könyvtárat. Kérjük, próbálja újra.",
  wiping_data: "Adatok törlése...",
  hard_reset_database: "Könyvtár törlése",
  developer_tools: "Fejlesztői eszközök",
  developer_tools_subtitle: "Használd ezt a gombot a személyes felhőadataid teljes törléséhez. (Ez NEM törli a nyilvános vendégkönyvtárat). Töröld ezt a kódból a közzététel előtt.",
  hard_reset_warning: "⚠️ FIGYELMEZTETÉS: BIZTOSAN törölni akarod az ÖSSZES személyes importált szókincsedet? (A nyilvános könyvtárat ez nem érinti). Ezt nem lehet visszavonni!",
  hard_reset_success: "Adatbázis teljesen törölve! Tiszta lappal kezdesz.",

  // Quizzes
  quizzes_title: "Kvízek",
  quizzes_subtitle: "Válassz egy témát a gyakorláshoz.",
  test_your_knowledge: "Teszteld a tudásod",
  test_your_knowledge_subtitle: "Gyakorolj a nyilvános adatbázisunkkal.",
  vocabulary: "Szókincs",
  vocabulary_quiz_subtitle: "Gyakorold az alapvető szavakat.",
  articles_quiz: "Névelők",
  articles_quiz_subtitle: "Gyakorold a der, die, das névelőket.",
  phrases_quiz: "Kifejezések és mondatok",
  phrases_quiz_subtitle: "Hasznos mindennapi kifejezések és mondatok.",
  phrases_sentences_quiz: "Kifejezések és mondatok",
  prepositions_quiz: "Elöljárószavak",
  prepositions_quiz_subtitle: "Gyakorold az elöljárószavakat és eseteket.",
  verbs_quiz: "Igék",
  verbs_quiz_subtitle: "Gyakorold a német igéket és múlt időket.",
  create_your_own_quizzes: "Saját kvízek",
  create_your_own_quizzes_subtitle_loggedin: "Gyakorolj a saját importált szavaiddal.",
  vocabulary_quiz: "Szókincs",
  create_your_own_quizzes_subtitle_loggedout: "Jelentkezz be saját kvízek készítéséhez.",
  login_to_create_quizzes: "Bejelentkezés",
  question_of: "Kérdés: {current} / {total}",
  choose_correct_one: "Válaszd ki a helyes megoldást!",
  custom_vocab_desc: "Gyakorolj szófordításokat a saját szótáradból.",
  custom_articles_desc: "Gyakorold a 'der, die, das' névelőket a saját főneveiddel.",
  custom_phrases_desc: "Teszteld a tudásod a saját kifejezéseiddel és mondataiddal.",
  custom_prepositions_desc: "Gyakorold az eseteket az importált elöljárószavakkal.",
  custom_verbs_desc: "Saját igéid.",

  // Navigation & Layout
  home: "Kezdőlap",
  import: "Importálás",
  quizzes: "Kvízek",
  grammar: "Nyelvtan",
  statistics: "Statisztika",
  settings: "Beállítások",
  sign_out: "Kijelentkezés",
  login: "Bejelentkezés",
  vocabulary_short: "Szótár",
  support_micalingo: "Támogasd a MicaLingot",
  support_desc: "Válassz egy összeget a projekt támogatásához. Minden hozzájárulás sokat segít!",
  support_tier_1: "Egy kávé",
  support_tier_2: "Egy nasi",
  support_tier_3: "Egy ebéd",
  support_tier_4: "Hős 🚀",
  enjoying_micalingo_title: "Tetszik a MicaLingo?",
  consider_donation_desc: "Kérjük, fontold meg a projekt támogatását, hogy továbbra is működhessen és reklámmentes maradhasson.",
  yes_support: "Igen, mutasd!",
  maybe_later: "Talán később",

  // Home
  welcome_back: "Üdvözlünk, jó, hogy itt vagy!",
  ready_to_learn: "Készen állsz a német tudásod fejlesztésére? Hozd létre saját könyvtáradat, kvízeidet és tananyagaidat, és teszteld a tudásod most!",
  import_data: "Adatok importálása",
  upload_new_materials: "Tölts fel új szavakat és kifejezéseket.",
  login_required: "Bejelentkezés szükséges",
  to_create_new_quizzes_login_required: "Saját kvízekhez bejelentkezés szükséges",
  learn_new_words_from_library: "Böngéssz a könyvtárban vagy a saját szavaid között.",
  login_to_create_quizzes_desc: "Ha saját szótárat és kvízeket szeretnél létrehozni, kérjük, jelentkezz be!",
  for_extending_login_required: "Saját szótárhoz bejelentkezés szükséges",
  coming_soon: "Hamarosan",
  review_grammar_topics: "Nyelvtani szabályok és magyarázatok.",
  track_your_progress: "Kövesd nyomon a fejlődésedet.",

  // Import
  import_title: "Fájlok importálása",
  accepted_format_guide: "Elfogadott formátumok",
  vocab_phrases: "Szókincs / Kifejezések / Elöljárószavak:",
  format_vocab_phrases: "A oszlop = Német (Kifejezés/Mondat), B oszlop = Magyar (Jelentés), C oszlop = Példa (Opcionális).",
  verbs_quiz_format_title: "Ige Kvíz:",
  verbs_quiz_format_desc: "A oszlop = Német (ige), B oszlop = Magyar (Jelentés), C oszlop = Múlt idejű alakok vagy Példák.",
  prepositions_quiz_format_title: "Vonzatos Igék Kvíz:",
  prepositions_quiz_format_desc: "A oszlop: Német ige, B oszlop: elöljárószó + eset, C oszlop: Magyar jelentés egy példamondattal együtt, vesszővel elválasztva.",
  articles_quiz_label: "Névelők Kvíz:",
  format_articles: "A oszlop = Névelő, B oszlop = Főnév, C oszlop = Magyar, D oszlop = Példa.",
  need_starting_point: "Szükséged van egy kiindulópontra?",
  download_template_desc: "Tölts le egy Excel sablont az adatok egyszerű kitöltéséhez.",
  vocab_template: "Szókincs sablon",
  articles_template: "Névelők sablon",
  verbs_template: "Igék sablon",
  prepositions_template: "Vonzatos Igék Sablon",
  template_german_verb_header: "Német Ige",
  template_prep_case_header: "Elöljárószó + Eset",
  template_meaning_example_header: "Jelentés és Példa",
  drag_and_drop: "Húzd ide vagy kattints a tallózáshoz",
  supported_files: "Támogatott fájlok: Excel, Word, PDF, CSV és TXT",
  preview_filename: "Előnézet: {filename}",
  items_detected: "{count} elem észlelve",
  article: "Névelő", noun: "Főnév + Többes", example: "Példa", column_a: "A oszlop", column_b: "B oszlop", column_c: "C oszlop", column_c_d: "C/D oszlop", column_d: "D oszlop",
  invalid_columns: "Nem sikerült érvényes oszlopokat észlelni.",
  invalid_columns_desc: "Ellenőrizd, hogy a fájl tabulátorokat (Excel), pontosvesszőket vagy vesszőket használ a szavak elválasztására.",
  save_to: "Mentés ide:",
  cancel: "Mégse",
  saving: "Mentés...",
  save_import: "Importálás mentése",
  manage_imported_files: "Importált fájlok kezelése",
  manage_imported_files_desc: "Egy fájl törlése eltávolítja az abból importált összes szót a kvízeidből és a szótáradból.",
  search_files: "Fájlok vagy kulcsszavak keresése...",
  files_selected: "{count} fájl kiválasztva",
  download_selected: "Kiválasztottak letöltése",
  delete_selected: "Kiválasztottak törlése",
  file_name: "Fájlnév",
  format: "Formátum",
  used_in: "Használva itt",
  items: "Elemek",
  action: "Művelet",
  download: "Letöltés",
  delete: "Törlés",
  hint: "Tipp / Múlt idő",
  confirm_delete_file: "Biztosan törölni szeretnéd a(z) \"{fileName}\" fájlt? Ez véglegesen eltávolítja a hozzá kapcsolódó {count} szót.",
  error_delete_file_desc: "Hiba történt a fájl elemeinek törlésekor.",
  confirm_bulk_delete: "Biztosan törölni szeretnél {count} fájlt? Minden kapcsolódó szó el lesz távolítva.",
  error_bulk_delete_desc: "Hiba történt a fájlok törlésekor.",
  no_items_export: "Nincsenek exportálható elemek.",
_items_save: "Nincsenek érvényes szavak a mentéshez, vagy nem vagy bejelentkezve.",
  import_success_with_duplicates: "Importálás kész! {saved} új elem mentve. {duplicates} duplikátum kihagyva.",
  import_success: "Importálás kész! {saved} új elem mentve.",
  import_overwritten: "{count} meglévő elem felülírva.",
  import_skipped: "{count} duplikátum kihagyva.",
  overwrite_confirm_title: "Felülírod a duplikátumokat?",
  overwrite_confirm_desc: "{count} már létező elemet találtunk. Felül szeretnéd írni őket a fájlban lévő új adatokkal?",
  overwrite_button: "Felülírás",
  skip_button: "Duplikátumok kihagyása",
  error_saving_db: "Hiba történt az adatbázisba mentés során.",

  // Vocabulary Page
  vocab_title: "Szótár",
  vocab_subtitle: "Böngéssz és kezeld a tanult szavaidat.",
  add_word: "Szó hozzáadása",
  open_library: "Nyilvános könyvtár",
  personalized_space: "Privát tér",
  search_vocabulary: "Keresés a szótárban...",
  words_found: "{count} szó található",
  words_count: "{count} szó",
  no_words_match_search: "Nincs a keresésnek megfelelő szó.",
  checking_account: "Fiók ellenőrzése...",
  personalized_space_description: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal, hogy saját privát szókincset, gyűjteményeket és kvízeket hozhass létre, valamint elmentsd a haladásodat.",
  login_with_google: "Bejelentkezés Google-fiókkal",
  loading_vocabulary: "A szótárad betöltése...",
  words_selected: "{count} szó kiválasztva",
  delete_selected_words: "Kiválasztottak törlése",
  edit_word: "Szó szerkesztése",
  delete_word: "Szó törlése",
  modal_edit_word_title: "Szó szerkesztése",
  modal_add_word_title: "Új szó hozzáadása",
  modal_category_label: "Kategória",
  modal_german_label: "Német (névelővel és többes számmal) *",
  modal_german_placeholder: "pl. der Apfel",
  modal_article_label: "Névelő *",
  modal_noun_label: "Főnév (többes számmal) *",
  modal_noun_placeholder: "pl. Mann, die Männer",
  modal_german_phrase_label: "Német Kifejezés/Mondat *",
  modal_german_phrase_placeholder: "pl. Wie geht es Ihnen?",
  modal_hungarian_phrase_placeholder: "pl. Hogy van?",
  modal_german_prep_label: "Német Elöljárószó *",
  modal_german_prep_placeholder: "pl. mit",
  modal_hungarian_prep_placeholder: "pl. val/vel",
  prep_case_label: "Elöljárószó + Eset *",
  modal_prep_case_placeholder: "pl. auf + Akkusativ",
  meaning_example_label: "Jelentés és Példa",
  meaning_example_placeholder: "pl. lemondani valamiről, Ich verzichte auf das Angebot.",
  modal_german_verb_label: "Német ige *",
  modal_german_verb_placeholder: "pl. machen",
  modal_hungarian_verb_placeholder: "pl. csinálni",
  modal_german_ff_label: "Német Hamis Barát *",
  modal_german_ff_placeholder: "pl. das Gift, die Gifte",
  modal_hungarian_ff_placeholder: "pl. a méreg",
  modal_hungarian_label: "Magyar *",
  modal_hungarian_placeholder: "pl. alma",
  modal_example_label: "Példa / Megjegyzés",
  modal_example_placeholder: "pl. Ich esse einen Apfel.",
  modal_save_changes: "Módosítások mentése",
  modal_save_word: "Szó mentése",
  alert_fill_fields_login: "Kérlek, töltsd ki legalább a német és magyar mezőket. Győződj meg róla, hogy be vagy jelentkezve.",
  alert_confirm_delete_word: "Biztosan törölni szeretnéd ezt a szót?",
  alert_confirm_bulk_delete_words: "Biztosan törölni szeretnél {count} kiválasztott szót?",
  alert_login_failed: "Sikertelen bejelentkezés a Google-fiókkal.",
  alert_word_exists: "Ez a szó már szerepel a(z) '{category}' részben!",
  duplicates_found_title: "Duplikátumok",
  duplicates_found_subtitle: "Ezek az elemek már léteznek a célhelyen, és nem lettek áthelyezve.",
  all_categories: "Minden kategória",

  // Dropdown Categories
  dropdown_vocabulary: "Szókincs kvíz",
  dropdown_reading: "Szókincs (olvasnivaló)",
  dropdown_articles: "Névelők kvíz",
  dropdown_phrases: "Kifejezések és mondatok kvíz",
  dropdown_prepositions: "Elöljárószavak kvíz",
  dropdown_adjectives: "Melléknevek kvíz",
  dropdown_verbs: "Igék kvíz",
  dropdown_false_friends: "Hamis barátok",

  // Quiz Page
  loading_questions: "Kérdések betöltése...",
  not_enough_words: "Nincs elég szó",
  not_enough_words_desc: "Nincs elég szó a személyes szótáradban egy {topic} kvízhez.",
  need_more_items: "Legalább 4 '{topic}' kategóriájú elemre van szükség.",
  import_more_words: "További szavak importálása",
  quiz_complete: "Kvíz befejezve!",
  your_score: "Pontszámod:",
  back_to_quizzes: "Vissza a kvízekhez",
  retry_quiz: "Kvíz újraindítása",
  go_to_level: "Tovább a(z) {level}. szintre",
  next_question: "Következő kérdés",
  finish_quiz: "Kvíz befejezése",
  back_button: "← Vissza",
  next_quiz_button: "Következő kvíz →",
  example_label: "Példa",
  quiz_title_public: "{topic} Kvíz {id}",
  quiz_title_custom: "Saját {topic} Kvíz {id}",
  quiz_title_personal: "Privát Kvíz",
  items_count: "{count} elem",
  quit_quiz_title: "Kilépsz a kvízből?",
  quit_quiz_desc: "A haladásod automatikusan mentve lett. Később onnan folytathatod, ahol abbahagytad.",
  quit: "Kilépés",

  // Topic Quizzes
  topic_not_found: "Téma nem található",
  return_to_quizzes: "Vissza a kvízekhez",
  select_level_to_start: "Válassz egy szintet a gyakorlás megkezdéséhez.",
  level_id: "{id}. Szint",
  start_button: "Indítás →",
  continue_button: "Folytatás →",
  personalized_quizzes: "Privát kvízek",
  personalized_quizzes_desc: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal, hogy saját privát szókincset, gyűjteményeket és kvízeket hozhass létre, valamint elmentsd a haladásodat.",
  your_custom_quizzes: "Saját kvízeid",
  custom_quizzes_count_desc: "Jelenleg {count} elem van elmentve ehhez a témához.",
  start_custom_quiz: "Saját kvíz indítása",
  import_more_data: "További adatok importálása",

  // Create Quiz
  create_custom_quiz_title: "Saját {topic} Kvíz létrehozása",
  choose_data_source: "Válaszd ki az adatforrást a kezdéshez.",
  use_personal_library: "Saját szótár használata",
  use_personal_library_desc: "Készíts kvízt a már importált és '{topic}' kategóriába sorolt szavakból.",
  upload_new_file: "Új fájl feltöltése",
  upload_new_file_desc: "Importálj egy új fájlt kifejezetten ehhez a kvíztípushoz.",
  required_format: "Elvárt formátum:",
  download_template: "Sablon letöltése",
  go_to_import_page: "Tovább az importáláshoz →",
  instructions_articles: "Az A oszlop legyen a névelő ('der', 'die', 'das'). A B oszlop legyen a főnév (és a többes szám, teljesen kiírva névelővel). A C oszlop a magyar jelentés. A D oszlop opcionális a példamondatokhoz.",
  instructions_prepositions: "Az A oszlop legyen a német elöljárószó, a B oszlop a magyar jelentés. Ezek kötelezőek. A C oszlop opcionális a példákhoz.",
  instructions_vocabulary: "Az A oszlop legyen a német szó (hozzáadhatod a többes számot is ugyanabban az oszlopban, pl. 'das Haus, die Häuser'). A B oszlop a magyar jelentés. Ezek kötelező mezők. A C oszlop opcionális a példamondatokhoz.",
  instructions_phrases: "Az A oszlopba a német kifejezés vagy mondat kerüljön. A B oszlop a magyar jelentés. Ezek kötelező mezők. A C oszlop opcionális a példamondatokhoz.",
  template_article_header: "Névelő (A)",
  template_noun_header: "Főnév + Többes sz. (B)",
  template_hungarian_header: "Magyar (C)",
  template_example_header: "Példa (D)",
  template_german_header: "Német",
  template_german_mandatory_header: "Német (Kötelező, pl. névelővel/többes számmal)",
  template_hungarian_mandatory_header: "Magyar (Kötelező)",
  template_example_optional_header: "Példa (Opcionális)",

  // Grammar & Statistics
  grammar_page_title: "Nyelvtan",
  grammar_page_subtitle: "Nyelvtani szabályok és magyarázatok áttekintése.",
  grammar_cases: "Esetek (Fälle)",
  grammar_tenses: "Igeidők (Zeitformen)",
  grammar_articles: "Névelők és Nemek",
  grammar_adjectives: "Melléknévragozás",
  grammar_prepositions: "Elöljárószavak",
  grammar_sentence_structure: "Mondatszerkezet",
  add_grammar_rule: "Nyelvtani szabály hozzáadása",
  edit_grammar_rule: "Nyelvtani szabály szerkesztése",
  delete_grammar_rule: "Nyelvtani szabály törlése",
  grammar_rule_title: "Szabály címe",
  grammar_rule_content: "Nyelvtani magyarázat",
  fetch_content: "Tartalom lekérése",
  fetch_error: "Nem sikerült lekérni a tartalmat. Kérjük, ellenőrizze az URL-t, vagy illessze be kézzel.",
  bullet_list: "• Felsorolás",
  undo_button: "↩ Visszavonás",
  no_items: "Még nincsenek elemek.",
  confirm_delete_grammar: "Biztosan törölni szeretnéd ezt a nyelvtani szabályt?",
  statistics_page_title: "Statisztika",
  statistics_page_subtitle: "Kövesd nyomon a tanulási folyamatodat.",
  page_under_construction: "Ez az oldal jelenleg fejlesztés alatt áll.",
  check_back_later: "Kérlek, nézz vissza később!",
  guest_warning_stats: "Vendégként az eredményeid itt jelennek meg, amíg be nem zárod a weboldalt/alkalmazást. Ha szeretnéd elmenteni a haladásodat, jelentkezz be",
  guest_warning_stats_link: "itt!",
  quizzes_solved: "Megoldott kvízek",
  materials_read: "Elolvasott anyagok",
  no_quizzes_solved: "Még nem fejeztél be egyetlen kvízt sem.",
  no_materials_read: "Még nem olvastál el semmilyen anyagot.",
  review_button: "Áttekintés",
  download_button: "Letöltés",
  redo_button: "Újra",
  correct_answer: "Helyes válasz",
  your_answer: "Saját válaszod",
  csv_question: "Kérdés",
  csv_result: "Eredmény",
  result: "Eredmény",
  status_excellent: "Kiváló",
  status_good: "Jó",
  status_needs_practice: "Gyakorlás szükséges",
  csv_correct: "Helyes",
  csv_incorrect: "Helytelen",
  delete_selected_records: "Kiválasztottak törlése",
  confirm_delete_record: "Biztosan törölni szeretnéd ezt az eredményt?",
  confirm_bulk_delete_records: "Biztosan törölni szeretnél {count} kiválasztott eredményt?",
  records_selected: "{count} eredmény kiválasztva",

  // Login Page
  login_page_title: "Bejelentkezés",
  login_page_subtitle: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal a privát szótárad eléréséhez és a fejlődésed nyomon követéséhez.",

  // Results Page
  results_page_title: "Kvíz eredmények",
  results_page_subtitle: "Nézd át a válaszaidat az utolsó kvízből.",
  review_answers: "Válaszok áttekintése",
  retry_mistakes: "Hibák újrajátszása",
  close: "Bezárás",

  // Library & Learning Materials
  library: "Könyvtár",
  library_subtitle: "Férj hozzá a szótáradhoz és a segédanyagaidhoz.",
  learning_materials: "Segédanyagok",
  learning_materials_subtitle: "Olvass szövegeket, hallgass hanganyagokat és egyebeket.",
  read_materials: "Olvasás",
  read_materials_desc: "Olvass szövegeket, cikkeket és történeteket.",
  listen_materials: "Hallgatás",
  listen_materials_desc: "Hallgass hanganyagokat és podcastokat.",
  save_to_reading: "Olvasnivaló",
  save_to_listening: "Hallgatnivaló",
  interesting_section: "Érdekes",
  articles_section: "Cikkek",
  books_section: "Könyvek",
  music_section: "Zene",
  podcasts_section: "Podcastok",
  audiobooks_section: "Hangoskönyvek",
  history: "Történelem",
  history_desc: "Történelmi események és személyiségek.",
  animals: "Állatok",
  animals_desc: "Vadvilág és természet.",
  music: "Zene",
  music_desc: "Zeneszerzők, hangszerek és műfajok.",
  culture: "Kultúra",
  culture_desc: "Művészet, koncertek és kiállítások.",
  politics: "Politika",
  politics_desc: "Kormányzat és társadalom.",
  science: "Tudomány",
  science_desc: "Felfedezések és kutatások.",
  celebrities: "Hírességek",
  celebrities_desc: "Híres emberek és popkultúra.",
  classic_literature: "Klasszikus irodalom",
  classic_literature_desc: "Olvasd a mesterműveket.",
  short_stories: "Novellák",
  short_stories_desc: "Rövid olvasmányok a napi gyakorláshoz.",
  pop: "Pop",
  pop_desc: "Népszerű zenei slágerek.",
  rock: "Rock",
  rock_desc: "Rock és alternatív zene.",
  other_music: "Egyéb",
  other_music_desc: "Különféle egyéb műfajok.",
  travel: "Utazás",
  travel_desc: "Történetek és tippek a világ minden tájáról.",
  psychology: "Pszichológia",
  psychology_desc: "Elme, viselkedés és mentális egészség.",
  other_podcasts: "Egyéb",
  other_podcasts_desc: "Különféle egyéb podcast témák.",
  fiction: "Fikció",
  fiction_desc: "Regények és történetek.",
  non_fiction: "Tényirodalom",
  non_fiction_desc: "Tényszerű és oktató jellegű.",
  other_audiobooks: "Egyéb",
  other_audiobooks_desc: "Különféle egyéb hangoskönyvek.",

  // Protected Route / Login Prompt
  protected_space_title: "Privát tér",
  protected_space_desc_1: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal a privát szókincsed, gyakorlataid és haladásod eléréséhez.",
  protected_space_desc_2: "Jelentkezz be a folytatáshoz!",
  continue_with_google: "Folytatás Google-fiókkal",

  // Admin
  admin_mode: "Admin Mód",
  admin_mode_desc: "Adminisztrátorként vagy bejelentkezve. Hozzáadhatsz anyagokat a nyilvános könyvtárhoz.",
  switch_to_normal_user: "Váltás normál felhasználóra",
  switch_to_admin: "Váltás Admin Módra",
  admin_prompt_title: "Üdvözlünk, Admin!",
  admin_prompt_desc: "Válaszd ki, hogyan szeretnéd használni az alkalmazást ebben a munkamenetben.",
  admin_mode_dev: "Fejlesztői Mód (Nyilvános könyvtár szerkesztése)",
  admin_mode_normal: "Normál Felhasználói Mód (Csak privát)",

  // False Friends
  false_friends: "Hamis barátok",
  false_friends_desc: "Olyan szavak, amelyek hasonlóan néznek ki vagy hangzanak, sőt néha ugyanazt is jelentik németül és magyarul. Könnyű megjegyezni őket!",
  false_friends_template: "Hamis barátok sablon",
  template_note_header: "Megjegyzés (D)",
  note: "Megjegyzés / Jelentés",
  admin_save_public: "Admin: Mentés a nyilvános könyvtárba",
  media_player: "Médialejátszó",
  play_content: "Tartalom lejátszása",
  fetch_error_audio: "Nem sikerült lekérni az audió adatait. Kérjük, ellenőrizze az URL-t, vagy illessze be manuálisan.",
  save_error_audio: "Nem sikerült menteni az audiót. Kérjük, jelentkezz be.",
  delete_error_audio: "Nem sikerült törölni az audiót.",
  confirm_delete_audio: "Biztosan törölni szeretnéd ezt az audiót?",
  add_audio: "Audio hozzáadása",
  audio_url: "Audio/Video URL címe",
  fetch_audio: "Tartalom lekérése",
  audio_title: "Audio címe",
  audio_content: "Audio leírása / tartalma",
  audio_source: "Előadó / Forrás",
  audio_source_placeholder: "pl. Rammstein",
  save_audio: "Audio mentése",
  edit_audio: "Audio szerkesztése",
  delete_audio: "Audio törlése",
  audio_url_note: "Megjegyzés: A YouTube és a Spotify URL-ek automatikusan beágyazott lejátszót generálnak!",
  add_article: "Cikk hozzáadása",
  article_url: "Cikk URL címe",
  fetch_article: "Tartalom lekérése",
  article_title: "Cikk címe",
  article_content: "Cikk tartalma",
  article_source: "Forrás",
  article_source_placeholder: "pl. Der Standard",
  save_article: "Cikk mentése",
  edit_article: "Cikk szerkesztése",
  delete_article: "Cikk törlése",
  confirm_delete_article: "Biztosan törölni szeretnéd ezt a cikket?",
  add_book: "Könyv hozzáadása",
  book_url: "Könyv URL címe",
  fetch_book: "Tartalom lekérése",
  book_title: "Könyv címe",
  book_content: "Könyv tartalma",
  book_source: "Szerző / Forrás",
  book_source_placeholder: "pl. Goethe",
  save_book: "Könyv mentése",
  edit_book: "Könyv szerkesztése",
  delete_book: "Könyv törlése",
  confirm_delete_book: "Biztosan törölni szeretnéd ezt a könyvet?",
  bookmark_instructions_logged_in: "Jelölj ki bármilyen szöveget olvasás közben a könyvjelző mentéséhez, vagy mentsd el a kijelölt szöveget közvetlenül a saját szótáradba, vagy kvízeidbe!",
  bookmark_instructions_guest: "Jelölj ki bármilyen szöveget olvasás közben a könyvjelző mentéséhez, vagy mentsd el a kijelölt szöveget közvetlenül a saját szótáradba, vagy kvízeidbe! (Ez a funkció kizárólag bejelentkezett felhasználók számára érhető el. Jelentkezz be a használatához!)",
  save_bookmark: "Könyvjelző",
  continue_from: "Folytatás innen:",
  no_audio_yet: "Még nincsenek hanganyagok.",
  no_audio_yet_admin: "Itt még nincsenek tartalmak. Kattintson a fenti '+ Audio hozzáadása' gombra az első zeneszám hozzáadásához!",
  private_reading_hint: "Hozd létre saját olvasási kategóriáidat a szövegek, cikkek vagy könyvek rendszerezéséhez.",
  private_listening_hint: "Hozz létre kategóriákat zenei stílus szerint, vagy csoportosítsd kedvenc dalaidat előadók alapján.",
  private_grammar_hint: "Hozz létre saját nyelvtani kategóriákat a jegyzeteid rendszerezéséhez.",
  private_category_1: "1. Kategória",
  private_category_2: "2. Kategória",
  private_category_3: "3. Kategória",
  private_category_4: "4. Kategória",
  private_category_5: "5. Kategória",
  edit_category: "Kategória szerkesztése",
  adjectives_quiz: 'Melléknevek',
  adjectives_quiz_subtitle: 'Gyakorold a német mellékneveket.',
  custom_adjectives_desc: 'Saját mellékneveid.',
  template_adjective_header: 'Melléknév (kötelező)',
  template_levels_header: 'Fokozás (pl. jobb, legjobb)',
  format_adjectives: 'A oszlop: Német, B oszlop: Magyar, C oszlop: Fokozás (pl. jobb, legjobb vagy példamondat).',
  adjectives_template: 'Melléknevek Sablon',
  adjective: 'Melléknév',
  levels: 'Fokozás',
  url_optional: "URL (Opcionális)",
  title_label: "Cím",
  source_author: "Forrás / Szerző",
  source_artist: "Forrás / Előadó",
  content_label: "Tartalom",
  fetch_note: "Megjegyzés: A lekérés proxyn keresztül történik. Összetett oldalak blokkolhatják. A tartalmat bármikor beillesztheted manuálisan is.",
  no_items_left: "Nincs több elem. Mentsd el az összes törléséhez.",
  original_source: "Eredeti forrás",
  add_interesting: "Érdekes tartalom hozzáadása",
  edit_interesting: "Érdekes tartalom szerkesztése",
  delete_interesting: "Tartalom törlése",
  confirm_delete_interesting: "Biztosan törölni szeretnéd ezt a tartalmat?",
  interesting_url: "Tartalom URL címe",
  fetch_interesting: "Tartalom lekérése",
  interesting_title: "Cím",
  interesting_source: "Forrás",
  interesting_source_placeholder: "pl. Wikipédia",
  interesting_content: "Tartalom",
  save_interesting: "Tartalom mentése",
  fun_facts: "Érdekességek",
  fun_facts_desc: "Érdekes tények és tudnivalók.",
  idioms: "Szólások",
  idioms_desc: "Gyakori mondások és szólások.",
  save_to_vocabulary: "Szó mentése",
  add_content: "Tartalom hozzáadása",
  add_image: "Kép hozzáadása",
  explanation_label: "Magyarázat",
  explanation_placeholder: "Magyarázat",
  add_idiom: "Szólás hozzáadása",
  edit_idiom: "Szólás szerkesztése",
  idiom_german_label: "Német szólás *",
  idiom_german_placeholder: "pl. Ich verstehe nur Bahnhof",
  idiom_hungarian_label: "Magyar jelentés *",
  idiom_hungarian_placeholder: "pl. Nekem ez kínai",
  idiom_note_label: "Megjegyzés (Magyarázat)",
  idiom_note_placeholder: "Szó szerinti jelentés...",
  save_content: "Tartalom mentése",
  confirm_delete_idiom: "Biztosan törölni szeretnéd ezt a szólást?",
};