export const hu = {
  title: "Német vizsga előkészítő",

  // Settings
  settings_title: "Beállítások",
  settings_subtitle: "Kezeld a fiókod és az alkalmazás beállításait.",
  language_preferences: "Nyelvi beállítások",
  language_preferences_subtitle: "Válaszd ki az alkalmazás nyelvét.",
  app_language: "Alkalmazás nyelve",
  english: "Angol",
  german: "Német",
  hungarian: "Magyar",
  practice_settings: "Gyakorlás beállításai",
  practice_settings_subtitle: "Szabd testre a kvíz élményét.",
  show_example_sentences: "Példamondatok mutatása",
  show_example_sentences_subtitle: "Példamondatok megjelenítése a kérdések megválaszolása után.",
  save_preferences: "Beállítások mentése",
  saving_preferences: "Mentés...",
  save_button: "Mentés",
  saved: "Mentve!",
  data_management: "Adatkezelés",
  data_management_subtitle: "Kvízeredményeid törlése.",
  clear_local_data: "Kvízeredményeid törlése",
  clear_local_data_desc: "A felhőbe korábban feltöltött és ott tárolt szókincset nem törli.",
  confirm_clear_data: "Biztosan törölni szeretnéd az összes kvízeredményed? Ezt nem lehet visszavonni.",
  data_cleared: "A kvízeredményeid sikeresen törölted.",
  reset_personal_library: "Saját könyvtár visszaállítása",
  reset_personal_library_desc: "Véglegesen törlöd az összes egyénileg importált szót és nyelvtani anyagot a felhőből. Ezt nem lehet visszavonni.",
  confirm_reset_library: "Biztosan törölni szeretnéd a saját könyvtár összes elemét? Ezt nem lehet visszavonni.",
  library_wiped: "A saját könyvtár sikeresen törölve.",
  wipe_error: "Nem sikerült törölni a saját könyvtárat. Kérlek, próbáld újra.",
  wiping_data: "Adatok törlése...",
  hard_reset_database: "Könyvtár törlése",
  developer_tools: "Fejlesztői eszközök",
  developer_tools_subtitle: "Használd ezt a gombot a személyes felhőadataid teljes törléséhez. (Ez NEM törli a nyilvános vendégkönyvtárat). Töröld ezt a kódból a közzététel előtt.",
  hard_reset_warning: "⚠️ FIGYELMEZTETÉS: BIZTOSAN törölni akarod az ÖSSZES személyes importált szókincsedet? (A nyilvános könyvtárat ez nem érinti). Ezt nem lehet visszavonni!",
  hard_reset_success: "Adatbázis teljesen törölve! Tiszta lappal kezdesz.",

  // Quizzes
  quizzes_title: "Kvízek",
  quizzes_subtitle: "Válassz egy kategóriát a gyakorláshoz.",
  test_your_knowledge: "Teszteld a tudásod",
  test_your_knowledge_subtitle: "Gyakorolj a nyilvános adatbázisunkkal.",
  vocabulary: "Szókincs",
  vocabulary_quiz_subtitle: "Gyakorold az alapvető szavakat.",
  articles_quiz: "Névelők",
  articles_quiz_subtitle: "Gyakorold a der, die, das névelőket.",
  phrases_quiz: "Kifejezések és mondatok",
  phrases_quiz_subtitle: "Hasznos mindennapi kifejezések és mondatok.",
  phrases_sentences_quiz: "Kifejezések és mondatok",
  prepositions_quiz: "Elöljárószavak",
  prepositions_quiz_subtitle: "Gyakorold az elöljárószavakat és eseteket.",
  verbs_quiz: "Igék",
  verbs_quiz_subtitle: "Gyakorold a német igéket és múlt időket.",
  create_your_own_quizzes: "Saját kvízek",
  create_your_own_quizzes_subtitle_loggedin: "Gyakorolj a saját importált szavaiddal.",
  vocabulary_quiz: "Szókincs",
  create_your_own_quizzes_subtitle_loggedout: "Jelentkezz be saját kvízek készítéséhez.",
  login_to_create_quizzes: "Bejelentkezés",
  question_of: "Kérdés: {current} / {total}",
  choose_correct_one: "Válaszd ki a helyes megoldást!",
  custom_vocab_desc: "Gyakorolj szófordításokat a saját szótáradból.",
  custom_articles_desc: "Gyakorold a 'der, die, das' névelőket a saját főneveiddel.",
  custom_phrases_desc: "Teszteld a tudásod a saját kifejezéseiddel és mondataiddal.",
  custom_prepositions_desc: "Gyakorold az eseteket az importált elöljárószavakkal.",
  custom_verbs_desc: "Saját igéid.",

  // Navigation & Layout
  home: "Kezdőlap",
  import: "Importálás",
  quizzes: "Kvízek",
  grammar: "Nyelvtan",
  statistics: "Statisztika",
  settings: "Beállítások",
  sign_out: "Kijelentkezés",
  login: "Bejelentkezés",
  vocabulary_short: "Szótár",
  support_micalingo: "Támogasd a MicaLingot",
  support_desc: "Válassz egy összeget a projekt támogatásához. Minden hozzájárulás sokat segít!",
  support_tier_1: "Egy kávé",
  support_tier_2: "Egy nasi",
  support_tier_3: "Egy ebéd",
  support_tier_4: "Hős 🚀",
  enjoying_micalingo_title: "Tetszik a MicaLingo?",
  consider_donation_desc: "Kérlek, fontold meg a projekt támogatását, hogy továbbra is működhessen és reklámmentes maradhasson.",
  yes_support: "Igen, mutasd!",
  maybe_later: "Talán később",

  // Home
  welcome_back: "Üdvözlünk, jó, hogy itt vagy!",
  ready_to_learn: "Készen állsz a német tudásod fejlesztésére? Hozd létre saját könyvtáradat, kvízeidet és tananyagaidat, és teszteld a tudásod most!",
  import_data: "Adatok importálása és kezelése",
  upload_new_materials: "Tölts fel új szavakat és kifejezéseket.",
  login_required: "Bejelentkezés szükséges",
  to_create_new_quizzes_login_required: "Saját kvízekhez bejelentkezés szükséges",
  learn_new_words_from_library: "Böngéssz a könyvtárban vagy a saját szavaid között.",
  login_to_create_quizzes_desc: "Ha saját szótárat és kvízeket szeretnél létrehozni, kérlek, jelentkezz be!",
  for_extending_login_required: "Saját szótárhoz bejelentkezés szükséges",
  coming_soon: "Hamarosan",
  review_grammar_topics: "Nyelvtani szabályok és magyarázatok.",
  track_your_progress: "Kövesd nyomon a fejlődésedet.",
  download_android: "Töltsd le az Android alkalmazást",
  download_android_desc: "Vidd magaddal a MicaLingo-t! Töltsd le közvetlenül a telefonodra.",
  download_apk: "Letöltés",
  android_install_note: "Megjegyzés: Mivel ezt az alkalmazást közvetlenül töltöd le, a telefonod biztonsági figyelmeztetést jeleníthet meg. A folytatáshoz kattints a 'További részletek', majd a 'Telepítés mindenképpen' gombra.",

  // Import
  import_title: "Fájlok importálása",
  accepted_format_guide: "Elfogadott formátumok",
vocab_phrases: "Szókincs (Olvasnivaló vagy Kvíz) / Kifejezések Kvíz:",
  format_vocab_phrases: "A oszlop = Német (Kifejezés/Mondat), B oszlop = Magyar (Jelentés), C oszlop = Példa (Opcionális).",
  verbs_quiz_format_title: "Ige Kvíz:",
  verbs_quiz_format_desc: "A oszlop = Német (ige), B oszlop = Magyar (Jelentés), C oszlop = Múlt idejű alakok vagy Példák.",
  prepositions_quiz_format_title: "Vonzatos igék Kvíz:",
  prepositions_quiz_format_desc: "A oszlop: Német ige + magyar jelentés, B oszlop: elöljárószó + eset, C oszlop: Példamondat.",
  articles_quiz_label: "Névelők Kvíz:",
  format_articles: "A oszlop = Névelő, B oszlop = Főnév, C oszlop = Magyar, D oszlop = Példa.",
  need_starting_point: "Szükséged van egy kiindulópontra?",
  download_template_desc: "Tölts le egy Excel sablont az adatok egyszerű kitöltéséhez.",
  vocab_template: "Szókincs (olvasni vagy kvíz) sablon",
  articles_template: "Névelők kvíz sablon",
  verbs_template: "Igék kvíz sablon",
  prepositions_template: "Vonzatos igék kvíz sablon",
  template_german_verb_header: "Német ige + Magyar jelentés",
  template_prep_case_header: "Elöljárószó + Eset",
  template_meaning_example_header: "Példamondat",
  drag_and_drop: "Húzd ide vagy kattints a tallózáshoz",
  supported_files: "Támogatott fájlok: Excel, Word, PDF, CSV és TXT",
  preview_filename: "Előnézet: {filename}",
  items_detected: "{count} elem észlelve",
  article: "Névelő", noun: "Főnév + Többes", example: "Példa", column_a: "A oszlop", column_b: "B oszlop", column_c: "C oszlop", column_c_d: "C/D oszlop", column_d: "D oszlop",
  invalid_columns: "Nem sikerült érvényes oszlopokat észlelni.",
  invalid_columns_desc: "Ellenőrizd, hogy a fájl tabulátorokat (Excel), pontosvesszőket vagy vesszőket használ a szavak elválasztására.",
  save_to: "Mentés ide:",
  cancel: "Mégse",
  saving: "Mentés...",
  save_import: "Importálás mentése",
  manage_imported_files: "Importált fájlok kezelése",
  manage_imported_files_desc: "Egy fájl törlése eltávolítja az abból importált összes szót a kvízeidből és a szótáradból.",
  search_files: "Fájlok vagy kulcsszavak keresése...",
  files_selected: "{count} fájl kiválasztva",
  download_selected: "Kiválasztottak letöltése",
  delete_selected: "Kiválasztottak törlése",
  file_name: "Fájlnév",
  format: "Formátum",
  used_in: "Használva itt",
  items: "Elemek",
  action: "Művelet",
  download: "Letöltés",
  delete: "Törlés",
  hint: "Tipp / Múlt idő",
  confirm_delete_file: "Biztosan törölni szeretnéd a(z) \"{fileName}\" fájlt? Ez véglegesen eltávolítja a hozzá kapcsolódó {count} szót.",
  error_delete_file_desc: "Hiba történt a fájl elemeinek törlésekor.",
  confirm_bulk_delete: "Biztosan törölni szeretnél {count} fájlt? Minden kapcsolódó szó el lesz távolítva.",
  error_bulk_delete_desc: "Hiba történt a fájlok törlésekor.",
  no_items_export: "Nincsenek exportálható elemek.",
_items_save: "Nincsenek érvényes szavak a mentéshez, vagy nem vagy bejelentkezve.",
  import_success_with_duplicates: "Importálás kész! {saved} új elem mentve. {duplicates} duplikátum kihagyva.",
  import_success: "Importálás kész! {saved} új elem mentve.",
  import_overwritten: "{count} meglévő elem felülírva.",
  import_skipped: "{count} duplikátum kihagyva.",
  overwrite_confirm_title: "Felülírod a duplikátumokat?",
  overwrite_confirm_desc: "{count} már létező elemet találtunk. Felül szeretnéd írni őket a fájlban lévő új adatokkal?",
  overwrite_button: "Felülírás",
  skip_button: "Duplikátumok kihagyása",
  error_saving_db: "Hiba történt az adatbázisba mentés során.",

  // Vocabulary Page
  vocab_title: "Szótár",
  vocab_subtitle: "Böngéssz és kezeld a tanult szavaidat.",
  add_word: "Szó hozzáadása",
  open_library: "Nyilvános könyvtár",
  personalized_space: "Privát tér",
  marked_words: "Megjelölt szavak",
  marked_words_subtitle: "Gyakorold a hibás válasz után csillaggal megjelölt szavakat.",
  marked_words_description: "Ha elhibázol egy kvízkérdést, koppints a csillagra, hogy ide mentsd. Gyakorolhatod vegyes kvízként, vagy egyenként törölheted a szavakat.",
  marked_words_empty: "Még nincs megjelölt szó",
  marked_words_empty_desc: "Hibázz egy kvízkérdésnél, majd koppints a jobb felső sarokban a csillagra, hogy ide mentsd.",
  marked_words_practice: "Megjelölt szavak gyakorlása",
  marked_words_manage: "Könyvtár kezelése",
  marked_words_manage_desc: "A szavakat egyenként csak a megjelölt listádról töröld. A nyilvános könyvtár kvízei nem változnak.",
  mark_word: "Szó megjelölése",
  unmark_word: "Megjelölés eltávolítása",
  word_marked: "Szó megjelölve",
  quiz_title_marked: "Megjelölt szavak kvíz {id}",
  personalized_space_empty: "A privát tered üres",
  search_vocabulary: "Keresés a szótárban...",
  words_found: "{count} szó található",
  words_count: "{count} szó",
  no_words_match_search: "Nincs a keresésnek megfelelő szó.",
  checking_account: "Fiók ellenőrzése...",
  personalized_space_description: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal, hogy saját privát szókincset, gyűjteményeket és kvízeket hozhass létre, valamint elmentsd a haladásodat.",
  login_with_google: "Bejelentkezés Google-fiókkal",
  loading_vocabulary: "A szótárad betöltése...",
  words_selected: "{count} szó kiválasztva",
  delete_selected_words: "Kiválasztottak törlése",
  edit_word: "Szerkesztés",
  delete_word: "Szó törlése",
  modal_edit_word_title: "Szerkesztés",
  modal_add_word_title: "Új szó hozzáadása",
  modal_category_label: "Kategória",
  modal_german_label: "Német (névelővel és többes számmal) *",
  modal_german_placeholder: "pl. der Apfel",
  modal_article_label: "Névelő *",
  modal_noun_label: "Főnév (többes számmal) *",
  modal_noun_placeholder: "pl. Mann, die Männer",
  modal_german_phrase_label: "Német kifejezés/mondat *",
  modal_german_phrase_placeholder: "pl. Wie geht es Ihnen?",
  modal_hungarian_phrase_placeholder: "pl. Hogy van?",
  modal_german_prep_label: "Német elöljárószó *",
  modal_german_prep_placeholder: "pl. mit",
  modal_hungarian_prep_placeholder: "pl. val/vel",
  prep_case_label: "Elöljárószó + eset *",
  modal_prep_case_placeholder: "pl. auf + Akk.",
  meaning_example_label: "Példamondat",
  meaning_example_placeholder: "pl. Ich verzichte auf das Angebot.",
  modal_german_prep_verb_label: "Német ige + magyar jelentés *",
  modal_german_prep_verb_placeholder: "pl. verzichten, lemondani valamiről/felhagyni valamivel",
  modal_german_verb_label: "Német ige *",
  modal_german_verb_placeholder: "pl. machen",
  modal_hungarian_verb_placeholder: "pl. csinálni",
  modal_german_ff_label: "Német hamis barát *",
  modal_german_ff_placeholder: "pl. das Gift, die Gifte",
  modal_hungarian_ff_placeholder: "pl. a méreg",
  modal_hungarian_label: "Magyar *",
  modal_hungarian_placeholder: "pl. alma",
  modal_example_label: "Példa / Megjegyzés",
  modal_example_placeholder: "pl. Ich esse einen Apfel.",
  modal_save_changes: "Módosítások mentése",
  modal_save_word: "Szó mentése",
  alert_fill_fields_login: "Kérlek, töltsd ki legalább a német és magyar mezőket. Győződj meg róla, hogy be vagy jelentkezve.",
  alert_confirm_delete_word: "Biztosan törölni szeretnéd ezt a szót?",
  alert_confirm_bulk_delete_words: "Biztosan törölni szeretnél {count} kiválasztott szót?",
  alert_login_failed: "Sikertelen bejelentkezés a Google-fiókkal.",
  alert_word_exists: "Ez a szó már szerepel a(z) '{category}' részben!",
  duplicates_found_title: "Duplikátumok",
  duplicates_found_subtitle: "Ezek az elemek már léteznek a célhelyen, és nem lettek áthelyezve.",
  all_categories: "Minden kategória",

  // Dropdown Categories
  dropdown_vocabulary: "Szókincs kvíz",
  dropdown_reading: "Szókincs (olvasnivaló)",
  vocab_reading_subtitle: "Csak olvasáshoz feltöltött szavak — külön a kvíz könyvtáraktól.",
  copy_to_quiz: "Hozzáadás kvízhez is...",
  copy_to_quiz_hint: "Külön kvíz-másolatot készít. A szó megmarad a Szókincs (olvasnivaló) könyvtárban.",
  category_separation_hint: "Az olvasnivaló és a kvíz könyvtárak külön vannak — ugyanaz a szó lehet mindkettőben.",
  dropdown_articles: "Névelők kvíz",
  dropdown_phrases: "Kifejezések és mondatok kvíz",
  dropdown_prepositions: "Elöljárószavak kvíz",
  dropdown_adjectives: "Melléknevek kvíz",
  dropdown_verbs: "Igék kvíz",
  dropdown_false_friends: "Hamis barátok",

  // Quiz Page
  loading_questions: "Kérdések betöltése...",
  not_enough_words: "Nincs elég szó",
  not_enough_words_desc: "Nincs elég szó a személyes szótáradban egy {topic} kvízhez.",
  need_more_items: "Legalább 4 '{topic}' kategóriájú elemre van szükség.",
  import_more_words: "További szavak importálása",
  quiz_complete: "Kvíz befejezve!",
  no_more_quizzes: "Ebből a témából minden elérhető kvízt teljesítettél!",
  great_job: "Szép munka, így tovább!",
  your_score: "Pontszámod:",
  back_to_quizzes: "Vissza a kvízekhez",
  retry_quiz: "Kvíz újraindítása",
  go_to_level: "Tovább a(z) {level}. szintre",
  next_question: "Következő kérdés",
  finish_quiz: "Kvíz befejezése",
  back_button: "← Vissza",
  next_quiz_button: "Következő kvíz →",
  example_label: "Példa",
  quiz_title_public: "{topic} kvíz {id}",
  quiz_title_custom: "Saját {topic} kvíz {id}",
  quiz_title_personal: "Privát Kvíz",
  items_count: "{count} elem",
  quit_quiz_title: "Kilépsz a kvízből?",
  quit_quiz_desc: "A haladásod automatikusan mentve lett. Később onnan folytathatod, ahol abbahagytad.",
  quit: "Kilépés",

  // Topic Quizzes
  topic_not_found: "Téma nem található",
  return_to_quizzes: "Vissza a kvízekhez",
  select_level_to_start: "Válassz egy szintet a gyakorlás megkezdéséhez.",
  level_id: "{id}. Szint",
  start_button: "Indítás →",
  continue_button: "Folytatás →",
  personalized_quizzes: "Privát kvízek",
  personalized_quizzes_desc: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal, hogy saját privát szókincset, gyűjteményeket és kvízeket hozhass létre, valamint elmentsd a haladásodat.",
  your_custom_quizzes: "Saját kvízeid",
  custom_quizzes_count_desc: "Jelenleg {count} elem van elmentve ehhez a témához.",
  start_custom_quiz: "Saját kvíz indítása",
  import_more_data: "További adatok importálása",

  // Create Quiz
  create_custom_quiz_title: "Saját {topic} kvíz létrehozása",
  choose_data_source: "Válaszd ki az adatforrást a kezdéshez.",
  use_personal_library: "Saját szótár használata",
  use_personal_library_desc: "Készíts kvízt a már importált és '{topic}' kategóriába sorolt szavakból.",
  upload_new_file: "Új fájl feltöltése",
  upload_new_file_desc: "Importálj egy új fájlt kifejezetten ehhez a kvíztípushoz.",
  required_format: "Elvárt formátum:",
  download_template: "Sablon letöltése",
  go_to_import_page: "Tovább az importáláshoz →",
  instructions_articles: "Az A oszlop = névelő ('der', 'die', 'das') — a kvíz válasza. A B oszlop = főnév; a C oszlop = magyar jelentés — együtt jelennek meg a kérdésben (pl. Mann (a férfi)). A D oszlop = opcionális példamondat, ha be vannak kapcsolva a példák.",
  instructions_prepositions: "Az A oszlop legyen a német elöljárószó, a B oszlop a magyar jelentés. Ezek kötelezőek. A C oszlop opcionális a példákhoz.",
  instructions_vocabulary: "Az A oszlop legyen a német szó (hozzáadhatod a többes számot is ugyanabban az oszlopban, pl. 'das Haus, die Häuser'). A B oszlop a magyar jelentés. Ezek kötelező mezők. A C oszlop opcionális a példamondatokhoz.",
  instructions_phrases: "Az A oszlopba a német kifejezés vagy mondat kerüljön. A B oszlop a magyar jelentés. Ezek kötelező mezők. A C oszlop opcionális a példamondatokhoz.",
  template_article_header: "Névelő (A)",
  template_noun_header: "Főnév + többes sz. (B)",
  template_hungarian_header: "Magyar (C)",
  template_example_header: "Példa (D)",
  template_german_header: "Német",
  template_german_mandatory_header: "Német (Kötelező, pl. névelővel/többes számmal)",
  template_hungarian_mandatory_header: "Magyar (Kötelező)",
  template_example_optional_header: "Példa (Opcionális)",

  // Grammar & Statistics
  grammar_page_title: "Nyelvtan",
  grammar_page_subtitle: "Nyelvtani szabályok és magyarázatok áttekintése.",
  grammar_cases: "Esetek",
  grammar_tenses: "Igeidők",
  grammar_articles: "Névelők és nemek",
  grammar_adjectives: "Melléknévragozás",
  grammar_prepositions: "Elöljárószavak",
  grammar_sentence_structure: "Mondatszerkezet",
  add_grammar_rule: "Nyelvtani szabály hozzáadása",
  edit_grammar_rule: "Nyelvtani szabály szerkesztése",
  delete_grammar_rule: "Nyelvtani szabály törlése",
  grammar_rule_title: "Szabály címe",
  grammar_rule_content: "Nyelvtani magyarázat",
  fetch_content: "Tartalom lekérése",
  fetch_error: "Nem sikerült lekérni a tartalmat. Kérlek, ellenőrizd az URL-t, vagy illeszd be kézzel.",
  bullet_list: "• Felsorolás",
  undo_button: "↩ Visszavonás",
  no_items: "Még nincsenek elemek.",
  confirm_delete_grammar: "Biztosan törölni szeretnéd ezt a nyelvtani szabályt?",
  statistics_page_title: "Statisztika",
  statistics_page_subtitle: "Kövesd nyomon a tanulási folyamatodat.",
  page_under_construction: "Ez az oldal jelenleg fejlesztés alatt áll.",
  check_back_later: "Kérlek, nézz vissza később!",
  guest_warning_stats: "Vendégként az eredményeid itt jelennek meg, amíg be nem zárod a weboldalt/alkalmazást. Ha szeretnéd elmenteni a haladásodat, jelentkezz be",
  guest_warning_stats_link: "itt!",
  quizzes_solved: "Megoldott kvízek",
  materials_read: "Elolvasott anyagok",
  no_quizzes_solved: "Még nem fejeztél be egyetlen kvízt sem.",
  no_materials_read: "Még nem olvastál el semmilyen anyagot.",
  select_all: "Összes kijelölése",
  stats_quiz: "Kvíz",
  stats_score: "Pontszám",
  stats_actions: "Műveletek",
  admin_target: "Admin cél",
  public_library_target: "Nyilvános könyvtár",
  personal_library_target: "Személyes könyvtár",
  review_button: "Áttekintés",
  download_button: "Letöltés",
  redo_button: "Újra",
  correct_answer: "Helyes válasz",
  your_answer: "Saját válaszod",
  csv_question: "Kérdés",
  csv_result: "Eredmény",
  result: "Eredmény",
  status_excellent: "Kiváló",
  status_good: "Jó",
  status_needs_practice: "Gyakorlás szükséges",
  csv_correct: "Helyes",
  csv_incorrect: "Helytelen",
  delete_selected_records: "Kiválasztottak törlése",
  confirm_delete_record: "Biztosan törölni szeretnéd ezt az eredményt?",
  confirm_bulk_delete_records: "Biztosan törölni szeretnél {count} kiválasztott eredményt?",
  records_selected: "{count} eredmény kiválasztva",

  // Login Page
  login_page_title: "Bejelentkezés",
  login_page_subtitle: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal a privát szótárad eléréséhez és a fejlődésed nyomon követéséhez.",

  // Results Page
  results_page_title: "Kvíz eredmények",
  results_page_subtitle: "Nézd át a válaszaidat az utolsó kvízből.",
  review_answers: "Válaszok áttekintése",
  retry_mistakes: "Hibák újrajátszása",
  close: "Bezárás",

  // Library & Learning Materials
  library: "Könyvtár",
  library_subtitle: "Férj hozzá a szótáradhoz és a segédanyagaidhoz.",
  learning_materials: "Segédanyagok",
  learning_materials_subtitle: "Olvass cikkeket, hallgass hanganyagokat és zenéket.",
  read_materials: "Olvasás",
  read_materials_desc: "Olvass szövegeket, cikkeket és történeteket.",
  listen_materials: "Hallgatás",
  listen_materials_desc: "Hallgass hanganyagokat, zenéket és podcastokat.",
  save_to_reading: "Olvasnivaló",
  save_to_listening: "Hallgatnivaló",
  interesting_section: "Érdekes",
  articles_section: "Cikkek",
  books_section: "Könyvek",
  music_section: "Zene",
  podcasts_section: "Podcastok",
  audiobooks_section: "Hangoskönyvek",
  history: "Történelem",
  history_desc: "Történelmi események és személyiségek.",
  animals: "Állatok",
  animals_desc: "Vadvilág és természet.",
  music: "Zene",
  music_desc: "Zeneszerzők, hangszerek és műfajok.",
  culture: "Kultúra",
  culture_desc: "Művészet, koncertek és kiállítások.",
  politics: "Politika",
  politics_desc: "Politika és társadalom.",
  science: "Tudomány",
  science_desc: "Felfedezések és kutatások.",
  celebrities: "Hírességek",
  celebrities_desc: "Híres emberek és popkultúra.",
  classic_literature: "Klasszikus irodalom",
  classic_literature_desc: "Olvasd a mesterműveket.",
  short_stories: "Novellák",
  short_stories_desc: "Rövid olvasmányok a napi gyakorláshoz.",
  pop: "Pop",
  pop_desc: "Népszerű pop/rádió slágerek.",
  rock: "Rock",
  rock_desc: "Rock és alternatív.",
  other_music: "Egyéb",
  other_music_desc: "Különféle, egyéb műfajok.",
  travel: "Utazás",
  travel_desc: "Történetek és tippek a világ minden tájáról.",
  psychology: "Pszichológia",
  psychology_desc: "Elme, viselkedés és mentális egészség.",
  other_podcasts: "Egyéb",
  other_podcasts_desc: "Különféle, egyéb podcast témák.",
  fiction: "Fikció",
  fiction_desc: "Regények és történetek.",
  non_fiction: "Tényirodalom",
  non_fiction_desc: "Tényszerű és oktató jellegű.",
  other_audiobooks: "Egyéb",
  other_audiobooks_desc: "Különféle egyéb hangoskönyvek.",

  // Protected Route / Login Prompt
  protected_space_title: "Privát tér",
  protected_space_desc_1: "Nincs szükség külön fiókra! Jelentkezz be biztonságosan a Google-fiókoddal a privát szókincsed, gyakorlataid és haladásod eléréséhez.",
  protected_space_desc_2: "Jelentkezz be a folytatáshoz!",
  continue_with_google: "Folytatás Google-fiókkal",

  // Admin
  admin_mode: "Admin Mód",
  admin_mode_desc: "Adminisztrátorként vagy bejelentkezve. Hozzáadhatsz anyagokat a nyilvános könyvtárhoz.",
  switch_to_normal_user: "Váltás normál felhasználóra",
  switch_to_admin: "Váltás Admin Módra",
  admin_prompt_title: "Üdvözlünk, Admin!",
  admin_prompt_desc: "Válaszd ki, hogyan szeretnéd használni az alkalmazást ebben a munkamenetben.",
  admin_mode_dev: "Fejlesztői Mód (Nyilvános könyvtár szerkesztése)",
  admin_mode_normal: "Normál Felhasználói Mód (Csak privát)",

  // False Friends
  false_friends: "Hamis barátok",
  false_friends_desc: "Olyan szavak, amelyek hasonlóan néznek ki vagy hangzanak, sőt néha ugyanazt is jelentik németül és magyarul. Könnyű megjegyezni őket!",
  false_friends_template: "Hamis barátok sablon",
  template_note_header: "Megjegyzés (D)",
  note: "Megjegyzés / Jelentés",
  admin_save_public: "Admin: Mentés a nyilvános könyvtárba",
  media_player: "Médialejátszó",
  play_content: "Tartalom lejátszása",
  fetch_error_audio: "Nem sikerült lekérni az audió adatait. Kérlek, ellenőrizd az URL-t, vagy illeszd be manuálisan.",
  save_error_audio: "Nem sikerült menteni az audiót. Kérlek, jelentkezz be.",
  delete_error_audio: "Nem sikerült törölni az audiót.",
  confirm_delete_audio: "Biztosan törölni szeretnéd ezt az audiót?",
  add_audio: "Audio hozzáadása",
  audio_url: "Audio/Video URL címe",
  fetch_audio: "Tartalom lekérése",
  audio_title: "Audio címe",
  audio_content: "Audio leírása / tartalma",
  audio_source: "Előadó / Forrás",
  audio_source_placeholder: "pl. Rammstein",
  save_audio: "Audio mentése",
  edit_audio: "Audio szerkesztése",
  delete_audio: "Audio törlése",
  audio_url_note: "Megjegyzés: A YouTube és a Spotify URL-ek automatikusan beágyazott lejátszót generálnak!",
  add_article: "Cikk hozzáadása",
  article_url: "Cikk URL címe",
  fetch_article: "Tartalom lekérése",
  article_title: "Cikk címe",
  article_content: "Cikk tartalma",
  article_source: "Forrás",
  article_source_placeholder: "pl. Der Standard",
  save_article: "Cikk mentése",
  edit_article: "Cikk szerkesztése",
  delete_article: "Cikk törlése",
  confirm_delete_article: "Biztosan törölni szeretnéd ezt a cikket?",
  add_book: "Könyv hozzáadása",
  book_url: "Könyv URL címe",
  fetch_book: "Tartalom lekérése",
  book_title: "Könyv címe",
  book_content: "Könyv tartalma",
  book_source: "Szerző / Forrás",
  book_source_placeholder: "pl. Goethe",
  save_book: "Könyv mentése",
  edit_book: "Könyv szerkesztése",
  delete_book: "Könyv törlése",
  confirm_delete_book: "Biztosan törölni szeretnéd ezt a könyvet?",
  bookmark_instructions_logged_in: "Jelölj ki bármilyen szöveget olvasás közben a könyvjelző mentéséhez, vagy mentsd el a kijelölt szöveget közvetlenül a saját szótáradba, vagy kvízeidbe!",
  bookmark_instructions_guest: "Jelölj ki bármilyen szöveget olvasás közben a könyvjelző mentéséhez, vagy mentsd el a kijelölt szöveget közvetlenül a saját szótáradba, vagy kvízeidbe! (Ez a funkció kizárólag bejelentkezett felhasználók számára érhető el. Jelentkezz be a használatához!)",
  save_bookmark: "Könyvjelző",
  continue_from: "Folytatás innen:",
  no_audio_yet: "Még nincsenek hanganyagok feltöltve.",
  no_audio_yet_admin: "Itt még nincsenek tartalmak. Kattints a fenti '+ Audio hozzáadása' gombra az első zeneszám hozzáadásához!",
  private_reading_hint: "Hozd létre saját olvasási kategóriáidat a szövegek, cikkek vagy könyvek rendszerezéséhez.",
  private_listening_hint: "Hozz létre kategóriákat zenei stílus szerint, vagy csoportosítsd kedvenc dalaidat előadók alapján.",
  private_grammar_hint: "Hozz létre saját nyelvtani kategóriákat a jegyzeteid rendszerezéséhez.",
  private_category_1: "1. Kategória",
  private_category_2: "2. Kategória",
  private_category_3: "3. Kategória",
  private_category_4: "4. Kategória",
  private_category_5: "5. Kategória",
  edit_category: "Kategória szerkesztése",
  adjectives_quiz: 'Melléknevek',
  adjectives_quiz_subtitle: 'Gyakorold a német mellékneveket.',
  custom_adjectives_desc: 'Saját mellékneveid.',
  template_adjective_header: 'Melléknév (kötelező)',
  template_levels_header: 'Fokozás (pl. jobb, legjobb)',
  adjectives_quiz_label: 'Melléknevek Kvíz:',
  format_adjectives: 'A oszlop: Német, B oszlop: Magyar, C oszlop: Fokozás (pl. jobb, legjobb vagy példamondat).',
  adjectives_template: 'Melléknevek kvíz sablon',
  adjective: 'Melléknév',
  levels: 'Fokozás',
  url_optional: "URL (Opcionális)",
  title_label: "Cím",
  source_author: "Forrás / Szerző",
  source_artist: "Forrás / Előadó",
  content_label: "Tartalom",
  fetch_note: "Megjegyzés: A lekérés proxyn keresztül történik. Összetett oldalak blokkolhatják. A tartalmat bármikor beillesztheted manuálisan is.",
  no_items_left: "Nincs több elem. Mentsd el az összes törléséhez.",
  original_source: "Eredeti forrás",
  add_interesting: "Érdekes tartalom hozzáadása",
  edit_interesting: "Érdekes tartalom szerkesztése",
  delete_interesting: "Tartalom törlése",
  confirm_delete_interesting: "Biztosan törölni szeretnéd ezt a tartalmat?",
  interesting_url: "Tartalom URL címe",
  fetch_interesting: "Tartalom lekérése",
  interesting_title: "Cím",
  interesting_source: "Forrás",
  interesting_source_placeholder: "pl. Wikipédia",
  interesting_content: "Tartalom",
  save_interesting: "Tartalom mentése",
  fun_facts: "Érdekességek",
  fun_facts_desc: "Érdekes tények és tudnivalók.",
  idioms: "Szólások",
  idioms_desc: "Gyakori mondások és szólások.",
  save_to_vocabulary: "Szó mentése",
  add_content: "Tartalom hozzáadása",
  add_image: "Kép hozzáadása",
  explanation_label: "Magyarázat",
  explanation_placeholder: "Magyarázat",
  add_idiom: "Szólás hozzáadása",
  edit_idiom: "Szólás szerkesztése",
  idiom_german_label: "Német szólás *",
  idiom_german_placeholder: "pl. Ich verstehe nur Bahnhof",
  idiom_hungarian_label: "Magyar jelentés *",
  idiom_hungarian_placeholder: "pl. Nekem ez kínai",
  idiom_note_label: "Megjegyzés (Magyarázat)",
  idiom_note_placeholder: "Szó szerinti jelentés...",
  save_content: "Tartalom mentése",
  confirm_delete_idiom: "Biztosan törölni szeretnéd ezt a szólást?",
  confirm_delete_ff: "Biztosan törölni szeretnéd ezt a hamis barátot?",
  ff_note_placeholder: "pl. Hamis barát: gift != ajándék",
  alert_fill_fields_admin: "Kérlek, töltsd ki legalább a német és magyar mezőket.",
  confirm_exit_app: "Biztosan ki akarsz lépni az alkalmazásból?",

  // Footer & legal pages
  footer_privacy: "Adatvédelmi irányelvek",
  footer_terms: "Általános szerződési feltételek",
  footer_about: "Rólunk és kapcsolat",
  footer_cookies: "Süti tájékoztató",
  footer_impressum: "Impresszum",
  footer_cookie_settings: "Süti beállítások",
  footer_rights: "Minden jog fenntartva.",
  last_updated: "Utolsó frissítés: 2026. augusztus 18.",

  privacy_title: "Adatvédelmi irányelvek",
  privacy_intro: "Ez az Adatvédelmi irányelv ismerteti, hogyan kezeli a MicaLingo („mi”, „minket” vagy „saját”) a személyes adatokat, amikor Ön a micalingo.com webhelyünket és mobilalkalmazásunkat (együttesen: a „Szolgáltatás”) használja. A személyes adatokat az EU általános adatvédelmi rendelete (GDPR) és a vonatkozó adatvédelmi jogszabályok szerint kezeljük. Az üzemeltető adatait az Impresszum tartalmazza.",
  privacy_s1_title: "1. Adatkezelő",
  privacy_s1_body: "A Szolgáltatással összefüggésben az Ön személyes adataiért felelős adatkezelő a MicaLingo, a https://micalingo.com webhely és a MicaLingo mobilalkalmazás üzemeltetője. Adatvédelmi megkereséseivel forduljon hozzánk a következő címen: support.micalingo@gmail.com. További üzemeltetői adatok az Impresszumban találhatók.",
  privacy_s2_title: "2. Az általunk kezelt információk",
  privacy_s2_body: "A bejelentkezés kizárólag Google Bejelentkezésen (Google Authentication) keresztül történik. Ha Ön a bejelentkezést választja, a Google a Google hitelesítési API-k és az Ön Google-fiókbeállításai szerint korlátozott fiókadatokat oszthat meg velünk (például Google-fiókazonosító, megjelenített név, profilkép URL-je és e-mail-cím). Nem üzemeltetünk önálló, jelszóalapú fiókrendszert, és nincs rálátásunk az Ön Google-jelszavára vagy Google-fiókjának teljes tartalmára. A Szolgáltatásban Ön által önként létrehozott vagy feltöltött tanulási előrehaladást, importált szókincset és hasonló tartalmakat is tárolhatjuk, az Ön hitelesített fiókjához kapcsolva.",
  privacy_s3_title: "3. Sütik és hasonló technológiák",
  privacy_s3_body: "A Szolgáltatás sütiket (cookie-kat) és hasonló tárolási technológiákat (például localStorage) használ a webhelyen és a mobilalkalmazásban.\n\nSzükséges sütik és helyi tárolás: kizárólag a Szolgáltatás működéséhez szükséges információkat tárolunk, ideértve a nyelvi beállítást, a sütihozzájárulás választását, valamint a munkamenet vagy bejelentkezés állapotát. Ezek a kért Szolgáltatás nyújtásához szükségesek, és nem igényelnek hozzájárulást.\n\nHirdetési sütik (Google): harmadik fél — a Google — sütiket használ a Google AdSense (és a kapcsolódó Google-hirdetési szolgáltatások) hirdetéseinek megjelenítéséhez. Ezek a sütik hirdetések megjelenítésére szolgálhatnak, ideértve az Ön korábbi, ezen vagy más webhelyeken tett látogatásain alapuló hirdetéseket is, és olyan adatokat gyűjthetnek, mint az IP-cím, az eszköz- és böngészőadatok, valamint a hirdetésekkel való interakció.\n\nHirdetési sütiket csak akkor használunk, ha Ön a süti bannerben (vagy később a Süti beállításokban) hozzájárul. A hozzájárulást bármikor visszavonhatja. A személyre szabott hirdetéseket a Google Hirdetésbeállításokban is kikapcsolhatja: https://www.google.com/settings/ads\nA Google itt ismerteti, hogyan használja a partnerwebhelyek adatait: https://policies.google.com/technologies/partner-sites\nTovábbi részletek a Süti tájékoztatóban találhatók.",
  privacy_s4_title: "4. Az adatkezelés célja és jogalapja",
  privacy_s4_body: "A személyes adatokat a Szolgáltatás nyújtása és biztonsága, a felhasználók Google Bejelentkezéssel történő hitelesítése, a tanulási anyagok és az előrehaladás eszközök közötti szinkronizálása (ahol alkalmazható), a támogatási megkeresések megválaszolása, valamint — az Ön hozzájárulása esetén — a Szolgáltatás ingyenességét segítő hirdetések megjelenítése érdekében kezeljük. A GDPR szerinti jogalap az adatkezelési tevékenységtől függően lehet: szerződés teljesítése (GDPR 6. cikk (1) bekezdés b) pont), jogos érdek a biztonságos tanulási Szolgáltatás működtetésében és fejlesztésében (GDPR 6. cikk (1) bekezdés f) pont), valamint az Ön hozzájárulása, ahol az a nem szükséges sütikhez és hirdetésekhez kell (GDPR 6. cikk (1) bekezdés a) pont).",
  privacy_s5_title: "5. Az e-mail-címek marketing célú felhasználásának tilalma",
  privacy_s5_body: "Az Ön e-mail-címét nem használjuk marketing célokra. Nem küldünk hírleveleket, promóciós kampányokat vagy reklámleveleket. Az e-mail-címet – ha azt Google Bejelentkezésen keresztül megkapjuk – kizárólag a fiók működtetéséhez, valamint a Szolgáltatással kapcsolatos kommunikációhoz használjuk, amikor Ön megkeres minket, vagy amikor az ilyen kommunikáció a Szolgáltatás nyújtásához szükséges. A hirdetések — ha megjelennek — a Szolgáltatáson belül láthatók, nem az e-mail-fiókjába érkeznek.",
  privacy_s6_title: "6. Harmadik felek szolgáltatásai (Google)",
  privacy_s6_body: "A Google-t (a) Google Bejelentkezésen keresztüli hitelesítésre és (b) Google AdSense hirdetések megjelenítésére használjuk. Ezekre a Google-szolgáltatásokra a Google Adatvédelmi irányelve és Általános Szerződési Feltételei is vonatkoznak. A Google bizonyos adatokat saját irányelvei szerint önálló adatkezelőként kezelhet, ideértve a hirdetések megjelenítéséhez használt sütiket.\n\nA Google hirdetési sütijeinek használata lehetővé teszi a Google és partnerei számára, hogy az Ön ezen és/vagy más webhelyeken tett látogatásai alapján jelenítsenek meg hirdetéseket. A személyre szabott hirdetéseket a https://www.google.com/settings/ads címen vagy a https://www.aboutads.info oldalon kapcsolhatja ki.\nA Google így használja a szolgáltatásait igénybe vevő webhelyek vagy alkalmazások adatait: https://policies.google.com/technologies/partner-sites\nA Google API-kból kapott információk MicaLingo általi felhasználása – ahol alkalmazandó – megfelel a Google API Services User Data Policy előírásainak, beleértve a Limited Use követelményeket.",
  privacy_s7_title: "7. Adatmegőrzés",
  privacy_s7_body: "A fiókhoz kapcsolódó és a felhasználó által létrehozott tanulási adatokat addig őrizzük meg, amíg a fiók aktív, illetve amíg a Szolgáltatás nyújtásához szükséges. Kérheti személyes adatai törlését, a jogszabályi megőrzési kötelezettségek figyelembevételével. Az eszközön tárolt helyi előrehaladás általában az alkalmazás Beállítások területén törölhető. A sütihozzájárulás választása az eszközén marad, amíg meg nem változtatja, vagy nem törli a webhelyadatait.",
  privacy_s8_title: "8. Az Ön jogai (EU / EGT)",
  privacy_s8_body: "Ha az Európai Unióban vagy az Európai Gazdasági Térségben tartózkodik, joga van kérni személyes adataihoz való hozzáférést, azok helyesbítését, törlését vagy az adatkezelés korlátozását; ahol alkalmazható, az adathordozhatósághoz való jogot; a jogos érdeken alapuló adatkezelés elleni tiltakozás jogát; valamint a hozzájárulás visszavonásának jogát, ha az adatkezelés hozzájáruláson alapul — ideértve a hirdetési sütiket is —, anélkül, hogy ez érintené a visszavonás előtti adatkezelés jogszerűségét. Emellett joga van panaszt tenni a helyi felügyeleti hatóságnál. Jogai gyakorlásához vegye fel velünk a kapcsolatot az alábbi e-mail-címen. A süti beállításokat a lábléc Süti beállítások hivatkozásával vagy az alkalmazás Beállítások menüjében is módosíthatja.",
  privacy_s9_title: "9. Nemzetközi adattovábbítás",
  privacy_s9_body: "Mivel Google-hitelesítést, Google-hirdetéseket és felhőinfrastruktúrát használunk, a személyes adatok az Ön lakóhelye szerinti országon kívül is feldolgozásra kerülhetnek, ideértve az EU/EGT-n kívüli országokat is. Ahol szükséges, az ilyen továbbítások a vonatkozó jogszabályokkal összhangban megfelelő garanciákkal történnek (például a szolgáltatók által alkalmazott általános szerződési kikötések).",
  privacy_s10_title: "10. Gyermekek adatainak védelme",
  privacy_s10_body: "A Szolgáltatás olyan felhasználóknak készült, akik a Google feltételei és a vonatkozó jogszabályok szerint képesek Google-fiókot létrehozni vagy használni. Ha úgy véli, hogy egy gyermek a vonatkozó szabályok megsértésével adott meg nekünk személyes adatokat, kérjük, vegye fel velünk a kapcsolatot, hogy megtehessük a megfelelő intézkedéseket.",
  privacy_s11_title: "11. Az irányelv módosításai",
  privacy_s11_body: "Ezt az Adatvédelmi irányelvet időről időre frissíthetjük gyakorlataink vagy a jogszabályi követelmények változásainak megfelelően. Az oldal tetején található „Utolsó frissítés” dátum jelzi, mikor került sor a legutóbbi módosításra. A Szolgáltatás frissítés utáni további használata – ahol a jogszabályok ezt lehetővé teszik – a módosított Irányelv tudomásulvételének minősül.",
  privacy_s12_title: "12. Kapcsolat",
  privacy_s12_body: "Adatvédelmi kérdésekkel vagy érintetti kérelmekkel forduljon hozzánk: support.micalingo@gmail.com. Webhely: https://micalingo.com. Üzemeltetői adatok: lásd az Impresszumot.",
  privacy_s13_title: "13. Hirdetések (Google AdSense)",
  privacy_s13_body: "Ahhoz, hogy a webhely és az alkalmazás ingyenesen használható maradjon, Google AdSense hirdetéseket jelenítünk meg. Harmadik felek, ideértve a Google-t, sütiket használnak a Szolgáltatásban megjelenő hirdetésekhez. A Google hirdetési sütijeinek használata lehetővé teszi a Google és partnerei számára, hogy az Ön ezen és/vagy más webhelyeken tett látogatásai alapján jelenítsenek meg hirdetéseket.\n\nAz Európai Gazdasági Térségben, az Egyesült Királyságban és Svájcban a személyre szabott hirdetési sütiket csak az Ön előzetes hozzájárulásával használjuk. Ha a hirdetési sütiket elutasítja, a Szolgáltatás továbbra is elérhető marad; a Google ekkor nem személyre szabott vagy kevesebb hirdetést jeleníthet meg, a Google rendszereitől függően.\n\nA személyre szabott hirdetéseket a Google Hirdetésbeállításokban kapcsolhatja ki: https://www.google.com/settings/ads\nHarmadik fél hirdetési sütijeit a https://www.aboutads.info oldalon is letilthatja.\nA Google partnerwebhelyekre vonatkozó tájékoztatója: https://policies.google.com/technologies/partner-sites",

  terms_title: "Általános szerződési feltételek",
  terms_intro: "Ezek az Általános szerződési feltételek („Feltételek”) szabályozzák a MicaLingo micalingo.com webhelyéhez és mobilalkalmazásához (a „Szolgáltatás”) való hozzáférését és azok használatát. A Szolgáltatás elérésével vagy használatával Ön elfogadja ezeket a Feltételeket. Ha nem ért egyet, ne használja a Szolgáltatást.",
  terms_s1_title: "1. A Szolgáltatás leírása",
  terms_s1_body: "A MicaLingo egy oktatási alkalmazás, amely kvízekkel, szókincsgyakorlással, nyelvtani anyagokkal, olvasási és hallásértési forrásokkal, valamint kapcsolódó tanulási eszközökkel segíti a felhasználókat a német nyelvvizsgára való felkészülésben. A Szolgáltatás webhelyként és mobilalkalmazásként érhető el. Egyes funkciók Google-fiókkal történő bejelentkezést igényelhetnek. A Szolgáltatás ingyenességének fenntartása érdekében hirdetések (ideértve a Google AdSense-t) jelenhetnek meg.",
  terms_s2_title: "2. Jogosultság és fiókok",
  terms_s2_body: "A személyre szabott funkciók eléréséhez Google-fiókra lehet szüksége. Ön felelős Google-fiókja biztonságának megőrzéséért, valamint a hitelesített munkamenete alatt végzett minden tevékenységért. Ön vállalja, hogy a Szolgáltatást kizárólag e Feltételek, a Google Általános Szerződési Feltételei és a vonatkozó jogszabályok szerint használja.",
  terms_s3_title: "3. Elfogadható használat és etikus magatartás",
  terms_s3_body: "Ön vállalja, hogy a Szolgáltatást kizárólag etikus szemlélettel és jogszerű nyelvtanulási célokra használja. Tilos a Szolgáltatást gyűlöletbeszéddel, diszkriminációval, zaklatással, erőszakkal, terrorizmussal, szélsőségességgel, bűncselekménnyel vagy bármely más jogellenes, illetve a Google Általános Szerződési Feltételeit vagy irányelveit sértő szavak, kifejezések, mondatok vagy egyéb tartalmak tanulására, létrehozására, feltöltésére, tárolására, megosztására vagy gyakorlására használni. Tilos a Szolgáltatást mások kárára, biztonsági intézkedések megkerülésére, rendszereink visszaélő lekérdezésére vagy más felhasználók hozzáférésének zavarására használni.",
  terms_s4_title: "4. Felhasználói tartalom",
  terms_s4_body: "Ön megőrzi a tulajdonjogát az Ön által importált vagy létrehozott szókincs, jegyzetek és egyéb anyagok felett („Felhasználói tartalom”). A Felhasználói tartalom benyújtásával Ön korlátozott licencet biztosít számunkra annak tárolására és megjelenítésére, kizárólag a Szolgáltatás Ön számára történő működtetéséhez szükséges mértékben. Ön kijelenti, hogy rendelkezik a Felhasználói tartalom benyújtásához szükséges jogokkal, és hogy az nem sérti harmadik felek jogait vagy e Feltételeket.",
  terms_s5_title: "5. Szellemi tulajdon",
  terms_s5_body: "A Szolgáltatás – beleértve a márkanevet, a dizájnt, az általunk biztosított nyilvános tanulási anyagokat és a szoftvert – szellemi tulajdonjogi védelem alatt áll. Az Ön Felhasználói tartalmát kivéve a Szolgáltatás nem másolható, nem módosítható, nem terjeszthető, nem értékesíthető, és nem készíthető belőle származékos mű előzetes írásbeli engedélyünk nélkül, kivéve, ha azt kógens jogszabály lehetővé teszi.",
  terms_s6_title: "6. Harmadik felek szolgáltatásai",
  terms_s6_body: "A Szolgáltatás harmadik felek szolgáltatóira támaszkodik, ideértve a Google-t a hitelesítéshez (Google Bejelentkezés) és a Google AdSense-t a hirdetések megjelenítéséhez. A Google és partnerei sütiket helyezhetnek el, ahogy azt az Adatvédelmi irányelvek és a Süti tájékoztató leírja. A Google-szolgáltatások használatára a Google Általános Szerződési Feltételei és Adatvédelmi irányelve is vonatkozik. Nem vállalunk felelősséget az ésszerű ellenőrzésünkön kívül eső harmadik felek szolgáltatásaiért. A hirdetési sütiket a süti bannerben, a lábléc Süti beállítások hivatkozásával vagy az alkalmazás Beállítások menüjében kezelheti.",
  terms_s7_title: "7. Szavatosság kizárása",
  terms_s7_body: "A Szolgáltatás „ahogy van” és „ahogy elérhető” alapon kerül nyújtásra, bármilyen kifejezett vagy hallgatólagos szavatosság nélkül – ideértve az eladhatóságra, meghatározott célra való alkalmasságra és jogtisztaságra vonatkozó hallgatólagos szavatosságokat is –, a vonatkozó jogszabályok által megengedett legnagyobb mértékben. Nem garantáljuk a folyamatos rendelkezésre állást, a hibamentes működést vagy konkrét vizsgaeredményeket.",
  terms_s8_title: "8. Felelősségkorlátozás",
  terms_s8_body: "Az alkalmazandó uniós és nemzeti jog által megengedett maximális mértékben a MicaLingo és üzemeltetői nem felelnek semmilyen közvetett, járulékos, különleges, következményes vagy büntető jellegű kárért, sem adat-, nyereség- vagy goodwill-veszteségért, amely a Szolgáltatás használatából ered. E Feltételek semmit sem zárnak ki és nem korlátoznak olyan felelősséget, amelyet a vonatkozó jogszabályok alapján nem lehet kizárni vagy korlátozni – ideértve a gondatlanságból eredő halálért vagy személyi sérülésért, illetve a csalásért való felelősséget.",
  terms_s9_title: "9. Felfüggesztés és megszüntetés",
  terms_s9_body: "Felfüggeszthetjük vagy megszüntethetjük a Szolgáltatáshoz való hozzáférést, ha Ön megsérti e Feltételeket, visszaél a Szolgáltatással, illetve biztonsági vagy jogi okokból. Ön bármikor abbahagyhatja a Szolgáltatás használatát. Azok a rendelkezések, amelyek természetüknél fogva a megszűnés után is hatályban maradnak, hatályban maradnak.",
  terms_s10_title: "10. A Feltételek módosítása",
  terms_s10_body: "Ezeket a Feltételeket időről időre frissíthetjük. Az „Utolsó frissítés” dátum jelzi a legutóbbi módosítást. A Szolgáltatás változások hatálybalépése utáni további használata – ahol a jogszabályok ezt lehetővé teszik – a frissített Feltételek elfogadásának minősül.",
  terms_s11_title: "11. Irányadó jog",
  terms_s11_body: "Ezekre a Feltételekre az Európai Unióban alkalmazandó jog, valamint a fogyasztókra vonatkozó tagállami jogszabályok az irányadók, az Ön lakóhelye szerinti ország kötelező fogyasztóvédelmi szabályainak sérelme nélkül.",
  terms_s12_title: "12. Kapcsolat",
  terms_s12_body: "A Feltételekkel kapcsolatos kérdésekben forduljon hozzánk: support.micalingo@gmail.com. Webhely: https://micalingo.com. Üzemeltetői adatok: lásd az Impresszumot.",

  about_title: "Rólunk és kapcsolat",
  about_heading: "A MicaLingo-ról",
  about_body: "A MicaLingo egy német nyelvvizsgára felkészítő alkalmazás és webhely (micalingo.com), amely szókinccsel, nyelvtannal, kvízekkel, olvasási és hallásértési anyagokkal segíti a tanulókat. Saját könyvtáradat azonban használhatod más nyelvre, de akár más téma gyakorlására is! Tesztelheted tudásodat történelmi évszámokkal, fővárosok és országok neveivel, matematikai feladványokat is generálhatsz magadnak. Az oldal és az Android alkalmazás jelenleg ingyenesen elérhető, de az oldal fejlesztője támogatható tetszőleges összeggel ({support_link}). Ahhoz, hogy jelenleg ingyenesen használható legyen az oldal, reklámhirdetéseket engedélyeztünk. Megértésedet köszönjük!",
  about_mission: "Célunk, hogy a strukturált, valódi vizsgafelkészülés igényeire fókuszálva támogassuk a fejlődésedet.",
  contact_heading: "Kapcsolat és támogatás",
  contact_body: "Kérdésed, visszajelzésed van, vagy segítségre van szükséged? Örömmel hallunk rólad.",
  contact_support_label: "Támogatás és visszajelzés",
  contact_website_label: "Webhely",

  cookies_title: "Süti tájékoztató",
  cookies_intro: "Ez a Süti tájékoztató ismerteti, hogyan használja a MicaLingo a sütiket és hasonló technológiákat a https://micalingo.com webhelyen és a MicaLingo mobilalkalmazásban. Az Adatvédelmi irányelvekkel együtt kell olvasni.",
  cookies_s1_title: "1. Mik azok a sütik?",
  cookies_s1_body: "A sütik (cookie-k) kis szöveges fájlok, amelyeket az eszközén tárol a böngésző, amikor egy webhelyet felkeres. Hasonló technológia a localStorage és a sessionStorage a böngészőben vagy az alkalmazás WebView-jában. Lehetnek saját (első féltől származó, MicaLingo által elhelyezett) vagy harmadik féltől származó (más szervezet, például a Google által elhelyezett) sütik.",
  cookies_s2_title: "2. Szükséges sütik",
  cookies_s2_body: "Ezek a Szolgáltatás működéséhez kellenek, és nem kapcsolhatók ki. Ide tartozik: a nyelvi beállítás (micalingo_language), a sütihozzájárulás választása (micalingo_cookie_consent), valamint a Google Bejelentkezéshez és az alkalmazás működéséhez szükséges technikai munkamenet- vagy bejelentkezési állapot. Jogalap: a GDPR 6. cikk (1) bekezdés b) és/vagy f) pontja, valamint az ePrivacy irányelv szükséges tárolásra vonatkozó kivétele.",
  cookies_s3_title: "3. Hirdetési sütik (Google AdSense)",
  cookies_s3_body: "Ha Ön hozzájárul, a Google — harmadik fél — sütiket használ a Szolgáltatásban megjelenő hirdetésekhez. A Google hirdetési sütijei az ezen és más webhelyeken tett látogatásai alapján jeleníthetnek meg hirdetéseket, mérhetik a hirdetések teljesítményét, és korlátozhatják, milyen gyakran lát egy hirdetést. Tipikus adatok lehetnek az IP-cím, az eszközazonosítók, a böngésző típusa és a hirdetésekkel való interakció.\n\nEzeket a sütiket hirdetési célra csak akkor helyezzük el, ha a süti bannerben elfogadja őket. Jogalap: az Ön hozzájárulása (GDPR 6. cikk (1) bekezdés a) pont).",
  cookies_s4_title: "4. Hogyan használja a Google az adatokat",
  cookies_s4_body: "A Google itt ismerteti, hogyan használja a szolgáltatásait igénybe vevő webhelyek vagy alkalmazások adatait: https://policies.google.com/technologies/partner-sites\nA személyre szabott hirdetéseket a Google Hirdetésbeállításokban kezelheti: https://www.google.com/settings/ads\nBizonyos harmadik fél hirdetési sütijeit a https://www.aboutads.info oldalon is letilthatja.",
  cookies_s5_title: "5. A hozzájárulás kezelése és visszavonása",
  cookies_s5_body: "Az első látogatáskor süti bannert jelenítünk meg. Elfogadhatja az összes sütit, elutasíthatja a nem szükségeseket, vagy kategóriánként választhat. Választását bármikor módosíthatja a lábléc Süti beállítások hivatkozásával, az alkalmazás Beállítások menüjében, vagy a banner újbóli megnyitásával. A hozzájárulás visszavonása nem érinti a visszavonás előtt már lezajlott adatkezelést.",
  cookies_s6_title: "6. Böngésző- és eszközbeállítások",
  cookies_s6_body: "A sütiket a böngésző vagy az eszköz beállításaiban is törölheti vagy blokkolhatja. Az összes süti blokkolása érintheti a bejelentkezést, a nyelvet vagy a Szolgáltatás egyéb funkcióit.",
  cookies_s7_title: "7. Kapcsolat",
  cookies_s7_body: "Sütikkel kapcsolatos kérdések: support.micalingo@gmail.com. Webhely: https://micalingo.com.",

  impressum_title: "Impresszum",
  impressum_intro: "Ez az impresszum azonosítja, ki üzemelteti a MicaLingo webhelyet és mobilalkalmazást.",
  impressum_s1_title: "1. Üzemeltető",
  impressum_s1_body: "Szolgáltatás neve: MicaLingo\nWebhely: https://micalingo.com\nMobilalkalmazás: MicaLingo (ugyanazon Szolgáltatás Android / iOS WebView-ja)\nÜzemeltető: MicaLingo, önállóan működtetett oktatási projekt.",
  impressum_s2_title: "2. Kapcsolat",
  impressum_s2_body: "E-mail: support.micalingo@gmail.com\nWebhely: https://micalingo.com\nEz az elérhetőség a felhasználói, adatvédelmi és jogi megkeresésekhez.",
  impressum_s3_title: "3. A Szolgáltatás jellege",
  impressum_s3_body: "A MicaLingo német nyelvvizsgára felkészítő webhely és alkalmazás, kvízekkel, szókinccsel, nyelvtannal, olvasási és hallásértési anyagokkal. A Szolgáltatás jelenleg ingyenesen használható, és a működési költségek fedezésére hirdetéseket (Google AdSense) jeleníthet meg. A fejlesztés támogatására önkéntes adományozás is elérhető lehet.",
  impressum_s4_title: "4. A tartalomért felelős",
  impressum_s4_body: "Az üzemeltető felel a Szolgáltatás szerkesztett tartalmáért. A harmadik felek hirdetései és a külső hivatkozások a vonatkozó szolgáltatók felelőssége. A felhasználók által feltöltött tanulási tartalom a feltöltő felhasználó felelőssége marad.",
  impressum_s5_title: "5. Uniós online vitarendezés",
  impressum_s5_body: "Az Európai Bizottság online vitarendezési platformot biztosít: https://ec.europa.eu/consumers/odr\nA kérdéseket előnyben részesítjük közvetlenül a support.micalingo@gmail.com címen rendezni.",
  impressum_s6_title: "6. Kapcsolódó jogi oldalak",
  impressum_s6_body: "Az Adatvédelmi irányelvek, az ÁSZF, a Süti tájékoztató, valamint a Rólunk és kapcsolat oldal a webhely és az alkalmazás láblécéből érhető el.",

  cookie_banner_title: "Sütiket használunk",
  cookie_banner_body: "Szükséges sütiket használunk a MicaLingo működéséhez. Az Ön hozzájárulásával harmadik fél — a Google — is használ sütiket hirdetések (Google AdSense) megjelenítéséhez, ideértve az ezen és más webhelyeken tett látogatásain alapuló hirdetéseket. Elfogadhatja, elutasíthatja vagy testre szabhatja ezt.",
  cookie_banner_accept: "Összes elfogadása",
  cookie_banner_reject: "Nem szükségesek elutasítása",
  cookie_banner_customize: "Testreszabás",
  cookie_banner_save: "Választás mentése",
  cookie_banner_necessary: "Szükséges",
  cookie_banner_necessary_desc: "A webhely és az alkalmazás működéséhez kell (nyelv, bejelentkezés, a süti választás tárolása).",
  cookie_banner_ads: "Hirdetés (Google)",
  cookie_banner_ads_desc: "Lehetővé teszi a Google AdSense számára, hogy sütiket használjon hirdetések — ideértve a személyre szabott hirdetéseket — megjelenítéséhez.",
  cookie_banner_always_on: "Mindig be",
  cookie_settings_title: "Süti beállítások",
  cookie_settings_desc: "Itt állíthatja be, hogy a Google használhat-e hirdetési sütiket a webhelyen és az alkalmazásban.",
  cookie_settings_manage: "Süti beállítások módosítása",
  cookie_settings_status_accepted: "Hirdetési sütik: engedélyezve",
  cookie_settings_status_rejected: "Hirdetési sütik: tiltva",
  cookie_settings_status_unset: "Még nem választott süti beállítást.",
};